<div class="l-row header report-details">
        <div class="l-split-wide-col">
        
                <a href="/petroleum/reports.php">&lsaquo; All Petroleum and Other Liquids Reports</a>
                <h2>Petroleum Marketing Monthly</h2>

                <div class="release-dates">
                        <div class="label-series">Data for November 2016</div><!-- /label-series -->
<                                <div class="date-container">
                                        <div class="label">Release Date:</div><!-- /label -->
                                <div class="date">February 1, 2017</div><!-- /date -->
                        </div><!-- /date-container -->
                        <div class="report-download-container">
                                <a href="pdf/pmmall.pdf"><i class="ico pdf"></i>full report</a>
                                </div>
                        </div>
                </div>
        </div>
        <div class="l-split-narrow-col gradient">
                <span class="form-wrapper-outer">
                        <h4>Previous Issues</h4>
                        <span class="form-wrapper-inner">

                                <form name="form" id="form">
                                        <label>Month:</label>
                                        <select name="jumpMenu" id="jumpMenu">
                                                <option value="/petroleum/marketing/monthly/archive/2017/2017_02/pmm_2017_02.php" selected="selected">February 2017</option>
<!--                                                <option value="/petroleum/marketing/monthly/archive/2011/2011_11/pmm_2011_11.html">November 2012</option>-->
                                                <option value="/petroleum/marketing/monthly/archive/2017/2017_01/pmm_2017_01.php">January 2017</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_12/pmm_2016_12.php">December 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_11/pmm_2016_11.php">November 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_10/pmm_2016_10.php">October 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_09/pmm_2016_09.php">September 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_08/pmm_2016_08.php">August 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_07/pmm_2016_07.php">July 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_06/pmm_2016_06.php">June 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_05/pmm_2016_05.php">May 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_04/pmm_2016_04.php">April 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_03/pmm_2016_03.php">March 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/2016/2016_02/pmm_2016_02.php">February 2016</option>
                                                <option value="/petroleum/marketing/monthly/archive/">prior issues</option>
                                        </select>
                                        <input type="button" name="go_button" class="arrow_go" id="go_button" value="Go" />
                                </form>
                        </span>
                </span>
        </div>
</div>

