<table width="100%" border="0" cellpadding="0" cellspacing="0" class="basic_table" >
  <caption>Key indicators  </caption>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th style="text-align:right">  November 2014</th>
      <th style="text-align:right">% change from<br /> 
       November 2013</th>
	</tr>
  </thead>
  <tbody>
     <tr>
       	<td>Total net generation <br /> 
       	<span style="font-size:11px; font-style:italic">thousand megawatthours</span></td>
       	<td>317,176</td>
       	<td>1.1%</li>
     	<tr>
     	  <td>Residential retail price<br /> 
     	<span style="font-size:11px; font-style:italic">cents/kilowatthour</span></td>
     	  <td>12.46</td>
     	  <td>3.1%</li>
     <tr>
        <td>Retail sales<br /> 
        <span style="font-size:11px; font-style:italic">thousand megawatthours</span></td>
        <td>282,002</td>
        <td>0.9%</li>
    <?php /*<tr>
      <td>Natural gas price, Henry Hub <br />($/MMBtu)</td>
      <td>4.69</td>
      <td>12.8%</li>*/ ?>
    <tr>
      <td>Natural gas consumption<br />
      <span style="font-size:11px; font-style:italic">million cubic feet</span></td>
      <td>627,008</td>
      <td>-0.3%</li>
    <tr>
      <td>Coal consumption<br />
      <span style="font-size:11px; font-style:italic">thousand tons</span></td>
      <td>64,688</td>
      <td>-1.8%</li>
    <tr>
      <td>Heating degree-days</td>
      <td>611</td>
      <td>7.2%</li>
    <?php /*<tr>
      <td>Coal stocks<br />(thousand tons)</td>
      <td>136,218</td>
      <td>-22.9%</li>
    <tr>
      <td>Nuclear generation<br />(thousand MWh)</td>
      <td>62,116</td>
      <td>-1.2%</li>*/ ?>

  </tbody>
  <tfoot>
  <tr>
  <td colspan="3">Source: <a href="/electricity/monthly/update/">Electricity Monthly Update</a></li>
  </tfoot>
</table>
