<table width="100%" border="0" cellpadding="0" cellspacing="0" class="basic_table">
  <caption>Key indicators</caption>

  <thead>
    <tr>
      <th>&nbsp;</th>
      <th style="text-align:right"> December 2016</th>
      <th style="text-align:right">% change from<br />
        December 2015  </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Total net generation <br />
        <span style="font-size:11px; font-style:italic">thousand megawatthours</span></td>
      <td>345,238</td>
      <td>6.40%</li>
    <tr>
      <td>Residential retail price<br />
        <span style="font-size:11px; font-style:italic">cents/kilowatthour</span></td>
      <td>12.21</td>
      <td>-0.90%</li>
    <tr>
      <td>Retail sales<br />
        <span style="font-size:11px; font-style:italic">thousand megawatthours</span></td>
      <td>306,163</td>
      <td>3.00%</li>
    </tr>

    <tr>
      <td>Natural gas consumption<br />
        <span style="font-size:11px; font-style:italic">million cubic feet</span></td>
      <td>706,376</td>
      <td>-12.50%</li>
    <tr>
      <td>Coal consumption<br />
        <span style="font-size:11px; font-style:italic">thousand tons</span></td>
      <td>64,883</td>
      <td>29.20%</li>
    </tr>
    <tr>
      <td>Heating Degree-Days</td>
      <td>785</td>
      <td>36.30%</li>

  </tbody>

  <tfoot>
    <tr>
      <td colspan="3">Source: <a href="/electricity/monthly/update/">Electricity Monthly Update</a></li>
  </tfoot>

</table>

