<?php /*cfinclude template="side_content.php"*/ ?>

<?php /* Interactive Table Viewer Promo */ ?>
      <span class="blue_side">
        <h4 class="d_side">Interactive Electricity Data </h2></li>
        
        <p><em>browse pre-defined or custom data views, graph or map data series down to the plant level</span></li>
			<li>        <br /><b><a href="/electricity/data/browser/">Electricity data browser &rsaquo;</a></b><br />
	     <br />
         <?php /*hr width="55" align="center"/*/ ?>
         <span style="font-size:18px; text-align:center"> - OR - </span><br /><br />
          <em> create your own app with our </em>
          <a href="/beta/api/qb.php?category=0"><b> API </b><b>  &rsaquo;</b></a><br />
	</p>
    </span>	
		<?php /* Interactive Table Viewer Promo */ ?>


<div class="secondary">
<ul>
<li class="head"><h2>Detailed and historical electricity data by survey</h2></li>
<li>
<ul>
         <li> <a href="/electricity/data/state/">State-level</a></li>  
         <li> <a href="/electricity/data/eia826/">Sales and revenue</a></li>  
         <li> <a href="/electricity/data/eia860/">Generating capacity</a></li> 
         <li> <a href="/electricity/data/eia923/">Power plant operating data</a></li> 
         <li> <a href="/electricity/data/detail-data.html">see more...</a></li> 
         </ul>
</span>