<table class="basic_table" >
  <caption>Total production of uranium concentrate in the United States<br/>
  <span class="units">pounds U<sub>3</sub>O<sub>8</sub></span></caption>
  <thead>
    <tr>
      <th>Quarter/year</th>
      <th>2018P</th>
      <th>2017</th>
      <th>2016</th>
      <th>2015</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td nowrap="nowrap"><strong>1st Quarter</strong></td>
      <td nowrap="nowrap">226,780</td>
      <td nowrap="nowrap">450,215 </td>
      <td nowrap="nowrap">626,522</td>
      <td nowrap="nowrap">1,154,408</li>
    <tr>
      <td nowrap="nowrap"><strong>2nd Quarter</strong></td>
      <td nowrap="nowrap">--</td>
      <td nowrap="nowrap">726,375</td>
      <td nowrap="nowrap">745,306</td>
      <td nowrap="nowrap">789,980</li>
    <tr>
      <td nowrap="nowrap"><strong>3rd Quarter</strong></td>
      <td nowrap="nowrap">--</td>
      <td nowrap="nowrap">643,212</td>
      <td nowrap="nowrap">818,783</td>
      <td nowrap="nowrap">774,541</li>
    <tr>
      <td nowrap="nowrap"><strong>4th Quarter</strong></td>
      <td nowrap="nowrap">--</td>
      <td nowrap="nowrap">622,987</td>
      <td nowrap="nowrap">725,947</td>
      <td nowrap="nowrap">624,278</li>
    <tr class="total">
      <td nowrap="nowrap"><strong>Calendar year total</strong></td>
      <td nowrap="nowrap">226,780</td>
      <td nowrap="nowrap"><strong>2,422,789</strong></td>
      <td nowrap="nowrap"><strong>2,916,558</strong></td>
      <td nowrap="nowrap"><strong>3,343,207</strong></li>
  </tbody>
 <tfoot>
    <tr>
      <td colspan="6">Source: U.S. Energy Information Administration, <a href="/uranium/production/quarterly/">Domestic Uranium Production Report - Quarterly</a></li>
  </tfoot></table>
