<table>
  <caption>Total production of uranium concentrate in the United States<br/>
  <span class="units">pounds U<sub>3</sub>O<sub>8</sub></span></caption>
  <thead>
    <tr>
      <th>Quarter/year</th>
      <th>2018P</th>
      <th>2017</th>
      <th>2016</th>
      <th>2015</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>1st Quarter</strong></td>
      <td>226,780</td>
      <td>450,215 </td>
      <td>626,522</td>
      <td>1,154,408</td>
    </tr>
    <tr>
      <td><strong>2nd Quarter</strong></td>
      <td>--</td>
      <td>726,375</td>
      <td>745,306</td>
      <td>789,980</td>
    </tr>
    <tr>
      <td><strong>3rd Quarter</strong></td>
      <td>--</td>
      <td>643,212</td>
      <td>818,783</td>
      <td>774,541</td>
    </tr>
    <tr>
      <td><strong>4th Quarter</strong></td>
      <td>--</td>
      <td>622,987</td>
      <td>725,947</td>
      <td>624,278</td>
    </tr>
    <tr class="total">
      <td><strong>Calendar year total</strong></td>
      <td>226,780</td>
      <td><strong>2,422,789</strong></td>
      <td><strong>2,916,558</strong></td>
      <td><strong>3,343,207</strong></td>
    </tr>
  </tbody>
 <tfoot>
    <tr>
      <td colspan="6">Source: U.S. Energy Information Administration, <a href="/uranium/production/quarterly/">Domestic Uranium Production Report - Quarterly</a></td>
    </tr>
  </tfoot></table>
