<?php /* Main Column */ ?>
<p>Find environmental data on carbon dioxide emissions from energy and industry,  by consuming sector (residential, commercial, industrial, transportation,  electric power), and other emissions.</p>
<div class="accordion">
<div class="expand-collapse-container">
<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
</div>
<table class="contable">
<?php /* BEGIN Summary Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="summary"></a>Summary</h2>
	<div class="accordion-content">
		<ul>
			<li class="head">U.S. Carbon dioxide emissions from energy consumption (from 1973) </strong><em class="hideme"><br />
<div> <em>
<script language="JavaScript" type="text/JavaScript" src="/totalenergy/data/monthly/txt/new_merheader.txt"></script></em> 
</div></li>



			<li class="head">By source</strong></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_3.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By source "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.01&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By source "><i class="ico xls"><span>XLS</span></i></a></span></li>

			<li class="head">By residential sector</strong></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_5.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By residential sector "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.02&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By residential sector "><i class="ico xls"><span>XLS</span></i></a></span></li>

			<li class="head">By commercial sector </strong></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_6.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By commercial sector  "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.03&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By commercial sector  "><i class="ico xls"><span>XLS</span></i></a></span></li>

			<li class="head">By industrial sector</strong></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_7.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By industrial sector "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.04&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By industrial sector "><i class="ico xls"><span>XLS</span></i></a></span></li>

			<li class="head">By transportation sector</strong></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_8.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By transportation sector "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.05&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By transportation sector "><i class="ico xls"><span>XLS</span></i></a></span></li>

			<li class="head">By electric power</strong></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_9.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By electric power "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.06&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By electric power "><i class="ico xls"><span>XLS</span></i></a></span></li>

			<li class="head">From biomass</strong></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_10.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions From biomass "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.07&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions From biomass "><i class="ico xls"><span>XLS</span></i></a></span></li>

			<li class="head"><a href="/environment/emissions/state/state_emissions.cfm">State CO<sub>2</sub> emissions &rsaquo;</a></li>
			<li>
<em class="hideme">Release Date: October 24, 2017  </li>


<li><p><strong><a href="/environment/emissions/co2_vol_mass.cfm">Fuel carbon dioxide emission coefficients &rsaquo;</a></li>
			<li>
<em class="hideme">Release Date: February 2, 2016</em> </p></li>

<?php /* 
			<li class="head">CO<sub>2</sub> Emissions Coefficients - Quadrillion (10<sup>15</sup>) BTU</strong></li>
			<li class="additional-formats">Available formats: XLS</span></li>*/ ?>

<li><em class="hideme"><strong>Annual Energy Review carbon data &rsaquo;</li>
			<li>
Release Date: September 27, 2012</em> | data from: <em> <a href="/totalenergy/data/annual/">Annual Energy Review</a></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/annual/pdf/sec11.pdf" class="ico_pdf" title="Annual Energy Review carbon data  "><i class="ico pdf"><span>PDF</span></i></a></span></li>          
<?php /*
			<li class="head"><a href="/environment/emissions/ghg_report/ghg_gwp.cfm">High-Global Warning Potential Gasses &rsaquo;</a></strong><em class="hideme"></em><em></li>
*/ ?>
<?php /* END Summary Content ////////////////*/ ?>
<?php /* BEGIN Electric Power Plant Environmental Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="electric"></a>Electric power plant environmental</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/electricity/annual/html/epa_04_01.html">Number of generators &amp; capacity &rsaquo;</a></li>
			<li>
<em class="hideme">Release Date: December 7, 2017</em> | data from: <em> <a href="/electricity/annual/">Electric Power Annual</a></li>


			<li class="head"><a href="/electricity/annual/html/epa_09_04.html">Average flue gas desulfurization (scrubber) costs &rsaquo;</a></li>
			<li>
<em class="hideme">Release Date: December 7, 2017</em> | data from:<em><a href="/electricity/annual/">Electric Power Annual</a></span></li>
			<li></li>


			<li class="head"><a href="/electricity/annual/html/epa_09_01.html">Emissions from energy consumption at conventional power plants and combined-heat-and-power &rsaquo;</a></li>
			<li>
<em class="hideme">Release Date: December 7, 2017</em>| data from:<em><a href="/electricity/annual/">Electric Power Annual</a></li>


			<li class="head"><a href="/electricity/annual/html/epa_09_02.html">Quality and net summer capacity of operable environmental equipment &rsaquo;</a></li>
			<li>
<em class="hideme">Release Date: December 7, 2017</em>| data from:<em><a href="/electricity/annual/">Electric Power Annual</a></li>

<?php /* END Electric Power Plant Environmental Content ////////////////*/ ?>
<?php /* BEGIN International Emissions Content ////////////////*/ ?>

	<h2><i class="ico expand-collapse"></i><a name="intl"></a>International emissions</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=90&pid=44&aid=8">Total emissions &rsaquo;</a></li>
			<li>            Data from: <em> <a href="/beta/international/data/browser/">International Energy Statistics </a></li>


			<li class="head"><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=45&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MTCDPP">Per capita emissions &rsaquo;</a></li>
			<li>
Data from: <em><a href="/beta/international/data/browser/">International Energy Statistics </a></li>


			<li class="head"><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=5&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from petroleum consumption &rsaquo;</a></li>
			<li>
Data from: :<em><a href="/beta/international/data/browser/">International Energy Statistics </a></li>


			<li class="head"><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=3&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from natural gas consumption &rsaquo;</a></li>
			<li>
Data from: <em><a href="/beta/international/data/browser/">International Energy Statistics </a></li>


			<li class="head"><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=1&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from coal consumption &rsaquo;</a></li>
			<li>
Data from: <em><a href="/beta/international/data/browser/">International Energy Statistics </a></li>


			<li class="head"><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=91&pid=46&aid=31">Energy related carbon intensity &rsaquo;</a></li>
			<li>
Data from: <em><a href="/beta/international/data/browser/">International Energy Statistics </a></li>

<?php /* END International Emissions Content ////////////////*/ ?>

</table>

<?php /* Main Column */ ?>