<div class="secondary">
    <ul>
        <li class="head">
            <h2>Most requested environment data</h2>
        </li>
        <li class="sub-head">Carbon Dioxide Projections from the Annual Energy Outlook</li>
        <li>
            <ul>
                <li class="icon">
                    <a href="/outlooks/aeo/er/excel/aeotab_18.xlsx"><i class="ico xls">
					<span>XLS</span>
				</i>Table 18</a>
                </li>
                <li class="icon">
                    <a href="/outlooks/aeo/er/excel/aeotab_19.xlsx"><i class="ico xls"><span>XLS</span></i>Table 19</a></li>
            </ul>
        </li>
        <li class="sub-head">Short-Term Energy Outlook Emissions Table</li>
        <li>
            <ul>
                <li class="icon"><a href="/outlooks/steo/tables/pdf/9atab.pdf"><i class="ico pdf">
                    <span>PDF</span>
                </i>Table 9a</a></li>
            </ul>
        </li>
    </ul>
</div>