<div class="secondary">
    <ul>
        <li class="head">
            <h2>Most requested environment data</h2>
        </li>
        <li class="sub-head">Carbon Dioxide Projections from the Annual Energy Outlook</li>
        <li class="ico xls"><a href="/outlooks/aeo/er/excel/aeotab_18.xlsx">Table 18</a></li>
        <li class="ico xls"><a href="/outlooks/aeo/er/excel/aeotab_19.xlsx">Table 19</a></li>
        <li class="sub-head">Short-Term Energy Outlook Emissions Table</li>
        <li class="ico pdf"><a href="/outlooks/steo/tables/pdf/9atab.pdf">Table 9a</a></li>

    </ul>
</div>