<div class="primary">
<p>Find environmental data on carbon dioxide emissions from energy and industry, by consuming sector (residential, commercial, industrial, transportation, electric power), and other emissions.</p>
<span class="expand-collapse-container">
<i class="ico expand"><span>Expand all</span></i>
<i class="ico collapse"><span>Collapse all</span></i>
</span>
<div class="accordion">
<h3><a name="summary"></a>Summary</h3>
<div class="accordion-content">
<ul>
<li class="head" class="head">
U.S. Carbon dioxide emissions from energy consumption (from 1973)</li>
<li><!-- class="include" --><span class="release-date">Release date:</span> <span class="date"><?php include('totalenergy/data/monthly/includes/releasedate.inc') ?></span><span class="pipe">|</span><span class="source">Data from:</span> <span class="source"><a href="/totalenergy/data/monthly/">Monthly Energy Review</a></li>
</ul>
<ul>
<li class="head">
By source</li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/monthly/pdf/sec12_3.pdf" title="U.S. Carbon dioxide emissions By source">
<i class="ico pdf">
<span>PDF</span>
</i>
</a><a href="/totalenergy/data/browser/xls.php?tbl=T12.01&amp;freq=m" title="U.S. Carbon dioxide emissions By source">
<i class="ico xls">
<span>XLS</span>
</i>
</a></li>
</ul>
<ul>
<li class="head">
By residential sector</li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/monthly/pdf/sec12_5.pdf" title="U.S. Carbon dioxide emissions By residential sector">
<i class="ico pdf">
<span>PDF</span>
</i>
</a><a href="/totalenergy/data/browser/xls.php?tbl=T12.02&amp;freq=m" title="U.S. Carbon dioxide emissions By residential sector">
<i class="ico xls">
<span>XLS</span>
</i>
</a></li>
</ul>
<ul>
<li class="head">
By commercial sector</li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/monthly/pdf/sec12_6.pdf" title="U.S. Carbon dioxide emissions By commercial sector">
<i class="ico pdf">
<span>PDF</span>
</i>
</a><a href="/totalenergy/data/browser/xls.php?tbl=T12.03&amp;freq=m" title="U.S. Carbon dioxide emissions By commercial sector">
<i class="ico xls">
<span>XLS</span>
</i>
</a></li>
</ul>
<ul>
<li class="head">
By industrial sector</li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/monthly/pdf/sec12_7.pdf" title="U.S. Carbon dioxide emissions By industrial sector">
<i class="ico pdf">
<span>PDF</span>
</i>
</a><a href="/totalenergy/data/browser/xls.php?tbl=T12.04&amp;freq=m" title="U.S. Carbon dioxide emissions By industrial sector">
<i class="ico xls">
<span>XLS</span>
</i>
</a></li>
</ul>
<ul>
<li class="head">
By transportation sector</li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/monthly/pdf/sec12_8.pdf" title="U.S. Carbon dioxide emissions By transportation sector">
<i class="ico pdf">
<span>PDF</span>
</i>
</a><a href="/totalenergy/data/browser/xls.php?tbl=T12.05&amp;freq=m" title="U.S. Carbon dioxide emissions By transportation sector">
<i class="ico xls">
<span>XLS</span>
</i>
</a></li>
</ul>
<ul>
<li class="head">
By electric power</li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/monthly/pdf/sec12_9.pdf" title="U.S. Carbon dioxide emissions By electric power">
<i class="ico pdf">
<span>PDF</span>
</i>
</a><a href="/totalenergy/data/browser/xls.php?tbl=T12.06&amp;freq=m" title="U.S. Carbon dioxide emissions By electric power">
<i class="ico xls">
<span>XLS</span>
</i>
</a></li>
</ul>
<ul>
<li class="head">
From biomass</li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/monthly/pdf/sec12_10.pdf" title="U.S. Carbon dioxide emissions From biomass">
<i class="ico pdf">
<span>PDF</span>
</i>
</a><a href="/totalenergy/data/browser/xls.php?tbl=T12.07&amp;freq=m" title="U.S. Carbon dioxide emissions From biomass">
<i class="ico xls">
<span>XLS</span>
</i>
</a></li>
</ul>
<ul>
<li class="head"><a href="/environment/emissions/state/state_emissions.php">State CO<sub>2</sub> emissions</a></li>
<li>
<span class="release-date">Release date:</span> <span class="date">October 24, 2017</span></li>
</ul>
<ul>
<li class="head"><a href="/environment/emissions/co2_vol_mass.php">Fuel carbon dioxide emission coefficients</a></li>
<li>
<span class="release-date">Release date:</span> <span class="date">February 2, 2016</span></li>
</ul>
<ul>
<li class="head">
Annual Energy Review carbon data</li>
<li>
<span class="release-date">Release date:</span> <span class="date">September 27, 2012</span><span class="pipe">|</span><span class="source">Data from:</span> <a href="/totalenergy/data/annual/">Annual Energy Review</a></li>
<li><span class="formats">Available formats:</span>
<a href="/totalenergy/data/annual/pdf/sec11.pdf" title="Annual Energy Review carbon data">
<i class="ico pdf">
<span>PDF</span>
</i>
</a></li>
</ul>
</div>
<!-- END Summary Content //////////////// -->
<!-- BEGIN Electric Power Plant Environmental Content //////////////// -->
<h3><a name="electric"></a>Electric power plant environmental</h3>
<div class="accordion-content">
<ul>
<li class="head"><a href="/electricity/annual/html/epa_04_01.html">Number of generators &amp; capacity</a></li>
<li>
<span class="release-date">Release date:</span> <span class="date">December 7, 2017</span>
</span><span class="pipe">|</span><span class="source">Data from:</span>
<a href="/electricity/annual/">Electric Power Annual</a></li>
</ul>
<ul>
<li class="head"><a href="/electricity/annual/html/epa_09_04.html">Average flue gas desulfurization (scrubber) costs</a></li>
<li>
<span class="release-date">Release date:</span> <span class="date">December 7, 2017</span>
</span><span class="pipe">|</span><span class="source">Data from:</span>
<a href="/electricity/annual/">Electric Power Annual</a></li>
</ul>
<ul>
<li class="head"><a href="/electricity/annual/html/epa_09_01.html">Emissions from energy consumption at conventional power plants and combined-heat-and-power</a></li>
<li>
<span class="release-date">Release date:</span> <span class="date">December 7, 2017</span>
</span><span class="pipe">|</span><span class="source">Data from:</span>
<a href="/electricity/annual/">Electric Power Annual</a></li>
</ul>
<ul>
<li class="head"><a href="/electricity/annual/html/epa_09_02.html">Quality and net summer capacity of operable environmental equipment</a></li>
<li>
<span class="release-date">Release date:</span> <span class="date">December 7, 2017</span>
</span><span class="pipe">|</span><span class="source">Data from:</span>
<a href="/electricity/annual/">Electric Power Annual</a></li>
</ul>
</div>
<!-- END Electric Power Plant Environmental Content //////////////// -->
<!-- BEGIN International Emissions Content //////////////// -->
<h3><a name="intl"></a>International emissions</h3>
<div class="accordion-content">
<ul>
<li class="head" class="head"><a href="/cfapps/ipdbproject/IEDIndex3.php?tid=90&pid=44&aid=8">Total emissions</a></li>
<li>Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>
</ul>
<ul>
<li class="head"><a href="/cfapps/ipdbproject/iedindex3.php?tid=90&amp;pid=45&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MTCDPP">Per capita emissions</a></li>
<li>Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>
</ul>
<ul>
<li class="head"><a href="/cfapps/ipdbproject/iedindex3.php?tid=90&amp;pid=5&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from petroleum consumption</a></li>
<li>Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>
</ul>
<ul>
<li class="head"><a href="/cfapps/ipdbproject/iedindex3.php?tid=90&amp;pid=3&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from natural gas consumption</a></li>
<li>Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>
</ul>
<ul>
<li class="head"><a href="/cfapps/ipdbproject/iedindex3.php?tid=90&amp;pid=1&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from coal consumption</a></li>
<li>Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>
</ul>
<ul>
<li class="head"><a href="/cfapps/ipdbproject/IEDIndex3.php?tid=91&pid=46&aid=31">Energy related carbon intensity</a></li>
<li>Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>
</ul>
</div>
</div>
</div>