<div class="secondary">
	<ul>
		<li class="head"><h2>Most Requested Environment Data</h2></li>
		<li class="sub-head"><strong>Carbon Dioxide Projections from the Annual Energy Outlook</strong></li>
		<li>
			<ul>
				<li><a href="/outlooks/aeo/er/excel/aeotab_18.xlsx" class="ico_xls">Table 18</a></li>
				<li><a href="/outlooks/aeo/er/excel/aeotab_19.xlsx" class="ico_xls">Table 19</a></li>
			</ul>
		</li>
		<li class="sub-head"><strong>Short-Term Energy Outlook Emissions Table</strong></li>
		<li>
			<ul>
			<li><a href="/outlooks/steo/tables/pdf/9atab.pdf" class="ico_pdf">Table 9a</a></li>
			</ul>
		</li>
	</ul>
</div>
