

<!-- Main Column  -->
<p>Find environmental data on carbon dioxide emissions from energy and industry,  by consuming sector (residential, commercial, industrial, transportation,  electric power), and other emissions.</p>
<div class="accordion">
	<div class="expand-collapse-container">
		<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
		<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
	</div>
	<!-- BEGIN Summary Content //////////////// -->
	<h2><i class="ico expand-collapse"></i><a name="summary"></a>Summary</h2>
	<div class="accordion-content">
		<ul>
			<li><strong>U.S. Carbon dioxide emissions from energy consumption (from 1973) </strong></strong></li>
			<?php include('css_rehab/archive/totalenergy/data/monthly/includes/new-mer-header.inc') ?></span> 
			
			<li><strong>By source</strong></strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_3.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By source"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.01&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By source"><i class="ico xls"><span>XLS</span></i></a></li>
			
			<li><strong>By residential sector</strong></strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_5.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By residential sector"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.02&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By residential sector"><i class="ico xls"><span>XLS</span></i></a></li>
			
			<li><strong>By commercial sector </strong></strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_6.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By commercial sector"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.03&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By commercial sector"><i class="ico xls"><span>XLS</span></i></a></li>
			
			<li><strong>By industrial sector</strong></strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_7.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By industrial sector"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.04&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By industrial sector"><i class="ico xls"><span>XLS</span></i></a></li>
			
			<li><strong>By transportation sector</strong></strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_8.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By transportation sector"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.05&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By transportation sector"><i class="ico xls"><span>XLS</span></i></a></li>
			
			<li><strong>By electric power</strong></strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_9.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions By electric power"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.06&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions By electric power"><i class="ico xls"><span>XLS</span></i></a></li>
			
			<li><strong>From biomass</strong></strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_10.pdf" class="ico_pdf" title="U.S. Carbon dioxide emissions From biomass"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.php?tbl=T12.07&amp;freq=m" class="ico_xls" title="U.S. Carbon dioxide emissions From biomass"><i class="ico xls"><span>XLS</span></i></a></li>
			
			<li><strong><a href="/environment/emissions/state/state_emissions.cfm">State CO<sub>2</sub> emissions &rsaquo;</a></strong></li>
			<li><span class="release-date item-divider">Release Date: </span><span class="date">October 24, 2017</span></li>
			
			<li><strong><a href="/environment/emissions/co2_vol_mass.cfm">Fuel carbon dioxide emission coefficients &rsaquo;</a></strong></li>
			<li><span class="release-date item-divider">Release Date: </span><span class="date">February 2, 2016</span></li>
			
			<li><strong>Annual Energy Review carbon data &rsaquo;</strong></li>
			<li><span class="release-date">Release Date: </span><span class="date">September 27, 2012</span> | <span class="date"> data from: <a href="/totalenergy/data/annual/">Annual Energy Review</a></li>
			<li class="additional-formats solid-dashed">Available formats: <a href="/totalenergy/data/annual/pdf/sec11.pdf" class="ico_pdf" title="Annual Energy Review carbon data"><i class="ico pdf"><span>PDF</span></i></a></li>          
		</ul>
	</div>
	<!-- END Summary Content //////////////// -->
	<!-- BEGIN Electric Power Plant Environmental Content //////////////// -->
	<h2><i class="ico expand-collapse"></i><a name="electric"></a>Electric power plant environmental</h2>
	<div class="accordion-content">
		<ul>
			<li class="additional-formats item-divider"><strong><a href="/electricity/annual/html/epa_04_01.html">Number of generators &amp; capacity &rsaquo;</a></strong></li>
			<li class="item-divider"><span class="release-date">Release Date: </span><span class="date">December 7, 2017</span> </span> | <span class="date"> data from: <a href="/electricity/annual/">Electric Power Annual</a></li>

			<li><strong><a href="/electricity/annual/html/epa_09_04.html">Average flue gas desulfurization (scrubber) costs &rsaquo;</a></strong></li>
			<li class="item-divider"><span class="release-date">Release Date: </span><span class="date">December 7, 2017</span> </span> | data from: <span class="date"><a href="/electricity/annual/">Electric Power Annual</a></span></li>

			<li><strong><a href="/electricity/annual/html/epa_09_01.html">Emissions from energy consumption at conventional power plants and combined-heat-and-power &rsaquo;</a></strong></li>
			<li class="item-divider"><span class="release-date">Release Date: </span><span class="date">December 7, 2017</span></span> | data from: <span class="date"><a href="/electricity/annual/">Electric Power Annual</a></li>

			<li><strong><a href="/electricity/annual/html/epa_09_02.html">Quality and net summer capacity of operable environmental equipment &rsaquo;</a></strong></li>
			<li class="solid-dashed"><span class="release-date">Release Date: </span><span class="date">December 7, 2017</span></span> | data from: <span class="date"><a href="/electricity/annual/">Electric Power Annual</a></li>
		</ul>
	</div>
	<!-- END Electric Power Plant Environmental Content //////////////// -->
	<!-- BEGIN International Emissions Content //////////////// -->
	<h2><i class="ico expand-collapse"></i><a name="intl"></a>International emissions</h2>
	<div class="accordion-content">
		<ul>
			<li><strong><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=90&pid=44&aid=8">Total emissions &rsaquo;</a></strong></li>
			<li class="item-divider">Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>

			<li><strong><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=45&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MTCDPP">Per capita emissions &rsaquo;</a></strong></li>
			<li class="item-divider">Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>

			<li><strong><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=5&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from petroleum consumption &rsaquo;</a></strong></li>
			<li class="item-divider">Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>

			<li><strong><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=3&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from natural gas consumption &rsaquo;</a></strong></li>
			<li class="item-divider">Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>

			<li><strong><a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&amp;pid=1&amp;aid=8&amp;cid=&amp;syid=2004&amp;eyid=2010&amp;unit=MMTCD">Emissions from coal consumption &rsaquo;</a></strong></li>
			<li class="item-divider">Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>

			<li><strong><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=91&pid=46&aid=31">Energy related carbon intensity &rsaquo;</a></strong></li>
			<li class="solid-dashed">Data from: <span class="date"><a href="/beta/international/data/browser/">International Energy Statistics</a></li>
		</ul>
	</div>
	<!-- END International Emissions Content //////////////// -->