<div class="secondary">
<ul>
<li class="head"><h2>Most Requested Environment Data</h2></li>
  <li class="sub-head"><strong>Carbon Dioxide Projections from the Annual Energy Outlook</strong></li>
<li>
<ul>
  <li><a href="/outlooks/aeo/er/excel/aeotab_18.xlsx" class="ico_xls">Table 18</a>
</li>
  	<li><a href="/outlooks/aeo/er/excel/aeotab_19.xlsx" class="ico_xls">Table 19</a>
</li></ul>
</li>
<li class="sub-head"><strong>Short-Term Energy Outlook Emissions Table</strong></li>
<li>
<ul>
  	<li><a href="/outlooks/steo/tables/pdf/9atab.pdf" class="ico_pdf">Table 9a</a>
</li></ul>
<?php /* </ul>
</li>
<li class="sub-head"><strong>Emissions Factors</strong></li>
<li>
<ul>
     <li>       <a href="/oiaf/1605/coefficients.html">Gallons &amp; Barrels</a></li>
     <li>         <a href="/oiaf/1605/ggrpt/excel/CO2_coeffs_08.xls">Quadrillion 
                (10<sup>15</sup>) BTU</a></li>
   </ul>
</li>
<li class="sub-head"><strong>Other Greenhouse Gases</strong></li>
<li>
<ul>
  	<li>  		<a href="/environment/emissions/ghg_report/ghg_methane.cfm"> Methane (CH<sub>4</sub>)</a>
</li>
  	<li>  		<a href="/environment/emissions/ghg_report/ghg_nitrous.cfm">Nitrous Oxide (N<sub>2</sub>O)</a>
</li>
  	<li>      <a href="/environment/emissions/ghg_report/ghg_gwp.cfm">High-Global Warming Potential Gases</a>	
</li>
 </ul>
</li>
<li class="sub-head"><strong>Electric Power Plant Environmental Data</strong></li>
<li>
<ul>
 	 <li> 	 	<a href="/electricity/annual/html/table3.10.cfm"> Number of Generators &amp; Capacity</a></li>
 	 <li> 	 	<a href="/electricity/annual/html/table3.11.cfm">Average FGD (Scrubber) Costs</a>
</li>
 </ul><br />

<li class="head"><h2>International Data</h2></li>
<li>
<ul>
 	 <li> 	 	<a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=90&pid=44&aid=8">Total 
                      Emissions </a>
</li>
   <li>   	  <a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&pid=45&aid=8&cid=&syid=2004&eyid=2008&unit=MMTCD">Per capita Emissions</a>
</li>
   <li>   	 <a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&pid=5&aid=8&cid=&syid=2004&eyid=2008&unit=MTCDPP">Emissions from Petroleum Consumption</a>
</li>
   <li>   	<a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&pid=3&aid=8&cid=&syid=2004&eyid=2008&unit=MMTCD">Emissions from Natural Gas Consumption</a>
</li>
   <li>   	<a href="/cfapps/ipdbproject/iedindex3.cfm?tid=90&pid=1&aid=8&cid=&syid=2004&eyid=2008&unit=MMTCD">Emissions from Coal Consumption</a>
</li>
 </ul>
</li>
<li class="sub-head"><strong>Carbon Intensity</strong></li>
<li>
<ul>
 	<li> <a  href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=91&pid=46&aid=31">Energy 
                      Related Carbon Intensity</a>		
</li>
</ul>*/ ?>
</span>  