
<table>
<caption>
Carbon dioxide emissions by fuel<br />
<span class="units">million metric tons</span></caption>
<thead>
	<tr>
	<th>&nbsp;</th>
    <th>2016</th>
    <th>2017</th>
    <th>2018F</th>
    <th>2019F</th>
    </tr>
    </thead>
    <tbody>
        
		<tr>	
		<td>Petroleum and other liquid fuels</td>	
		<td>2,327</td>
		<td>2,338</td>
		<td>2,363</td>
		<td><em>2,385</em></td>
		</tr>
		
			
        <tr>
        <td>Natural gas</td>
		<td>1,496</td>
		<td>1,474</td>
		<td>1,580</td>
		<td><em>1,580</em></td>
		     
        </tr>
		
			
        <tr>
        <td>Coal</td>
		<td>1,354</td>
		<td>1,318</td>	
		<td>1,279</td>	
		<td><em>1,227</em></td>
		      
        </tr>
					
        <tr> 
        <td>Total energy</td>
		<td>5,189</td>	
		<td>5,142</td>		
		<td>5,233</td>		
		<td><em>5,204</em></td>
		</tr>
        
		<tfoot>
        <tr>
        <td colspan="7">Source:  Short-Term Energy Outlook <a href="/outlooks/steo/report/renew_co2.php?src=Environment-b1">Renewables and Carbon Dioxide Emissions</a><br />
        Note: F= Forecast.
</td>
        </tr>
        </tfoot>
        </tbody>
</table>

<?php /*<h2>Updated Data Series</h2>
      <ul class="updated_data">
        <li><span class="series_date">09/09/14</span> <a href="/forecasts/steo/report/coal.cfm">Coal prices</a></li>
        <li><span class="series_date">09/09/14</span> <a href="/forecasts/steo/report/natgas.cfm">Natural Gas prices</a></li>
        <li><span class="series_date">09/09/14</span> <a href="/forecasts/steo/report/us_oil.cfm">Petroleum prices</a></li>
      </ul>*/ ?>


