<table width="100%" border="0" cellpadding="0" cellspacing="0" class="basic_table" >
  <caption>Wholesale spot petroleum prices, 3/27/2017 close</caption>
  <thead>

    <tr>
      <th>Product</th>
      <th style="text-align:right">Area</th>
      <th>Price</th>
      <th style="text-align:right">% change*</th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <td>Crude Oil <i>($/barrel)</i></td>
      <td>WTI</td>
      <td>47.02</td>
      <td>-0.6</li>

    <tr>
      <td>&nbsp;</td>
      <td>Brent</td>
      <td>50.12</td>
      <td>+0.3</li>
    <tr>
      <td>&nbsp;</td>
      <td>Louisiana Light</td>
      <td>48.87</td>
      <td>-0.6</li>
    <tr>
      <td>Gasoline (RBOB) <i>($/gallon)</i></td>
      <td>NY Harbor</td>
      <td>1.46</td>
      <td>+0.5</li>


    <tr>
      <td>&nbsp;</td>
      <td>Gulf Coast</td>
      <td>1.59</td>
      <td>+0.4</li>
    <tr>
      <td>&nbsp;</td>
      <td>Los Angeles</td>
      <td>1.71</td>
      <td>+0.2</li>
    <tr>
      <td>Heating Oil <i>($/gallon)</i></td>
      <td>NY Harbor</td>
      <td>1.46</td>
      <td>-0.3</li>

    <tr>
      <td>&nbsp;</td>
      <td>Gulf Coast</td>
      <td>1.33</td>
      <td>-0.3</li>

    <td nowrap="nowrap"><a href="/todayinenergy/includes/CrackSpread_Explain.cfm">3:2:1 Crack Spread <i>($/barrel)</i></a></td>
    <td>Gulf Coast (LLS)</td>
    <td>16.18</td>
    <td>+2.6</li>

    <tr>
      <td nowrap="nowrap">Low-Sulfur Diesel <i>($/gallon)</i></td>
      <td>NY Harbor</td>
      <td>1.50</td>
      <td>-0.3</li>

    <tr>
      <td>&nbsp;</td>
      <td>Gulf Coast</td>
      <td>1.47</td>
      <td>-0.3</li>
    <tr>
      <td>&nbsp;</td>
      <td>Los Angeles</td>
      <td>1.56</td>
      <td>-0.3</li>
    <tr>
      <td>Propane <i>($/gallon)</i></td>
      <td nowrap="nowrap">Mont Belvieu, TX</td>
      <td>0.56</td>
      <td>-2.7</li>

    <?php /*<div class="t_source">
			<br>*Percent changes based on daily settlement price from previous business day.<br>NA = Data was not available at time of retrieval.  Percent Change column will display NA if data from previous day was not retrieved.<br>
			Sources: CME Group, <img src="/todayinenergy/images/logo-thomsonreuters.gif">, <a href="http://www.snl.com/Sectors/Energy/Default.aspx" target="_blank">SNL Energy</a>, AAA Fuel Gauge Report
		</div>*/ ?>

  </tbody>

  <tfoot>
    <tr>
      <td colspan="4">Source: <a href="/todayinenergy/prices.cfm">Daily Prices</a></li>
  </tfoot>

</table>


