<p>Find statistics on crude oil, gasoline, diesel, propane, jet fuel, ethanol, and other liquid fuels. Click on the blue bars
	below for information on petroleum prices, crude reserves and production, refining and processing, imports/exports, stocks,
	and consumption/sales.</p>
<div class="accordion">
	<div class="expand-collapse-container">
		<i class="ico expand-all">+ Expand all</i>
		<i class="ico collapse-all">- Collapse all</i>
	</div>
	<h2><i class="ico expand-collapse"></i>
		<!-- id="summary --><a name="summary"></a>Summary
		<div class="additional-formats">Additional formats</div>
	</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">Weekly supply estimates</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Production, refinery inputs and utilization, stocks, days of supply, imports, exports, and product supplied estimates for crude oil and petroleum products by U.S., PAD District</li>
			<li><span class="date">weekly and 4-week average</span></li>





			<li class="head"><a href="/dnav/pet/pet_sum_snd_d_nus_mbbl_m_cur.htm">Supply and disposition</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Field production, net production, imports, net receipts, stock changes, net inputs, exports, and product supplied statistics for crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_sum_crdsnd_k_m.htm">U.S. crude oil supply &amp; disposition</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Detailed statistics for crude oil supply, disposition, and ending stocks. Includes statistics for commercial and Strategic Petroleum Reserve sectors</li>





			<li class="head"><a href="/dnav/pet/pet_sum_mkt_dcu_nus_m.htm">Prices, sales volumes &amp; stocks by state</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span></li>
			<li>U.S., PAD District, and state level data includes retail prices, prime supplier sales volumes and stocks</li>





			<li class="head">Petroleum overview</li>
			<li><script src="/totalenergy/data/monthly/txt/new_merheader.txt" type="text/JavaScript"></script> (<a href="/totalenergy/data/monthly/#petroleum" class="no-border">more on petroleum</a>) <div class="additional-formats"><a href="/totalenergy/data/monthly/pdf/sec3_3.pdf"><i class="ico pdf">PDF</i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T03.01"><i class="ico csv">CSV</i></a>					<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.01&amp;freq=m"><i class="ico xls">XLS</i></a></div></li>






			<li class="head"><a href="http://tonto.eia.gov/cfapps/ipdbproject/IEDIndex3.cfm">Petroleum statistics by country</a></li>
			<li class="date">Release Date: Varies</li>
			<li>Query detailed country and regional energy data supply, disposition</li>
			<li><span class="date">annual, selected quarterly, monthly</span></li>
		</ul>
	</div>
	<?php /* END Summary Content ////////////////*/ ?>




















	<h2><i class="ico expand-collapse"></i><a name="prices"></a>Prices</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/petroleum/gasdiesel/">Gasoline and diesel fuel update</a></li>
			<li><script src="/petroleum/gasdiesel/rdate_gdu.txt" type="text/JavaScript"></script>Prices of regular gasoline and on-highway diesel fuel by PAD District. <div class="additional-formats">Additional formats</div></li>
			<li class="date">weekly</li>





			<li class="head"><a href="/petroleum/heatingoilpropane/">Heating Oil and Propane Update</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsrshopp.txt" type="text/JavaScript"></script> Weekly heating oil and propane prices; October through March..</li>
			<li class="date">Weekly</li>

			



			<li class="head"><a href="/dnav/pet/pet_pri_gnd_dcus_nus_w.htm">Weekly retail gasoline and on-highway diesel prices</a></li>
			<li><script src="/petroleum/gasdiesel/rdate_gdu.txt" type="text/JavaScript"></script>Gasoline prices by grade and formulation and diesel prices by sulfur content for U.S., PAD District, selected states and cities</li>
			<li class="date">Weekly</li>

					



			<li class="head">Motor gasoline retail prices, U.S. city average &rsaquo;</li>
			<li><script src="/totalenergy/data/monthly/txt/new_merheader.txt" type="text/JavaScript"></script><div class="additional-formats"><a href="/totalenergy/data/monthly/pdf/sec9_6.pdf "><i class="ico pdf">PDF</i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T09.04"><i class="ico csv">CSV</i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T09.04&amp;freq=m"><i class="ico xls">XLS</i></a></div></li>

			



			<li class="head"><a href="/totalenergy/data/annual/showtext.cfm?t=ptb0524">Motor gasoline retail prices </a><div class="additional-formats"><a href="/totalenergy/data/annual/pdf/sec5_59.pdf"><i class="ico pdf">PDF</i></a> <a href="/totalenergy/data/annual/xls/stb0524.xls"><i class="ico xls">XLS</i></a></div></li>
			<li class="date">Release Date: September 27, 2012</span></li>
			<li>U.S. city average, annual from 1949&#8211;current</li>
			<li class="date">Annual Energy Review</li>






			<li class="head"><a href="/dnav/pet/pet_pri_spt_s1_d.htm">Spot prices</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Crude oil and petroleum products by selected U.S. and international areas</li>
			<li class="date">daily, weekly, monthly, annual</li>





			<li class="head"><a href="/dnav/pet/pet_pri_fut_s1_d.htm">Futures prices (NYMEX)</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Crude oil, motor gasoline, heating oil, and propane</li>
			<li class="date">daily, weekly, monthly, annual</li>





			<li class="head"><a href="/dnav/pet/pet_pri_wfr_dcus_nus_w.htm">Weekly heating oil &amp; propane prices</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsrshopp.txt" type="text/JavaScript"></script> Residential and wholesale prices of heating oil and propane by U.S., selected PAD Districts and states</li>
			<li class="date">weekly, monthly from October - March</li>





			<li class="head">Refiner petroleum product prices by sales type</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span></li>
			<li>Petroleum product retail and wholesale prices by U.S., PAD District and state
				<ul>
					<li><a href="/dnav/pet/pet_pri_refoth_dcu_nus_m.htm">Refiner petroleum product prices by sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_refmg_dcu_nus_m.htm">Refiner gasoline prices by grade, sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_refmg2_d_nus_PTG_dpgal_m.htm">Refiner gasoline prices by formulation, grade, sales type</a></li>
				</ul>
			</li>


	


			<li class="head">Refiner, reseller, and retailer monthly prices (suspended)</li>
			<li><span class="date">Monthly Release Date: May 2, 2011</span></li>
			<li><span class="date">Annual  Release Date: August 6, 2010</span></li>
			<li>Petroleum product retail and wholesale prices by U.S., PAD District and state
				<ul>
					<li><a href="/dnav/pet/pet_pri_allmg_d_nus_PTA_dpgal_m.htm">Gasoline prices by formulation, grade, sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_dist_dcu_nus_m.htm">No. 2 distillate prices by sales type and selected states</a></li>
					<li><a href="/dnav/pet/pet_pri_prop_dcu_nus_m.htm">Propane (consumer grade) prices by sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_resid_dcu_nus_m.htm">Residual fuel oil prices by sales type</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/pet_pri_rac2_dcu_nus_m.htm">Refiner acquisition cost of crude oil</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span></li>
			<li>Domestic, imported, and composite costs by U.S. and PAD Districts</li>





			<li class="head">Domestic crude oil first purchase prices</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span>
				<ul>
					<li><a href="/dnav/pet/pet_pri_dfp1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_pri_dfp2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_pri_dfp3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head">F.O.B. costs of imported crude oil</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span>
				<ul>
					<li><a href="/dnav/pet/pet_pri_imc1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_pri_imc2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_pri_imc3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head">Landed costs of imported crude oil</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span>
				<ul>
					<li><a href="/dnav/pet/pet_pri_land1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_pri_land2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_pri_land3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head"><a href="/outlooks/steo/realprices/">Real U.S. petroleum prices (past &amp; projected)</a></li>
			<li><script src="/outlooks/steo/includes/rdate_steo.txt" type="text/JavaScript"></script> Real and nominal U.S. prices for gasoline, heating oil, diesel fuel, and imported crude oil</li>
			<li class="date">monthly, annual; past and projected values</li>
		</ul>
	</div>





















	<h2><i class="ico expand-collapse"></i><a name="crude"></a>Crude reserves and production</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_crd_crpdn_adc_mbbl_m.htm">Crude oil production</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> by U.S., PAD District and state</li>





			<li class="head"><a href="/dnav/pet/pet_crd_api_adc_mbblpd_m.htm">Crude Oil and Lease Condensate Production by API Gravity</a> &rsaquo;</li>
			<li>Monthly crude oil production by API gravity data collected on Form EIA-914 (Monthly Crude Oil, Lease Condensate, and Natural Gas Production Report) <span class="date">monthly</span></li>





			<li class="head"><a href="/energyexplained/images/charts/u.s.tight_oil_production.jpg" class="lightbox">Tight oil production estimates by play</a>					&rsaquo;
			<div class="additional-formats"><a href="/energyexplained/data/U.S. tight oil production.xlsx"><i class="ico xls">XLS</i></a></div></li>
			<li class="date"><span class="date">Release Date: `monthly</span></li>
			<li>Estimated monthly production derived from state administrative data</li>
			<li class="date">monthly</li>






			<li class="head">Proved reserves, reserves changes, and production</li>
			<li class="date">Release Date: February 13, 2018</span>
				<ul>
					<li><a href="/dnav/pet/pet_crd_pres_dcu_NUS_a.htm">Crude oil</a><a href="/emeu/international/ngasprie.html"></a></li>
					<li><a href="/dnav/pet/pet_crd_cplc_dcu_NUS_a.htm">Crude oil plus lease condensate</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/PET_CRD_NPROD_DCU_NUS_A.htm">Proved nonproducing reserves</a></li>
			<li class="date">Release Date: February 13, 2018</span></li>
			<li>Reported proved reserves of crude oil, lease condensate, and wet natural gas, after lease separation by U.S., region, and state</li>
			<li class="date">annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_gom_s1_a.htm">Gulf of Mexico Federal Offshore production</a></li>
			<li class="date">Release Date: November 19, 2015</span></li>
			<li>Production of crude oil, natural gas wet after lease separation, natural gas liquids, dry natural gas, and lease condensate</li>
			<li class="date">annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_drill_s1_m.htm">Crude oil and natural gas drilling activity</a></li>
			<li><script src="/dnav/pet/includes/rdate_petmer.txt" type="text/JavaScript"></script> Rotary rigs in operation, footage drilled, and active well service rig counts</li>
			<li class="date">monthly, annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_wellend_s1_m.htm">Crude oil and natural gas exploratory and development wells</a></li>
			<li><script src="/dnav/pet/includes/rdate_petmer.txt" type="text/JavaScript"></script> Exploratory and development wells drilled for crude oil, natural gas and dry holes; total footage drilled</li>
			<li class="date">monthly, annual></li>





			<li class="head"><a href="/dnav/pet/pet_crd_wellfoot_s1_a.htm">Footage drilled for crude oil and natural gas wells</a></li>
			<li><script src="/dnav/pet/includes/rdate_petmer.txt" type="text/JavaScript"></script> Footage drilled by exploratory and development wells and by crude oil, natural gas, and dry holes</li>
			<li class="date">annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_welldep_s1_a.htm">Average depth of crude oil and natural gas wells</a></li>
			<li><script src="/dnav/pet/includes/rdate_petmer.txt" type="text/JavaScript"></script> Average depth of wells drilled by exploratory and development wells and by crude oil, natural gas, and dry holes</li>
			<li class="date">annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_wellcost_s1_a.htm">Costs of crude oil and natural gas wells drilled</a></li>
			<li><script src="/dnav/pet/includes/rdate_petmer.txt" type="text/JavaScript"></script> Per well and per foot costs of crude oil, natural gas, and dry hole wells</li>
			<li class="date">annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_seis_s1_m.htm">Maximum U.S. active seismic crew counts</a></li>
			<li><script src="/dnav/pet/includes/rdate_petmer.txt" type="text/JavaScript"></script> by onshore/offshore/Alaska and dimension</li>
			<li class="date">monthly</li>





			<li class="head"><a href="/petroleum/production/">Monthly Crude Oil and Natural Gas Production</a></li>
			<li><script src="/petroleum/production/includes/rdate_914.txt" type="text/JavaScript"></script> Monthly crude oil and natural gas production data collected on Form EIA-914 (Monthly Crude Oil, Lease Condensate,
				and Natural Gas Production Report)</li>
			<li class="date">monthly</li>





			<li class="head"><a href="/naturalgas/archive/cost_indices_equipment_production/current/coststudy.html">Oil and gas lease equipment and operating costs 1994 Through 2009</a></li>
			<li class="date">Release Date: September 28, 2010</span></li>
			<li>Regional and national oil and gas equipping and operating cost trends.</li>
			<li class="date">annual</li>





			<li class="head"><a href="/naturalgas/fieldcode/">Oil and gas county code master list</a></li>
			<li><script src="/naturalgas/fieldcode/includes/rdate_fcml.txt" type="text/JavaScript"></script> Comprehensive listing of U.S. oil and gas field names.</li>
			<li class="date">annual</li>





			<li class="head"><a href="/petroleum/wells/">Distribution and production of oil &amp; gas wells</a></li>
			<li class="date">Release Date: December 11, 2017</span></li>
			<li>State level tables and graphs</li>
			<li class="date">annual</li>
		</ul>
	</div>




















	<h2><i class="ico expand-collapse"></i><a name="refining"></a>Refining and processing <div class="additional-formats">Additional formats</div></h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_pnp_wiup_dcu_nus_w.htm">Weekly inputs &amp; utilization</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Refiner inputs, operable capacity, percent utilization, and refinery and blender net inputs by U.S. and PAD District</li>
			<li class="date">weekly, 4-week average</li>





			<li class="head">Weekly production</li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Production of petroleum products by U.S. and PAD District</li>
			<li><span class="date">weekly, 4-week average</span>
				<ul>
					<li><a href="/dnav/pet/pet_pnp_wprodrb_dcu_nus_w.htm">Refiner &amp; blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_wprodr_s1_w.htm">Refiner</a></li>
					<li><a href="/dnav/pet/pet_pnp_wprodb_s1_w.htm">Blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_wprode_s1_w.htm">Ethanol plant</a></li>
				</ul>
			</li>





			<li class="head">Net input</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Net input of crude oil and petroleum products by PAD and Refining Districts</li>
			<li>
				<ul>
					<li><a href="/dnav/pet/pet_pnp_inpt_dc_nus_mbbl_m.htm">Refiner & blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_inpt2_dc_nus_mbbl_m.htm">Refiner</a></li>
					<li><a href="/dnav/pet/pet_pnp_inpt3_dc_nus_mbbl_m.htm">Blender</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_unc_dcu_nus_m.htm">Refinery utilization and capacity</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Gross input to crude distillation units, operable capacity and utilization rate by PAD and Refining Districts</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_crq_dcu_nus_m.htm">Crude oil input qualities</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil sulfur content and API</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_dwns_dc_nus_mbblpd_m.htm">Downstream processing of fresh feed input</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Catalytic cracking, catalytic hydrocracking, and delayed and fluid coking by PAD and Refining Districts</li>





			<li class="head">Net production</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Net production of finished petroleum products by PAD and Refining Districts</li>
			<li>
				<ul>
					<li><a href="/dnav/pet/pet_pnp_refp_dc_nus_mbbl_m.htm">Refiner & blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_refp2_dc_nus_mbbl_m.htm">Refiner</a></li>
					<li><a href="/dnav/pet/pet_pnp_refp3_dc_nus_mbbl_m.htm">Blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_oxy_dc_nus_mbbl_m.htm">Oxygenate (ethanol and MTBE)</a></li>
				</ul>
	</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_pct_dc_nus_pct_m.htm">Refinery yield</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Percent yield of petroleum products by PAD and Refining Districts</li>





			<li class="head">Refinery Capacity</li>
			<li class="date">Release Date: June 21, 2017</li>
			<li>By U.S., PAD District and state</li>
			<li><span class="date">annual</span>
				<ul>
					<li><a href="/dnav/pet/pet_pnp_cap1_dcu_nus_a.htm">Number and capacity</a></li>
					<li><a href="/dnav/pet/pet_pnp_capprod_dcu_nus_a.htm">Production capacity</a></li>
					<li><a href="/dnav/pet/pet_pnp_capchg_dcu_nus_a.htm">Downstream charge capacity</a></li>
					<li><a href="/dnav/pet/pet_pnp_capwork_dcu_nus_a.htm">Working storage capacity</a> (historical data 1982 - 2010)</li>
					<li><a href="/dnav/pet/pet_pnp_capshell_dcu_nus_a.htm">Shell storage capacity</a> (historical data 1982 - 2010)</li>
					<li><a href="/dnav/pet/pet_pnp_caprec_dcu_nus_a.htm">Receipts of crude oil by method of transport</a></li>
					<li><a href="/dnav/pet/pet_pnp_capfuel_dcu_nus_a.htm">Fuel consumed at refineries</a></li>
					<li><a href="/dnav/pet/pet_pnp_feedng_k_a.htm">Natural gas used as feedstock for hydrogen production</a></li>
					<li><a href="/petroleum/refinerycapacity/">Refinery capacity report</a></li>
					<li>Refinery capacity data by individual refinery as of January 1, 2017 <div class="additional-formats"><a href="/petroleum/refinerycapacity/refcap17.xls"><i class="ico xls">XLS</i></a></div></li>
					<li><a href="/totalenergy/data/annual/showtext.cfm?t=ptb0509">Refinery capacity and utilization data, annual 1949 - 2011</a> <div class="additional-formats"><a href="/totalenergy/data/annual/pdf/sec5_23.pdf"><i class="ico pdf">PDF</i></a> <a href="/totalenergy/data/annual/xls/stb0509.xls"><i class="ico xls">XLS</i></a></div></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_gp_dc_nus_mbbl_m.htm">Natural gas plant field production</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Net production of petroleum products by PAD and Refining Districts</li>





			<li class="head"><a href="/petroleum/ethanolcapacity/">U.S. fuel ethanol plant production capacity</a></li>
			<li><span class="date">Release Date:  June 20, 2017</span></li>
			<li>The U.S. Energy Information Administration released its annual fuel ethanol production capacity report. The new report contains data for all operating U.S. fuel ethanol production plants as of January 1, 2017.</li>
			<li class="date">annual</li>





			<li class="head"><a href="/biofuels/biodiesel/production/">Monthly biodiesel production</a></li>
			<li><span class="date">Monthly</span> <script src="/biofuels/biodiesel/production/includes/rdate_biodiesel.txt" type="text/JavaScript"></script> The U.S. Energy Information Administration release showing national and regional monthly biodiesel production. In addition to biodiesel production, data included producer sales, producer stocks, and feedstock inputs.</li>
			</ul>
		</div>

















	<h2><i class="ico expand-collapse"></i><a name="imports"></a>Imports/exports &amp; movements</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_move_wkly_dc_NUS-Z00_mbblpd_w.htm">Weekly imports &amp; exports</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Crude oil and petroleum products by U.S. and PAD District</li>
			<li class="date">weekly, 4-week average</li>





			<li class="head"><a href="/dnav/pet/pet_move_wimpc_s1_w.htm">Weekly preliminary crude imports by country of origin</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> U.S. crude oil imports</li>
			<li class="date">weekly, 4-week average</li>





			<li class="head"><a href="/dnav/pet/pet_move_imp_dc_NUS-Z00_mbbl_m.htm">Imports by area of entry</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_move_imp2_dc_R10-Z00_mbbl_m.htm">Imports by processing area</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_move_impcus_a2_nus_ep00_im0_mbbl_m.htm">U.S. imports by country of origin</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and petroleum products by country of origin</li>





			<li class="head"><a href="/dnav/pet/pet_move_impcp_a2_r10_ep00_ip0_mbbl_m.htm">PAD District imports by country of origin</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and unfinished oils by country of origin</li>





			<li class="head"><a href="/petroleum/imports/companylevel/">Company level imports</a></li>
			<li><script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> Crude oil and total petroleum imports by the top 15 countries (monthly) and a summary of crude oil imports by company from the Persian Gulf (year-to-date).</li>





			<li class="head"><a href="/dnav/pet/pet_move_res_dc_nus-Z00_mbbl_m.htm">Residual fuel imports by state of entry</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> by U.S., PAD District, state</li>





			<li class="head"><a href="/dnav/pet/pet_move_ipct_k_m.htm">Percentages of total imported crude oil by API gravity</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span>





			<li class="head"><a href="/dnav/pet/pet_move_exp_dc_NUS-Z00_mbbl_m.htm">Exports</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_move_expc_a_EP00_EEX_mbbl_m.htm">Exports by destination</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> by country of export destination</li>





			<li class="head"><a href="/dnav/pet/pet_move_neti_a_EP00_IMN_mbblpd_m.htm">U.S. net imports by country</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and petroleum products by country and region</li>





			<li class="head">Movements between PAD Districts</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script>
				<ul>
					<li><a href="/dnav/pet/pet_move_ptb_dc_R20-R10_mbbl_m.htm">By pipeline, tanker, barge, and rail</a></li>
					<li><a href="/dnav/pet/pet_move_pipe_dc_R20-R10_mbbl_m.htm">By pipeline</a></li>
					<li><a href="/dnav/pet/pet_move_tb_dc_R20-R10_mbbl_m.htm">By tanker and barge</a></li>
					<li><a href="/dnav/pet/PET_MOVE_RAIL_A_EPC0_RAIL_MBBL_M.htm">By rail</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/PET_MOVE_RAILNA_A_EPC0_RAIL_MBBL_M.htm">Movements of Crude Oil and Selected Products by Rail</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script></li>





			<li class="head"><a href="/dnav/pet/pet_move_netr_d_r10-z0p_VNR_mbbl_m.htm">Net receipts of crude oil and petroleum products by pipeline, tanker, barge, and rail</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script></li>





			<li class="head">F.O.B. costs of imported crude oil</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span>				<ul>
					<li><a href="/dnav/pet/pet_move_imc1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_move_imc2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_move_imc3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head">Landed costs of imported crude oil</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span>
				<ul>
					<li><a href="/dnav/pet/pet_move_land1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_move_land2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_move_land3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>
		</ul>
	</div>




















	<h2><i class="ico expand-collapse"></i><a name="stocks"></a>Stocks</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_stoc_wstk_dcu_nus_w.htm">Weekly stocks</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Crude oil and petroleum products by U.S. and PAD District</li>
			<li class="date">weekly</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_ts_dcu_nus_m.htm">Stocks of motor gasoline, distillate fuel oil, residual fuel oil, propane, and propylene</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Stocks of selected petroleum products by U.S., PAD District, and sub-PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_typ_d_nus_SAE_mbbl_m.htm">Stocks by type</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_st_dc_NUS_mbbl_m.htm">Refinery, bulk terminal, and natural gas plant stocks by state</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and petroleum products</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_ref_dc_nus_mbbl_m.htm">Refinery stocks</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Crude oil and petroleum products by U.S., PAD and Refining District</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_cu_s1_m.htm">Crude oil stocks at tank farms & pipelines</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> by U.S., PAD District, and Cushing, Oklahoma</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_gp_dcu_nus_m.htm">Natural gas plant stocks</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> Petroleum products by U.S., PAD and Refining District</li>





			<li class="head"><a href="/petroleum/storagecapacity/">Working and net available shell storage capacity</a></li>
			<li class="date">Release Date: November 30, 2017</li>
			<li>Working and net available shell storage capacity as of March 31, 2017 is the U.S. Energy Information Administration's (EIA) report containing semi-annual storage capacity data. It includes three tables detailing working and net available shell storage capacity by facility type, product, and PAD District as of March 31.</li>
			<li class="date">semi-annual</li>
		</ul>
	</div>










	<h2><i class="ico expand-collapse"></i><a name="consumption"></a>Consumption/sales</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_cons_wpsup_k_w.htm">U.S. weekly product supplied</a></li>
			<li><script src="/petroleum/supply/weekly/includes/rdate_wpsr.txt" type="text/JavaScript"></script> Measures the disappearance of petroleum products from primary sources; approximately represents consumption of petroleum products.</li>
			<li class="date">weekly, 4-week average</li>





			<li class="head"><a href="/dnav/pet/pet_cons_psup_dc_nus_mbbl_m.htm">Product supplied</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/supply/monthly/includes/rdate_psm.txt" type="text/JavaScript"></script> <span class="date">Annual</span> <script src="/petroleum/supply/annual/volume1/includes/rdate_psa.txt" type="text/JavaScript"></script> by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_cons_prim_dcu_nus_m.htm">Prime supplier sales volumes</a></li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/prime/includes/rdate_psr.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: April 1, 2013</span></li>
			<li>Sales of petroleum products by refiners, gas plant operators, importers and large inter-state distributors into the final local markets of consumption by U.S., PAD District, State</li>





			<li class="head">Refiner sales volumes</li>
			<li><span class="date">Monthly</span> <script src="/petroleum/marketing/monthly/includes/rdate_pmm.txt" type="text/JavaScript"></script> <span class="date">Annual  Release Date: June 1, 2016</span></li>
			<li>by U.S., PAD District, state and sales type
				<ul>
					<li><a href="/dnav/pet/pet_cons_refmg_d_nus_VTR_mgalpd_m.htm">Motor gasoline</a></li>
					<li><a href="/dnav/pet/pet_cons_refres_d_nus_VTR_mgalpd_m.htm">Residual fuel oil and No. 4 fuel oil</a></li>
					<li><a href="/dnav/pet/pet_cons_refoth_d_nus_VTR_mgalpd_m.htm">Other products</a></li>
				</ul>
			</li>





			<li class="head">Sales of fuel oil and kerosene</li>
			<li><script src="/petroleum/fueloilkerosene/includes/rdate_foks.txt" type="text/JavaScript"></script> by U.S., PAD District, state</li>
			<li><span class="date">annual</span>
				<ul>
					<li><a href="/dnav/pet/pet_cons_821dst_dcu_nus_a.htm">Distillate by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821rsd_dcu_nus_a.htm">Residual fuel oil by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821ker_dcu_nus_a.htm">Kerosene by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821use_dcu_nus_a.htm">Distillate and kerosene by end use</a></li>
				</ul>
			</li>





			<li class="head">Adjusted sales of fuel oil and kerosene</li>
			<li><script src="/petroleum/fueloilkerosene/includes/rdate_foks.txt" type="text/JavaScript"></script> by U.S., PAD District, state</li>
			<li><span class="date">annual</span>
				<ul>
					<li><a href="/dnav/pet/pet_cons_821dsta_dcu_nus_a.htm">Distillate by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821rsda_dcu_nus_a.htm">Residual fuel oil by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821kera_dcu_nus_a.htm">Kerosene by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821usea_dcu_nus_a.htm">Distillate and kerosene by end use</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>