<a name="weeklies"></a>
<div class="primary-alt">
    <ul class="accent">
        <li class="head"><h2>Regular Weekly Releases*</h2></li>
        <li class="sub-head"><h3>Monday</h3></li>
        <li class="list-spacer">
            <ul>
                <li><a href="/petroleum/gasdiesel/">Gasoline and Diesel Fuel Update</a></li>
                <li class="release-schedule">Usually Monday by 5:00 p.m. Eastern Time</li>
            </ul>
        </li>
        <li class="sub-head"><h3>Wednesday</h3></li>
        <li class="list-spacer">
            <ul>
                <li><a href="/oil_gas/petroleum/data_publications/weekly_petroleum_status_report/wpsr.html">Weekly Petroleum Status Report</a></li>
                <li class="release-schedule">10:30 a.m. Eastern Time</li>
            </ul>
            <ul>
                <li><a href="/petroleum/weekly/">This Week in Petroleum</a></li>
                <li class="release-schedule">After 1:00 p.m. Eastern Time</li>
            </ul>
            <ul>
                <li><a href="/petroleum/heatingoilpropane/">Heating Oil and Propane Update</a><li>
                <li class="release-schedule">After 1:00 p.m. Eastern Time (Oct - March)</li>
            </ul>
        </li>

        <li class="release-schedule">*No releases: Monday, Tuesday, or Friday. Releases change on weeks with Federal holidays.</li>
    </ul>
</div>