<div class="secondary">
    <ul>
        <li class="head">
            <h2>Most Requested Coal Data</h2>
        </li>
        <li class="icon sub-head"><a href="/coal/annual/pdf/table28.pdf" title="PDF format: "><i class="ico pdf"><span>PDF</span></i>Prices</a></li>
        <li>
            <ul>
                <li class="icon"><a href="/coal/annual/pdf/table33.pdf" title="PDF format: Average Sales Prices"><i class="ico pdf"><span>PDF</span></i>Average sales prices</a></li>
            </ul>
        </li>
        <li class="icon sub-head"><a href="/coal/production/quarterly/pdf/t1p01p1.pdf" title="PDF format: "><i class="ico pdf"><span>PDF</span></i>Production</a></li>
        <li>
            <ul>
                <li class="icon"><a href="/coal/annual/pdf/table1.pdf" title="PDF format: Production &amp; Number of Mines"><i class="ico pdf"><span>PDF</span></i>Production &amp; number of mines</a></li>
            </ul>
        </li>
        <li>
            <ul>
                <li class="icon"><a href="/coal/annual/pdf/table21.pdf" title="PDF format: Productivity & Employees"><i class="ico pdf"><span>PDF</span></i>Productivity &amp; employees</a></li>
            </ul>
        </li>
        <li class="sub-head"><a href="/coal/reserves/" title="html format: Reserves">Reserves</a></li>
        <li class="sub-head">Consumption</li>
        <li>
            <ul>
                <li class="icon"><a class="subcategory" href="/coal/production/quarterly/pdf/t32p01p1.pdf" title="PDF format: Consumption by End-Use Sector"><i class="ico pdf"><span>PDF</span></i>By end-use sector</a></li>
            </ul>
        </li>
        <li>
            <ul>
                <li class="icon"><a class="subcategory" href="/coal/annual/pdf/table26.pdf" title="PDF format: by End-Use Sector for Census Division & State"><i class="ico pdf"><span>PDF</span></i>By end-use  sector for Census division &amp; state</a></li>
            </ul>
        </li>
        <li>
            <ul>
                <li class="icon"><a href="/coal/production/quarterly/pdf/t35p01p1.pdf" title="PDF format: Consumption at Manufacturing Plants"><i class="ico pdf"><span>PDF</span></i>At manufacturing plants</a></li>
            </ul>
        </li>
        <li class="icon sub-head"><a href="/coal/production/quarterly/pdf/t37p01p1.pdf" title="PDF format: "><i class="ico pdf"><span>PDF</span></i>Stocks</a></li>
        <li class="sub-head">Imports &amp; exports</li>
        <li>
            <ul>
                <li class="icon"><a class="subcategory" href="/coal/production/quarterly/pdf/t18p01p1.pdf" title="PDF format: Coal Imports"><i class="ico pdf"><span>PDF</span></i>Coal imports</a></li>
            </ul>
        </li>
        </li>
        <li>
            <ul>
                <li class="icon"><a class="subcategory" href="/coal/production/quarterly/pdf/t7p01p1.pdf" title="PDF format: Coal Exports"><i class="ico pdf"><span>PDF</span></i>Coal exports</a></li>
            </ul>
        </li>
    </ul>
</div>