<div class="secondary">
	<ul>
		<li class="head">
			<h2>Most requested coal data</h2>
		</li>
		<li class="icon sub-head"><a href="/coal/annual/pdf/table28.pdf" title="pdf format: ">Prices</a>
			<a>
				<i class="ico pdf">
					<span>PDF</span>
				</i>
			</a>
		</li>
		<li>
			<ul>
				<li class="icon"><a href="/coal/annual/pdf/table33.pdf" title="html format: Average Sales Prices">Average sales prices</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
		<li class="icon sub-head"><a href="/coal/production/quarterly/pdf/t1p01p1.pdf" title="pdf format: ">Production</a>
			<a>
				<i class="ico pdf">
					<span>PDF</span>
				</i>
			</a>
		</li>
		<li>
			<ul>
				<li class="icon"><a href="/coal/annual/pdf/table1.pdf" title="pdf format: Production &amp; Number of Mines">Production &amp; number of mines</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
		<li>
			<ul>
				<li class="icon"><a href="/coal/annual/pdf/table21.pdf" title="pdf format: Productivity & Employees">Productivity & employees</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
		<li class="sub-head"><a href="/coal/reserves/" title="html format: Reserves">Reserves</a></li>
		<li class="sub-head">Consumption</li>
		<li>
			<ul>
				<li class="icon"><a class="subcategory" href="/coal/production/quarterly/pdf/t32p01p1.pdf"
						title="PDF format: Consumption by End-Use Sector">By end-use sector</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
		<li>
			<ul>
				<li class="icon"><a class="subcategory" href="/coal/annual/pdf/table26.pdf"
						title="PDF format: by End-Use Sector for Census Division & State">By end-use  sector for Census division & state</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
		<li>
			<ul>
				<li class="icon"><a href="/coal/production/quarterly/pdf/t35p01p1.pdf"
						title="PDF format: Consumption at Manufacturing Plants">At manufacturing plants</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
		<li class="icon sub-head"><a href="/coal/production/quarterly/pdf/t37p01p1.pdf" title="PDF format: ">Stocks</a>
			<a>
				<i class="ico pdf">
					<span>PDF</span>
				</i>
			</a>
		</li>
		<li class="sub-head">Imports &amp; exports</li>
		<li>
			<ul>
				<li class="icon"><a class="subcategory" href="/coal/production/quarterly/pdf/t18p01p1.pdf"
						title="PDF format: Coal Imports">Coal imports</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
		</li>
		<li>
			<ul>
				<li class="icon"><a class="subcategory" href="/coal/production/quarterly/pdf/t7p01p1.pdf"
						title="PDF format: Coal Exports">Coal exports</a>
					<a>
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</li>
	</ul>
</div>