<div class="content-container light-top-border-container grey-background">
<ul>
<li class="head"><h2>Most requested coal data</h2></li>
<li class="sub-head"><strong><a href="/coal/annual/pdf/table28.pdf" title="pdf format: ">Prices</a></strong></li>
<li>
<ul>
  <li><a href="/coal/annual/pdf/table33.pdf" title="html format: Average Sales Prices">Average sales prices</a></li>
</ul>
</li>
<li class="sub-head"><strong><a href="/coal/production/quarterly/pdf/t1p01p1.pdf" title="pdf format: ">Production</a></strong></li>
<li>
<ul>
  <li><a href="/coal/annual/pdf/table1.pdf" title="pdf format: Production &amp; Number of Mines">Production &amp; number of mines</a></li>
  <li><a href="/coal/annual/pdf/table21.pdf" title="pdf format: Productivity & Employees">Productivity & employees</a></li>
</ul>
</li>
<li class="sub-head"><strong><a href="/coal/reserves/" title="html format: Reserves">Reserves</a></strong></li>
<li class="sub-head"><strong>Consumption</strong></li>
<li>
<ul>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t32p01p1.pdf" title="html format: Consumption by End-Use Sector">By end-use sector</a></li>
  <li><a class="subcategory" href="/coal/annual/pdf/table26.pdf" title="html format: by End-Use Sector for Census Division & State">By end-use  sector for Census division & state</a></li>
  <li><a href="/coal/production/quarterly/pdf/t35p01p1.pdf" title="html format: Consumption at Manufacturing Plants">At manufacturing plants</a></li>
</ul>
</li>
<li class="sub-head"><strong><a href="/coal/production/quarterly/pdf/t37p01p1.pdf" title="html format: ">Stocks</a></b>
<li class="sub-head"><strong>Imports &amp; exports</strong></li>
<li>
<ul>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t18p01p1.pdf" title="html format: Coal Imports">Coal imports</a></li>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t7p01p1.pdf" title="html format: Coal Exports">Coal exports</a></li>
</ul>
</li>
</ul>
</div>