<div class="content-container basic-table">
    <h1>Recent Data</h1>
    <?php /*include('/analysis/includes/data_table_excel.inc') */?>
	<?php /*<?php include ('includes/data_table_electric_test.inc') ; ?>*/ ?>
	<?php include ('includes/data_table1.inc') ; ?>
	<?php /* <?php include ('includes/data_table2.inc') ; ?>*/ ?>
    <ul class="basic_table">
        <li class="foot"><a href="data.php">See more data</a></li>
	</ul>
</div>