      <?php /* List Promo/Dark Blue Top Example */ ?>
      <span class="dblue_side_top blue_top "><b>Regular Weekly Releases*</b></span>
      <span class="grey_side side_list2">
        <li class="head"><h2>Monday</h2></li>
          <p><a href="/cneaf/coal/page/nymex/nymex_report.html">NYMEX Coal Futures  &rsaquo;</a><br />
          <i>By 5:00 p.m. EST</i></p>
        <br />
		<li class="head"><h2>Tuesday</h2></li>
          <p class="no-border"><i>No weekly releases</i></p><br />
		<li class="head"><h2>Wednesday</h2></li>
          <p><i>No weekly releases</i></p>
          <br />
		<li class="head"><h2>Thursday        </h2></li>
		<p class="no-border"><a href="/cneaf/coal/weekly/weekly_html/wcppage.html">Weekly Coal Production &rsaquo;</a><br />
          <i>By 5:00 p.m. EST</i></p><br />
		<li class="head"><h2>Friday</h2></li>
          <p><i>No weekly releases</i></p>
          <p class="no-border"><i>*Releases change on weeks with Federal holidays</i></p>
      </span>
      <div class="content-container light-top-border-container grey-background">
  <p class="ico_reports">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/calendar/reports.html">Full list of upcoming reports</a></p>
          <p class="ico_email">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Sign up for email notifications </a></p>
          <p class="ico_rss">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Get the What's New RSS feed </a></p>
      </span>
      <?php /* List Promo/Dark Blue Top Example */ ?>