<span class="grey_side blue_top">
<h4>Most requested coal data</h4>
<p class="no-border"><b><a href="/coal/annual/pdf/table28.pdf" title="pdf format: ">Prices</a></b></p>
<ul>
  <li><a href="/coal/annual/pdf/table33.pdf" title="html format: Average Sales Prices">Average sales prices</a></li>

</ul>
<p class="no-border"><b><a href="/coal/production/quarterly/pdf/t1p01p1.pdf" title="pdf format: ">Production</a></b></p>
<ul>
  <li><a href="/coal/annual/pdf/table1.pdf" title="pdf format: Production &amp; Number of Mines">Production &amp; number of mines</a> </li>
  <li><a href="/coal/annual/pdf/table21.pdf" title="pdf format: Productivity & Employees">Productivity & employees</a> </li>
</ul>
<p class="no-border"><b><a href="/coal/reserves/" title="html format: Reserves">Reserves</a></b></p>
<p class="no-border"><b>Consumption</b></p>
<ul>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t32p01p1.pdf" title="html format: Consumption by End-Use Sector">By end-use sector</a> </li>
  <li><a class="subcategory" href="/coal/annual/pdf/table26.pdf" title="html format: by End-Use Sector for Census Division & State">By end-use  sector for Census division & state</a></li>
  <li><a href="/coal/production/quarterly/pdf/t35p01p1.pdf" title="html format: Consumption at Manufacturing Plants">At manufacturing plants</a> </li>
</ul>
<p class="no-border"><b><a href="/coal/production/quarterly/pdf/t37p01p1.pdf" title="html format: ">Stocks</a></b>
<p class="no-border"><strong>Imports &amp; exports</strong></p>
<ul>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t4p01p1.pdf" title="html format: Coal Imports">Coal imports</a></li> 
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t4p01p1.pdf" title="html format: Coal Exports">Coal exports</a> </li> 
</ul>

</span>
<?php /*
cfinclude template="side_content.cfm"
<span class="dblue_side_top blue_top "><b>Regular Weekly Releases*</b></span>
  <span class="grey_side side_list2">
  <h4>Monday</h4>
  <p class="no-border"><a href="/coal/page/nymex/nymex_report.html">Weekly NYMEX Coal Futures&rsaquo;</a></p>
  <p class="no-border"><a href="/coal/page/coalnews/coalmar.html">Coal News &amp; Markets &rsaquo;</a></p>
  <br />
  <h4>Thursday</h4>
  <p class="no-border"><a href="/coal/weekly/weekly_html/wcppage.html">Weekly Coal Production &rsaquo;</a></p>

  </span>
</span>*/ ?>
