      <?php /* List Promo/Dark Blue Top Example */ ?>
      <span class="dblue_side_top blue_top "><b>Regular Weekly Releases*</b></span>
      <span class="grey_side side_list2">
        <h4>Monday</h4>
          <p><a href="/cneaf/coal/page/nymex/nymex_report.html">NYMEX Coal Futures  &rsaquo;</a><br />
          <i>By 5:00 p.m. EST</i></p>
        <br />
		<h4>Tuesday</h4>
          <p class="no-border"><i>No weekly releases</i></p><br />
		<h4>Wednesday</h4>
          <p><i>No weekly releases</i></p>
          <br />
		<h4>Thursday        </h4>
		<p class="no-border"><a href="/cneaf/coal/weekly/weekly_html/wcppage.html">Weekly Coal Production &rsaquo;</a><br />
          <i>By 5:00 p.m. EST</i></p><br />
		<h4>Friday</h4>
          <p><i>No weekly releases</i></p>
          <p class="no-border"><i>*Releases change on weeks with Federal holidays</i></p>
      </span>
      <span class="grey_side blue_top">
  <p class="ico_reports">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/calendar/reports.html">Full list of upcoming reports</a></p>
          <p class="ico_email">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Sign up for email notifications </a></p>
          <p class="ico_rss">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Get the What's New RSS feed </a></p>
      </span>
      <?php /* List Promo/Dark Blue Top Example */ ?>