<div class="secondary">
<ul>
<li class="head"><h2>Most requested coal data</h2></li>
<li class="sub-head"><strong><a href="/coal/annual/pdf/table28.pdf" title="pdf format: ">Prices</a></strong></li>
<li>
<ul>
  <li><a href="/coal/annual/pdf/table33.pdf" title="PDF format: Average Sales Prices">Average sales prices</a></li>

</ul>
</li>
<li class="sub-head"><strong><a href="/coal/production/quarterly/pdf/t1p01p1.pdf" title="pdf format: ">Production</a></strong></li>
<li>
<ul>
  <li><a href="/coal/annual/pdf/table1.pdf" title="pdf format: Production &amp; Number of Mines">Production &amp; number of mines</a></li>
  <li><a href="/coal/annual/pdf/table21.pdf" title="pdf format: Productivity & Employees">Productivity & employees</a></li>
</ul>
</li>
<li class="sub-head"><strong><a href="/coal/reserves/" title="html format: Reserves">Reserves</a></strong></li>
<li class="sub-head"><strong>Consumption</strong></li>
<li>
<ul>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t32p01p1.pdf" title="PDF format: Consumption by End-Use Sector">By end-use sector</a></li>
  <li><a class="subcategory" href="/coal/annual/pdf/table26.pdf" title="PDF format: by End-Use Sector for Census Division & State">By end-use  sector for Census division & state</a></li>
  <li><a href="/coal/production/quarterly/pdf/t35p01p1.pdf" title="PDF format: Consumption at Manufacturing Plants">At manufacturing plants</a></li>
</ul>
</li>
<li class="sub-head"><strong><a href="/coal/production/quarterly/pdf/t37p01p1.pdf" title="PDF format: ">Stocks</a></b>
<li class="sub-head"><strong>Imports &amp; exports</strong></li>
<li>
<ul>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t18p01p1.pdf" title="PDF format: Coal Imports">Coal imports</a></li>
  <li><a class="subcategory" href="/coal/production/quarterly/pdf/t7p01p1.pdf" title="PDF format: Coal Exports">Coal exports</a></li>
</ul>

</span>
<?php /*
cfinclude template="side_content.cfm"
<span class="dblue_side_top blue_top "><b>Regular Weekly Releases*</b></span>
  <span class="grey_side side_list2">
  <li class="head"><h2>Monday</h2></li>
  <p class="no-border"><a href="/coal/page/nymex/nymex_report.html">Weekly NYMEX Coal Futures&rsaquo;</a></p>
  <p class="no-border"><a href="/coal/page/coalnews/coalmar.html">Coal News &amp; Markets &rsaquo;</a></p>
  <br />
  <li class="head"><h2>Thursday</h2></li>
  <p class="no-border"><a href="/coal/weekly/weekly_html/wcppage.html">Weekly Coal Production &rsaquo;</a></p>

  </span>
</span>*/ ?>
