<div class="secondary">
    <ul class="upcoming-releases">
        <li class="head">
            <h2>
                Upcoming Releases
            </h2></li>
        <li><em>Release days may change on weeks with Federal holidays</em>.</li>
        <li>*<a href="/coal/markets/">Coal Markets</a>: <em>5:00 p.m. ET, Monday</em> (*Formerly <em>Weekly NYMEX Coal Futures</em> and <em>Coal News &amp; Markets</em>)</li>
        <li><a href="/coal/production/weekly/">Weekly Coal Production</a>: <em>5:00 p.m. ET, Thursday</em></li>
        <li class="foot"><a href="/reports/upcoming.php">See all upcoming</a></li>
    </ul>
</div>