<a name="weeklies">
</a>
<div class="content-container-border primary-alt">
    <ul>
        <li class="head">
            <h2>Regular Weekly Releases*</h2>
        </li>
        <li class="sub-head">
            <h3>Monday</h3>
        </li>
        <li><a href="/coal/markets/">Coal Markets</a> (*Formerly Weekly NYMEX Coal Futures and Coal News & Markets)
            <</li>
                <li class="sub-head">
                    <h3>Thursday</h3>
                </li>
                <li><a href="/coal/production/weekly/">Weekly Coal Production</a></li>
                <li class="date">*No releases: Monday, Tuesday, or Friday. Releases change on weeks with Federal holidays.</li>
    </ul>
</div>