<?php
/**
 * Created by PhpStorm.
 * User: HSH
 * Date: 3/14/16
 * Time: 10:40 AM
 */
?>
<table  width="100%" class="basic_table">
    <caption>Average weekly coal commodity spot prices<br />
        <span class="units">dollars per short ton</span></caption>
    <thead>
    <tr class="double-header">
        <th>&nbsp;  </th>
        <th colspan="4">Week ended</th></tr>
    <tr>
        <th>Coal commodity regions</th>
        <th>11/20/2015</th>
        <th>11/30/2015</th>
        <th>12/4/2015</th>
        <th>12/11/2015</th>
    </tr>
    </thead>
    <tbody>

    <tr>
        <td nowrap="nowrap">Central Appalachia<br /> 12,500 Btu, 1.2 SO<sub>2</sub></td>
        <td>$43.50</td>
        <td>$43.50</td>
        <td>$43.50</td>
        <td>$43.50</li>
    <tr>
        <td nowrap="nowrap">Northern Appalachia <br />13,000 Btu, &lt;3.0 SO<sub>2</sub></td>
        <td>$48.95</td>
        <td>$48.95</td>
        <td>$48.95</td>
        <td>$48.95</li>
    <tr>
        <td nowrap="nowrap">Illinois Basin <br />11,800 Btu, 5.0 SO<sub>2</sub></td>
        <td>$32.60</td>
        <td>$32.60</td>
        <td>$32.60</td>
        <td>$32.60</li>
    <tr>
        <td nowrap="nowrap">Powder River Basin <br />8,800 Btu, 0.8 SO<sub>2</sub></td>
        <td>$10.90</td>
        <td>$10.90</td>
        <td>$10.90</td>
        <td>$10.90</li>
    <tr>
        <td nowrap="nowrap">Uinta Basin <br />11,700 Btu, 0.8 SO<sub>2</sub></td>
        <td>$40.65</td>
        <td>$40.65</td>
        <td>$40.65</td>
        <td>$40.65</li>
    <tfoot>
    <tr>
        <td colspan="5">Source: U.S. Energy Information Administration, <a href="/coal/news_markets/">Coal News & Markets</a></li>
    </tfoot>
    </tbody>
</table>

