        <?php $what = 'coal'; ?>
        <?php include ('about/new/whatsnew_sitewide.php') ; ?>
       <?php /* Weekly Releases */ ?>
         <div class="secondary">
<ul>
<li class="head"><h2>Regular Weekly Releases*</h2></li>
        <p><a href="/coal/nymex/">Weekly NYMEX Coal Futures &rsaquo;</a><br />

<?php /*        <p><a href="/cneaf/coal/page/nymex/nymex_report.html">Weekly NYMEX Coal Futures &rsaquo;</a><br /> */ ?>
           <i>5:30 p.m. ET, Monday</i>
<?php /* Commented out by CA2 requested by Melinda Hobbs on 01/27/2012
      <p><a href="/cneaf/coal/page/coalnews/coalmar.html">Coal News & Markets &rsaquo;</a><br />
           <i>5:00 p.m. ET, Monday</i>
*/ ?>
		<p><a href="/coal/news_markets/">Coal News & Markets &rsaquo;</a><br />
           <i>5:30 p.m. ET, Monday</i>
        <p><a href="/cneaf/coal/weekly/weekly_html/wcppage.html">Weekly Coal Production &rsaquo;</a><br />
           <i>5:30 p.m. ET, Thursday</i>
            
         
        <p class="no-border"><i>*No releases: Tuesday, Wednesday or Friday. Releases change on weeks with Federal holidays.</i></p>
       
        </span> 
           <?php /* Survey */ ?>
         <div class="secondary">
<ul>
<li class="head"><h2>Survey Forms, Changes & Announcements</h2></li>
            <p><a href="/cneaf/coal/page/coalforms.html">Coal survey forms &rsaquo;</a> </p>
          <?php /*  <p><a href="/cneaf/coal/page/surveys/coal_survey_auth.html">Coal survey authorization 2011-14 &rsaquo;</a></p>
       <p><a href="/cneaf/coal/page/schedule/product_description.html">Coal data & analysis products: descriptions & schedules &rsaquo;</a> </p> */ ?>
          </span>
		  <?php /*
       <span class="grey_side green_top">
            <li class="head"><h2>Coal Maps</h2></li>
            
          <p><a href="/energy_in_brief/role_coal_us.php "><img src="/energy_in_brief/images/charts/coal_production_regions_medium_map.jpg"  width="200"></a><br/><br/><a href="/maps#coal">See more coal maps &rsaquo;</a></p>
          </span>
		  */ ?>
        <?php /* FAQ Promo */ ?>
        <span class="blue_side">
          <h4 class="q_side"><a href="/tools/faqs/faq.php?id=69&t=2">Which States produce the most coal? &rsaquo;</a></h2></li>
          <p><a href="/tools/faqs/#coal">See all coal FAQs  &rsaquo;</a></p>
        </span>
         <?php /* Energy Explained Promo */ ?>
        
        <p><a href="/energyexplained/index.php?page=coal_home"><img src="/energyexplained/images/section-banners/coal.jpg" alt="Energy Explained - Coal" width="240" /></a></p>
        <?php /* Kids Promo */ ?>
        <?php include ('global/includes/kids_dates.inc') ; ?>