<div class="report_header">
<span class="left rtitle">
  <?php /*a href="/naturalgas/reports.php">&lsaquo; See all Natural Gas Reports</a*/ ?>
  <h2>Annual Energy Review</h2>
  <?php /*p><strong>With Data for  2012</strong>&nbsp;&nbsp;|&nbsp;&nbsp;<strong>Release Date:</strong>&nbsp;June 10, 2013&nbsp;&nbsp;|&nbsp;&nbsp;<strong>Next Update:</strong> July 2013<br /</p*/ ?>
  <p><?php /*strong>Next release date:</strong*/ ?> Superseded -- see MER for key annual tables</p>
</span>
<span  class="left rtitle_form do-not-print">
	<?php /*span class="left rtitle_form"*/ ?>
  <h4>Annual Energy Review archives</h4>
  <p><span class="rtitle_form_a">
  <form name="form" id="form">
<label style="color:#000">for data year:&nbsp;</label>
<select name="jumpMenu" size="1" id="jumpMenu" style="width:80px">

<option value="/totalenergy/data/annual/archive/038411.pdf" selected="selected">2011</option>
<option value="/totalenergy/data/annual/archive/038410.pdf">2010</option>
<option value="/totalenergy/data/annual/archive/038409.pdf">2009</option>
<option value="/totalenergy/data/annual/archive/038408.pdf">2008</option>
<option value="/totalenergy/data/annual/archive/">all archives</option>
                 </select>
					 
<input type="button" name="go_button" class="arrow_go" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                   </form>
  
  
  </span> </p>
  <?php /*/span*/ ?>       
</span>
</div>
