
<table  width="100%" class="basic_table">
<caption>U.S. Renewables consumption<br />
<span class="units">quadrillion Btu</span></caption>
<thead>
	<tr>
	<th>&nbsp;</th>
    <th>2013</th>
    <th>2014</th>
    <th>2015 E</th>
    <th>2016 P</th>
    </tr>
    </thead>
    <tbody>
        
        <tr>	
		<td>Hydroelectric power</td>
   		<td>2.562</td>
   		<td>2.469</td>
   		<td><i>2.257</i></td>
    	<td><i>2.415</i></li>
        <tr>
        <td>Geothermal</td>
        <td>0.214</td>
        <td>0.222</td>
        <td><i>0.226</i></td>
        <td><i>0.236</i></li>
        <tr>
        <td>Solar</td>
        <td>0.305</td>
        <td>0.427</td>
        <td><i>0.522</i></td>
        <td><i>0.624</i></li>
        <tr>
        <td>Wind</td>
        <td>1.596</td>
        <td>1.729</td>
        <td><i>1.765</i></td>
        <td><i>2.042</i></li>
        <tr>
        <td>Wood biomass</td>
        <td>2.170</td>
        <td>2.214</td>
        <td>2.041</td>
        <td>1.980</li>
        <tr>
          <td>Ethanol</td>
          <td>1.090</td>
          <td>1.107</td>
          <td><i>1.141</i></td>
          <td><i>1.144</i></li>
        <tr>
          <td>Biodiesel</td>
          <td>0.205</td>
          <td>0.198</td>
          <td><i>0.222</i></td>
          <td><i>0.261</i></li>
        <tr>
          <td>Waste biomass</td>
          <td>0.496</td>
          <td>0.488</td>
          <td><i>0.494</i></td>
          <td><i>0.502</i></li>
        <tr>
        <td>Total</td>
        <td>9.349</td>
        <td>9.603</td>
        <td><i>9.432</i></td>
        <td><i>9.970</i></li>
        <tfoot>
        <tr>
        <td colspan="7">Source:  Short-Term Energy Outlook <a href="http://www.eia.gov/outlooks/steo/report/renew_co2.cfm?src=Environment-b1">Renewables and Carbon Dioxide Emissions</a>
</li>
        </tfoot>
        </tbody>
</table>

