<?php /* Renewable Sub Nav */ ?>
    <div class="pub_title">
	<?php /* Page/Section Title */ ?>
    <a href="/renewable/reports.cfm">&lsaquo; See All Renewable Reports</a>
      <h2>Green Pricing and Net Metering Programs 2009</h2>
      <p><b>Release Date:</b> July 2011 &nbsp; | &nbsp;<b>Next Release Date: </b>July 2012 &nbsp; | &nbsp; <a href="/renewable/annual/pdf/rea_report.pdf" class="pdf">full report</a></p>
</div><?php /*/ Page/Section Title */ ?>
<?php /*/ Page/Sub Nav */ ?>