<?php /* Renewable Sub Nav */ ?>
    <div class="pub_title">
	<?php /* Page/Section Title */ ?>
    <a href="/renewable/reports.cfm">&lsaquo; See All Renewable Reports</a>
      <h2>Solar Thermal Collector Manufacturing Activities</h2>
      <p><b>Release Date:</b> December 2010 &nbsp; | &nbsp;<b>Next Release Date: </b>Discontinued &nbsp; | &nbsp; <a href="/renewable/annual/pdf/rea_report.pdf" class="pdf">full report</a></p>
    </div><?php /*/ Page/Section Title */ ?>
<?php /*/ Page/Sub Nav */ ?>