<?php /* Renewable Sub Nav */ ?>
    <div class="pub_title">
	<?php /* Page/Section Title */ ?>
    <a href="/renewable/reports.cfm">&lsaquo; See All Renewable Reports</a>
      <h2>Alternatives to Traditional Transportation Fuels 2009</h2>
      <p><b>Release Date:</b> April  2011 &nbsp; | &nbsp;<b>Next Release Date: </b>April 2012 &nbsp; | &nbsp; <a href="pdf/afv-atf2009.pdf" class="pdf">full report</a></p>
</div><?php /*/ Page/Section Title */ ?>
<?php /*/ Page/Sub Nav */ ?>