<?php /* Renewable Sub Nav */ ?>
<div class="report_header">
<span class="left rtitle">

    <a href="/renewable/reports.cfm">&lsaquo; See All Renewable Reports</a>
      <h2>Solar Photovoltaic Cell/Module Shipments Report</h2>
      <p><b>With data for 2010</b>&nbsp; | &nbsp;<b>Release Date:</b> January 30, 2012&nbsp; | &nbsp;<b>Next Release Date: </b>January 2013&nbsp; | &nbsp;<a href="/renewable/annual/solar_photo/pdf/pv_report.pdf" class="pdf">full report</a></p>
</span>
              <span  class="left rtitle_form">
<h4>Previous Solar Photovoltaic Cell/Module  Reports</h4>
 
<?php /*<span class="subnav">*/ ?><p><?php /*</span>*/ ?>

<form name="form" id="form">
                   <label>available in pdf:</label>
                     <select name="jumpMenu" size="1" id="jumpMenu" style="width:80px">
          <option value="/renewable/annual/solar_photo/archive/solarpv09.pdf" selected="selected">2009</option>
                       <option value="/renewable/annual/solar_photo/archive/solarpv08.pdf">2008</option>
                       <option value="/renewable/annual/solar_photo/archive/solarpv07.pdf">2007</option>
                     </select>
                     <input type="button" name="go_button" class="arrow_go" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                   </form>
             
   </p> 
              </span>
              
</span>
</div>


<?php /*/ Page/Sub Nav */ ?>