<?php /* Renewable Sub Nav */ ?>
<div class="report_header">
<span class="left rtitle" style="width:675px">

    <a href="/renewable/reports.cfm">&lsaquo; See All Renewable Reports</a>
      <h2>Trends in Renewable Energy Consumption and Electricity</h2>
      <p><b>With data for 2010</b>&nbsp; | &nbsp;<b>Release Date:</b> December 11, 2012&nbsp; | &nbsp;<b>Next Release Date: </b>Suspended&nbsp; <?php /*| &nbsp;<a href="/renewable/annual/trends/pdf/trends.pdf" class="pdf">full report</a>*/ ?></p>
</span>

<span  class="left rtitle_form do-not-print" style="width:275px">
<span  class="left rtitle_form" style="width:275px">
<h4>Previous Issues</h4>
 
<?php /*<span class="subnav">*/ ?><p><?php /*</span>*/ ?>
<span class="rtitle_form_a" style="width:275px">
<form name="form" id="form">
                   <label>year:</label>
                     <select name="jumpMenu" size="1" id="jumpMenu" style="width:80px">
                     <option value="/renewable/annual/trends/archive/2009/pdf/trends.pdf" selected="selected">2009 (pdf)</option>
                     <option value="/renewable/annual/trends/archive/trends08.pdf" >2008(pdf)</option> 
                     <option value="/renewable/annual/trends/archive/trends07.pdf">2007(pdf)</option>
                       <option value="/renewable/annual/trends/archive/trends06.pdf">2006(pdf)</option>
                       <option value="/renewable/annual/trends/archive/062805.pdf">2005(pdf)</option>
                       <option value="/renewable/annual/trends/archive/062804.pdf">2004(pdf)</option>
                       <option value="/renewable/annual/trends/archive/06282000.pdf">2000(pdf)</option>
                       <option value="/renewable/annual/trends/archive/062898.pdf">1998(pdf)</option>
                       <?php /*05 and 04*/ ?>
                     </select>
                     <input type="button" name="go_button" class="arrow_go" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                   </form>
             
   </p> 
  </span>
 </span>           
</span>
</div>


<?php /*/ Page/Sub Nav */ ?>