<table width="100%" border="0" cellpadding="0" cellspacing="0" class="basic_table" >
<caption>Select spot prices for delivery today</caption>
<thead>

		<tr class="double-header">
	        <th >&nbsp;</th>
	        <th colspan="2">Natural Gas</th>
	        <th colspan="2">Electricity</th>
	        <th ><a class="lbox" href="/todayinenergy/includes/sparkspread_explain.cfm">Spark<br />Spread</a></th>
		</tr>
		<tr >
        	<th ><a class="lbox" href="/todayinenergy/includes/Region_Explain.cfm">Region</a></th>
			<th ><span style="font-weight:normal;float:right">$/million Btu</span></th>
			<th ><span style="font-weight:normal;float:none">% chg*</span></th>
			<th ><span style="font-weight:normal;float:none">$/MWh</span></th>
			<th ><span style="font-weight:normal;float:none">% chg*</span></th>
            <th ><span style="font-weight:normal;float:none">$/MWh</span></th>
		</tr>

</thead>
		<tr>

					<td class="s1">New England</td>
					<td class="d1">3.10</td>
					<td class="up">+1.6</td>
					<td class="d1">30.73</td>
					<td class="dn">-0.4</td>
					<td class="d1">9.03</td>

		</tr>



		<tr>

					<td class="s1">Mid-Atlantic</td>
					<td class="d1">2.82</td>
					<td class="%c.ngasmidatlclass">+1.5</td>

					<td class="d1">30.97</td>
					<td class="%c.electmidatlclass">+0.5</td>

					<td class="d1">11.23</td>

		</tr>


		<tr>

					<td class="s1">Midwest</td>
					<td class="d1">3.12</td>
					<td class="up">+2.0</td>

					<td class="d1">30.46</td>
					<td class="dn">-6.5</td>

					<td class="d1">8.60</td>

		</tr>



		<tr>

					<td class="s1">Southwest</td>
					<td class="d1">2.85</td>
					<td class="up">+3.5</td>

					<td class="d1">38.25</td>
					<td class="up">+3.4</td>

					<td class="d1">18.33</td>

		</tr>


		<tr>

					<td class="s1">Northwest</td>
					<td class="d1">2.68</td>
					<td class="up">+3.5</td>

					<td class="d1">24.75</td>
					<td class="dn">-20.2</td>

					<td class="d1">5.99</td>

		</tr>

        <tfoot>
            <tr>
            <td colspan="6"> *Percent changes based on daily settlement price from previous business day.<br />Source: <a href="/todayinenergy/prices.cfm">Daily Prices</a>
            </td>
            </tr>
        </tfoot>

	</table>
