<div class="content-container light-top-border-container grey-background">
	<ul>
		<li class="head"><h2>Most Requested Natural Gas Data</h2></li>
		<li class="sub-head"><strong>Summary</strong></li>
		<li>
			<ul>
				<li><a href="/dnav/ng/ng_sum_lsum_dcu_nus_m.htm">Monthly Summary of Prices and Volumes</a></li>
			</ul>
		</li>
		<li class="sub-head"><strong>Prices</strong></li>
		<li>
			<ul>
				<li><a href="/dnav/ng/ng_pri_sum_dcu_nus_m.htm">Monthly Wholesale and Retail Prices</a></li>
			</ul>
		</li>
		<li class="sub-head"><strong>Exploration &amp; Reserves</strong></li>
		<li>
			<ul>
				<li><a href="/dnav/ng/ng_enr_sum_dcu_NUS_a.htm">Reserves Summary</a></li>
			</ul>
		</li>
		<li class="sub-head"><strong>Production</strong></li>
		<li>
			<ul>
				<li><a href="/dnav/ng/ng_prod_sum_dc_NUS_MMCF_m.htm">Gross Withdrawals and Production</a></li>
				<li><a href="/dnav/ng/ng_prod_wells_s1_a.htm">Number of Producing Wells</a></li>
				<li><a href="/dnav/ng/ng_prod_whv_dcu_nus_a.htm">Wellhead Value and Marketed Production</a></li>
			</ul>
		</li>
		<li class="sub-head"><strong>Imports/Exports &amp; Pipelines</strong></li>
		<li>
			<ul>
				<li><a href="/dnav/ng/ng_move_impc_s1_m.htm">Imports by country</a></li>
				<li><a href="/dnav/ng/ng_move_expc_s1_m.htm">Exports by country</a></li>
				<li><a href="/dnav/ng/ng_move_ist_a2dcu_nus_a.htm">Interstate Movements</a></li>
			</ul>
		</li>
		<li class="sub-head"><strong>Storage</strong></li>
		<li>
			<ul>
				<li><a href="/dnav/ng/ng_stor_wkly_s1_w.htm">Weekly Working Gas in Underground Storage</a></li>
				<li><a href="/dnav/ng/ng_stor_sum_dcu_nus_m.htm">Underground Storage</a></li>
				<li><a href="/dnav/ng/ng_stor_cap_dcu_nus_a.htm">Underground Storage Capacity</a></li>
			</ul>
		</li>
		<li class="sub-head"><strong>Consumption</strong></li>
		<li>
			<ul>
				<li><a href="/dnav/ng/ng_cons_sum_dcu_nus_m.htm">Consumption by End Use</a></li>
				<li><a href="/dnav/ng/ng_cons_num_dcu_nus_a.htm">Number of Consumers</a></li>
			</ul>
		</li>
		<li class="head"><h2>International Data</h2></li>
		<li class="sub-head"><strong>Overview</strong></li>
		<li>
			<ul>
				<li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=3&amp;aid=1">Production</a></li>
				<li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=26&amp;aid=2">Consumption</a></li>
				<li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=26&amp;aid=3">Imports</a></li>
				<li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=26&amp;aid=4">Exports</a></li>
				<li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=3&amp;aid=6">Reserves</a></li>
				<li class="foot"><a href="/emeu/international/contents.html">more</a></li>
			</ul>
		</li>
	</ul>
</div>