<?php /*<span class="grey_side blue_top">
<h4>Announcement:</h4>
<p>The July 2011 Monthly Natural Gas Gross Production Report and July 2011 Natural Gas Monthly, originally scheduled for release July 29th, 2011, will be released August 2, 2011. The delay is due to processing difficulties arising from recent resource reductions to EIA.</p>
</span>*/ ?>
<span class="grey_side blue_top">
<h4>Most Requested Natural Gas Data</h4>
<p class="no-border"><strong>Summary</strong></p>
<ul>
  <li><a href="/dnav/ng/ng_sum_lsum_dcu_nus_m.htm">Monthly Summary of Prices and Volumes</a></li>
</ul>
<p class="no-border"><strong>Prices</strong></p>
<ul>
  <li><a href="/dnav/ng/ng_pri_sum_dcu_nus_m.htm">Monthly Wholesale and Retail Prices</a></li>
</ul>
<p class="no-border"><strong>Exploration &amp; Reserves</strong></p>
<ul>
  <li><a href="/dnav/ng/ng_enr_sum_dcu_NUS_a.htm">Reserves Summary</a></li>
</ul>
<p class="no-border"><strong>Production</strong></p>
<ul>
  <li><a href="/dnav/ng/ng_prod_sum_dc_NUS_MMCF_m.htm">Gross Withdrawals and Production</a></li>
  <li><a href="/dnav/ng/ng_prod_wells_s1_a.htm">Number of Producing Wells</a></li>
  <li><a href="/dnav/ng/ng_prod_whv_dcu_nus_a.htm">Wellhead Value and Marketed Production</a></li>
</ul>
<p class="no-border"><strong>Imports/Exports &amp; Pipelines</strong></p>
<ul>
  <li><a href="/dnav/ng/ng_move_impc_s1_m.htm">Imports by country</a></li>
  <li><a href="/dnav/ng/ng_move_expc_s1_m.htm">Exports by country</a></li>
  <li><a href="/dnav/ng/ng_move_ist_a2dcu_nus_a.htm">Interstate Movements</a></li>
</ul>
<p class="no-border"><strong>Storage</strong></p>
<ul>
  <li><a href="/dnav/ng/ng_stor_wkly_s1_w.htm">Weekly Working Gas in Underground Storage</a></li>
  <li><a href="/dnav/ng/ng_stor_sum_dcu_nus_m.htm">Underground Storage</a></li>
  <li><a href="/dnav/ng/ng_stor_cap_dcu_nus_a.htm">Underground Storage Capacity</a></li>
</ul>

<p class="no-border"><strong>Consumption</strong></p>
<ul>
  <li><a href="/dnav/ng/ng_cons_sum_dcu_nus_m.htm">Consumption by End Use</a></li>
  <li><a href="/dnav/ng/ng_cons_num_dcu_nus_a.htm">Number of Consumers</a></li>
</ul>
<br />
<h4>International Data</h4>
<p class="no-border"><strong>Overview</strong></p>
<ul>
  <li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=3&amp;aid=1">Production</a></li>
  <li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=26&amp;aid=2">Consumption</a></li>
  <li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=26&amp;aid=3">Imports</a></li>
  <li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=26&amp;aid=4">Exports</a></li>
  <li><a href="/cfapps/ipdbproject/IEDIndex3.cfm?tid=3&amp;pid=3&amp;aid=6">Reserves</a></li>
  <li><a href="/emeu/international/contents.html">more &#8250;</a></li>
</ul>
</span>


<?php /* List Promo/Dark Blue Top Example>
      <span class="dblue_side_top blue_top "><a name="weekly releases"><b>Regular Weekly Releases*</b></a></span>
      <span class="grey_side side_list2">
<h4>Thursday</h4>
          <p><a href="http://ir.eia.gov/ngs/ngs.html">Weekly Natural Gas Storage Report &rsaquo;</a><br />
            <i>10:30 a.m. EST</i></p>
          <p><a href="/oog/info/ngw/ngupdate.asp">Natural Gas Weekly Update &rsaquo;</a><br />
            <i>2:00 - 2:30 p.m. EST</i><br />
		</p>
          <p></p>
          <p class="no-border"><i>*No releases: Monday, Tuesday, Wednesday or Friday<br />
          Releases change on weeks with Federal holidays</i></p>
      </span>
      <span class="grey_side blue_top">
          <p class="ico_reports">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/reports/">Full list of upcoming reports</a></p>
          <p class="ico_email">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/tools/emailupdates/">Sign up for email notifications </a></p>
          <p class="ico_rss">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/tools/rssfeeds/">Get the What's New RSS feed </a></p>
      </span>
      <--List Promo/Dark Blue Top Example */ ?>