      <?php /* List Promo/Dark Blue Top Example */ ?>
      <span class="dblue_side_top blue_top "><b>Regular Weekly Releases*</b></span>
      <span class="grey_side side_list2">
        <li class="head"><h2>Monday - Wednesday</h2></li>
          <p><i>No weekly releases</i></p>
          <br />
		
		<li class="head"><h2>Thursday</h2></li>
          <p><a href="/oog/info/ngw/ngupdate.asp">Weekly Natural Gas Storage Report &rsaquo;</a><br />
            <i>10:30 a.m. EST</i></p>
          <p><a href="/oog/info/ngw/ngupdate.asp">Natural Gas Weekly Update &rsaquo;</a><br />
            <i>2:00 - 2:30 p.m. EST</i><br />
		</p>
        <li class="head"><h2>Friday</h2></li>
          <p><i>No weekly releases</i></p>
          <p class="no-border"><i>*Releases change on weeks with Federal holidays</i></p>
      </span>
      <div class="content-container light-top-border-container grey-background">
<p class="ico_reports">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/calendar/reports.html">Full list of upcoming reports</a></p>
          <p class="ico_email">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Sign up for email notifications </a></p>
          <p class="ico_rss">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Get the What's New RSS feed </a></p>
      </span>
      <?php /* List Promo/Dark Blue Top Example */ ?>