<table>
<caption>Working gas in underground storage, lower 48 states</caption>
<thead>
	    <tr class="double-header">
	      <th>&nbsp; </th>
              <th colspan="9">Stocks<br/>
                <span>billion cubic feet (Bcf)</span></th>
              </tr>
			
            <tr>
              <th>Region</td>
              <th colspan="3" style="text-align:left">07/20/18</td>
              <th colspan="3" style="text-align:left">07/13/18</td>
              <th colspan="3" style="text-align:left">net change</td>	  
	    </tr>

            </thead>
            <tbody>
 
            <tr>
              <td><strong>East</strong></td>
               <td style="text-align:center">527</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
               <td>507</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
               <td>20</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
              </tr>

            <tr>
              <td><strong>Midwest</strong></td>
               <td style="text-align:center">524</td>
			      <td class="flag">&nbsp;</td>
               	  <td class="flag">&nbsp;</td>
               <td>501</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
               <td>23</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
		      </tr>

 
            <tr>
              <td><strong>Mountain</strong></td>
               <td style="text-align:center">145</td>
			      <td class="flag">&nbsp;</td>
               	  <td class="flag">&nbsp;</td>
               <td>144</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
               <td>1</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
			 </tr>
			
	    <tr>
              <td><strong>Pacific</strong></td>
               <td style="text-align:center">257</td>
			      <td class="flag">&nbsp;</td>
               	  <td class="flag">&nbsp;</td>
               <td>259</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
               <td>-2</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
			  </tr>
			
			  <tr>
              <td><strong>South Central</strong></td>
               <td style="text-align:center">820</td>
			      <td class="flag">&nbsp;</td>
               	  <td class="flag">&nbsp;</td>
               <td>838</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
               <td>-18</td>
			      <td class="flag">&nbsp;</td>
                  <td class="flag">&nbsp;</td>
			  </tr>
			   <tr>
			    <td>&nbsp;&nbsp;&nbsp;<strong>Salt</strong></td>
			    <td style="text-align:center">214</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
			    <td>230</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
			    <td>-16</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
		      </tr>
			  <tr>
			    <td>&nbsp;&nbsp;&nbsp;<strong>NonSalt</strong></td>
			    <td style="text-align:center">606</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
			    <td>608</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
			    <td>-2</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
		      </tr>
			  <tr class="total">
			    <td><strong>Total</strong></td>
			    <td style="text-align:center">2,273</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
			    <td>2,249</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
			    <td>24</td>
			    <td class="flag">&nbsp;</td>
			    <td class="flag">&nbsp;</td>
		      </tr>
 				
        <tfoot>
            <tr>
            <td colspan="10"> Source: <a href="http://ir.eia.gov/ngs/ngs.html">Weekly Natural Gas Storage Report</a>
            </td>
            </tr>
        </tfoot>

</tbody></table>


