<a name="weeklies"></a>
<div class="primary-alt">
    <ul class="accent">
        <li class="head"><h2>Regular Weekly Releases*</h2></li>
        <li class="sub-head"><h3>Thursday</h3></li>
        <li class="sub-list">
            <ul>
                <li><a href="http://ir.eia.gov/ngs/ngs.html">Weekly Natural Gas Storage Report</a></li>
                <li class="release-schedule">10:30 a.m. EST</li>
            </ul>
            <ul>
                <li><a href="/naturalgas/weekly/">Natural Gas Weekly Update</a></li>
                <li class="release-schedule">2:00 - 2:30 p.m. EST</li>
            </ul>
        </li>
        <li class="release-schedule">*No releases: Monday, Tuesday, Wednesday or Friday. Releases change on weeks with Federal holidays.</li>
    </ul>
</div>