<a name="weeklies"></a>
<div class="content-container-border primary-alt">
    <ul>
        <li class="head">
            <h2>Regular Weekly Releases*</h2>
        </li>
        <li class="sub-head">
            <h3>Thursday</h3>
        </li>
        <li><a href="http://ir.eia.gov/ngs/ngs.html">Weekly Natural Gas Storage Report &rsaquo;</a></li>
        <li class="date">10:30 a.m. EST</li>
        <li><a href="/naturalgas/weekly/">Natural Gas Weekly Update &rsaquo;</a></li>
        <li class="date">2:00 - 2:30 p.m. EST</li>
        <li class="date">*No releases: Monday, Tuesday, Wednesday or Friday. Releases change on weeks with Federal holidays.</li>
    </ul>
</div>