<a name="weekly release"></a><div class="weeklies">
          <span>
            <h2>Regular Weekly Releases*</h2>
            <h3>Thursday</h3>
            <p><a href="http://ir.eia.gov/ngs/ngs.html">Weekly Natural Gas Storage Report &rsaquo;</a><br />
              <i>10:30 a.m. EST</i></p>
            <p><a href="/naturalgas/weekly/">Natural Gas Weekly Update &rsaquo;</a><br />
            <i>2:00 - 2:30 p.m. EST</i></p>
            <p class="no-border"><i>*No releases: Monday, Tuesday, Wednesday or Friday. Releases change on weeks with Federal holidays.</i></p>
