<p>Find statistics on electric power plants, capacity, generation, fuel consumption, sales, prices and customers.</p>
<span class="condaterange"><a class="no-border expandall"> EXPAND ALL</a></span>
<table class="contable">
<?php /* BEGIN Summary Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="summary"></a>Summary</th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr class="white_first">
			<li><strong>Electricity overview </strong> <span class="right"><a href="/totalenergy/data/monthly/pdf/sec7_3.pdf" class="ico_pdf" title=" Electricity overview  ">PDF</a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T07.01" class="ico_csv" title=" Electricity overview  ">CSV</a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T07.01&amp;freq=m" class="ico_xls" title=" Electricity overview  ">XLS</a>&nbsp;<span class="beta right"> <a href="/beta/MER/?tbl=T07.01#/?f=M&start=200001" title=" Electricity overview  ">INTERACTIVE</a></span></span>


<div>
<script language="JavaScript" type="text/JavaScript" src="/totalenergy/data/monthly/txt/new_merheader.txt"></script> <em>Interactive data from Total Energy Data Browser</em> </div></li>
<tr class="white_first">
			<li><p><strong>Total electric power industry summary statistics</strong></p>
<ul>
<li><strong>Monthly</strong>
</li>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>

<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_es1a.xlsx" class="ico_xls" title=" Total electric power industry summary statistics - monthly  ">XLS</a></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_es1a" title=" Total electric power industry summary statistics  ">Latest month </a> </li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_es1b.xlsx" class="ico_xls" title=" Total electric power industry summary statistics - Year-to-date  ">XLS</a></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_es1b" title=" Total electric power industry summary statistics  ">Year-to-date </a></li>
</ul>
<li><strong>Annual</strong>
(back to 2005)
</li>
<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>

<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_01_02.xlsx" class="ico_xls" title=" Total electric power industry summary statistics - annual  ">XLS</a></span><a href="/electricity/annual/html/epa_01_02.html">Summary statistics </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_01_03.xlsx" class="ico_xls" title=" Total electric power industry summary statistics - annual Supply and disposition of electricity ">XLS</a></span><a href="/electricity/annual/html/epa_01_03.html">Supply and disposition of electricity </a></li>
</ul>
</ul>
</li>
			<li><a href="/totalenergy/data/monthly/#electricity">...more national-level summary data </a></li>


			<li><a href="/electricity/state/">State summary statistics</a> (Capacity, generation, price,  emissions and more)<br />  
			<li><span class="release-date">Release Date: </span><span class="date">January 25, 2018 | data from: State Electricity Profiles</em></li>


			<li><strong>International electricity data</li>
			<li>
<em>data from: <a href="/beta/international/data/browser/">International Energy Statistics</a></em>
<ul>
<li><a href="/beta/international/data/browser/#?ord=SA&amp;cy=2013&amp;v=H&amp;vo=0&amp;so=0&amp;io=0&amp;start=1980&amp;end=2013&amp;vs=INTL.2-12-AFRC-BKWH.A~INTL.2-12-ASOC-BKWH.A~INTL.2-12-CSAM-BKWH.A~INTL.2-12-EURA-BKWH.A~INTL.2-12-EURO-BKWH.A~INTL.2-12-MIDE-BKWH.A~INTL.2-12-NOAM-BKWH.A&amp;c=4100000002000060000000000000g000200000000000000001&amp;pa=00000000000000000000000000000fvu&amp;f=A&amp;ug=g&amp;ct=1&amp;tl_type=p&amp;tl_id=2-A">Generation </a></li>
<li><a href="/beta/international/data/browser/#?ord=SA&amp;cy=2012&amp;v=H&amp;vo=0&amp;so=0&amp;io=0&amp;start=1980&amp;end=2012&amp;vs=INTL.2-2-AFRC-BKWH.A~INTL.2-2-ASOC-BKWH.A~INTL.2-2-CSAM-BKWH.A~INTL.2-2-EURA-BKWH.A~INTL.2-2-EURO-BKWH.A~INTL.2-2-MIDE-BKWH.A~INTL.2-2-NOAM-BKWH.A&amp;c=4100000002000060000000000000g000200000000000000001&amp;pa=0000002&amp;f=A&amp;ug=g&amp;ct=1&amp;tl_type=p&amp;tl_id=2-A">Consumption </a></li>

</ul></li>

<?php /* END Summary Content ////////////////*/ ?>
<?php /* BEGIN Sales, Revenue, Prices & Customers Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="sales"></a>Sales (consumption), revenue, prices &amp; customers</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>

			<li><strong> Detailed preliminary <a href="/survey/#eia-826">EIA-826</a> monthly survey data</strong> (back to 1990)
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/data/eia826/xls/sales_revenue.xls" class="ico_xls" title=" Revenue, sales, customer counts, and retail price by state and sector  ">XLS</a></span>Revenue, sales, customer counts, and retail price by state and sector</li>
</ul></li>
<tr class="white_first">
			<li><p><strong>Retail sales of electricity to ultimate customers</strong></p>
<ul>
<li><strong>Monthly</strong></li>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_5_01.xlsx" class="ico_xls" title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers ">XLS</a> <span class="beta right"><a title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers " href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=g&amp;linechart=ELEC.SALES.US-ALL.M~ELEC.SALES.US-RES.M~ELEC.SALES.US-COM.M~ELEC.SALES.US-IND.M&amp;columnchart=ELEC.SALES.US-ALL.M~ELEC.SALES.US-RES.M~ELEC.SALES.US-COM.M~ELEC.SALES.US-IND.M&amp;map=ELEC.SALES.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg">INTERACTIVE</a></span></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_01">By sector</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_5_04_b.xlsx" class="ico_xls" title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers  ">XLS</a> <span class="beta right"><a title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers  " href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;linechart=ELEC.SALES.TX-ALL.M~ELEC.SALES.TX-RES.M~ELEC.SALES.TX-COM.M~ELEC.SALES.TX-IND.M&amp;columnchart=ELEC.SALES.TX-ALL.M~ELEC.SALES.TX-RES.M~ELEC.SALES.TX-COM.M~ELEC.SALES.TX-IND.M&amp;map=ELEC.SALES.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201510&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg">INTERACTIVE</a></span></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_04_a" title=" Monthly retail sales of electricity to ultimate customers  ">By sector, by state  </a></li>
</ul>
<li><strong>Annual</strong> </li>
<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_02_02.xlsx" class="ico_xls" title=" Annual retail sales of electricity to ultimate customers  ">XLS</a> <span class="beta right"><a  href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;linechart=ELEC.SALES.US-ALL.A&amp;columnchart=ELEC.SALES.US-ALL.A&amp;map=ELEC.SALES.US-ALL.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title=" Annual retail sales of electricity to ultimate customers  ">INTERACTIVE</a></span></span> <a href="/electricity/annual/html/epa_02_02.html" title=" Annual retail sales of electricity to ultimate customers  ">By sector, by provider</a> (back to 2005, Interactive to 2001)</li>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/sales_annual.xlsx" class="ico_xls" title=" Annual retail sales of electricity to ultimate customers by sector, by state, by provider ">XLS</a></span>By sector, by state, by provider (back to 1990)<br />
			<li><span class="release-date">Release Date: </span><span class="date">November 6, 2017 | <a href="/electricity/data/eia861/">Form EIA-861 annual survey data</a></em></li>
<li><strong>By state and utility</strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/sales_revenue_price/esr_header.txt"></script>
</div>
<?php /*li>By state and utility<a href="/electricity/annual/html/epa_01_03.html"> </a>                </li*/ ?>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table6.pdf" class="ico_pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility residential sector  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table6.xlsx" class="ico_xls" title=" Annual retail sales of electricity to ultimate customers By state and utility residential sector  ">XLS</a> </span>Residential  sector </li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table7.pdf" class="ico_pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility commercial sector  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table7.xlsx" class="ico_xls" title=" Annual retail sales of electricity to ultimate customers By state and utility commercial sector  ">XLS</a></span>Commercial  sector </li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table8.pdf" class="ico_pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility industrial sector  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table8.xlsx" class="ico_xls" title=" Annual retail sales of electricity to ultimate customers By state and utility industrial sector  ">XLS</a></span>Industrial   sector </li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table9.pdf" class="ico_pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility transportation sector  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table9.xlsx" class="ico_xls" title=" Annual retail sales of electricity to ultimate customers By state and utility transportation sector  ">XLS</a></span>Transportation    sector </li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table10.pdf" class="ico_pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility all sectors  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table10.xlsx" class="ico_xls" title=" Annual retail sales of electricity to ultimate customers By state and utility all sectors  ">XLS</a></span>Total, all sectors </li>
</ul>
</ul>
</ul></li>
<tr class="white_first">
			<li><strong>Revenue from retail sales of electricity to ultimate customers</strong>

<li><strong>Monthly</strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_5_02.xlsx" class="ico_xls" title=" monthly revenue from retail sales of electricity to ultimate customers ">XLS</a> <span class="beta right"><a title="View in Total Energy Browser monthly revenue from retail sales of electricity to ultimate customers by sector" href="/electricity/data/browser/#/topic/6?agg=0,1&amp;geo=g&amp;linechart=ELEC.REV.US-ALL.M~ELEC.REV.US-RES.M~ELEC.REV.US-COM.M~ELEC.REV.US-IND.M&amp;columnchart=ELEC.REV.US-ALL.M~ELEC.REV.US-RES.M~ELEC.REV.US-COM.M~ELEC.REV.US-IND.M&amp;map=ELEC.REV.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg">INTERACTIVE</a></span></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_02" title=" monthly revenue from retail sales of electricity to ultimate customers ">By sector</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_5_05_a.xlsx" class="ico_xls" title=" monthly revenue from retail sales of electricity to ultimate customers ">XLS</a> <span class="beta right"><a title="View in Total Energy Browser monthly revenue from retail sales of electricity to ultimate customers by sector, by state" href="/electricity/data/browser/#/topic/6?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0">INTERACTIVE</a></span></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_05_a" title=" monthly revenue from retail sales of electricity to ultimate customers ">By sector, by state</a></li>

</ul>
</li>
<br />
<li><strong>Annual</strong>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_02_03.xlsx" class="ico_xls" title=" annual revenue from retail sales of electricity to ultimate customers By sector, by provider (back to 2005) ">XLS</a></span> <a href="/electricity/annual/html/epa_02_03.html" title=" annual revenue from retail sales of electricity to ultimate customers By sector ">By sector, by provider</a> (back to 2005)

<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>

</li>

<!--              </ul>
					<ul> -->
<li class="additional-formats">Available formats: <a href="/electricity/data/state/revenue_annual.xlsx" class="ico_xls" title=" annual revenue from retail sales of electricity to ultimate customers By sector, by state, by provider (back to 2005) ">XLS</a></span> By sector, by state, by provider (back to 1990)<br />
			<li><span class="release-date">Release Date: </span><span class="date">November 6, 2017 | <a href="/electricity/data/eia861/">Form EIA-861 annual survey data</a></em></li>
<li><span class="right"><span class="beta"><a href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;linechart=ELEC.SALES.US-ALL.A&amp;columnchart=ELEC.SALES.US-ALL.A&amp;map=ELEC.SALES.US-ALL.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title=" annual revenue from retail sales of electricity to ultimate customers By sector, by state, by provider (back to 2005) ">INTERACTIVE</a></span></span> By sector, by state (back to 2001)

<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script>
</div>

</li>
<li><strong>By state and utility</strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/sales_revenue_price/esr_header.txt"></script>
</div>

<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table6.pdf" class="ico_pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility residential, sector  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table6.xls" class="ico_xls" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, residential sector  ">XLS</a></span>Residential sector</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table7.pdf" class="ico_pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, commercial sector  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table7.xlsx" class="ico_xls" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, commercial sector  ">XLS</a></span>Commercial  sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table8.pdf" class="ico_pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility Industrial sector  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table8.xlsx" class="ico_xls" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, Industrial sector  ">XLS</a></span>Industrial   sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table9.pdf" class="ico_pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, transportation sector   ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table9.xlsx" class="ico_xls" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, transportation sector   ">XLS</a></span>Transportation    sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table10.pdf" class="ico_pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, all sectors  ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table10.xlsx" class="ico_xls">XLS</a></span title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, all sectors  ">Total, all sectors</li>
</ul>
</li>
</ul>
</li>
</ul>            </li>

			<li><strong>Average retail price  of electricity to ultimate customers:</strong>
<ul>
<li><strong>Monthly</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script></div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_5_03.xlsx" class="ico_xls" title="Monthly average retail price of electricity to ultimate customers  ">XLS</a> <span class="beta right"><a title="View in Total Energy Browser Monthly average retail price of electricity to ultimate customers  by sector" href="/electricity/data/browser/#/topic/7?agg=0,1&amp;geo=g&amp;linechart=ELEC.PRICE.US-ALL.M~ELEC.PRICE.US-RES.M~ELEC.PRICE.US-COM.M~ELEC.PRICE.US-IND.M&amp;columnchart=ELEC.PRICE.US-ALL.M~ELEC.PRICE.US-RES.M~ELEC.PRICE.US-COM.M~ELEC.PRICE.US-IND.M&amp;map=ELEC.PRICE.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg">INTERACTIVE</a></span></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_03" title="Monthly average retail price of electricity to ultimate customers  ">By sector</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_5_06_a.xlsx" class="ico_xls" title="Monthly average retail price of electricity to ultimate customers  ">XLS</a> <span class="beta right"><a title="View in Total Energy Browser Annual  average retail price of electricity to ultimate customers  by sector" href="/electricity/data/browser/#/topic/7?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0">INTERACTIVE</a></span></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_06_a" title="Annual  average retail price of electricity to ultimate customers ">By sector, by state</a></li>
</ul>
</li>
<br />
<li><strong>Annual</strong>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_02_04.xlsx" class="ico_xls" title="Annual  average retail price of electricity to ultimate customers  by sector, by provider(back to 2005) ">XLS</a></span> <a href="/electricity/annual/html/epa_02_04.html" title="Annual  average retail price of electricity to ultimate customers ">By sector, by provider</a>  (back to 2005)
<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
</li>

<li class="additional-formats">Available formats: <a href="/electricity/data/state/avgprice_annual.xlsx" class="ico_xls" title="Annual  average retail price of electricity to ultimate customers  by sector, by provider (back to 1990) ">XLS</a></span> By sector, by state, by provider (back to 1990)</li>
			<li><span class="release-date">Release Date: </span><span class="date">November 6, 2017 | <a href="/electricity/data/eia861/">Form EIA-861 annual survey data</a></em>

</li>
<li><span class="right"><span class="beta"><a href="/electricity/data/browser/#/topic/7?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;linechart=ELEC.PRICE.US-ALL.A&amp;columnchart=ELEC.PRICE.US-ALL.A&amp;map=ELEC.PRICE.US-ALL.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual  average retail price of electricity to ultimate customers  by sector, by provider (back to 2001) ">INTERACTIVE</a></span></span> By sector, by state (back to 2001)
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script>
</div>
</li>
<li><strong>By state and utility</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/sales_revenue_price/esr_header.txt"></script> </div>

<ul>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table6.pdf" class="ico_pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, residential sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table6.xlsx" class="ico_xls" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, residential sector ">XLS</a> </span>Residential sector</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table7.pdf" class="ico_pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, commercial sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table7.xlsx" class="ico_xls" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, commercial sector ">XLS</a></span>Commercial  sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table8.pdf" class="ico_pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, industrial sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table8.xlsx" class="ico_xls" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, industrial sector ">XLS</a></span>Industrial   sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table9.pdf" class="ico_pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, transportation sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table9.xlsx" class="ico_xls" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, transportation sector ">XLS</a></span>Transportation    sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table10.pdf" class="ico_pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, all sectors ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table10.xlsx" class="ico_xls" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, all sectors ">XLS</a></span>All sectors</li>
</ul>
</ul>
</li>
</ul>            </li>

			<li><strong>Number of customers (annual):</strong>

<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_02_01.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) ">XLS</a></span> <a href="/electricity/annual/html/epa_02_01.html" title=" Number of customers (annual) (back to 2005) ">By sector, by provider</a>
(back to 2005)
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div></li>
<li><strong>By sector by state and/or utility</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/sales_revenue_price/esr_header.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/customers_annual.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) by state, by provider ">XLS</a></span>By state, by provider
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table1.pdf" class="ico_pdf" title=" Number of customers (annual) (back to 2005) by state, by sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table1.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) by state, by sector ">XLS</a></span>By state by sector,
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table6.pdf" class="ico_pdf" title=" Number of customers (annual) (back to 2005) by state, residential sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table6.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) by state, residential sector ">XLS</a> </span>Residential sector</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table7.pdf" class="ico_pdf" title=" Number of customers (annual) (back to 2005) by state, commercial sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table7.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) by state, commercial sector ">XLS</a></span>Commercial  sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table8.pdf" class="ico_pdf" title=" Number of customers (annual) (back to 2005) by state, industrial sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table8.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) by state, industrial sector ">XLS</a></span>Industrial   sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table9.pdf" class="ico_pdf" title=" Number of customers (annual) (back to 2005) by state, transportation sector ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table9.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) by state, transportation sector ">XLS</a></span>Transportation    sector
</li>
<li class="additional-formats">Available formats: <a href="/electricity/sales_revenue_price/pdf/table10.pdf" class="ico_pdf" title=" Number of customers (annual) (back to 2005) by state, all sectors ">PDF</a> <a href="/electricity/sales_revenue_price/xls/table10.xlsx" class="ico_xls" title=" Number of customers (annual) (back to 2005) by state, all sectors ">XLS</a></span>All sectors by state and utility
</li>
</ul>
</li>
</ul>
<blockquote>
<p><!--<li class="additional-formats">Available formats: <a href="/electricity/data/eia826/xls/sales_revenue.xls" class="ico_xls">XLS</a></span>By state back to 2007 (Form EIA-826) </li> -->
</p>
</blockquote>
</li>
<!--
			<li>
<a href="/electricity/sales_revenue_price/">More sales, revenue, price, and consumers data tables </a>

</li> -->
	<h2><i class="ico expand-collapse"></i><a name="netmetering"></a>Net metering</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr class="white_first">
			<li><strong> Net metering</strong>
<ul>
<li><strong>Monthly</strong> (back to 2011)
<ul>
<li><a href="/electricity/data/eia826/" title=" monthly ">Net metering</a> - capacity, number of meters, and energy sold back, by state, sector, and utility</li>
<li><a href="/electricity/data/eia826/index.html#ammeter" title=" monthly ">Advanced metering</a> - number  and megawatthours served, by state by sector </li>
</ul>
</li>
<br />
<li><strong>Annual</strong> (back to 2005)
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_10.xlsx" class="ico_xls" title=" annual net metering back to 2005 ">XLS</a></span> <a href="/electricity/annual/html/epa_04_10.html">Net metering customers and capacity by technology type, by end use sector</a>
<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>  </li>
</ul>
</li>

</ul>
</li>

	<h2><i class="ico expand-collapse"></i><a name="generation"></a>Generation and thermal output</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>

			<li><strong>Detailed preliminary <a href="/survey/#eia-923">EIA-923</a> monthly and annual survey data </strong>(back to 1990)

<ul>
<li><a href="/electricity/data/eia923/index.html">Plant-level generation and fuel consumption data </a></li>
<li>State-level generation and fuel consumption data</li>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/generation_monthly.xlsx" class="ico_xls" title=" State-level generation and fuel consumption, monthly (back to 2001)  ">XLS</a></span> Monthly (back to 2001)
</li>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/annual_generation_state.xls" class="ico_xls" title=" State-level generation and fuel consumption, annual (back to 1990)  ">XLS</a></span> Annual (back to 1990)
</li>
</ul>
</ul>
</li>
<tr  class="white_first">
			<li><p><strong>Net generation</strong></p>
<ul>
<li><strong>Monthly</strong>

<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script>
</div>


<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_1_01.xlsx" class="ico_xls" title=" Monthly Net generation By all energy sources "><i class="ico xls"><span>XLS</span></i></a> <span class="beta right"> <a href="/electricity/data/browser/#/topic/0?agg=0,1&amp;fuel=vtvo&amp;geo=vvvvvvvvvvvvo&amp;linechart=ELEC.GEN.ALL-US-99.M&amp;columnchart=ELEC.GEN.ALL-US-99.M&amp;map=ELEC.GEN.ALL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title=" Monthly Net generation By all energy sources ">
INTERACTIVE</a></span></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_01" title=" Monthly Net generation ">
By all energy sources</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_1_01_a.xlsx" class="ico_xls" title="Monthly Net generation By type of renewable source "><i class="ico xls"><span>XLS</span></i></a> <span class="beta right"> <a href="/electricity/data/browser/#/topic/0?agg=1,0,2&amp;fuel=02&amp;geo=vvvvvvvvvvvvo&amp;sec=o3g&amp;linechart=ELEC.GEN.AOR-US-99.M~ELEC.GEN.AOR-US-1.M~ELEC.GEN.AOR-US-94.M~ELEC.GEN.AOR-US-96.M~ELEC.GEN.AOR-US-97.M&amp;columnchart=ELEC.GEN.AOR-US-99.M~ELEC.GEN.AOR-US-1.M~ELEC.GEN.AOR-US-94.M~ELEC.GEN.AOR-US-96.M~ELEC.GEN.AOR-US-97.M&amp;map=ELEC.GEN.AOR-US-99.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly Net generation By type of renewable source ">
INTERACTIVE</a></span></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_01_a" title="Monthly Net generation ">
By type of  renewable source</a></li>
<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec7_5.pdf" class="ico_pdf" title=" Monthly Net generation By energy source (plus by annual back to 1950) "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T07.02A" class="ico_csv" title=" Monthly Net generation By energy source (plus by annual back to 1950) "><i class="ico csv"><span>CSV</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T07.02A&amp;freq=m" class="ico_xls" title=" Monthly Net generation By energy source (plus by annual back to 1950) "><i class="ico xls"><span>XLS</span></i></a> <span class="beta right"><a href="/beta/MER/?tbl=T07.02A#/?f=A&amp;start=1949&amp;end=2014&amp;charted=1-2-3-5-8-14" title=" Monthly Net generation By energy source (plus by annual back to 1950) ">
INTERACTIVE</a></span></span> By energy source (plus by annual back to 1950)
<div>
<script language="javascript" type="text/javascript" src="/totalenergy/data/monthly/txt/new_merheader.txt"></script>
<em>Interactive data from <a href="/totalenergy/data/browser/">Total Energy Data Browser</a></em></div>
</li>
<li><strong>By energy source and producing sector</strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script>
</div>
<ul>
<li><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=8&amp;linechart=ELEC.GEN.ALL-US-1.M~ELEC.GEN.COW-US-1.M~ELEC.GEN.NG-US-1.M~ELEC.GEN.NUC-US-1.M~ELEC.GEN.HYC-US-1.M&amp;columnchart=ELEC.GEN.ALL-US-1.M~ELEC.GEN.COW-US-1.M~ELEC.GEN.NG-US-1.M~ELEC.GEN.NUC-US-1.M~ELEC.GEN.HYC-US-1.M&amp;map=ELEC.GEN.ALL-US-1.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="  title="Monthly Net generation By energy source and producing sector Electric utilities ">
INTERACTIVE</a></span><span class="right"> <a href="/electricity/monthly/xls/table_1_02.xlsx" class="ico_xls" title="Monthly Net generation By energy source and producing sector Electric utilities "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_a" title="Monthly Net generation By energy source and producing sector ">
Electric utilities</a></li>
<li><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;linechart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;columnchart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;map=ELEC.GEN.ALL-US-94.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Monthly Net generation By energy source and producing sector  Independent power producers Electric utilities ">
INTERACTIVE</a></span><span class="right"> <a href="/electricity/monthly/xls/table_1_03.xlsx" class="ico_xls" title="Monthly Net generation By energy source and producing sector  Independent power producers  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_b" title="Monthly Net generation By energy source and producing sector  ">
Independent power producers</a></li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;linechart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;columnchart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;map=ELEC.GEN.ALL-US-94.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Monthly Net generation By energy source and producing sector Commercial combined heat and power sector ">
INTERACTIVE</a></span></span><span class="right"> <a href="/electricity/monthly/xls/table_1_04.xlsx" class="ico_xls" title="Monthly Net generation By energy source and producing sector Commercial combined heat and power sector "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_c" title="Monthly Net generation By energy source and producing sector ">
Commercial combined heat and power sector</a></li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=0g&amp;linechart=ELEC.GEN.ALL-US-5.M~ELEC.GEN.COW-US-5.M~ELEC.GEN.AOR-US-5.M~ELEC.GEN.NG-US-5.M&amp;columnchart=ELEC.GEN.ALL-US-5.M~ELEC.GEN.COW-US-5.M~ELEC.GEN.AOR-US-5.M~ELEC.GEN.NG-US-5.M&amp;map=ELEC.GEN.ALL-US-5.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly Net generation By energy source and producing sector Industrial combined heat and power sector ">
INTERACTIVE</a></span></span><span class="right"> <a href="/electricity/monthly/xls/table_1_05.xlsx" class="ico_xls" title="Monthly Net generation By energy source and producing sector Industrial combined heat and power sector "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_d" title="Monthly Net generation By energy source and producing sector ">
Industrial combined heat and power sector</a></li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vtvv&amp;geo=g&amp;sec=004&amp;freq=M&amp;start=200101&amp;end=201610&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly Net generation By energy source and producing sector Residential combined heat and power sector ">
INTERACTIVE</a></span></span><span class="right"> <a href="/electricity/monthly/xls/table_1_05.xlsx" class="ico_xls" title="Monthly Net generation By energy source and producing sector Residential combined heat and power sector "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_e" title="Monthly Net generation By energy source and producing sector  ">
Residential combined heat and power sector</a>                  </li>
</ul>
</li>
</ul>
</li>

</ul><?php /*/td>
<td colspan="2"*/ ?>
<a href="/electricity/monthly/#generation" style="margin-left:20px">... more monthly generation data from the <em>Electric Power Monthly</em></a><?php /*/td>
<td colspan="2"*/ ?>
<br /><br />
<ul>
<li><strong>Annual</strong>

<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script>
</div>

<ul>
<li><strong>By all energy sources and by producing sector</strong>
<ul>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=04&amp;linechart=ELEC.GEN.ALL-US-7.A~ELEC.GEN.COW-US-7.A~ELEC.GEN.NG-US-7.A~ELEC.GEN.AOR-US-7.A&amp;columnchart=ELEC.GEN.ALL-US-7.A~ELEC.GEN.COW-US-7.A~ELEC.GEN.NG-US-7.A~ELEC.GEN.AOR-US-7.A&amp;map=ELEC.GEN.ALL-US-7.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation By all energy sources and by producing sector  All sectors ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_01_a.xlsx" class="ico_xls" title="Annual Net generation By all energy sources and by producing sector  All sectors "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_01_a.html" title="Annual Net generation By all energy sources and by producing sector">
All sectors</a></li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=8&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation By all energy sources and by producing sector  Electric utilities ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_02_a.xlsx" class="ico_xls" title="Annual Net generation By all energy sources and by producing sector  Electric utilities "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_02_a.html" title="Annual Net generation By all energy sources and by producing sector ">
Electric utilities</a>
</li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation By all energy sources and by producing sector  Independent power producers ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_03_a.xlsx" class="ico_xls" title="Annual Net generation By all energy sources and by producing sector  Independent power producers "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_03_a.html" title="Annual Net generation By all energy sources and by producing sector ">
Independent power producers</a>
</li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=01&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation   Commercial sector ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_04_a.xlsx" class="ico_xls" title="Annual Net generation   Commercial sector "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_04_a.html" title="Annual Net generation ">
Commercial sector</a>
</li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation   Industrial sector ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_05_a.xlsx" class="ico_xls" title="Annual Net generation   Industrial sector "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_05_a.html" title="Annual Net generation ">
Industrial sector</a></li>
<li><strong>By type of renewable source</strong>
	<ul>
		<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation  By type of renewable source All sectors ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_01_b.xlsx" class="ico_xls" title="Annual Net generation  By type of renewable source All sectors "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_01_b.html" title="Annual Net generation  By type of renewable source ">
All sectors</a></li>
		<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=8&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation  By type of renewable source Electric utilities ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_02_b.xlsx" class="ico_xls" title="Annual Net generation  By type of renewable source Electric utilities "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_02_b.html" title="Annual Net generation  By type of renewable source ">
Electric utilities</a>
		</li>
		<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=00g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation  By type of renewable source Independent power producers ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_03_b.xlsx" class="ico_xls" title="Annual Net generation  By type of renewable source Independent power producers "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_03_b.html" title="Annual Net generation  By type of renewable source ">
Independent power producers</a>
		</li>
		<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=01&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation  By type of renewable source Commercial sector ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_04_b.xlsx" class="ico_xls" title="Annual Net generation  By type of renewable source Commercial sector "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_04_b.html" title="Annual Net generation  By type of renewable source ">
Commercial sector</a> </li>
		<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation  By type of renewable source Industrial sector ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/annual/xls/epa_03_05_b.xlsx" class="ico_xls" title="Annual Net generation  By type of renewable source Industrial sector "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_03_05_b.html" title="Annual Net generation  By type of renewable source">
Industrial sector</a></li>
	</ul>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</li>


</tr--->
<?php /* END Sales, Revenue, Prices & Customers Content ////////////////*/ ?>
<?php /* BEGIN Generation and Thermal Output Content ////////////////*/ ?>


			<li>
<strong>Useful thermal output</strong>
<ul>
<li><strong>By energy source and type of combined heat and power producers</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_03_23.xlsx" class="ico_xls" title="Useful thermal output All sectors "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_03_23.html" title="Useful thermal output">
All sectors</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_03_24.xlsx" class="ico_xls" title="Useful thermal output Electric power sector "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_03_24.html" title="Useful thermal output">Electric power sector</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_03_25.xlsx" class="ico_xls" title="Useful thermal output Commercial sector "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_03_25.html" title="Useful thermal output ">
Commercial sector</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_03_26.xlsx" class="ico_xls" title="Useful thermal output Industrial sector "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_03_26.html" title="Useful thermal output  ">
Industrial sector</a></li>
<!--<li><a href="/electricity/data/eia923/index.html">Monthly and annual generation &amp; fuel consumption detailed data files</a>
The EIA-906, EIA-920, EIA-923 and predecessor forms provide monthly and annual data on useful thermal output at the power plant and prime mover level.</li> -->
</ul>
</li>

			<li>
<strong>International</strong>
<ul>
<li><a href="/beta/international/data/browser/#?ord=SA&amp;cy=2013&amp;v=H&amp;vo=0&amp;so=0&amp;io=0&amp;start=1980&amp;end=2013&amp;vs=INTL.2-12-AFRC-BKWH.A~INTL.2-12-ASOC-BKWH.A~INTL.2-12-CSAM-BKWH.A~INTL.2-12-EURA-BKWH.A~INTL.2-12-EURO-BKWH.A~INTL.2-12-MIDE-BKWH.A~INTL.2-12-NOAM-BKWH.A&amp;c=4100000002000060000000000000g000200000000000000001&amp;pa=00000000000000000000000000000fvu&amp;f=A&amp;ug=g&amp;ct=1&amp;tl_type=p&amp;tl_id=2-A" title="International ">
Total  net generation</a><br />
<em>data from: <a href="/beta/international/data/browser/">International Energy Statistics</a></em>
</ul></li>
<?php /* END Generation and Thermal Output Content ////////////////*/ ?>
<?php /* BEGIN Electric Power Plants Generating Capacity Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="gencapacity"></a>Capacity of electric power plants</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>

			<li><strong>Detailed <a href="/survey/#eia-860">EIA-860</a> survey data </strong>
<ul>
<li><a href="/electricity/data/eia860M/">Preliminary monthly electric generator inventory </a></li>
<li><a href="/electricity/data/eia860/">Annual generator-level capacity information</a> (back to 1990)</li>

<!-- 
<li><form name="form3"  id="form3" >
<span class="right ico_xls">
<select name="jumpMenu3" id="jumpMenu3" >
<option value="/electricity/capacity/xls/existing_gen_units_2015.xlsx">2015</option>
<option value="/electricity/capacity/xls/existing_gen_units_2014.xls">2014</option>
<option value="/electricity/capacity/xls/existing_gen_units_2013.xls">2013</option>
<option value="/electricity/capacity/xls/existing_gen_units_2012.xls">2012</option>
<option value="/electricity/capacity/xls/existing_gen_units_2011.xls">2011</option>
<option value="/electricity/capacity/xls/existing_gen_units_2010.xls">2010</option>
<option value="/electricity/capacity/xls/existing_gen_units_2009.xls">2009</option>
<option value="/electricity/capacity/xls/existing_gen_units_2008.xls">2008</option>
<option value="/electricity/capacity/xls/existing_gen_units_2007.xls">2007</option>
<option value="/electricity/capacity/xls/existing_gen_units_2006.xls">2006</option>
<option value="/electricity/capacity/xls/existing_gen_units_2005.xls">2005</option>
<option value="/electricity/capacity/xls/existing_gen_units_2004.xls">2004</option>
<option value="/electricity/capacity/xls/existing_gen_units_2003.xls">2003</option>
</select>
<input type="button" name="go_button3" class="arrow_go" align="right"  id= "go_button3" value="Go" onclick="MM_jumpMenuGo('jumpMenu3','parent',1)" />
</span>
</form>
Coal-fired generating units capacity, energy source, date of first operation, and planned retirement date.</li>
-->              
</ul>
</li>
<tr class="white_first">
			<li>

<ul>
<li>  <strong>Monthly</strong>

<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_6_03.xlsx" class="ico_xls" title="Monthly New electric generating units ">XLS</a></span> New electric generating units</li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_6_05.xlsx" class="ico_xls" title=" Monthly Planned electric generating unit additions  "><i class="ico xls"><span>XLS</span></i></a></span> Planned electric generating unit additions </li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_6_06.xlsx" class="ico_xls" title="Monthly Planned electric generating unit retirements  "><i class="ico xls"><span>XLS</span></i></a></span> Planned electric generating unit retirements </li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_6_04.xlsx" class="ico_xls" title=" Monthly Retired electric generating units "><i class="ico xls"><span>XLS</span></i></a></span> Retired electric generating units</li>
</ul>

</li></ul>
<li><strong>Annual</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>

<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_03.xlsx" class="ico_xls" title="Annual Net generation By energy source  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_04_03.html" title="Annual Net generation  ">
By energy source</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_04.xlsx" class="ico_xls" title="Annual Net generation By producer type  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_04_04.html" title="Annual Net generation  ">
By producer type</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_02_a.xlsx" class="ico_xls" title="Annual Net generation By energy source, by producer   "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_04_02_a.html" title="Annual Net generation  ">
By energy source, by producer </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_02_b.xlsx" class="ico_xls" title="Annual Net generation By other renewables, by producer   "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_04_02_b.html" title="Annual Net generation  ">
By other renewables, by producer </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/existcapacity_annual.xls" class="ico_xls" title="Existing capacity by energy source, by producer, by state back to 2000 (annual data from the EIA-860) "><i class="ico xls"><span>XLS</span></i></a></span> Existing capacity by energy source, by producer, by state back to 2000 (annual data from the EIA-860)</li>

<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_06.xlsx" class="ico_xls" title="Annual Additions, retirements and changes in 2015  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_04_06.html">Additions, retirements and changes in 2015 </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_05.xlsx" class="ico_xls" title="Annual Planned generating capacity changes, by energy source, 2016-2020 "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_04_05.html">Planned generating capacity changes, by energy source, 2016-2020</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_01.xlsx" class="ico_xls" title="Annual Count of power plants by predominant source  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_04_01.html">Count of power plants by predominant source </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_02.xlsx" class="ico_xls" title="Annual Heat rates for selected energy sources  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_08_01.html">Heat rates for selected energy sources </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_04_04.xlsx" class="ico_xls" title="Annual Heat rates by prime mover "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_08_02.html">Heat rates by prime mover </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/plancapacity_annual.xls" class="ico_xls" title="Annual Proposed additions by year, energy source, and state "><i class="ico xls"><span>XLS</span></i></a></span> Proposed additions by year, energy source, and state (annual data from the <a href="/electricity/data/eia860/">Form EIA-860</a>)</li>
</ul>
<br />
<ul>
<li><strong>Daily nuclear capacity status/outages </strong>(with annual capacity)</li>
<ul>
<li><span class="right"><span class="right beta"><a href="/beta/outages/" title="Status of nuclear power plants ">
INTERACTIVE</a></span></span>Status of nuclear power plants</li>
</ul>
</ul>
</li>
<!--
			<li><strong>Generating Units</strong>

<ul>
<li class="additional-formats">Available formats: <a href="/cneaf/electricity/page/capacity/existingunits2008.xls" class="ico_xls">XLS</a></span>by State, by Company, by Plant</li>

<li class="additional-formats">Available formats: <a href="/cneaf/electricity/page/capacity/existingunitsbs2008.xls" class="ico_xls">XLS</a></span>by State, by Company, by Plant, by dominant Source</li>

</ul></li> --> <!--
			<li class="head"><a href="/cneaf/electricity/page/gen_companies/codesp1.html">Electric Power Industry Companies </a></strong></li>
 -->
<?php /* END Electric Power Plants Generating Capacity Content ////////////////*/ ?>
<?php /* BEGIN Consumption of Fuels Used to Generate Electricity Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="consumption"></a>Consumption of fuels used to generate electricity</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>


			<li><strong>Detailed <a href="/survey/#eia-923">EIA-923</a> (and previous) annual and preliminary monthly survey data </strong>
<ul>
<li><a href="/electricity/data/eia923/">By plant and utility/operator</a></li>
</ul>
</li>

<tr class="white_first">
			<li><strong>Monthly and annual</strong>
<div>
<script language="JavaScript" type="text/JavaScript" src="/totalenergy/data/monthly/txt/new_merheader.txt"></script> <em>Interactive data from <a href="/totalenergy/data/browser/" title="Consumption of fuels used to generate electricity ">
Total Energy Data Browser</a></em> </div>
<ul>
<li>All combustible fuels (monthly back to 1973, annual to 1949)<span class="right"><a href="/totalenergy/data/monthly/pdf/sec7_9.pdf" class="ico_pdf" title="All combustible fuels (monthly back to 1973, annual to 1949)  "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T07.03A" class="ico_csv" title="All combustible fuels (monthly back to 1973, annual to 1949)  "><i class="ico csv"><span>CSV</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T07.03A&amp;freq=m" class="ico_xls" title="All combustible fuels (monthly back to 1973, annual to 1949)  "><i class="ico xls"><span>XLS</span></i></a> <span class="beta right"><a href="/beta/MER/?tbl=T07.03A#/?f=M&amp;start=200001" title="All combustible fuels (monthly back to 1973, annual to 1949)  ">
INTERACTIVE</a></span></span> </li>

<li><strong>By energy source</strong>


<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script></div>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script></div></li>

<ul>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=8&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.COW-US-99.M~ELEC.CONS_EG.COW-US-1.M~ELEC.CONS_EG.COW-US-94.M~ELEC.CONS_EG.COW-US-96.M~ELEC.CONS_EG.COW-US-97.M&amp;columnchart=ELEC.CONS_EG.COW-US-99.M~ELEC.CONS_EG.COW-US-1.M~ELEC.CONS_EG.COW-US-94.M~ELEC.CONS_EG.COW-US-96.M~ELEC.CONS_EG.COW-US-97.M&amp;map=ELEC.CONS_EG.COW-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Consumption of fuels used to generate electricity by coal ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/monthly/xls/table_2_01_a.xlsx" class="ico_xls" title="Consumption of fuels used to generate electricity by coal "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_01_a" title="Consumption of fuels used to generate electricity by   ">
Coal</a>
</li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=4&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.PEL-US-99.M~ELEC.CONS_EG.PEL-US-1.M~ELEC.CONS_EG.PEL-US-94.M~ELEC.CONS_EG.PEL-US-96.M~ELEC.CONS_EG.PEL-US-97.M&amp;columnchart=ELEC.CONS_EG.PEL-US-99.M~ELEC.CONS_EG.PEL-US-1.M~ELEC.CONS_EG.PEL-US-94.M~ELEC.CONS_EG.PEL-US-96.M~ELEC.CONS_EG.PEL-US-97.M&amp;map=ELEC.CONS_EG.PEL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Consumption of fuels used to generate electricity by Petroleum liquids ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/monthly/xls/table_2_02_a.xlsx" class="ico_xls" title="Consumption of fuels used to generate electricity by Petroleum liquids "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_02_a" title="Consumption of fuels used to generate electricity by   ">
Petroleum liquids</a>
</li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=2&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.PC-US-99.M~ELEC.CONS_EG.PC-US-1.M~ELEC.CONS_EG.PC-US-94.M~ELEC.CONS_EG.PC-US-96.M~ELEC.CONS_EG.PC-US-97.M&amp;columnchart=ELEC.CONS_EG.PC-US-99.M~ELEC.CONS_EG.PC-US-1.M~ELEC.CONS_EG.PC-US-94.M~ELEC.CONS_EG.PC-US-96.M~ELEC.CONS_EG.PC-US-97.M&amp;map=ELEC.CONS_EG.PC-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title="Consumption of fuels used to generate electricity by Petroleum coke ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/monthly/xls/table_2_03_a.xlsx" class="ico_xls" title="Consumption of fuels used to generate electricity by Petroleum coke "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_03_a" title="Consumption of fuels used to generate electricity by   ">
Petroleum coke</a></li>
<li><span class="right"><span class="beta right"><a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Consumption of fuels used to generate electricity by Natural gas ">
INTERACTIVE</a></span></span> <span class="right"><a href="/electricity/monthly/xls/table_2_04_a.xlsx" class="ico_xls" title="Consumption of fuels used to generate electricity by Natural gas "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_04_a" title="Consumption of fuels used to generate electricity by   ">
Natural gas</a></li> </ul>
<li><strong>By industry type and state</strong></li>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/consumption_monthly.xls" class="ico_xls" title="Consumption of fuels used to generate electricity by industry type and state, monthly  "><i class="ico xls"><span>XLS</span></i></a></span> Monthly</li>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/annual_consumption_state.xls" class="ico_xls" title="Consumption of fuels used to generate electricity by industry type and state, annual  "><i class="ico xls"><span>XLS</span></i></a></span> Annual (back to 1990)</li>
</ul>
</ul>
<br />
... more fuel consumption data from: <a href="/electricity/monthly/#two"> <em>Electric Power Monthly</em></a> and <a href="/electricity/annual/#five" ><em>Electric Power Annual</em></a>
</li>
<?php /* END Consumption of Fuels Used to Generate Electricity Content ////////////////*/ ?>

<?php /* BEGIN Receipts of Fossil-Fuels for Electricity Generation Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="fossilfuels"></a>Receipts of fossil-fuels for electricity generation</strong></th>
<th><span class="right"></th>

</thead>
<tr class="white_first">
			<li>
<strong>Monthly summary </strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<ul>
<li>Physical units                <span class="right"> <a href="/electricity/monthly/xls/table_es2a.xlsx" class="ico_xls" title="Monthly summary Receipts of fossil-fuels for electricity generation Physical units  "><i class="ico xls"><span>XLS</span></i></a></span>
</li>
<li>Btu             <span class="right"> <a href="/electricity/monthly/xls/table_es2b.xlsx" class="ico_xls">
<span hidden="Monthly summary Receipts of fossil-fuels for electricity generation Btu "><i class="ico xls"><span>XLS</span></i></a></span>

</li>
</ul>

</li>


			<li><strong>By fuel</strong>
<ul>
<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_06_a" title="Monthly summary Receipts of fossil-fuels for electricity generation  ">
Coal</a> <span class="right"><a href="/electricity/monthly/xls/table_4_06_a.xlsx" class="ico_xls" title="Monthly summary Receipts of fossil-fuels for electricity generation coal "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"><a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=8&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.COW-US-99.M&amp;columnchart=ELEC.RECEIPTS.COW-US-99.M&amp;map=ELEC.RECEIPTS.COW-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly summary Receipts of fossil-fuels for electricity generation coal ">
INTERACTIVE</a></span></span></li>

<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_07_a" title="Monthly summary Receipts of fossil-fuels for electricity generation  ">
Petroleum liquids</a> <span class="right"><a href="/electricity/monthly/xls/table_4_07_a.xlsx" class="ico_xls" title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum liquids "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"><a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=4&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.PEL-US-99.M&amp;columnchart=ELEC.RECEIPTS.PEL-US-99.M&amp;map=ELEC.RECEIPTS.PEL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum liquids ">
INTERACTIVE</a></span></span></li>

<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_08_a" title="Monthly summary Receipts of fossil-fuels for electricity generation  ">
Petroleum coke</a> <span class="right"><a href="/electricity/monthly/xls/table_4_08_a.xlsx" class="ico_xls" title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum coke "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"><a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=2&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.PC-US-99.M&amp;columnchart=ELEC.RECEIPTS.PC-US-99.M&amp;map=ELEC.RECEIPTS.PC-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum coke ">
INTERACTIVE</a></span></span></li>

<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_09_a" title="Monthly summary Receipts of fossil-fuels for electricity generation  ">
Natural gas</a> <span class="right"><a href="/electricity/monthly/xls/table_4_09_a.xlsx" class="ico_xls" title="Monthly summary Receipts of fossil-fuels for electricity generation natural gas "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"><a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=1&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.NG-US-99.M&amp;columnchart=ELEC.RECEIPTS.NG-US-99.M&amp;map=ELEC.RECEIPTS.NG-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Monthly summary Receipts of fossil-fuels for electricity generation natural gas ">
INTERACTIVE</a></span></span>              </li>
</ul>
<br />
... more fuel receipts data from: <a href="/electricity/monthly/#four" title="more fuel receipts data from ">
<em>Electric Power Monthly</em></a> and <a href="/electricity/annual/#seven"  title="more fuel receipts data from "><em>Electric Power Annual</em></a>

</li>
<?php /* END Monthly Receipts of Fossil-Fuels for Electricity Generation Content ////////////////*/ ?>

<?php /* BEGIN Average Cost of Fossil-Fuels for Electricity Generation Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="avgcost"></a>Average cost of fossil-fuels for electricity generation</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr >
			<li><strong>Detailed <a href="/survey/#eia-923">EIA-923</a> (and previous) annual and preliminary monthly survey data </strong>
<ul>
<li><a href="/electricity/data/eia923/">By plant and utility/operator</a> </li>
</ul>
</li>

<tr class="white_first">
			<li>
<ul>
<li><strong>Monthly</li>
			<li>
<strong>Average cost of fossil fuels delivered by state</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script></div>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script></div>
<ul>
<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_10_a" title="Monthly Average cost of fossil fuels delivered by state  ">
Coal</a> <span class="right"><a href="/electricity/monthly/xls/table_4_10_a.xlsx" class="ico_xls" title="Monthly Average cost of fossil fuels delivered by state  Coal "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"><a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=8&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.COW-US-98.M&amp;columnchart=ELEC.COST_BTU.COW-US-98.M&amp;map=ELEC.COST_BTU.COW-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly Average cost of fossil fuels delivered by state  Coal ">
INTERACTIVE</a></span></span></li>
<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_11_a" title="Monthly Average cost of fossil fuels delivered by state  ">
Petroleum liquids</a> <span class="right"><a href="/electricity/monthly/xls/table_4_11_a.xlsx" class="ico_xls" title="Monthly Average cost of fossil fuels delivered by state Petroleum liquids "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"><a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=4&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.PEL-US-98.M&amp;columnchart=ELEC.COST_BTU.PEL-US-98.M&amp;map=ELEC.COST_BTU.PEL-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Monthly Average cost of fossil fuels delivered by state Petroleum liquids ">
INTERACTIVE</a></span></span></li>
<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_12_a" title="Monthly Average cost of fossil fuels delivered by state  ">
Petroleum coke</a> <span class="right"><a href="/electricity/monthly/xls/table_4_12_a.xlsx"class="ico_xls" title="Monthly Average cost of fossil fuels delivered by state Petroleum coke "><i class="ico xls"><span>XLS</span></i></a> <span class="beta right"><a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=2&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.PC-US-98.M&amp;columnchart=ELEC.COST_BTU.PC-US-98.M&amp;map=ELEC.COST_BTU.PC-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly Average cost of fossil fuels delivered by state Petroleum coke ">
INTERACTIVE</a></span></span></li>
<li><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_13_a" title="Monthly Average cost of fossil fuels delivered by state  ">
Natural gas</a> <span class="right"><a href="/electricity/monthly/xls/table_4_13_a.xlsx" class="ico_xls" title="Monthly Average cost of fossil fuels delivered by state Natural gas "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"><a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=1&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.NG-US-98.M&amp;columnchart=ELEC.COST_BTU.NG-US-98.M&amp;map=ELEC.COST_BTU.NG-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0" title="Monthly Average cost of fossil fuels delivered by state Natural gas ">
INTERACTIVE</a></span></span></li>
</ul>
</li>

</ul>
<br />
... more fuel cost data from: <a href="/electricity/monthly/#four"> <span hidden="more fuel cost data from ">
<em>Electric Power Monthly</em></a>

</li>
<?php /*tr><li><a href="/electricity/monthly/index.cfm#four">More fuel cost data data from the Electric Power Monthly</a></li></tr*/ ?>

			<li>
<ul>
<li><strong>Annual <br />
Receipts, average cost, and quality of fossil fuels for electricity generation</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_07_01.xlsx" class="ico_xls" title="Receipts, cost, and quality of coal, petroleum, and natural gas  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_07_01.html">Receipts,  cost, and quality of coal, petroleum, and natural gas</a>
</li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_07_02.xlsx" class="ico_xls" title="Receipts and quality of coal  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_07_02.html">Receipts and quality of coal</a>
</li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_07_03.xlsx" class="ico_xls" title="Average quality of coal, petroleum, and natural gas  "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_07_03.html">Average quality of coal, petroleum, and natural gas</a>
</li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_07_04.xlsx" class="ico_xls" title=" Weighted average cost of coal, petroleum, and natural gas "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/annual/html/epa_07_04.html">Weighted average cost of coal, petroleum, and natural gas</a>
</li>
</ul>
</li>

</ul>
<br />
... more fuel cost data from: <a href="/electricity/annual/#seven" ><em>Electric Power Annual</em></a>

</li>
<?php /*tr><li><a href="/electricity/annual/index.cfm#seven">More fuel cost data data from the Electric Power Annual</a></li></tr*/ ?>
<?php /* END Average Cost of Fossil-Fuels for Electricity Generation Content ////////////////*/ ?>
<?php /* BEGIN Fossil-Fuel Stocks for Electricity Generation Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="ffstocks"></a>Fossil-fuel stocks for electricity generation</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr class="white_first">
			<li><strong>Stocks of fossil fuels by</strong>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<div>
<script language="JavaScript" type="text/javascript" src="/electricity/monthly/electricitydatabrowser.txt"></script></div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_3_01.xlsx" class="ico_xls" title="Stocks of fossil fuels by Electric power sector "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_01" title="Stocks of fossil fuels by  ">
Electric power sector</a> </li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_3_02.xlsx" class="ico_xls" title="Stocks of fossil fuels by state "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_02" title="Stocks of fossil fuels by  ">
State</a> </li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_3_03.xlsx" class="ico_xls" title="Stocks of fossil fuels by Census division "><i class="ico xls"><span>XLS</span></i></a></span> <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_03" title="Stocks of fossil fuels by  ">
Census division</a> </li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_3_04.xlsx" class="ico_xls" title="Stocks of fossil fuels by Coal and rank "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_04" title="Stocks of fossil fuels by  ">
Coal and rank</a> </li>
<li><span class="right"><span class="beta"><a href="/electricity/data/browser/#/topic/11?agg=2,0,1&amp;fuel=e&amp;geo=vvvvvvvvvvvvo&amp;sec=008&amp;freq=M&amp;start=200801&amp;end=201411&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Stocks of fossil fuels by State and Census division ">
INTERACTIVE</a></span></span> State and Census division </li>
</li>
</ul></li>
<?php /* END Fossil-Fuel Stocks for Electricity Generation Content ////////////////*/ ?>
<?php /* BEGIN Electricity Costs Content ////////////////*/ ?>
<?php /* END Electricity Costs Content ////////////////*/ ?>
<?php /* BEGIN Revenue and Exepense Statistics for... Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="revenue"></a>Cost, revenue and expenses</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr class="white_first">
			<li><div>
<strong>For major investor-owned utilities</strong></li>
			<li><span class="release-date">Release Date: </span><span class="date"><script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_03.xlsx" class="ico_xls" title="Revenue and expense statistics  "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_08_03.html">Revenue and expense statistics </a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_03.xlsx" class="ico_xls" title="Average power plant operating expenses  "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_08_04.html">Average power plant operating expenses </a></li>
</ul>
<!--              <strong>For cooperative borrower-owned utilities</li>
			<li> <script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script> 
	</div>
	<ul>
		<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_05.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_05.html">Revenue and expense statistics </a></li></ul>
--> <strong>Forecast assumptions</li>
			<li>
<em class="hideme">Release date: February 6, 2018 | <a href="/outlooks/aeo/">Annual Energy Outlook 2018</a></em>
<ul>
<li><a href="/outlooks/aeo/electricity_generation.cfm">Levelized cost of new generating technologies</a></li>
<!--<li><a href="/analysis/studies/powerplants/capitalcost/">Updated capital cost estimates for electricity generation plants</a></li> -->
<li><a href="/outlooks/aeo/assumptions/pdf/table_8.2.pdf">Cost and performance characteristics of new    generating technologies</a></li>
</li>
</ul>
<b>Generator Construction cost data</b><br />
<em class="hideme">Release date: May 18, 2017 | data from <a href="/electricity/data/eia860/">Form EIA-860</a></em>
<li><a href="/electricity/generatorcosts/">For electric generators installed in 2015</a>&nbsp;&nbsp;&nbsp;  <a href="/electricity/generatorcosts/xls/generator_costs_2015.xlsx" class="ico_xls" title="Generator Construction cost data or electric generators installed in 2015    "><i class="ico xls"><span>XLS</span></i></a></li>
<li><a href="/electricity/generatorcosts/archive/2014/">For electric generators installed in 2014</a>&nbsp;&nbsp;&nbsp;  <a href="/electricity/generatorcosts/archive/2014/xls/generator_costs_2014.xlsx" class="ico_xls" title="Generator Construction cost data or electric generators installed in 2014    "><i class="ico xls"><span>XLS</span></i></a></li>
<li><a href="/electricity/generatorcosts/archive/2013/">For electric generators installed in 2013</a>&nbsp;&nbsp;&nbsp;  <a href="/electricity/generatorcosts/archive/2013/xls/generator_costs_2013.xlsx" class="ico_xls" title="Generator Construction cost data or electric generators installed in 2013    "><i class="ico xls"><span>XLS</span></i></a></li>
</li>
<?php /* END Revenue and Exepenses Content ////////////////*/ ?>
<?php /* BEGIN Electricity Costs: Trade &amp; Reliability Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i><a name="traderel"></a>Electricity transactions, reliability<!--, transmission capacity --></strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr >
			<li>
<strong>Detailed EIA-411 survey  data </strong>(Data for 1990-2015, projections for 2016-2026)
<ul>
<li><a href="/electricity/data/eia411/">Electric reliability information and bulk power supply and demand information </a> <br />
</li>
</ul>
</li>
<tr class="white_first">
			<li><li><strong>Electricity transactions</strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_02_11.xlsx" class="ico_xls" title="Electricity purchases    "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_02_11.html">Electricity purchases</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_02_12.xlsx" class="ico_xls" title="Electricity sales for resale  "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_02_12.html">Electricity sales for resale</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_02_13.xlsx" class="ico_xls" title="Electricity imports and exports  "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_02_13.html">Electricity imports and exports</a></li>
<li><a href="/electricity/wholesale/">Wholesale market data </a></li>
</ul>
</li>
<br />
<li><strong>Electric disturbance events</strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/monthly/epm_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_b_1.xlsx" class="ico_xls" title="Electric disturbance events,  Monthly, year-to-date current year   "><i class="ico xls"><span>XLS</span></i></a></span>Monthly, year-to-date current year </li>
<li class="additional-formats">Available formats: <a href="/electricity/monthly/xls/table_b_2.xlsx" class="ico_xls" title="Electric disturbance events, Monthly, last year     "><i class="ico xls"><span>XLS</span></i></a></span>Monthly, last year </li>
<li><a href="/electricity/data/disturbance/disturb_events_archive.html" title="Electric disturbance events, ">
Monthly, prior years </a> </li>
</ul>
</li>
<!--<ul>

<li><strong>Transmission capacity by high-voltage size</strong>
<div> 
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script> 
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_10_b.xlsx" class="ico_xls">XLS</a></span> <a href="/electricity/annual/html/epa_08_10_a.html">Existing</a>
</li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_10_b.xlsx" class="ico_xls">XLS</a></span> <a href="/electricity/annual/html/epa_08_10_b.html">Proposed</a>
</li>
</ul>
</ul> --></li>
<?php /* END Electricity Costs: Trade &amp; Reliability Content ////////////////*/ ?>
<?php /* BEGIN Demand, Capability Resources, and Capability Margins Content ////////////////*/ ?>
<!--        	<h2><i class="ico expand-collapse"></i><a name="demand"></a>Demand, load, capacity resources, and capacity margins</strong></th>
<th><span class="right"></th>

</thead>
<tr class="white_first">
			<li><div> 
<script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script> 
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_06_a.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_06_a.html">Noncoincident peak load, 2002-2012 actual</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_06_b.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_06_b.html">Noncoincident peak load , 2012 actual, 2013-2017 projected</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_07_a.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_07_a.html">Net energy for load , 2002-2012 actual</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_07_b.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_07_b.html">Net energy for load , 2012 actual, 2013-2017 projected</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_08_a.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_08_a.html">Summer net internal demand, capacity resources, and capacity margins, 2002-2012 actual</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_08_b.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_08_b.html">Summer net internal demand, capacity resources, and capacity margins, 2012 actual, 2013-2017 projected</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_09_a.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_09_a.html">Winter net internal demand, capacity resources, and capacity margins, 2002-2012 actual</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_08_09_b.xlsx" class="ico_xls">XLS</a></span><a href="/electricity/annual/html/epa_08_09_b.html">Winter net internal demand, capacity resources, and capacity margins, 2012 actual, 2013-2017 projected</a></li>
</li>
</ul>
 -->
	<h2><i class="ico expand-collapse"></i><a name="dsm"></a>Demand-side management program</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr class="white_first">
			<li><div>
<script language="JavaScript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_10_06.xlsx" class="ico_xls" title="Energy efficiency   "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_10_06.html">Energy efficiency</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_10_07.xlsx" class="ico_xls" title="Energy efficiency - life cycle     "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_10_07.html">Energy efficiency - life cycle</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_10_08.xlsx" class="ico_xls" title="Demand response - yearly energy and demand savings   "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_10_08.html">Demand response - yearly energy and demand savings</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_10_09.xlsx" class="ico_xls" title="Demand response- program costs  "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_10_09.html">Demand response- program costs</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_10_10.xlsx" class="ico_xls" title="Advanced metering count by technology type  "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_10_10.html">Advanced metering  count by technology type</a></li>
</li>
</ul></li>


<?php /* END Demand, Capability Resources, and Capability Margins Content ////////////////*/ ?>
<?php /* BEGIN Electricity and the Environment Content ////////////////*/ ?>
	<h2><i class="ico expand-collapse"></i>
<th align="right"><a name="elecenv"></a>Electricity and the environment</strong></th>
<th><span class="right"><?php /*Additional formats*/ ?></span></th>

</thead>
<tr >
			<li><strong>Detailed EIA-923 emissions survey  data</strong>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/data/state/emission_annual.xls" class="ico_xls" title="Electric power industry estimated emissions by state (back to 1990 )   "> XLS</a></span> Electric power industry estimated emissions by state (back to 1990 )</li>
<li><a href="/electricity/data/emissions/">Annual emissions by plant and region</a><br />
			<li><span class="release-date">Release Date: </span><span class="date">December 18, 2017 </em></li>
<li><a href="/electricity/data/water/">Annual thermoelectric cooling water data</a><br />
			<li><span class="release-date">Release Date: </span><span class="date">December 19, 2017 </em></li>
</ul></li>
<tr class="white_first">
			<li>
<ul>
<li><strong>Annual</strong>
<div>
<script language="javascript" type="text/javascript" src="/electricity/annual/epa_release_date.txt"></script>
</div>
<ul>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_09_01.xlsx" class="ico_xls" title="Emissions from energy consumption at power plants    "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_09_01.html">Emissions from energy consumption at power plants</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_09_02.xlsx" class="ico_xls" title="Generators with environmental equipment "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_09_02.html">Generators with environmental equipment</a></li>
<li class="additional-formats">Available formats: <a href="/electricity/annual/xls/epa_09_04.xlsx" class="ico_xls" title="Average flue gas desulfurization costs "><i class="ico xls"><span>XLS</span></i></a></span><a href="/electricity/annual/html/epa_09_04.html">Average flue gas desulfurization costs</a></li>
</ul>
</li>
</ul>
<ul>
<li><strong>Monthly/Annual</strong>
(monthly back to 2015, annual to 1950)
<div>
<script language="JavaScript" type="text/JavaScript" src="/totalenergy/data/monthly/txt/new_merheader.txt"></script>

<em>Interactive data from <a href="/totalenergy/data/browser/">Total Energy Data Browser</a></em>

</div>
<ul>
<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec12_9.pdf" class="ico_pdf" title="Carbon dioxide emissions from electricity generation   "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T12.06" class="ico_csv" title="Carbon dioxide emissions from electricity generation   "><i class="ico csv"><span>CSV</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T12.06&amp;freq=m" class="ico_xls" title="Carbon dioxide emissions from electricity generation   "><i class="ico xls"><span>XLS</span></i></a><span class="beta right"> <a href="/beta/MER/?tbl=T12.06#/?f=M&amp;start=200001" title="Carbon dioxide emissions from electricity generation   ">
INTERACTIVE</a></span></span> Carbon dioxide emissions from electricity generation
</li>
</ul>


</li>
</ul>          </li>
<?php /*
			<li class="head">Projected emissions of Carbon Dioxide from electricity generation</strong>
<em class="hideme">Release Date: April 26, 2011</li>
			<li class="additional-formats">Available formats:  <a href="/oiaf/aeo/tablebrowser/aeo_query_server/?event=ehExcel.getFile&amp;study=AEO2011&amp;region=1-0&amp;cases=ref2011-d020911a&amp;table=17-AEO2011&amp;yearFilter=0" class="ico_xls">XLS</a> </span></li>

			<li class="head">Projected emissions of Sulfur Dioxide from electricity generation</strong>
<em class="hideme">Release Date: April 26, 2011</li>
			<li class="additional-formats">Available formats:  <a href="/forecasts/aeo/excel/fig107.data.xls" class="ico_xls">XLS</a> </span></li>

			<li class="head">Projected emissions of Nitrogen Oxide from electricity generation</strong>
<em class="hideme">Release Date: April 26, 2011</li>
			<li class="additional-formats">Available formats:  <a href="/forecasts/aeo/excel/fig108.data.xls" class="ico_xls">XLS</a> </span></li>*/ ?>
<?php /* END Electricity and the Environment Content ////////////////*/ ?>
</table>
<?php /* End of Main Column */ ?>