<div class="secondary">
    <ul>
        <li class="head">
            <h2><i class="ico interactive"><span>Interactive</span></i>Interactive Electricity Data</h2></li>
        <li class="description">browse pre-defined or custom data views, graph or map data series down to the plant level</li>
        <li><a href="/electricity/data/browser/">Electricity data browser</a></li>
        <li style="text-align: center"> - OR -</li>
        <li><em>create your own app with our</em> <a href="/beta/api/qb.cfm?category=0"><strong>API</strong></a></li>
    </ul>
</div>
<div class="secondary">
    <ul>
        <li class="head">
            <h2>Detailed and historical electricity data by survey</h2></li>
        <li>
            <ul>
                <li><a href="/electricity/data/state/">State-level</a></li>
                <li><a href="/electricity/data/eia826/">Sales and revenue</a></li>
                <li><a href="/electricity/data/eia860/">Generating capacity</a></li>
                <li><a href="/electricity/data/eia923/">Power plant operating data</a></li>
                <li class="foot"><a href="/electricity/data/detail-data.html">More</a></li>
            </ul>
</li>
    </ul>
</div>