<div class="secondary">
	<ul>
		<li class="head"><h3>Interactive Electricity Data</h3></li>
		<li class="description">browse pre-defined or custom data views, graph or map data series down to the plant level</li>
		<li><a href="/electricity/data/browser/">Electricity data browser</a></li>
		<li> - OR - </li>
		<li><em> create your own app with our</em> <a href="/beta/api/qb.cfm?category=0"><strong>API</strongb></a></li>
	</ul>
</div>
<div class="secondary">
	<ul>
		<li class="head"><h2>Detailed and historical electricity data by survey</h2></li>
		<li>
			<ul>
				<li><a href="/electricity/data/state/">State-level</a></li>  
				<li><a href="/electricity/data/eia826/">Sales and revenue</a></li>  
				<li><a href="/electricity/data/eia860/">Generating capacity</a></li> 
				<li><a href="/electricity/data/eia923/">Power plant operating data</a></li> 
				<li><a href="/electricity/data/detail-data.html">see more...</a></li> 
			</ul>
		</li>
	</ul>
</div>