<p>
    Find statistics on electric power plants, capacity, generation, fuel consumption, sales, prices and customers.</p>
<span class="expand-collapse-container">
<i class="ico expand"><span>Expand all</span></i>
<i class="ico collapse"><span>Collapse all</span></i>
</span>
<div id="accordion" class="accordion">
    <h3>
        <a name="summary"></a>Summary</h3>
    <div class="content">
        <ul>
            <li>
                Electricity overview
            </li>
            <li class="include">
                <?php include('adaptive/totalenergy/data/monthly/includes/new-mer-header.inc') ?>
            </li>
            <li>
                <span class="source">Interactive
							<span class="source">data from:</span> Total Energy Data Browser</li>
            <li>
                <span class="formats">Available formats:</span>
                <a href="/totalenergy/data/monthly/pdf/sec7_3.pdf" title=" Electricity overview">
                    <i class="ico pdf">
								<span>PDF</span>
							</i>
                </a>
            </li>
            <li>
                <span class="formats">Available formats:</span>
                <a href="/totalenergy/data/browser/csv.cfm?tbl=T07.01" title=" Electricity overview">
                    <i class="ico csv">
								<span>CSV</span>
							</i>
                </a>
                <a href="/totalenergy/data/browser/xls.cfm?tbl=T07.01&amp;freq=m" title=" Electricity overview">
                    <i class="ico xls">
								<span>XLS</span>
							</i>
                </a> |
                <a href="/beta/MER/?tbl=T07.01#/?f=M&start=200001" title=" Electricity overview">
                    <i class="ico interactive">
								<span>Interactive</span>
							</i>
                </a>
            </li>
            <li>
                Total electric power industry summary statistics
            </li>
            <li>
                <ul>
                    <li>
                        Monthly
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_es1a" title=" Total electric power industry summary statistics">Latest month </a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_es1a.xlsx" title=" Total electric power industry summary statistics - monthly">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_es1b" title=" Total electric power industry summary statistics">Year-to-date </a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_es1b.xlsx" title=" Total electric power industry summary statistics - Year-to-date">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Annual (back to 2005)</li>
                    <li class="include">
                        <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_01_02.html">Summary statistics </a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_01_02.xlsx" title=" Total electric power industry summary statistics - annual">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                            <li>
                                <a href="/electricity/annual/html/epa_01_03.html">Supply and disposition of electricity </a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_01_03.xlsx" title=" Total electric power industry summary statistics - annual Supply and disposition of electricity">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li>
                <a href="/totalenergy/data/monthly/#electricity">...more national-level summary data </a>
            </li>
            <li>
                <a href="/electricity/state/">State summary statistics</a> (Capacity, generation, price, emissions and more)</li>
            <li>
                <span class="release-date">Release Date:</span>
                <span class="date">January 25, 2018 </span> |
                <span class="source">data from:</span> State Electricity Profiles</li>
            <li>
                International electricity data
            </li>
            <li>
                <span class="source">Data from:</span>
                <a href="/beta/international/data/browser/">International Energy Statistics</a>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/beta/international/data/browser/#?ord=SA&amp;cy=2013&amp;v=H&amp;vo=0&amp;so=0&amp;io=0&amp;start=1980&amp;end=2013&amp;vs=INTL.2-12-AFRC-BKWH.A~INTL.2-12-ASOC-BKWH.A~INTL.2-12-CSAM-BKWH.A~INTL.2-12-EURA-BKWH.A~INTL.2-12-EURO-BKWH.A~INTL.2-12-MIDE-BKWH.A~INTL.2-12-NOAM-BKWH.A&amp;c=4100000002000060000000000000g000200000000000000001&amp;pa=00000000000000000000000000000fvu&amp;f=A&amp;ug=g&amp;ct=1&amp;tl_type=p&amp;tl_id=2-A">Generation </a>
                    </li>
                    <li>
                        <a href="/beta/international/data/browser/#?ord=SA&amp;cy=2012&amp;v=H&amp;vo=0&amp;so=0&amp;io=0&amp;start=1980&amp;end=2012&amp;vs=INTL.2-2-AFRC-BKWH.A~INTL.2-2-ASOC-BKWH.A~INTL.2-2-CSAM-BKWH.A~INTL.2-2-EURA-BKWH.A~INTL.2-2-EURO-BKWH.A~INTL.2-2-MIDE-BKWH.A~INTL.2-2-NOAM-BKWH.A&amp;c=4100000002000060000000000000g000200000000000000001&amp;pa=0000002&amp;f=A&amp;ug=g&amp;ct=1&amp;tl_type=p&amp;tl_id=2-A">Consumption </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- END Summary Content -->
    <!-- BEGIN Sales, Revenue, Prices & Customers Content -->
    <h3>

        <a name="sales"></a>Sales (consumption), revenue, prices &amp; customers</h3>

    <div class="content">
        <ul class="highlight">
            <li>
                Detailed preliminary
                <a href="/survey/#eia-826">EIA-826</a> monthly survey data (back to 1990)</li>
            <li>
                <ul>
                    <li>Revenue, sales, customer counts, and retail price by state and sector</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/data/eia826/xls/sales_revenue.xls" title=" Revenue, sales, customer counts, and retail price by state and sector">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li>
                Retail sales of electricity to ultimate customers
            </li>
            <li>
                <ul>
                    <li>
                        Monthly
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_01">By sector</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_5_04_b.xlsx" title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a title="View in Total Energy Browser Monthly retail sales of electricity to ultimate customers " href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;linechart=ELEC.SALES.TX-ALL.M~ELEC.SALES.TX-RES.M~ELEC.SALES.TX-COM.M~ELEC.SALES.TX-IND.M&amp;columnchart=ELEC.SALES.TX-ALL.M~ELEC.SALES.TX-RES.M~ELEC.SALES.TX-COM.M~ELEC.SALES.TX-IND.M&amp;map=ELEC.SALES.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201510&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_04_a" title="Monthly retail sales of electricity to ultimate customers">By sector, by state </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Annual
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_02_02.html" title=" Annual retail sales of electricity to ultimate customers">By sector, by provider</a> (back to 2005, Interactive to 2001)</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_02_02.xlsx" title=" Annual retail sales of electricity to ultimate customers">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;linechart=ELEC.SALES.US-ALL.A&amp;columnchart=ELEC.SALES.US-ALL.A&amp;map=ELEC.SALES.US-ALL.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                                    title=" Annual retail sales of electricity to ultimate customers">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>By sector, by state, by provider (back to 1990)</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/data/state/sales_annual.xlsx" title=" Annual retail sales of electricity to ultimate customers by sector, by state, by provider">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                By state and utility
                            </li>
                            <li>
                                <span class="release-date">Release Date:</span>
                                <span class="date">November 6, 2017 </span> |
                                <span class="source">data from:</span>
                                <a href="/electricity/data/eia861/">Form EIA-861 annual survey data</a>
                            </li>
                            <li class="include">
                                <?php include('adaptive/electricity/sales_revenue_price/esr-header.inc') ?>
                            </li>
                            <li class="list-item">
                                <ul>
                                    <li>Residential sector</li>
                                    <li>
                                        <span class="formats">Available formats:</span>
                                        <a href="/electricity/sales_revenue_price/pdf/table6.pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility residential sector">
                                            <i class="ico pdf">
														<span>PDF</span>
													</i>
                                        </a>
                                        <a href="/electricity/sales_revenue_price/xls/table6.xlsx" title=" Annual retail sales of electricity to ultimate customers By state and utility residential sector">
                                            <i class="ico xls">
														<span>XLS</span>
													</i>
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>Commercial sector</li>
                                    <li>
                                        <span class="formats">Available formats:</span>
                                        <a href="/electricity/sales_revenue_price/pdf/table7.pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility commercial sector">
                                            <i class="ico pdf">
														<span>PDF</span>
													</i>
                                        </a>
                                        <a href="/electricity/sales_revenue_price/xls/table7.xlsx" title=" Annual retail sales of electricity to ultimate customers By state and utility commercial sector">
                                            <i class="ico xls">
														<span>XLS</span>
													</i>
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>Industrial sector</li>
                                    <li>
                                        <span class="formats">Available formats:</span>
                                        <a href="/electricity/sales_revenue_price/pdf/table8.pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility industrial sector">
                                            <i class="ico pdf">
														<span>PDF</span>
													</i>
                                        </a>
                                        <a href="/electricity/sales_revenue_price/xls/table8.xlsx" title=" Annual retail sales of electricity to ultimate customers By state and utility industrial sector">
                                            <i class="ico xls">
														<span>XLS</span>
													</i>
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>Transportation sector</li>
                                    <li>
                                        <span class="formats">Available formats:</span>
                                        <a href="/electricity/sales_revenue_price/pdf/table9.pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility transportation sector">
                                            <i class="ico pdf">
														<span>PDF</span>
													</i>
                                        </a>
                                        <a href="/electricity/sales_revenue_price/xls/table9.xlsx" title=" Annual retail sales of electricity to ultimate customers By state and utility transportation sector">
                                            <i class="ico xls">
														<span>XLS</span>
													</i>
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>Total, all sectors </li>
                                    <li>
                                        <span class="formats">Available formats:</span>
                                        <a href="/electricity/sales_revenue_price/pdf/table10.pdf" title=" Annual retail sales of electricity to ultimate customers By state and utility all sectors">
                                            <i class="ico pdf">
														<span>PDF</span>
													</i>
                                        </a>
                                        <a href="/electricity/sales_revenue_price/xls/table10.xlsx" title=" Annual retail sales of electricity to ultimate customers By state and utility all sectors">
                                            <i class="ico xls">
														<span>XLS</span>
													</i>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                Revenue from retail sales of electricity to ultimate customers
            </li>
        </ul>
        <ul>
            <li class="release-schedule">
                Monthly
            </li>
            <li class="include">
                <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
            </li>
            <li class="include">
                <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_02" title="monthly revenue from retail sales of electricity to ultimate customers">By sector</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_5_02.xlsx" title="monthly revenue from retail sales of electricity to ultimate customers">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a> |
                        <a title="View in Total Energy Browser monthly revenue from retail sales of electricity to ultimate customers by sector" href="/electricity/data/browser/#/topic/6?agg=0,1&amp;geo=g&amp;linechart=ELEC.REV.US-ALL.M~ELEC.REV.US-RES.M~ELEC.REV.US-COM.M~ELEC.REV.US-IND.M&amp;columnchart=ELEC.REV.US-ALL.M~ELEC.REV.US-RES.M~ELEC.REV.US-COM.M~ELEC.REV.US-IND.M&amp;map=ELEC.REV.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>

                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_05_a" title="monthly revenue from retail sales of electricity to ultimate customers">By sector, by state</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_5_05_a.xlsx" title="monthly revenue from retail sales of electricity to ultimate customers">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a> |
                        <a title="View in Total Energy Browser monthly revenue from retail sales of electricity to ultimate customers by sector, by state" href="/electricity/data/browser/#/topic/6?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                Annual
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_02_03.html" title=" annual revenue from retail sales of electricity to ultimate customers By sector">By sector, by provider</a> (back to 2005)</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_02_03.xlsx" title=" annual revenue from retail sales of electricity to ultimate customers By sector, by provider (back to 2005)">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                    </li>
                    <li>By sector, by state, by provider (back to 1990)</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/data/state/revenue_annual.xlsx" title=" annual revenue from retail sales of electricity to ultimate customers By sector, by state, by provider (back to 2005)">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                    <li>By sector, by state (back to 2001)</li>
                    <li>
                        <span class="release-date">Release Date:</span>
                        <span class="date">November 6, 2017 </span> |
                        <span class="source">data from:</span>
                        <a href="/electricity/data/eia861/">Form EIA-861 annual survey data</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <!-- span class="beta" -->
                        <a href="/electricity/data/browser/#/topic/5?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;linechart=ELEC.SALES.US-ALL.A&amp;columnchart=ELEC.SALES.US-ALL.A&amp;map=ELEC.SALES.US-ALL.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                            title=" annual revenue from retail sales of electricity to ultimate customers By sector, by state, by provider (back to 2005)">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
                    </li>
                    <li>
                        By state and utility
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/sales_revenue_price/esr-header.inc') ?>
                    </li>
                    <li>Residential sector</li>
                    <li>
                        <a href="/electricity/sales_revenue_price/xls/table6.xls" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, residential sector">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/sales_revenue_price/pdf/table6.pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility residential, sector">
                            <i class="ico pdf">
										<span>PDF</span>
									</i>
                        </a>
                    </li>
                    <li>Commercial sector</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/sales_revenue_price/pdf/table7.pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, commercial sector">
                            <i class="ico pdf">
										<span>PDF</span>
									</i>
                        </a>
                    </li>
                    <li>
                        <a href="/electricity/sales_revenue_price/xls/table7.xlsx" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, commercial sector">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                    <li>Industrial sector</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/sales_revenue_price/pdf/table8.pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility Industrial sector">
                            <i class="ico pdf">
										<span>PDF</span>
									</i>
                        </a>
                    </li>
                    <li>
                        <a href="/electricity/sales_revenue_price/xls/table8.xlsx" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, Industrial sector">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                    <li>Transportation sector</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/sales_revenue_price/pdf/table9.pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, transportation sector">
                            <i class="ico pdf">
										<span>PDF</span>
									</i>
                        </a>
                    </li>
                    <li>
                        <a href="/electricity/sales_revenue_price/xls/table9.xlsx" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, transportation sector">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                    <li>Total, all sectors</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/sales_revenue_price/pdf/table10.pdf" title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, all sectors">
                            <i class="ico pdf">
										<span>PDF</span>
									</i>
                        </a>
                        <a href="/electricity/sales_revenue_price/xls/table10.xlsx">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>span title=" Annual revenue from retail sales of electricity to ultimate customers By state and utility, all sectors">
                    </li>
                </ul>
            </li>
        </ul>
        </li>

        <li>
            Average retail price of electricity to ultimate customers:
        </li>
        <li class="list-item">
            <ul>
                <li class="release-schedule">
                    Monthly
                </li>
                <li class="include">
                    <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                </li>
                <li class="include">
                    <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
                </li>
                <li class="list-item">
                    <ul>
                        <li>
                            <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_03" title="Monthly average retail price of electricity to ultimate customers">By sector</a>
                        </li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/monthly/xls/table_5_03.xlsx" title="Monthly average retail price of electricity to ultimate customers">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a> |
                            <a title="View in Total Energy Browser Monthly average retail price of electricity to ultimate customers  by sector" href="/electricity/data/browser/#/topic/7?agg=0,1&amp;geo=g&amp;linechart=ELEC.PRICE.US-ALL.M~ELEC.PRICE.US-RES.M~ELEC.PRICE.US-COM.M~ELEC.PRICE.US-IND.M&amp;columnchart=ELEC.PRICE.US-ALL.M~ELEC.PRICE.US-RES.M~ELEC.PRICE.US-COM.M~ELEC.PRICE.US-IND.M&amp;map=ELEC.PRICE.US-ALL.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=&amp;endsec=vg">
                                <i class="ico interactive">
											<span>Interactive</span>
										</i>
                            </a>
                        </li>
                        <li>
                            <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_5_06_a" title="Annual  average retail price of electricity to ultimate customers">By sector, by state</a>
                        </li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/monthly/xls/table_5_06_a.xlsx" title="Monthly average retail price of electricity to ultimate customers">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a> |
                            <a title="View in Total Energy Browser Annual  average retail price of electricity to ultimate customers  by sector" href="/electricity/data/browser/#/topic/7?agg=0,1&amp;geo=vvvvvvvvvvvvo&amp;endsec=vg&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0">
                                <i class="ico interactive">
											<span>Interactive</span>
										</i>
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    Annual
                </li>
                <li class="list-item">
                    <ul>
                        <li>
                            <a href="/electricity/annual/html/epa_02_04.html" title="Annual  average retail price of electricity to ultimate customers">By sector, by provider</a> (back to 2005)
                        </li>
                        <li class="include">
                            <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                        </li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/annual/xls/epa_02_04.xlsx" title="Annual  average retail price of electricity to ultimate customers  by sector, by provider(back to 2005)">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>By sector, by state, by provider (back to 1990)</li>
                        <li>
                            <span class="release-date">Release Date:</span>
                            <span class="date">November 6, 2017 </span> |
                            <span class="date">
										<a href="/electricity/data/eia861/">Form EIA-861 annual survey data</a>
									</span>
                        </li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/data/state/avgprice_annual.xlsx" title="Annual  average retail price of electricity to ultimate customers  by sector, by provider (back to 1990)">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>By sector, by state (back to 2001)</li>
                        <li class="include">
                            <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
                        </li>
                        <li>
                            By state and utility
                        </li>
                        <li class="include">
                            <?php include('adaptive/electricity/sales_revenue_price/esr-header.inc') ?>
                        </li>
                        <li>Residential sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table6.pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, residential sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                        </li>
                        <li>
                            <a href="/electricity/sales_revenue_price/xls/table6.xlsx" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, residential sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>Commercial sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table7.pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, commercial sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table7.xlsx" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, commercial sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>Industrial sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table8.pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, industrial sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table8.xlsx" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, industrial sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>Transportation sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table9.pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, transportation sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table9.xlsx" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, transportation sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>All sectors</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table10.pdf" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, all sectors">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table10.xlsx" title="Annual  average retail price of electricity to ultimate customers  by sector, by state and utility, all sectors">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        </ul>
        </li>
        <li>
            Number of customers (annual):
        </li>
        <li>
            <ul>
                <li>
                    <a href="/electricity/annual/html/epa_02_01.html" title=" Number of customers (annual) (back to 2005)">By sector, by provider</a> (back to 2005)
                </li>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/annual/xls/epa_02_01.xlsx" title=" Number of customers (annual) (back to 2005)">
                        <i class="ico xls">
									<span>XLS</span>
								</i>
                    </a>
                </li>
                <li class="include">
                    <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                </li>
                <li>
                    By sector by state and/or utility
                </li>
                <li class="include">
                    <?php include('adaptive/electricity/sales_revenue_price/esr-header.inc') ?>
                </li>
                <li class="list-item">
                    <ul>
                        <li>By state, by provider</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/data/state/customers_annual.xlsx" title=" Number of customers (annual) (back to 2005) by state, by provider">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>By state by sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table1.pdf" title=" Number of customers (annual) (back to 2005) by state, by sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table1.xlsx" title=" Number of customers (annual) (back to 2005) by state, by sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>Residential sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table6.pdf" title=" Number of customers (annual) (back to 2005) by state, residential sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table6.xlsx" title=" Number of customers (annual) (back to 2005) by state, residential sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>Commercial sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table7.pdf" title=" Number of customers (annual) (back to 2005) by state, commercial sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table7.xlsx" title=" Number of customers (annual) (back to 2005) by state, commercial sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>Industrial sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table8.pdf" title=" Number of customers (annual) (back to 2005) by state, industrial sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table8.xlsx" title=" Number of customers (annual) (back to 2005) by state, industrial sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>Transportation sector</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table9.pdf" title=" Number of customers (annual) (back to 2005) by state, transportation sector">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table9.xlsx" title=" Number of customers (annual) (back to 2005) by state, transportation sector">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                        <li>All sectors by state and utility</li>
                        <li>
                            <span class="formats">Available formats:</span>
                            <a href="/electricity/sales_revenue_price/pdf/table10.pdf" title=" Number of customers (annual) (back to 2005) by state, all sectors">
                                <i class="ico pdf">
											<span>PDF</span>
										</i>
                            </a>
                            <a href="/electricity/sales_revenue_price/xls/table10.xlsx" title=" Number of customers (annual) (back to 2005) by state, all sectors">
                                <i class="ico xls">
											<span>XLS</span>
										</i>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        </ul>
    </div>

    <h3>

        <a name="netmetering"></a>Net metering</h3>

    <div class="content">
        <ul>
            <li>
                Net metering
            </li>
            <li class="list-item">
                <ul>
                    <li class="release-schedule">
                        Monthly (back to 2011)</li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/data/eia826/" title="monthly">Net metering</a> - capacity, number of meters, and energy sold back, by state, sector, and utility</li>
                            <li>
                                <a href="/electricity/data/eia826/index.html#ammeter" title="monthly">Advanced metering</a> - number and megawatthours served, by state by sector </li>
                        </ul>
                    </li>
                    <li>
                        Annual (back to 2005)</li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_04_10.html">Net metering customers and capacity by technology type, by end use sector</a>
                            </li>
                            <li class="include">
                                <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_04_10.xlsx" title=" annual net metering back to 2005">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>




    <h3>

        <a name="generation"></a>Generation and thermal output</h3>

    <div class="content">
        <ul class="highlight">
            <li>
                Detailed preliminary
                <a href="/survey/#eia-923">EIA-923</a> monthly and annual survey data (back to 1990)</li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/data/eia923/index.html">Plant-level generation and fuel consumption data </a>
                    </li>
                </ul>
                <ul>
                    <li>State-level generation and fuel consumption data</li>
                    <li class="list-item sub-list">
                        <ul>
                            <li>Monthly (back to 2001)</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/data/state/generation_monthly.xlsx" title=" State-level generation and fuel consumption, monthly (back to 2001)">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>Annual (back to 1990)</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/data/state/annual_generation_state.xls" title=" State-level generation and fuel consumption, annual (back to 1990)">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li>
                Net generation
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        Monthly
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_01" title="Monthly Net generation">By all energy sources</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_1_01.xlsx" title="Monthly Net generation By all energy sources">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=0,1&amp;fuel=vtvo&amp;geo=vvvvvvvvvvvvo&amp;linechart=ELEC.GEN.ALL-US-99.M&amp;columnchart=ELEC.GEN.ALL-US-99.M&amp;map=ELEC.GEN.ALL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                                    title="Monthly Net generation By all energy sources">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_01_a" title="Monthly Net generation">By type of renewable source</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_1_01_a.xlsx" title="Monthly Net generation By type of renewable source">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=1,0,2&amp;fuel=02&amp;geo=vvvvvvvvvvvvo&amp;sec=o3g&amp;linechart=ELEC.GEN.AOR-US-99.M~ELEC.GEN.AOR-US-1.M~ELEC.GEN.AOR-US-94.M~ELEC.GEN.AOR-US-96.M~ELEC.GEN.AOR-US-97.M&amp;columnchart=ELEC.GEN.AOR-US-99.M~ELEC.GEN.AOR-US-1.M~ELEC.GEN.AOR-US-94.M~ELEC.GEN.AOR-US-96.M~ELEC.GEN.AOR-US-97.M&amp;map=ELEC.GEN.AOR-US-99.M&amp;freq=M&amp;start=200101&amp;end=201412&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin="
                                    title="Monthly Net generation By type of renewable source">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>By energy source (plus by annual back to 1950)</li>
                            <li class="include">
                                <?php include('adaptive/totalenergy/data/monthly/includes/new-mer-header.inc') ?>
                            </li>
                            <li>
                                <span class="source">Interactive
											<span class="source">data from:</span>
                                <a href="/totalenergy/data/browser/">Total Energy Data Browser</a>
                                </span>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/totalenergy/data/monthly/pdf/sec7_5.pdf" title="Monthly Net generation By energy source (plus by annual back to 1950)">
                                    <i class="ico pdf">
												<span>PDF</span>
											</i>
                                </a>
                                <a href="/totalenergy/data/browser/csv.cfm?tbl=T07.02A" title="Monthly Net generation By energy source (plus by annual back to 1950)">
                                    <i class="ico csv">
												<span>CSV</span>
											</i>
                                </a>
                                <a href="/totalenergy/data/browser/xls.cfm?tbl=T07.02A&amp;freq=m" title="Monthly Net generation By energy source (plus by annual back to 1950)">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/beta/MER/?tbl=T07.02A#/?f=A&amp;start=1949&amp;end=2014&amp;charted=1-2-3-5-8-14" title="Monthly Net generation By energy source (plus by annual back to 1950)">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        By energy source and producing sector
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_a" title="Monthly Net generation By energy source and producing sector">Electric utilities</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_1_02.xlsx" title="Monthly Net generation By energy source and producing sector Electric utilities">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=8&amp;linechart=ELEC.GEN.ALL-US-1.M~ELEC.GEN.COW-US-1.M~ELEC.GEN.NG-US-1.M~ELEC.GEN.NUC-US-1.M~ELEC.GEN.HYC-US-1.M&amp;columnchart=ELEC.GEN.ALL-US-1.M~ELEC.GEN.COW-US-1.M~ELEC.GEN.NG-US-1.M~ELEC.GEN.NUC-US-1.M~ELEC.GEN.HYC-US-1.M&amp;map=ELEC.GEN.ALL-US-1.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                                    title="Monthly Net generation By energy source and producing sector Electric utilities">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_b" title="Monthly Net generation By energy source and producing sector">Independent power producers</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_1_03.xlsx" title="Monthly Net generation By energy source and producing sector  Independent power producers">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;linechart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;columnchart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;map=ELEC.GEN.ALL-US-94.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                                    title="Monthly Net generation By energy source and producing sector  Independent power producers Electric utilities">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_c" title="Monthly Net generation By energy source and producing sector">Commercial combined heat and power sector</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_1_04.xlsx" title="Monthly Net generation By energy source and producing sector Commercial combined heat and power sector">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;linechart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;columnchart=ELEC.GEN.ALL-US-94.M~ELEC.GEN.COW-US-94.M~ELEC.GEN.NG-US-94.M~ELEC.GEN.NUC-US-94.M~ELEC.GEN.HYC-US-94.M&amp;map=ELEC.GEN.ALL-US-94.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                                    title="Monthly Net generation By energy source and producing sector Commercial combined heat and power sector">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_d" title="Monthly Net generation By energy source and producing sector">Industrial combined heat and power sector</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_1_05.xlsx" title="Monthly Net generation By energy source and producing sector Industrial combined heat and power sector">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=0g&amp;linechart=ELEC.GEN.ALL-US-5.M~ELEC.GEN.COW-US-5.M~ELEC.GEN.AOR-US-5.M~ELEC.GEN.NG-US-5.M&amp;columnchart=ELEC.GEN.ALL-US-5.M~ELEC.GEN.COW-US-5.M~ELEC.GEN.AOR-US-5.M~ELEC.GEN.NG-US-5.M&amp;map=ELEC.GEN.ALL-US-5.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                                    title="Monthly Net generation By energy source and producing sector Industrial combined heat and power sector">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_1_02_e" title="Monthly Net generation By energy source and producing sector">Residential combined heat and power sector</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_1_05.xlsx" title="Monthly Net generation By energy source and producing sector Residential combined heat and power sector">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vtvv&amp;geo=g&amp;sec=004&amp;freq=M&amp;start=200101&amp;end=201610&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Monthly Net generation By energy source and producing sector Residential combined heat and power sector">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a href="/electricity/monthly/#generation">... more monthly generation
							<span class="source">data from:</span> the Electric Power Monthly</li>
					<li class="list-item">
						<ul>
							<li>
								Annual
							</li>
							<li class="incluide">
								<?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
							</li>
							<li class="include">
								<?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
							</li>
							<li class="list-item">
								<ul>
									<li>
										By all energy sources and by producing sector
									</li>
									<li class="list-item">
										<ul>
											<li>
												<a href="/electricity/annual/html/epa_03_01_a.html" title="Annual Net generation By all energy sources and by producing sector">All sectors</a>
            </li>
            <li>
                <span class="formats">Available formats:</span>
                <a href="/electricity/annual/xls/epa_03_01_a.xlsx" title="Annual Net generation By all energy sources and by producing sector  All sectors">
                    <i class="ico xls">
														<span>XLS</span>
													</i>
                </a> |
                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=04&amp;linechart=ELEC.GEN.ALL-US-7.A~ELEC.GEN.COW-US-7.A~ELEC.GEN.NG-US-7.A~ELEC.GEN.AOR-US-7.A&amp;columnchart=ELEC.GEN.ALL-US-7.A~ELEC.GEN.COW-US-7.A~ELEC.GEN.NG-US-7.A~ELEC.GEN.AOR-US-7.A&amp;map=ELEC.GEN.ALL-US-7.A&amp;freq=A&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0"
                    title="Annual Net generation By all energy sources and by producing sector  All sectors">
                    <i class="ico interactive">
														<span>Interactive</span>
													</i>
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="/electricity/annual/html/epa_03_02_a.html" title="Annual Net generation By all energy sources and by producing sector">Electric utilities</a>
            </li>
            <li>
                <span class="formats">Available formats:</span>
                <a href="/electricity/annual/xls/epa_03_02_a.xlsx" title="Annual Net generation By all energy sources and by producing sector  Electric utilities">
                    <i class="ico xls">
														<span>XLS</span>
													</i>
                </a> |
                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=8&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation By all energy sources and by producing sector  Electric utilities">
                    <i class="ico interactive">
														<span>Interactive</span>
													</i>
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="/electricity/annual/html/epa_03_03_a.html" title="Annual Net generation By all energy sources and by producing sector">Independent power producers</a>
            </li>
            <li>
                <span class="formats">Available formats:</span>
                <a href="/electricity/annual/xls/epa_03_03_a.xlsx" title="Annual Net generation By all energy sources and by producing sector  Independent power producers">
                    <i class="ico xls">
														<span>XLS</span>
													</i>
                </a> |
                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=00g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation By all energy sources and by producing sector  Independent power producers">
                    <i class="ico interactive">
														<span>Interactive</span>
													</i>
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="/electricity/annual/html/epa_03_04_a.html" title="Annual Net generation">Commercial sector</a>
            </li>
            <li>
                <span class="formats">Available formats:</span>
                <a href="/electricity/annual/xls/epa_03_04_a.xlsx" title="Annual Net generation   Commercial sector">
                    <i class="ico xls">
														<span>XLS</span>
													</i>
                </a> |
                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=01&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation   Commercial sector">
                    <i class="ico interactive">
														<span>Interactive</span>
													</i>
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="/electricity/annual/html/epa_03_05_a.html" title="Annual Net generation">Industrial sector</a>
            </li>
            <li>
                <span class="formats">Available formats:</span>
                <a href="/electricity/annual/xls/epa_03_05_a.xlsx" title="Annual Net generation   Industrial sector">
                    <i class="ico xls">
														<span>XLS</span>
													</i>
                </a> |
                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=vvg&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation   Industrial sector">
                    <i class="ico interactive">
														<span>Interactive</span>
													</i>
                </a>
            </li>
        </ul>
        </li>
        <li>
            By type of renewable source
        </li>
        <li class="list-item">
            <ul>
                <li>
                    <a href="/electricity/annual/html/epa_03_01_b.html" title="Annual Net generation  By type of renewable source">All sectors</a>
                </li>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/annual/xls/epa_03_01_b.xlsx" title="Annual Net generation  By type of renewable source All sectors">
                        <i class="ico xls">
														<span>XLS</span>
													</i>
                    </a> |
                    <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation  By type of renewable source All sectors">
                        <i class="ico interactive">
														<span>Interactive</span>
													</i>
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="/electricity/annual/html/epa_03_02_b.html" title="Annual Net generation  By type of renewable source">Electric utilities</a>
                </li>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/annual/xls/epa_03_02_b.xlsx" title="Annual Net generation  By type of renewable source Electric utilities">
                        <i class="ico xls">
														<span>XLS</span>
													</i>
                    </a> |
                    <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=8&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation  By type of renewable source Electric utilities">
                        <i class="ico interactive">
														<span>Interactive</span>
													</i>
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="/electricity/annual/html/epa_03_03_b.html" title="Annual Net generation  By type of renewable source">Independent power producers</a>
                </li>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/annual/xls/epa_03_03_b.xlsx" title="Annual Net generation  By type of renewable source Independent power producers">
                        <i class="ico xls">
														<span>XLS</span>
													</i>
                    </a> |
                    <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=00g&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation  By type of renewable source Independent power producers">
                        <i class="ico interactive">
														<span>Interactive</span>
													</i>
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="/electricity/annual/html/epa_03_04_b.html" title="Annual Net generation  By type of renewable source">Commercial sector</a>
                </li>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/annual/xls/epa_03_04_b.xlsx" title="Annual Net generation  By type of renewable source Commercial sector">
                        <i class="ico xls">
														<span>XLS</span>
													</i>
                    </a> |
                    <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=01&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;maptype=0&amp;rse=0&amp;pin=" title="Annual Net generation  By type of renewable source Commercial sector">
                        <i class="ico interactive">
														<span>Interactive</span>
													</i>
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="/electricity/annual/html/epa_03_05_b.html" title="Annual Net generation  By type of renewable source">Industrial sector</a>
                </li>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/annual/xls/epa_03_05_b.xlsx" title="Annual Net generation  By type of renewable source Industrial sector">
                        <i class="ico xls">
														<span>XLS</span>
													</i>
                    </a> |
                    <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Annual Net generation  By type of renewable source Industrial sector">
                        <i class="ico interactive">
														<span>Interactive</span>
													</i>
                    </a>
                </li>
            </ul>
        </li>
        </ul>
        </li>
        </ul>
        </li>
        </ul>
        </li>
        </ul>
        <ul>
            <li>
                Useful thermal output
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        By energy source and type of combined heat and power producers
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_03_23.html" title="Useful thermal output">All sectors</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_03_23.xlsx" title="Useful thermal output All sectors">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_03_24.html" title="Useful thermal output">Electric power sector</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_03_24.xlsx" title="Useful thermal output Electric power sector">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_03_25.html" title="Useful thermal output">Commercial sector</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_03_25.xlsx" title="Useful thermal output Commercial sector">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_03_26.html" title="Useful thermal output">Industrial sector</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_03_26.xlsx" title="Useful thermal output Industrial sector">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        International
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/beta/international/data/browser/#?ord=SA&amp;cy=2013&amp;v=H&amp;vo=0&amp;so=0&amp;io=0&amp;start=1980&amp;end=2013&amp;vs=INTL.2-12-AFRC-BKWH.A~INTL.2-12-ASOC-BKWH.A~INTL.2-12-CSAM-BKWH.A~INTL.2-12-EURA-BKWH.A~INTL.2-12-EURO-BKWH.A~INTL.2-12-MIDE-BKWH.A~INTL.2-12-NOAM-BKWH.A&amp;c=4100000002000060000000000000g000200000000000000001&amp;pa=00000000000000000000000000000fvu&amp;f=A&amp;ug=g&amp;ct=1&amp;tl_type=p&amp;tl_id=2-A"
                                    title="International">Total net generation</a>
                            </li>
                            <li>
                                <span class="source">data from:</span>
                                <a href="/beta/international/data/browser/">International Energy Statistics</a>
                        </ul>
                        </li>
                </ul>
                </li>
        </ul>
    </div>
    <!-- END Generation and Thermal Output Content -->
    <!-- BEGIN Electric Power Plants Generating Capacity Content -->
    <h3>

        <a name="gencapacity"></a>Capacity of electric power plants</h3>

    <div class="content">
        <ul>
            <li>
                Detailed
                <a href="/survey/#eia-860">EIA-860</a> survey data
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/data/eia860M/">Preliminary monthly electric generator inventory </a>
                    </li>
                    <li>
                        <a href="/electricity/data/eia860/">Annual generator-level capacity information</a> (back to 1990)</li>
                </ul>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        Monthly
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>New electric generating units</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_6_03.xlsx" title="Monthly New electric generating units">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>Planned electric generating unit additions</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_6_05.xlsx" title="Monthly Planned electric generating unit additions">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>Planned electric generating unit retirements</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_6_06.xlsx" title="Monthly Planned electric generating unit retirements">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>Retired electric generating units</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_6_04.xlsx" title="Monthly Retired electric generating units">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                Annual
            </li>
            <li class="include">
                <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_04_03.html" title="Annual Net generation">By energy source</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_03.xlsx" title="Annual Net generation By energy source">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_04_04.html" title="Annual Net generation">By producer type</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_04.xlsx" title="Annual Net generation By producer type">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_04_02_a.html" title="Annual Net generation">By energy source, by producer </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_02_a.xlsx" title="Annual Net generation By energy source, by producer">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_04_02_b.html" title="Annual Net generation">By other renewables, by producer </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_02_b.xlsx" title="Annual Net generation By other renewables, by producer">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>Existing capacity by energy source, by producer, by state back to 2000 (annual data from: the EIA-860)</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/data/state/existcapacity_annual.xls" title="Existing capacity by energy source, by producer, by state back to 2000 (annual data from: the EIA-860)">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_04_06.html">Additions, retirements and changes in 2015 </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_06.xlsx" title="Annual Additions, retirements and changes in 2015">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_04_05.html">Planned generating capacity changes, by energy source, 2016-2020</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_05.xlsx" title="Annual Planned generating capacity changes, by energy source, 2016-2020">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_04_01.html">Count of power plants by predominant source </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_01.xlsx" title="Annual Count of power plants by predominant source">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_08_01.html">Heat rates for selected energy sources </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_08_02.xlsx" title="Annual Heat rates for selected energy sources">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_08_02.html">Heat rates by prime mover </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_04_04.xlsx" title="Annual Heat rates by prime mover">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                    <li>Proposed additions by year, energy source, and state (annual
                        <span class="source">data from:</span> the
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/data/eia860/">Form EIA-860</a>)</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/data/state/plancapacity_annual.xls" title="Annual Proposed additions by year, energy source, and state">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                </li>
                <li class="list-item">
                    <ul>
                        <li>
                            Daily nuclear capacity status/outages(with annual capacity)</li>
                        <li class="list-item">
                            <ul>
                                <li>Status of nuclear power plants</li>
                                <li>
                                    <span class="formats">Available formats:</span>
                                    <a href="/beta/outages/" title="Status of nuclear power plants">
                                        <i class="ico interactive">
													<span>Interactive</span>
												</i>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
        </ul>
    </div>
    <!-- END Electric Power Plants Generating Capacity Content -->
    <!-- BEGIN Consumption of Fuels Used to Generate Electricity Content -->
    <h3>

        <a name="consumption"></a>Consumption of fuels used to generate electricity</h3>

    <div class="content">
        <ul class="highlight">
            <li>
                Detailed
                <a href="/survey/#eia-923">EIA-923</a> (and previous) annual and preliminary monthly survey data
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/data/eia923/">By plant and utility/operator</a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li>Monthly and annual
            </li>
            <li class="include">
                <?php include('adaptive/totalenergy/data/monthly/includes/new-mer-header.inc') ?>
            </li>
            <li>
                <span class="source">Interactive
							<span class="source">data from:</span>
                <a href="/totalenergy/data/browser/" title="Consumption of fuels used to generate electricity">Total Energy Data Browser</a>
            </li>
            <li class="list-item">
                <ul>
                    <li>All combustible fuels (monthly back to 1973, annual to 1949)</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/totalenergy/data/monthly/pdf/sec7_9.pdf" title="All combustible fuels (monthly back to 1973, annual to 1949)">
                            <i class="ico pdf">
										<span>PDF</span>
									</i>
                        </a>
                        <a href="/totalenergy/data/browser/csv.cfm?tbl=T07.03A" title="All combustible fuels (monthly back to 1973, annual to 1949)">
                            <i class="ico csv">
										<span>CSV</span>
									</i>
                        </a>
                        <a href="/totalenergy/data/browser/xls.cfm?tbl=T07.03A&amp;freq=m" title="All combustible fuels (monthly back to 1973, annual to 1949)">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a> |
                        <a href="/beta/MER/?tbl=T07.03A#/?f=M&amp;start=200001" title="All combustible fuels (monthly back to 1973, annual to 1949)">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        By energy source
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_01_a" title="Consumption of fuels used to generate electricity by">Coal</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_2_01_a.xlsx" title="Consumption of fuels used to generate electricity by coal">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=8&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.COW-US-99.M~ELEC.CONS_EG.COW-US-1.M~ELEC.CONS_EG.COW-US-94.M~ELEC.CONS_EG.COW-US-96.M~ELEC.CONS_EG.COW-US-97.M&amp;columnchart=ELEC.CONS_EG.COW-US-99.M~ELEC.CONS_EG.COW-US-1.M~ELEC.CONS_EG.COW-US-94.M~ELEC.CONS_EG.COW-US-96.M~ELEC.CONS_EG.COW-US-97.M&amp;map=ELEC.CONS_EG.COW-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                                    title="Consumption of fuels used to generate electricity by coal">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_02_a" title="Consumption of fuels used to generate electricity by">Petroleum liquids</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_2_02_a.xlsx" title="Consumption of fuels used to generate electricity by Petroleum liquids">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=4&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.PEL-US-99.M~ELEC.CONS_EG.PEL-US-1.M~ELEC.CONS_EG.PEL-US-94.M~ELEC.CONS_EG.PEL-US-96.M~ELEC.CONS_EG.PEL-US-97.M&amp;columnchart=ELEC.CONS_EG.PEL-US-99.M~ELEC.CONS_EG.PEL-US-1.M~ELEC.CONS_EG.PEL-US-94.M~ELEC.CONS_EG.PEL-US-96.M~ELEC.CONS_EG.PEL-US-97.M&amp;map=ELEC.CONS_EG.PEL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                                    title="Consumption of fuels used to generate electricity by Petroleum liquids">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_03_a" title="Consumption of fuels used to generate electricity by">Petroleum coke</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_2_03_a.xlsx" title="Consumption of fuels used to generate electricity by Petroleum coke">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/3?agg=1,0,2&amp;fuel=2&amp;geo=g&amp;sec=o3g&amp;linechart=ELEC.CONS_EG.PC-US-99.M~ELEC.CONS_EG.PC-US-1.M~ELEC.CONS_EG.PC-US-94.M~ELEC.CONS_EG.PC-US-96.M~ELEC.CONS_EG.PC-US-97.M&amp;columnchart=ELEC.CONS_EG.PC-US-99.M~ELEC.CONS_EG.PC-US-1.M~ELEC.CONS_EG.PC-US-94.M~ELEC.CONS_EG.PC-US-96.M~ELEC.CONS_EG.PC-US-97.M&amp;map=ELEC.CONS_EG.PC-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                                    title="Consumption of fuels used to generate electricity by Petroleum coke">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_2_04_a" title="Consumption of fuels used to generate electricity by">Natural gas</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_2_04_a.xlsx" title="Consumption of fuels used to generate electricity by Natural gas">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/0?agg=2,0,1&amp;fuel=03vo&amp;geo=g&amp;sec=02&amp;freq=A&amp;start=2001&amp;end=2014&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Consumption of fuels used to generate electricity by Natural gas">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        By industry type and state
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>Monthly</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/data/state/consumption_monthly.xls" title="Consumption of fuels used to generate electricity by industry type and state, monthly">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>Annual (back to 1990)</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/data/state/annual_consumption_state.xls" title="Consumption of fuels used to generate electricity by industry type and state, annual">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>... more fuel consumption
                        <span class="source">data from:</span>
                        <a href="/electricity/monthly/#two">Electric Power Monthly</a> and
                        <a href="/electricity/annual/#five">Electric Power Annual</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- END Consumption of Fuels Used to Generate Electricity Content -->
    <!-- BEGIN Receipts of Fossil-Fuels for Electricity Generation Content -->
    <h3>

        <a name="fossilfuels"></a>Receipts of fossil-fuels for electricity generation</h3>

    <div class="content">
        <ul>
            <li>
                Monthly summary
            </li>
            <li class="include">
                <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>Physical units</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_es2a.xlsx" title="Monthly summary Receipts of fossil-fuels for electricity generation Physical units">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>Btu</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_es2b.xlsx">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                By fuel
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_06_a" title="Monthly summary Receipts of fossil-fuels for electricity generation">Coal</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_4_06_a.xlsx" title="Monthly summary Receipts of fossil-fuels for electricity generation coal">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a> |
                        <a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=8&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.COW-US-99.M&amp;columnchart=ELEC.RECEIPTS.COW-US-99.M&amp;map=ELEC.RECEIPTS.COW-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                            title="Monthly summary Receipts of fossil-fuels for electricity generation coal">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_07_a" title="Monthly summary Receipts of fossil-fuels for electricity generation">Petroleum liquids</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_4_07_a.xlsx" title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum liquids">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a> |
                        <a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=4&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.PEL-US-99.M&amp;columnchart=ELEC.RECEIPTS.PEL-US-99.M&amp;map=ELEC.RECEIPTS.PEL-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                            title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum liquids">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_08_a" title="Monthly summary Receipts of fossil-fuels for electricity generation">Petroleum coke</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_4_08_a.xlsx" title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum coke">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a> |
                        <a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=2&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.PC-US-99.M&amp;columnchart=ELEC.RECEIPTS.PC-US-99.M&amp;map=ELEC.RECEIPTS.PC-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                            title="Monthly summary Receipts of fossil-fuels for electricity generation petroleum coke">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_09_a" title="Monthly summary Receipts of fossil-fuels for electricity generation">Natural gas</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_4_09_a.xlsx" title="Monthly summary Receipts of fossil-fuels for electricity generation natural gas">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a> |
                        <a href="/electricity/data/browser/#/topic/12?agg=1,0,2&amp;fuel=1&amp;geo=vvvvvvvvvvvvo&amp;sec=o3o&amp;linechart=ELEC.RECEIPTS.NG-US-99.M&amp;columnchart=ELEC.RECEIPTS.NG-US-99.M&amp;map=ELEC.RECEIPTS.NG-US-99.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                            title="Monthly summary Receipts of fossil-fuels for electricity generation natural gas">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                </ul>
            </li>
            <li>... more fuel receipts
                <span class="source">data from:</span>
                <a href="/electricity/monthly/#four" title="more fuel receipts data from:">Electric Power Monthly</a> and
                <a href="/electricity/annual/#seven" title="more fuel receipts">Electric Power Annual</a>
            </li>
        </ul>
    </div>
    <!-- END Monthly Receipts of Fossil-Fuels for Electricity Generation Content -->
    <!-- BEGIN Average Cost of Fossil-Fuels for Electricity Generation Content -->
    <h3>

        <a name="avgcost"></a>Average cost of fossil-fuels for electricity generation</h3>

    <div class="content">
        <ul class="highlight">
            <li>
                Detailed
                <a href="/survey/#eia-923">EIA-923</a> (and previous) annual and preliminary monthly survey data
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/data/eia923/">By plant and utility/operator</a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li class="list-item">
                <ul>
                    <li>Monthly</li>
                    <li>
                        Average cost of fossil fuels delivered by state
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_10_a" title="Monthly Average cost of fossil fuels delivered by state">Coal</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_4_10_a.xlsx" title="Monthly Average cost of fossil fuels delivered by state  Coal">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=8&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.COW-US-98.M&amp;columnchart=ELEC.COST_BTU.COW-US-98.M&amp;map=ELEC.COST_BTU.COW-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                                    title="Monthly Average cost of fossil fuels delivered by state  Coal">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_11_a" title="Monthly Average cost of fossil fuels delivered by state">Petroleum liquids</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_4_11_a.xlsx" title="Monthly Average cost of fossil fuels delivered by state Petroleum liquids">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=4&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.PEL-US-98.M&amp;columnchart=ELEC.COST_BTU.PEL-US-98.M&amp;map=ELEC.COST_BTU.PEL-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                                    title="Monthly Average cost of fossil fuels delivered by state Petroleum liquids">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_12_a" title="Monthly Average cost of fossil fuels delivered by state">Petroleum coke</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_4_12_a.xlsx" title="Monthly Average cost of fossil fuels delivered by state Petroleum coke">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=2&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.PC-US-98.M&amp;columnchart=ELEC.COST_BTU.PC-US-98.M&amp;map=ELEC.COST_BTU.PC-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;maptype=0&amp;rse=0&amp;pin="
                                    title="Monthly Average cost of fossil fuels delivered by state Petroleum coke">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_4_13_a" title="Monthly Average cost of fossil fuels delivered by state">Natural gas</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/monthly/xls/table_4_13_a.xlsx" title="Monthly Average cost of fossil fuels delivered by state Natural gas">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/electricity/data/browser/#/topic/15?agg=1,0,2&amp;fuel=1&amp;geo=vvvvvvvvvvvvo&amp;sec=80o&amp;linechart=ELEC.COST_BTU.NG-US-98.M&amp;columnchart=ELEC.COST_BTU.NG-US-98.M&amp;map=ELEC.COST_BTU.NG-US-98.M&amp;freq=M&amp;ctype=linechart&amp;ltype=pin&amp;pin=&amp;rse=0&amp;maptype=0"
                                    title="Monthly Average cost of fossil fuels delivered by state Natural gas">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>... more fuel cost
                <span class="source">data from:</span>
                <a href="/electricity/monthly/#four">more fuel cost
							<span class="source">data from:</span> Electric Power Monthly</a>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        Annual
                    </li>
                    <li>
                        Receipts, average cost, and quality of fossil fuels for electricity generation
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_07_01.html">Receipts, cost, and quality of coal, petroleum, and natural gas</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_07_01.xlsx" title="Receipts, cost, and quality of coal, petroleum, and natural gas">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_07_01.html">Receipts, cost, and quality of coal, petroleum, and natural gas</a>
                            </li>
                            <li>
                                <a href="/electricity/annual/html/epa_07_01.html">Receipts, cost, and quality of coal, petroleum, and natural gas</a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_07_02.xlsx" title="Receipts and quality of coal">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                            <li>
                                <a href="/electricity/annual/html/epa_07_02.html">Receipts and quality of coal</a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_07_03.xlsx" title="Average quality of coal, petroleum, and natural gas">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                            <li>
                                <a href="/electricity/annual/html/epa_07_03.html">Average quality of coal, petroleum, and natural gas</a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_07_04.xlsx" title=" Weighted average cost of coal, petroleum, and natural gas">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                            <li>
                                <a href="/electricity/annual/html/epa_07_04.html">Weighted average cost of coal, petroleum, and natural gas</a>
                            </li>
                        </ul>
                    </li>
                    <li>... more fuel cost
                        <span class="source">data from:</span>
                        <a href="/electricity/annual/#seven">Electric Power Annual</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- END Average Cost of Fossil-Fuels for Electricity Generation Content -->
    <!-- BEGIN Fossil-Fuel Stocks for Electricity Generation Content -->
    <h3>

        <a name="ffstocks"></a>Fossil-fuel stocks for electricity generation</h3>

    <div class="content">
        <ul>
            <li>
                Stocks of fossil fuels by
            </li>
            <li class="include">
                <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
            </li>
            <li class="include">
                <?php include('adaptive/electricity/monthly/electricity-data-browser.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_01" title="Stocks of fossil fuels by">Electric power sector</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_3_01.xlsx" title="Stocks of fossil fuels by Electric power sector">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_02" title="Stocks of fossil fuels by">State</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_3_02.xlsx" title="Stocks of fossil fuels by state">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_03" title="Stocks of fossil fuels by">Census division</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_3_03.xlsx" title="Stocks of fossil fuels by Census division">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/monthly/epm_table_grapher.cfm?t=epmt_3_04" title="Stocks of fossil fuels by">Coal and rank</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_3_04.xlsx" title="Stocks of fossil fuels by Coal and rank">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>State and Census division </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/data/browser/#/topic/11?agg=2,0,1&amp;fuel=e&amp;geo=vvvvvvvvvvvvo&amp;sec=008&amp;freq=M&amp;start=200801&amp;end=201411&amp;ctype=linechart&amp;ltype=pin&amp;rtype=s&amp;pin=&amp;rse=0&amp;maptype=0" title="Stocks of fossil fuels by State and Census division">
                            <i class="ico interactive">
										<span>Interactive</span>
									</i>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- END Fossil-Fuel Stocks for Electricity Generation Content -->
    <!-- BEGIN Electricity Costs Content -->
    <!-- END Electricity Costs Content -->
    <!-- BEGIN Revenue and Exepense Statistics for... Content -->
    <h3>

        <a name="revenue"></a>Cost, revenue and expenses</h3>

    <div class="content">
        <ul>
            <li>
                For major investor-owned utilities
            </li>
            <li class="include">
                <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_08_03.html">Revenue and expense statistics </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_08_03.xlsx" title="Revenue and expense statistics">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_08_04.html">Average power plant operating expenses </a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_08_03.xlsx" title="Average power plant operating expenses">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                Forecast assumptions
            </li>
            <li>
                <span class="release-date">Release Date:</span>
                <span class="date">February 6, 2018 </span> |
                <span class="source">data from:</span>
                <a href="/outlooks/aeo/">Annual Energy Outlook 2018</a>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/outlooks/aeo/electricity_generation.cfm">Levelized cost of new generating technologies</a>
                    </li>
                    <li>
                        <a href="/outlooks/aeo/assumptions/pdf/table_8.2.pdf">Cost and performance characteristics of new generating technologies</a>
                    </li>
                </ul>
            </li>
            <li>
                Generator Construction cost data
            </li>
            <li>
                <span class="release-date">Release Date:</span>
                <span class="date">May 18, 2017</span> |
                <span class="source">data from:</span>
                <a href="/electricity/data/eia860/">Form EIA-860</a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="/electricity/generatorcosts/">For electric generators installed in 2015</a>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/generatorcosts/xls/generator_costs_2015.xlsx" title="Generator Construction cost data or electric generators installed in 2015 ">
                        <i class="ico xls">
									<span>XLS</span>
								</i>
                    </a>
                </li>
        </ul>
        <ul>
            <li>
                <a href="/electricity/generatorcosts/archive/2014/">For electric generators installed in 2014</a>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/generatorcosts/archive/2014/xls/generator_costs_2014.xlsx" title="Generator Construction cost data or electric generators installed in 2014 ">
                        <i class="ico xls">
									<span>XLS</span>
								</i>
                    </a>
                </li>
        </ul>
        <ul>
            <li>
                <a href="/electricity/generatorcosts/archive/2013/">For electric generators installed in 2013</a>
                <li>
                    <span class="formats">Available formats:</span>
                    <a href="/electricity/generatorcosts/archive/2013/xls/generator_costs_2013.xlsx" title="Generator Construction cost data or electric generators installed in 2013 ">
                        <i class="ico xls">
									<span>XLS</span>
								</i>
                    </a>
                </li>
        </ul>
    </div>
    <!-- END Revenue and Exepenses Content -->
    <!-- BEGIN Electricity Costs: Trade &amp; Reliability Content -->
    <h3>

        <a name="traderel"></a>Electricity transactions, reliability</h3>

    <div class="content">
        <ul class="highlight">
            <li>
                Detailed EIA-411 survey data(Data for 1990-2015, projections for 2016-2026)</li>
            <li>
                <ul>
                    <li>
                        <a href="/electricity/data/eia411/">Electric reliability information and bulk power supply and demand information </a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li>
                Electricity transactions
            </li>
            <li class="include">
                <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_02_11.html">Electricity purchases</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_02_11.xlsx" title="Electricity purchases ">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_02_12.html">Electricity sales for resale</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_02_12.xlsx" title="Electricity sales for resale">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_02_13.html">Electricity imports and exports</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_02_13.xlsx" title="Electricity imports and exports">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/wholesale/">Wholesale market data</a>
                    </li>
                </ul>
            </li>
            <li>
                Electric disturbance events
            </li>
            <li class="include">
                <?php include('adaptive/electricity/monthly/epm-release-date.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>Monthly, year-to-date current year </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_b_1.xlsx" title="Electric disturbance events,  Monthly, year-to-date current year">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>Monthly, last year </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/monthly/xls/table_b_2.xlsx" title="Electric disturbance events, Monthly, last year  ">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/data/disturbance/disturb_events_archive.html" title="Electric disturbance events,">Monthly, prior years</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- END Electricity Costs: Trade &amp; Reliability Content -->
    <!-- BEGIN Demand, Capability Resources, and Capability Margins Content -->
    <h3>

        <a name="dsm"></a>Demand-side management program</h3>

    <div class="content">
        <ul>
            <li class="include">
                <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_10_06.html">Energy efficiency</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_10_06.xlsx" title="Energy efficiency">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_10_07.html">Energy efficiency - life cycle</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_10_07.xlsx" title="Energy efficiency - life cycle  ">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_10_08.html">Demand response - yearly energy and demand savings</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_10_08.xlsx" title="Demand response - yearly energy and demand savings">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_10_09.html">Demand response- program costs</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_10_09.xlsx" title="Demand response- program costs">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/annual/html/epa_10_10.html">Advanced metering count by technology type</a>
                    </li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/annual/xls/epa_10_10.xlsx" title="Advanced metering count by technology type">
                            <i class="ico xls">
										<span>XLS</span>
									</i>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- END Demand, Capability Resources, and Capability Margins Content -->
    <!-- BEGIN Electricity and the Environment Content -->
    <h3>

        <a name="elecenv"></a>Electricity and the environment</h3>

    <div class="content">
        <ul class="highlight">
            <li>
                Detailed EIA-923 emissions survey data
            </li>
            <li class="list-item">
                <ul>
                    <li>Electric power industry estimated emissions by state (back to 1990 )</li>
                    <li>
                        <span class="formats">Available formats:</span>
                        <a href="/electricity/data/state/emission_annual.xls" title="Electric power industry estimated emissions by state (back to 1990 )">XLS</a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/data/emissions/">Annual emissions by plant and region</a>
                    </li>
                    <li>
                        <span class="release-date">Release Date:</span>
                        <span class="date">December 18, 2017 </span>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/electricity/data/water/">Annual thermoelectric cooling water data</a>
                    </li>
                    <li>
                        <span class="release-date">Release Date:</span>
                        <span class="date">December 19, 2017 </span>
                    </li>
                </ul>
            </li>
        </ul>
        <ul>
            <li class="list-item">
                <ul>
                    <li>
                        Annual
                    </li>
                    <li class="include">
                        <?php include('adaptive/electricity/annual/epa-release-date.inc') ?>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_09_01.html">Emissions from energy consumption at power plants</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_09_01.xlsx" title="Emissions from energy consumption at power plants ">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_09_02.html">Generators with environmental equipment</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_09_02.xlsx" title="Generators with environmental equipment">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                        <ul>
                            <li>
                                <a href="/electricity/annual/html/epa_09_04.html">Average flue gas desulfurization costs</a>
                            </li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/electricity/annual/xls/epa_09_04.xlsx" title="Average flue gas desulfurization costs">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="list-item">
                <ul>
                    <li>
                        Monthly/Annual (monthly back to 2015, annual to 1950)</li>
                    <li class="include">
                        <?php include('adaptive/totalenergy/data/monthly/includes/new-mer-header.inc') ?>
                    </li>
                    <li>
                        <span class="source">Interactive
									<span class="source">data from:</span>
                        <a href="/totalenergy/data/browser/">Total Energy Data Browser</a>
                    </li>
                    <li class="list-item">
                        <ul>
                            <li>Carbon dioxide emissions from electricity generation</li>
                            <li>
                                <span class="formats">Available formats:</span>
                                <a href="/totalenergy/data/monthly/pdf/sec12_9.pdf" title="Carbon dioxide emissions from electricity generation">
                                    <i class="ico pdf">
												<span>PDF</span>
											</i>
                                </a>
                                <a href="/totalenergy/data/browser/csv.cfm?tbl=T12.06" title="Carbon dioxide emissions from electricity generation">
                                    <i class="ico csv">
												<span>CSV</span>
											</i>
                                </a>
                                <a href="/totalenergy/data/browser/xls.cfm?tbl=T12.06&amp;freq=m" title="Carbon dioxide emissions from electricity generation">
                                    <i class="ico xls">
												<span>XLS</span>
											</i>
                                </a> |
                                <a href="/beta/MER/?tbl=T12.06#/?f=M&amp;start=200001" title="Carbon dioxide emissions from electricity generation">
                                    <i class="ico interactive">
												<span>Interactive</span>
											</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>