<div class="l-row header">
    <div class="l-full-width-col">
        <div class="notice">
            <p><strong><em>New:</em> <a href="/beta/realtime_grid/?src=data#/summary/demand?end=20160725&amp;start=20160625">Electric System Operating Data</a></strong> provides <strong>hourly</strong> electric operating data including actual and forecast
                demand, net generation, and the power flowing between electric systems. Check it out and give us feedback!</p>
        </div>
    </div>
</div>