<div class="efmi_ui_container left">
          <?php /* Row 1 */ ?>
            <ul id="bubble2">
              <li>                <a href="supply-nonopec.cfm">
                  <img class="small" src="/finance/markets/images/ui/supply_non_oecd_off.png" alt="Supply non-OECD" />
                  <img class="large" src="/finance/markets/images/ui/supply_non_oecd_on.png" alt="Supply non-OECD" />
                </a>
              </li>
              <li>                <a href="balance.cfm">
                  <img class="small" src="/finance/markets/images/ui/balance_off.png" alt="Balance" />
                  <img class="large" src="/finance/markets/images/ui/balance_on.png" alt="Balance" />
                </a>
              </li>
              <li>                <a href="demand-nonoecd.cfm">
                  <img class="small" src="/finance/markets/images/ui/demand_non_oecd_off.png" alt="Demand non-OECD" />
                  <img class="large" src="/finance/markets/images/ui/demand_non_oecd_on.png" alt="Demand non-OECD" />
                </a>
              </li>
            </ul>
            <div class="clear"></div>
          <?php /* Row 2 */ ?>
            <ul id="bubble2">
              <li>&nbsp;</li>
              <li>                <a href="spot_prices.cfm">
                  <img class="small" src="/finance/markets/images/ui/spot_prices_off.png" alt="Spot Prices" />
                  <img class="large" src="/finance/markets/images/ui/spot_prices_on.png" alt="Spot Prices" />
                </a>
              </li>
              <li>&nbsp;</li>
            </ul>
            <div class="clear"></div>
          <?php /* Row 3 */ ?>
            <ul id="bubble2">
              <li>                <a href="supply-opec.cfm">
                  <img class="small" src="/finance/markets/images/ui/supply_oecd_off.png" alt="Supply OECD" />
                  <img class="large" src="/finance/markets/images/ui/supply_oecd_on.png" alt="Supply OECD" />
                </a>
              </li>
              <li>                <a href="financial_markets.cfm">
                  <img class="small" src="/finance/markets/images/ui/financial_markets_off.png" alt="Financial Markets" />
                  <img class="large" src="/finance/markets/images/ui/financial_markets_on.png" alt="Financial Markets" />
                </a>
              </li>
              <li>                <a href="demand-oecd.cfm">
                  <img class="small" src="/finance/markets/images/ui/demand_oecd_off.png" alt="Demand OECD" />
                  <img class="large" src="/finance/markets/images/ui/demand_oecd_on.png" alt="Demand OECD" />
                </a>
              </li>
            </ul>
          </div>
          
          <div class="efmi_ui_side left">
            <a href="/finance/markets/images/world_oil_prices.png" class="fb2"><img src="/finance/markets/images/world_oil_prices_small.png" width="313" height="220" /></a>
            <div id="lnk">
                <a href="index.cfm?v=y" class="btn btn1" title="Overveiw"></a>
                <a href="/finance/markets/images/who.png" class="btn btn2 fb2"></a>
                <a href="/finance/markets/images/factors.png" class="btn btn3 fb2"></a>
                <a href="eia_what_drives_crude_oil_prices.pdf" class="btn btn4" title="Energy Financial Markets Presentation"></a>
            </div>
          </div>
          <div class="clear"></div>