<div class="secondary">
    <ul>
        <li class="head">
            <h2>Most requested data</h2>
        </li>

        <li class="icon">

            <a href="/cfapps/frs/frstables.cfm?tableNumber=1">Selected Financial Items</a>

            <span class="formats">
<a href="/cfapps/frs/excel.cfm?tableNumber=1&amp;startYear=1977" title="Selected Financial Items">
<i class="ico xls">
<span>XLS</span>
            </i>
            </a>
            </span>





        </li>

        <li class="icon">
            <a href="/cfapps/frs/frstables.cfm?tableNumber=2">Consolidated Income Statement</a>
            <span class="formats"><a href="/cfapps/frs/excel.cfm?tableNumber=2" title="Consolidated Income Statement"><i class="ico xls"><span>XLS</span></i>
            </a>
            </span>
        </li>

        <li class="icon">
            <a href="/cfapps/frs/frstables.cfm?tableNumber=3">Consolidated Balance Sheet</a>
            <span class="formats">
    <a href="/cfapps/frs/excel.cfm?tableNumber=3&startYear=1977" title="Consolidated Balance Sheet">
<i class="ico xls">
<span>XLS</span>
            </i>
            </a>
            </span>
        </li>

        <li class="icon">
            <a href="/cfapps/frs/frstables.cfm?tableNumber=4">Statement of Cash Flows</a>
            <span class="formats">
    <a href="/cfapps/frs/excel.cfm?tableNumber=4&startYear=1977" title="Statement of Cash Flows">
<i class="ico xls">
<span>XLS</span>
            </i>
            </a>
            </span>
        </li>

        <li class="icon">


            <a href="/cfapps/frs/frstables.cfm?tableNumber=5">Statement of Income for U.S. &amp; Foreign Petroleum</a>




            <span class="formats">
<a href="/cfapps/frs/excel.cfm?tableNumber=5" title="Statement of Income for U.S. and Foreign Petroleum">
<i class="ico xls">
<span>XLS</span>
            </i>
            </a>
            </span>
        </li>

        <li class="icon">

            <a href="/cfapps/frs/frstables.cfm?tableNumber=6">Statement of Income for U.S. &amp; Foreign Downstream Natural Gas</a>

            <span class="formats">
            <a href="/cfapps/frs/excel.cfm?tableNumber=6" title="Statement of Income for U.S. and Foreign Downstream Natural Gas">
            <i class="ico xls">
            <span>XLS</span>
            </i>
            </a>
            </span>


        </li>
        </li>
        <li class="sub-head">FRS Survey Data 1977 - 2009</li>
        <li>
            <ul>
                <li>
                    <a href="archive/frsdata/frsdata.html">The Financial Reporting System Public Data</a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="/finance/performanceprofiles/CoList.cfm">Historical Respondent Company List</a>
                </li>
            </ul>
        </li>
    </ul>
</div>



<div class="secondary">
    <ul>
        <li class="head">
            <h2>Related Reports</h2>
        </li>
        <li>
            <a href="/workingpapers/#finance">Working Papers</a>
        </li>
        <li>
            <a href="/finance/workshops.cfm">Workshops</a>
        </li>
    </ul>
</div>