<div class="primary">
<h1 class="no-border"><a name="mpurc" id="mpurc"></a>Market Prices and Uncertainty Report Charts</h1>
<div class="accordion all-open">
    <h3><a name="selected-charts"></a>Selected Charts</h3>
    <div class="accordion-content">
        <ul>
            <li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig1.png" class="lightbox">Figure 1: Historical crude oil front month futures prices</a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig7.png" class="lightbox">Figure 7: Probability of the January 2016 WTI contract expiring above price levels</a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig8.png" class="lightbox">Figure 8: Historical RBOB futures prices and crack spreads</a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig12.png" class="lightbox">Figure 12: Probability of January 2016 retail gasoline exceeding different prices levels at expiration</a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig14.png" class="lightbox">Figure 14: U.S. natural gas prices and storage</a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig16.png" class="lightbox">Figure 16: Probability of the January 2016 Henry Hub contract expiring above price levels</a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/images/Fig1.png" class="lightbox">West Texas Intermediate (WTI) Crude Oil Price Confidence Intervals</a></li>
            <li><span class="formats">Available formats:</span> <a href="/forecasts/steo/xls/Fig1.xls" alt="West Texas Intermediate (WTI) Crude Oil Price Confidence Intervals"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/images/Probability_WTI.png" class="lightbox">West Texas Intermediate (WTI) Crude Oil Price Probabilities</a></li>
            <li><span class="formats">Available formats:</span> <a href="/forecasts/steo/xls/Probability_WTI.xls" alt="West Texas Intermediate (WTI) Crude Oil Price Probabilities"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/images/Fig4.png" class="lightbox">Henry Hub natural gas prices and confidence intervals</a></li>
            <li><span class="formats">Available formats:</span> <a href="/forecasts/steo/xls/Fig4.xls" alt="Henry Hub natural gas prices and confidence intervals"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li><a href="/forecasts/steo/images/Probability_HH.png" class="lightbox">Henry Hub natural gas price probabilities</a></li>
            <li><span class="formats">Available formats:</span> <a href="/forecasts/steo/xls/Probability_HH.xls" alt="Henry Hub natural gas price probabilities"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>
</div>

<h1><a name="archive" id="archive"></a>Archive</h1>
<h4><a name="frs"></a>Financial Reporting System (FRS) <span class="alert">(suspended)</span></h4>
<p>Find operating data and analysis for major U.S. energy companies.</p>
<span class="expand-collapse-container"> <i class="ico expand"><span>Expand all</span></i> <i class="ico collapse"><span>Collapse all</span></i> </span>
<div class="accordion">
    <h3><a name="finance"></a>Finance</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">Selected financial items</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-1.xlsx" alt="Selected financial items"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Consolidated income statement</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-2.xlsx" alt="Consolidated income statement"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Consolidated balance sheet</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-3.xlsx" alt="Consolidated balance sheet"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Statement of cash flows</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-4.xlsx" alt="Statement of cash flows"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Statement of income for U.S. &amp; foreign petroleum</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-5.xlsx" alt=" Statement of income for U.S. & foreign petroleum"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Statement of income for U.S. & foreign downstream natural gas</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-6.xlsx" alt=" Statement of income for U.S. & foreign downstream natural gas"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Statement of income for U.S. & foreign electric power</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-7.xlsx" alt=" Statement of income for U.S. & foreign electric power"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">PP&E and investments and advances, by lines of business</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-8.xlsx" alt=" PP&E and investments and advances, by lines of business"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Return on investment for lines of business</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-9.xlsx" alt=" Return on investment for lines of business"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Size distribution of net investment in place</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-10.xlsx" alt=" Size distribution of net investment in place"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Research and development</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-11.xlsx" alt="Research and development"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Income taxes</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-12.xlsx" alt="Income taxes "><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. taxes other than income taxes</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-13.xlsx" alt="U.S. taxes other than income taxes"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>
    <h3><a name="oil"></a>Oil and natural gas costs/expenditures</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">U.S. energy operating statistics</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-14.xlsx" alt="U.S. energy operating statistics"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Exploration and development expenditures</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-15.xlsx" alt="Exploration and development expenditures"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Exploration and development expenditures, U.S. &amp; foreign</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-16.xlsx" alt="Exploration and development expenditures, U.S. & foreign"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Exploration and development expenditures by region</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-17.xlsx" alt="Exploration and development expenditures by region"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Production (lifting) costs by region</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-18.xlsx" alt=" Production (lifting) costs by region"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Oil and natural gas reserves</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-19.xlsx" alt=" Oil and natural gas reserves"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Oil and natural gas reserve balances</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-20.xlsx" alt=" Oil and natural gas reserve balances"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Exploration and development expenditures, reserves, and production by region</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-21.xlsx" alt=" Exploration and development expenditures, reserves, and production by region"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Oil and natural gas acreage</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-22.xlsx" alt=" Oil and natural gas acreage"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. wells completed, and in-progress at year end</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-23.xlsx" alt=" U.S. wells completed, and in-progress at year end"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. drilling footage and producing wells</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-24.xlsx" alt="U.S. drilling footage and producing wells"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. wells completed, and average depth</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-25.xlsx" alt="U.S. wells completed, and average depth"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Foreign wells completed, in-progress, and producing, by region</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-26.xlsx" alt="Foreign wells completed, in-progress, and producing, by region"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>




    <h3><a name="refining"></a>Refining and marketing</h3>

    <div class="accordion-content">
        <ul>
            <li class="head">U.S. refining/marketing statement of income</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-27.xlsx" alt="U.S. refining/marketing statement of income"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. petroleum refining/marketing general operating expenses</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-28.xlsx" alt="U.S. petroleum refining/marketing general operating expenses"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. and foreign petroleum refining statistics</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-29.xlsx" alt="U.S. and foreign petroleum refining statistics"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Refinery output and capacity, U.S. & foreign</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-30.xlsx" alt="Refinery output and capacity, U.S. & foreign"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Sources and dispositions of raw materials, U.S. & foreign</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-31.xlsx" alt=" Sources and dispositions of raw materials, U.S. & foreign"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. purchases and sales of raw materials, and refined products</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-32.xlsx" alt=" U.S. purchases and sales of raw materials, and refined products"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">U.S. sales of refined products, by sales type</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-33.xlsx" alt=" U.S. sales of refined products, by sales type"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Sales of U.S. refined products, by volume and price</li>
            <li><span class="release-date">Annual Release Date:</span> <span class="date">April 2011</span></li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/T-34.xlsx" alt=" Sales of U.S. refined products, by volume and price"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>





    <h3><a name="operations"></a>Consolidated company operations</h3>

    <div class="accordion-content">
        <ul class="highlight">
            <li><strong>Time-series data:</strong> These files contain disclosure-free aggregate data from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
        </ul>
        <ul>
            <li class="head">Consolidating statement if Income</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5110.xls" alt="Consolidating statement if Income"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Research &amp; development funding &amp; expenditures</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5111.xls" alt="Research & development funding & expenditures"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Analysis of income taxes</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5112.xls" alt="Analysis of income taxes"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Selected consolidated data (balance sheet)</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5120.xls" alt="Selected consolidated data (balance sheet)"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Statement of sources &amp; uses of funds</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5130.xls" alt=" Statement of sources & uses of funds"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Consolidated statement of cash flows</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5131.xls" alt=" Consolidated statement of cash flows"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Download all consolidated company operations data</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s51.xls" alt=" Download all consolidated company operations data"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>





    <h3><a name="petroleumops"></a>Petroleum operations</h3>

    <div class="accordion-content">
        <ul class="highlight">
            <li><strong>Time-series data:</strong> These files contain disclosure-free aggregate data from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
        </ul>
        <ul>
            <li class="head">Statement of income</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5210.xls" alt="Statement of income"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Refining, exploration &amp; production operations, expenditures &amp; operating expense detail</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5211.xls" alt="Refining, exploration & production operations, expenditures & operating expense detail"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Purchases &amp; sales of raw materials &amp; refined products</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5212.xls" alt="Purchases & sales of raw materials & refined products"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Exploration, development, &amp; production statistics</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5241.xls" alt="Exploration, development, & production statistics"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Refining statistics</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5242.xls" alt=" Refining statistics"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Sources &amp; dispositions of crude &amp; NGL's</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5245.xls" alt=" Sources & dispositions of crude & NGL's"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Proved petroleum reserves</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5246.xls" alt=" Proved petroleum reserves"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Download all company petroleum operations data</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s52.xls" alt=" Download all company petroleum operations data"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>





    <h3><a name="coalops"></a>Coal operations</h3>

    <div class="accordion-content">
        <ul class="highlight">
            <li><strong>Time-series data:</strong> These files contain disclosure-free aggregate data from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>        </ul>
        <ul>
            <li class="head">Coal - reserves &amp; production statistics</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5341.xls" alt=" Coal - reserves & production statistics"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>





    <h3><a name="natgasops"></a>Downstream natural gas operations</h3>

    <div class="accordion-content">
        <ul class="highlight">
            <li><strong>Time-series data:</strong> These files contain disclosure-free aggregate data from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
        </ul>
        <ul>
            <li class="head">Statement of income</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5710.xls" alt="Downstream natural gas operations Statement of income"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">General operating expense detail</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5711.xls" alt="Downstream natural gas operations General operating expense detail"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Purchases &amp; sales of natural gas and NGL's</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5712.xls" alt="Downstream natural gas operations Purchases & sales of natural gas and NGL's"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Download all company downstream natural gas operations data</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s57.xls" alt="Downstream natural gas operations Download all company downstream natural gas operations data"><i class="ico xls"><span>XLS</span></i></a></li>
        </ul>
    </div>




        <h3><a nam="electricops"></a>Electric power operations</h3>
        <div class="accordion-content">
            <ul class="highlight">
                <li><strong>Time-series data:</strong> These files contain disclosure-free aggregate data from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
            </ul>
            <ul>
                <li class="head">Statement of Income</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/archive/frsdata/s5810.xls" alt="Electric power operations Statement of income"><i class="ico xls"><span>XLS</span></i></a></li>
            </ul>
        </div>
    </div>









<h4>Financial News for Major Energy Producers <span class="alert">(suspended)</span></h4>
<p>The "Financial News for Major Energy Companies" is issued quarterly to report recent trends in the financial performance of the major energy companies. These include the respondents to Form EIA-28 (Financial Reporting System (FRS)), with the exception
    of the FRS companies that do not issue quarterly earnings releases or do not provide separate information for the company's U.S. operations.</p>


<span class="expand-collapse-container"> <i class="ico expand"><span>Expand all</span></i> <i class="ico collapse"><span>Collapse all</span></i> </span>

<div class="accordion">
    <h3><a name="2010"></a>2010</h3>

    <div class="accordion-content">
        <ul>
            <li class="head">Third quarter 2010</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q310.pdf" alt="Financial News for Major Energy Producers Third quarter 2010"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Second quarter 2010</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q210.pdf" alt="Financial News for Major Energy Producers Second quarter 2010"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">First quarter 2010</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q110.pdf" alt="Financial News for Major Energy Producers First quarter 2010"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>




    <h3><a name="2009"></a>2009</h3>

    <div class="accordion-content">
        <ul>
            <li class="head">Fourth quarter 2009</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q409.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2009"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Third quarter 2009</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q309.pdf" alt="Financial News for Major Energy Producers Third quarter 2009"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Second quarter 2009</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q209.pdf" alt="Financial News for Major Energy Producers Second quarter 2009"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">First quarter 2009</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q109.pdf" alt="Financial News for Major Energy Producers First quarter 2009"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>




    <h3><a name="2008"></a>2008</h3>

    <div class="accordion-content">
        <ul>
            <li class="head">Fourth quarter 2008</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q408.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2008"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Third quarter 2008</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q308.pdf" alt="Financial News for Major Energy Producers Third quarter 2008"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Second quarter 2008</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q208.pdf" alt="Financial News for Major Energy Producers Second quarter 2008"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">First quarter 2008</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q108.pdf" alt="Financial News for Major Energy Producers First quarter 2008"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>




    <h3><a name="2007"></a>2007</h3>

    <div class="accordion-content">
        <ul>
            <li class="head">Fourth quarter 2007</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q407.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2007"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Third quarter 2007</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q307.pdf" alt="Financial News for Major Energy Producers Third quarter 2007"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Second quarter 2007</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q207.pdf" alt="Financial News for Major Energy Producers Second quarter 2007"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">First quarter 2007</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q107.pdf" alt="Financial News for Major Energy Producers First quarter 2007"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>




    <h3><a name="2006"></a>2006</h3>

    <div class="accordion-content">
        <ul>
            <li class="head">Fourth quarter 2006</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q406.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2006"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Third quarter 2006</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q306.pdf" alt="Financial News for Major Energy Producers Third quarter 2006"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Second quarter 2006</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q206.pdf" alt="Financial News for Major Energy Producers Second quarter 2006"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">First quarter 2006</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q106.pdf" alt="Financial News for Major Energy Producers First quarter 2006"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>




    <h3><a name="2005"></a>2005</h3>

    <div class="accordion-content">
        <ul>
            <li class="head">Fourth quarter 2005</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q405.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2005"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Third quarter 2005</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q305.pdf" alt="Financial News for Major Energy Producers Third quarter 2005"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Second quarter 2005</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q205.pdf" alt="Financial News for Major Energy Producers Second quarter 2005"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">First quarter 2005</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q105.pdf" alt="Financial News for Major Energy Producers First quarter 2005"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>




    <h3><a name="2004"></a>2004</h3>
    <div class="accordion-content">
        <ul>
            <li class="head">Fourth quarter 2004</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q404.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2004"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Third quarter 2004</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q304.pdf" alt="Financial News for Major Energy Producers Third quarter 2004"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">Second quarter 2004</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q204.pdf" alt="Financial News for Major Energy Producers Second quarter 2004"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
        <ul>
            <li class="head">First quarter 2004</li>
            <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q104.pdf" alt="Financial News for Major Energy Producers First quarter 2004"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>




        <h3><a name="2003"></a>2003</h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Fourth quarter 2003</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q403.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2003"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
            <ul>
                <li class="head">Third quarter 2003</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q303.pdf" alt="Financial News for Major Energy Producers Third quarter 2003"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
            <ul>
                <li class="head">Second quarter 2003</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q203.pdf" alt="Financial News for Major Energy Producers Second quarter 2003"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
            <ul>
                <li class="head">First quarter 2003</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q103.pdf" alt="Financial News for Major Energy Producers First quarter 2003"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
        </div>




        <h3><a name="2002"></a>2002</h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Fourth quarter 2002</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q402.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2002"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
            <ul>
                <li class="head">Third quarter 2002</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q302.pdf" alt="Financial News for Major Energy Producers Third quarter 2002"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
            <ul>
                <li class="head">Second quarter 2002</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q202.pdf" alt="Financial News for Major Energy Producers Second quarter 2002"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
            <ul>
                <li class="head">First quarter 2002</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q102.pdf" alt="Financial News for Major Energy Producers First quarter 2002"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
        </div>




        <h3><a name="2001"></a>2001</h3>
        <div class="accordion-content">
            <ul>
                <li class="head">Fourth quarter 2001</li>
                <li><span class="formats">Available formats:</span> <a href="/finance/performanceprofiles/news_m/q401.pdf" alt="Financial News for Major Energy Producers Fourth quarter 2001"><i class="ico pdf"><span>PDF</span></i></a></li>
            </ul>
            <ul>
                <li class="head">Third quarter 2001</li>
                <li><span class="formats">Available formats:</span> missing</li>
            </ul>
            <ul>
                <li class="head">Second quarter 2001</li>
                <li><span class="formats">Available formats:</span> missing</li>
            </ul>
        </div>
    </div>
</div>
