<span class="grey_side blue_top">
  <h4>Most Requested Data</h4>
  <span class="side_list2">
  <ul>
  	<li>    <a href="/cfapps/frs/frstables.cfm?tableNumber=1">Selected Financial Items</a></li>
  	<li class="additional-formats">Available formats: <a href="/cfapps/frs/excel.cfm?tableNumber=1&amp;startYear=1977" class="ico_xls" title="Selected Financial Items">XLS</a></span><br />
    </li>
  	<li>  	<a href="/cfapps/frs/frstables.cfm?tableNumber=2">Consolidated Income Statement</a></li>
  	<li class="additional-formats">Available formats: <a href="/cfapps/frs/excel.cfm?tableNumber=2" class="ico_xls" title="Consolidated Income Statement">XLS</a></span><br />
    </li>
  	<li>	<a href="/cfapps/frs/frstables.cfm?tableNumber=3">Consolidated Balance Sheet</a></li>
  	<li class="additional-formats">Available formats: <a href="/cfapps/frs/excel.cfm?tableNumber=3&startYear=1977" class="ico_xls"  title="Consolidated Balance Sheet">XLS</a></span></li>
  	<li><a href="/cfapps/frs/frstables.cfm?tableNumber=4">Statement of Cash Flows</a></li>
  	<li class="additional-formats">Available formats: <a href="/cfapps/frs/excel.cfm?tableNumber=4&startYear=1977" class="ico_xls" title="Statement of Cash Flows">XLS</a></span></li>
  	<li><a href="/cfapps/frs/frstables.cfm?tableNumber=5">Statement of Income for U.S. &amp; Foreign Petroleum</a></li>
  	<li class="additional-formats">Available formats: <a href="/cfapps/frs/excel.cfm?tableNumber=5" class="ico_xls" title="Statement of Income for U.S. and Foreign Petroleum">XLS</a></span><br />
    </li>
    <li>    <a href="/cfapps/frs/frstables.cfm?tableNumber=6">Statement of Income for U.S. &amp; Foreign Downstream Natural Gas</a></li>
    <li class="additional-formats">Available formats: <a href="/cfapps/frs/excel.cfm?tableNumber=6" class="ico_xls" title="Statement of Income for U.S. and Foreign Downstream Natural Gas">XLS</a></span><br />
    </li>
  </ul>
  </span>
  <div class="clear">&nbsp;</div>
<span class="side_list_nocolumn"><strong><p class="no-border">FRS Survey Data 1977 - 2009</p></strong>
  <ul>
  	<li>  		<a href="archive/frsdata/frsdata.html">The Financial Reporting System Public Data</a>
    </li>
    <li>    	<a href="/finance/performanceprofiles/CoList.cfm">Historical Respondent Company List</a>
    </li>
  </ul>
  </span>
  </span>
  <span class="grey_side green_top">
<h4>Related Reports</h4>
<p><a href="/workingpapers/#finance">Working Papers</a></p>
<p class="no-border"><a href="/finance/workshops.cfm">Workshops</a></p>
</span>
      
