<a name="mpurc" id="mpurc"></a><h1>Market Prices and Uncertainty Report Charts</h1>
<div class="accordion">
<a name="selected-charts</h2>"></a>Selected Charts</h2>
	<div class="accordion-content zebra show">
		<ul>
			<li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig1.png" class="lightbox">Figure 1: Historical crude oil front month futures prices</a></li>

			<li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig7.png" class="lightbox">Figure 7: Probability of the January 2016 WTI contract expiring above  price levels</a></li>

			<li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig8.png" class="lightbox">Figure 8: Historical RBOB futures prices and crack spreads</a></li>

			<li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig12.png" class="lightbox">Figure 12: Probability of January 2016  retail gasoline exceeding different prices levels at expiration</a></li>

			<li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig14.png" class="lightbox">Figure 14:  U.S. natural gas prices and storage</a></li>

			<li><a href="/forecasts/steo/uncertainty/images/uncertainty_fig16.png" class="lightbox">Figure 16: Probability of the January 2016 Henry Hub contract expiring above price levels</a></li>

			<li><a href="/forecasts/steo/images/Fig1.png" class="lightbox">West Texas Intermediate (WTI) Crude Oil Price Confidence Intervals</a></li>
			<li class="additional-formats no-bullet">Available formats: <a href="/forecasts/steo/xls/Fig1.xls" class="ico_xls"><span hidden="West Texas Intermediate (WTI) Crude Oil Price Confidence Intervals"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li><a href="/forecasts/steo/images/Probability_WTI.png" class="lightbox">West Texas Intermediate (WTI) Crude Oil Price Probabilities</a></li>
			<li class="additional-formats no-bullet">Available formats: <a href="/forecasts/steo/xls/Probability_WTI.xls" class="ico_xls"><span hidden="West Texas Intermediate (WTI) Crude Oil Price Probabilities"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li><a href="/forecasts/steo/images/Fig4.png" class="lightbox">Henry Hub natural gas prices and confidence intervals</a></li>
			<li class="additional-formats no-bullet">Available formats: <a href="/forecasts/steo/xls/Fig4.xls" class="ico_xls"><span hidden="Henry Hub natural gas prices and confidence intervals"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li><a href="/forecasts/steo/images/Probability_HH.png" class="lightbox">Henry Hub natural gas price probabilities</a></li>
			<li class="additional-formats no-bullet">Available formats: <a href="/forecasts/steo/xls/Probability_HH.xls" class="ico_xls"><span hidden="Henry Hub natural gas price probabilities"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
</div>
	
	
	
<h1><a name="archive" id="archive"></a>Archive</h1>

<h2><a name="frs"></a>Financial Reporting System (FRS) <span style="color:red; font-style:bold;" class="right">(suspended)</span></h2>
<p>Find operating data and analysis for major U.S. energy companies.</p>
<div class="accordion">
	<div class="expand-collapse-container">
		<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
		<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
	</div>
	<!-- BEGIN Summary Content  -->
	<h2><i class="ico expand-collapse"></i><a name="finance"></a>Finance</h2>
	<div class="accordion-content">
		<ul>
			<li>Selected financial items</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-1.xlsx" class="ico_xls"><span hidden="Selected financial items"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Consolidated income statement</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-2.xlsx" class="ico_xls"><span hidden="Consolidated income statement"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Consolidated balance sheet</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-3.xlsx" class="ico_xls"><span hidden="Consolidated balance sheet"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Statement of cash flows</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-4.xlsx" class="ico_xls"><span hidden="Statement of cash flows"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Statement of income for U.S. &amp; foreign petroleum</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-5.xlsx" class="ico_xls"><span hidden=" Statement of income for U.S. & foreign petroleum"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Statement of income for U.S. & foreign downstream natural gas</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-6.xlsx" class="ico_xls"><span hidden=" Statement of income for U.S. & foreign downstream natural gas"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Statement of income for U.S. & foreign electric power</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-7.xlsx" class="ico_xls"><span hidden=" Statement of income for U.S. & foreign electric power"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>PP&E and investments and advances, by lines of business</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-8.xlsx" class="ico_xls"><span hidden=" PP&E and investments and advances, by lines of business"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Return on investment for lines of business</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-9.xlsx" class="ico_xls"><span hidden=" Return on investment for lines of business"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Size distribution of net investment in place</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-10.xlsx" class="ico_xls"><span hidden=" Size distribution of net investment in place"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Research and development</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-11.xlsx" class="ico_xls"><span hidden="Research and development"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Income taxes</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-12.xlsx" class="ico_xls"><span hidden="Income taxes "></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>U.S. taxes other than income taxes </li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/T-13.xlsx" class="ico_xls"><span hidden="U.S. taxes other than income taxes"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Summary Content  --> 
	<!-- BEGIN Oil and Natural Gas Costs/Expenditures Content  -->
	<h2><i class="ico expand-collapse"></i><a name="oil"></a>Oil and natural gas costs/expenditures</h2>
	<div class="accordion-content">
		<ul>
			<li>U.S. energy operating statistics</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-14.xlsx" class="ico_xls"><span hidden="U.S. energy operating statistics"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Exploration and development expenditures</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-15.xlsx" class="ico_xls"><span hidden="Exploration and development expenditures"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Exploration and development expenditures, U.S. &amp; foreign</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-16.xlsx" class="ico_xls"><span hidden="Exploration and development expenditures, U.S. & foreign"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Exploration and development expenditures by region</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-17.xlsx" class="ico_xls"><span hidden="Exploration and development expenditures by region"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Production (lifting) costs by region</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-18.xlsx" class="ico_xls"><span hidden=" Production (lifting) costs by region"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Oil and natural gas reserves</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-19.xlsx" class="ico_xls"><span hidden=" Oil and natural gas reserves"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Oil and natural gas reserve balances</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-20.xlsx" class="ico_xls"><span hidden=" Oil and natural gas reserve balances"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Exploration and development expenditures, reserves, and production by region</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-21.xlsx" class="ico_xls"><span hidden=" Exploration and development expenditures, reserves, and production by region"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Oil and natural gas acreage</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-22.xlsx" class="ico_xls"><span hidden=" Oil and natural gas acreage"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>U.S. wells completed, and in-progress at year end</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-23.xlsx" class="ico_xls">X<span hidden=" U.S. wells completed, and in-progress at year end"></span>XLS</a></span></li>

			<li>U.S. drilling footage and producing wells</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-24.xlsx" class="ico_xls"><span hidden="U.S. drilling footage and producing wells"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>U.S. wells completed, and average depth</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-25.xlsx" class="ico_xls"><span hidden="U.S. wells completed, and average depth"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Foreign wells completed, in-progress, and producing, by region</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/T-26.xlsx" class="ico_xls"><span hidden="Foreign wells completed, in-progress, and producing, by region"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Oil and Natural Gas Costs/Expenditures Content  --> 
	<!-- BEGIN Refining and Marketing Content  -->
	<h2><i class="ico expand-collapse"></i><a name="refining"></a>Refining and marketing</h2>
	<div class="accordion-content">
		<ul>
			<li>U.S. refining/marketing statement of income</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-27.xlsx" class="ico_xls"><span hidden="U.S. refining/marketing statement of income"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>U.S. petroleum refining/marketing general operating expenses</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-28.xlsx" class="ico_xls"><span hidden="U.S. petroleum refining/marketing general operating expenses"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>U.S. and foreign petroleum refining statistics</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-29.xlsx" class="ico_xls"><span hidden="U.S. and foreign petroleum refining statistics"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Refinery output and capacity, U.S. & foreign</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-30.xlsx" class="ico_xls"><span hidden="Refinery output and capacity, U.S. & foreign"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Sources and dispositions of raw materials, U.S. & foreign</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-31.xlsx" class="ico_xls"><span hidden=" Sources and dispositions of raw materials, U.S. & foreign"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>U.S. purchases and sales of raw materials, and refined products</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-32.xlsx" class="ico_xls"><span hidden=" U.S. purchases and sales of raw materials, and refined products"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>U.S. sales of refined products, by sales type</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/T-33.xlsx" class="ico_xls"><span hidden=" U.S. sales of refined products, by sales type"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Sales of U.S. refined products, by volume and price</li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 2011</span></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/T-34.xlsx" class="ico_xls"><span hidden=" Sales of U.S. refined products, by volume and price"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Refining and Marketing Content  --> 
	<!-- BEGIN Consolidated Company Operations Content  -->
	<h2><i class="ico expand-collapse"></i><a name="operations"></a>Consolidated company operations</h2>
	<div class="accordion-content">
		<ul>
			<li class="highlight"><strong>Time-series data:</strong> These files contain disclosure-free aggregate data  from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
			<li>Consolidating statement if Income</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5110.xls" class="ico_xls"><span hidden="Consolidating statement if Income"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Research &amp; development funding &amp; expenditures</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5111.xls" class="ico_xls"><span hidden="Research & development funding & expenditures"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Analysis of income taxes</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5112.xls" class="ico_xls"><span hidden="Analysis of income taxes"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Selected consolidated data (balance sheet)</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5120.xls" class="ico_xls"><span hidden="Selected consolidated data (balance sheet)"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Statement of sources &amp; uses of funds</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5130.xls" class="ico_xls"><span hidden=" Statement of sources & uses of funds"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Consolidated statement of cash flows</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5131.xls" class="ico_xls"><span hidden=" Consolidated statement of cash flows"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Download all consolidated company operations data</strong></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/s51.xls" class="ico_xls"><span hidden=" Download all consolidated company operations data"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Consolidated Company Operations Content  --> 
	<!-- BEGIN Petroleum Operations Content  -->
	<h2><i class="ico expand-collapse"></i><a name="petroleumops"></a>Petroleum operations</h2>
	<div class="accordion-content">
		<ul>

<!-- start special styling -->
			<li class="highlight"><strong>Time-series data:</strong> These files contain disclosure-free aggregate data  from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
			<li>Statement of income</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5210.xls" class="ico_xls"><span hidden="Statement of income"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Refining, exploration &amp; production operations,  expenditures &amp; operating expense detail</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5211.xls" class="ico_xls"><span hidden="Refining, exploration & production operations, expenditures & operating expense detail"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Purchases &amp; sales of raw materials &amp; refined products</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5212.xls" class="ico_xls"><span hidden="Purchases & sales of raw materials & refined products"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Exploration, development, &amp; production statistics</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5241.xls" class="ico_xls"><span hidden="Exploration, development, & production statistics"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Refining statistics</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5242.xls" class="ico_xls"><span hidden=" Refining statistics"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Sources &amp; dispositions of crude &amp; NGL's</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5245.xls" class="ico_xls"><span hidden=" Sources & dispositions of crude & NGL's"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Proved petroleum reserves</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5246.xls" class="ico_xls"><span hidden=" Proved petroleum reserves"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Download all company petroleum operations data</strong></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/s52.xls" class="ico_xls"><span hidden=" Download all company petroleum operations data"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Petroleum Operations Content  --> 
	<!-- BEGIN Coal Operations Content  -->
	<h2><i class="ico expand-collapse"></i><a name="coalops"></a>Coal operations</h2>
	<div class="accordion-content">
		<ul>
			<li class="highlight"><strong>Time-series data:</strong> These files contain disclosure-free aggregate data  from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
			<li>Coal - reserves &amp; production statistics</strong></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/s5341.xls" class="ico_xls"><span hidden=" Coal - reserves & production statistics"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Coal Operations Content  --> 
	<!-- BEGIN Downstream Natural Gas Operations Content  -->
	<h2><i class="ico expand-collapse"></i><a name="natgasops"></a>Downstream natural gas operations</h2>
	<div class="accordion-content">
		<ul>
			<li class="highlight"><strong>Time-series data:</strong> These files contain disclosure-free aggregate data  from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
			<li>Statement of income</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5710.xls" class="ico_xls"><span hidden="Downstream natural gas operations Statement of income"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>General operating expense detail</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5711.xls" class="ico_xls"><span hidden="Downstream natural gas operations General operating expense detail"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Purchases &amp; sales of natural gas and NGL's</strong></li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/archive/frsdata/s5712.xls" class="ico_xls"><span hidden="Downstream natural gas operations Purchases & sales of natural gas and NGL's"></span><i class="ico xls"><span>XLS</span></i></a></li>

			<li>Download all company downstream natural gas operations data</strong></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/s57.xls" class="ico_xls"><span hidden="Downstream natural gas operations Download all company downstream natural gas operations data"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Downstream Natural Gas Operations Content  --> 
	<!-- BEGIN Electric Power Operations Content  -->
	<h2><i class="ico expand-collapse"></i><a nam="electricops"></a>Electric power operations</h2>
	<div class="accordion-content">
		<ul>
			<li class="highlight"><strong>Time-series data:</strong> These files contain disclosure-free aggregate data  from the Energy Information Administration's Financial Reporting System (FRS) database. The data cover the years 1977 through 2009.</li>
			<li>Statement of Income</strong></li>
			<li class="additional-formats divider">Available formats: <a href="/finance/archive/frsdata/s5810.xls" class="ico_xls"><span hidden="Electric power operations Statement of income"></span><i class="ico xls"><span>XLS</span></i></a></li>
		</ul>
	</div>
	<!-- END Electric Power Operations Content  -->
</div>










<h2>Financial News for Major Energy Producers<span style="color:red; font-style:bold;" class="right">(suspended)</span></h2>
<p>The"Financial News for Major Energy Companies" is issued quarterly to report recent trends in the financial performance of the major energy companies. These include the respondents to Form EIA-28 (Financial Reporting System (FRS)), with the exception of the FRS companies that do not issue quarterly earnings releases or do not provide separate information for the company's U.S. operations.</p>


<div class="accordion">
	<div class="expand-collapse-container">
		<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
		<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2010"></a>2010</h2>
	<div class="accordion-content">
		<ul>
			<li>Third quarter 2010 </li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q310.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2010"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2010</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q210.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2010"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2010</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q110.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2010"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2009"></a>2009</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2009</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q409.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2009"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2009</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q309.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2009"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2009</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q209.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2009"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2009</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q109.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2009"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2008"></a>2008</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2008</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q408.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2008"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2008</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q308.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2008"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2008</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q208.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2008"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2008</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q108.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2008"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2007"></a>2007</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2007</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q407.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2007"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2007</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q307.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2007"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2007</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q207.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2007"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2007</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q107.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2007"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2006"></a>2006</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2006</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q406.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2006"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2006</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q306.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2006"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2006</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q206.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2006"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2006</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q106.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2006"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2005"></a>2005</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2005</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q405.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2005"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2005</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q305.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2005"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2005</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q205.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2005"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2005</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q105.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2005"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2004"></a>2004</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2004</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q404.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2004"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2004</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q304.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2004"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2004</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q204.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2004"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2004</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q104.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2004"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2003"></a>2003</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2003</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q403.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2003"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2003</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q303.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2003"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2003</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q203.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2003"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2003</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q103.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2003"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2002"></a>2002</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2002</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q402.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2002"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2002</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q302.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Third quarter 2002"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Second quarter 2002</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q202.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Second quarter 2002"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>First quarter 2002</li>
			<li class="additional-formats divider">Available formats: <a href="/finance/performanceprofiles/news_m/q102.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers First quarter 2002"></span><i class="ico pdf"><span>PDF</span></i></a></li>
		</ul>
	</div>

	<h2><i class="ico expand-collapse"></i><a name="2001"></a>2001</h2>
	<div class="accordion-content">
		<ul>
			<li>Fourth quarter 2001</li>
			<li class="additional-formats item-divider">Available formats: <a href="/finance/performanceprofiles/news_m/q401.pdf" class="ico_pdf"><span hidden="Financial News for Major Energy Producers Fourth quarter 2001"></span><i class="ico pdf"><span>PDF</span></i></a></li>

			<li>Third quarter 2001</li>
			<li class="additional-formats item-divider">missing</li>

			<li>Second quarter 2001</li>
			<li class="additional-formats divider">missing</li>
		</ul>
	</div>
</div>