<div class="pub_title bg_pub_default"><?php /* Page/Section Title */ ?>
      <h3>Energy Financial Markets</h3>
      <h1 style="padding-top:0px;">Crude Oil Price Formation</h1>
    </div><?php /*/ Page/Section Title */ ?>
    
    <div class="subnav"><?php /* Page/Sub Nav */ ?>
    <span class="right"><a href="<?php echo "$glossary_path"?>">Glossary &rsaquo;</a> <a href="<?php echo "$faqs_path"?>">FAQS &rsaquo;</a></span>
       <ul>
        <li <?php if ( $locale == 'overview') {?>class="active"<?php  } // end if ?>><a href="/finance/markets/ui2.cfm">Overview</a></li>
      </ul>
    </div><?php /*/ Page/Sub Nav */ ?>