<div class="call-out">
    <p>The tables and graphs from the Monthly Energy Review are available in an interactive format on <a href="/totalenergy/data/browser/">EIA's Total Energy Data Browser</a>.</p>
    <p>Previous editions of the MER are available from January 1980 forward.</p>
    <p>EIA periodically adds tables to the MER containing data previously published in the Annual Energy Review, which has been discontinued. For a record of the MER expansion, please see &quot; <a href="/totalenergy/data/monthly/whatsnew.php">What's New in the Monthly Energy Review - Content Changes</a>.</p>
</div>