	  <?php /* Page Content Footer */ ?>
         <div class="aeo_footer blue_top">
            <div class="electric_inner">
              <span class="left_box">
                <h4>About the Electric Sales, Revenue, and Average Price Annual</h4>
                <ul class="no-liststyle">
                   <li><a href="/about/contact/electric.php">Contact Information and Staff</a></li>
                  <?php /* <li><a href="#">Press Release</a></li>*/ ?>
                </ul>
              </span>
                  <span class="mid_box">
             <span  class="left rtitle_form">
             <h5>More archives</h5>
 <ul class="no-liststyle"><li>Class of Ownership, Number of Bundled Ultimate Consumers, Revenue, Sales, and Average Retail Price</li></ul>
					
                   
                   <form name="form" id="form">
                   <label>2003 XLS:&nbsp;</label>
          <select name="jumpMenu" id="jumpMenu" style="width:90px">
        <option value="electricity/esr/archive/2003/esr_2003_tables.xls">2003 Tables</option>
          <?php /*  <option value="/cneaf/electricity/archive/esr/2003/table15.xls">Table 15</option>
          <option value="/cneaf/electricity/archive/esr/2003/table16.xls">Table 16.</option>
          <option value="/cneaf/electricity/archive/esr/2003/table17.xls">Table 17.</option>
          <option value="/cneaf/electricity/archive/esr/2003/table18.xls">Table 18.</option>*/ ?>
                         </select>
                     <input type="button" name="go_button" class="arrow_go" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                   </form>
                   &nbsp;<br/>

 <ul class="no-liststyle"><li>Class of Ownership, Number of Bundled Ultimate Consumers, Revenue, Sales, and Average Revenue per Kilowatthour</li></ul>					
          
                   <form name="form" id="form">
                   <label>2002 XLS: </label>
                     <select name="jumpMenu" id="jumpMenu" style="width:90px">
          <option value="electricity/esr/archive/2002/esr_2002_tables.xls">2002 Tables</option>
          <?php /*<option value="/cneaf/electricity/archive/esr/2002/table15.xls">Table 15.</option>
          <option value="/cneaf/electricity/archive/esr/2002/table16.xls">Table 16.</option>
          <option value="/cneaf/electricity/archive/esr/2002/table17.xls">Table 17.</option>*/ ?>
           </select>
                     <input type="button" name="go_button" class="arrow_go" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                   </form>
                   
                  
                    <form name="form" id="form">
                   <label>2001 XLS:&nbsp;</label>
                     <select name="jumpMenu" id="jumpMenu" style="width:90px">
          <option value="electricity/esr/archive/2001/esr_2001_tables.xls">2001 Tables</option>
          <?php /*<option value="/cneaf/electricity/archive/esr/2001/table15.xls">Table 15.</option>
          <option value="/cneaf/electricity/archive/esr/2001/table16.xls">Table 16.</option>
          <option value="/cneaf/electricity/archive/esr/2001/table17.xls">Table 17.</option>*/ ?>
                               </select>
                     <input type="button" name="go_button" class="arrow_go" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                   </form>
              </span>
              </span>
              <span class="right_box">
                <?php /*<h4>Documnetation and Assumptions</h4>
                <ul class="split_2columns no-liststyle">
                   <li><a href="#">Notes and Sources</a></li>
                   <li><a href="#">Assumption Report (2010)</a></li>
                   <li><a href="#">About the National<br />
                     Energy Modeling<br />
                     System (NEMS)</a></li>
                </ul>*/ ?>
              </span>
            </div>
         </div>
      <?php /* Page Content Footer */ ?>