      <div class="side_col right">
        <?php /* Side Column */ ?>
        <div class="secondary">
        <p><a href="/consumption/residential/about.php">About the RECS</a></p>
        <p><a href="/consumption/residential/methodology/index.php">Methodology</a></p>
        <p class="no_btm_border"><a href="/consumption/residential/surveyforms.php">Survey Forms</a></p>
        </span>

        <?php /* FAQ Promo 
        <span class="blue_side">
          <h4 class="q_side">
          	<a href="recs_faqs.php">Were you contacted about participating in RECS Energy Supplier Survey?</a>
      </h2></li>
          <strong>
          <p><a href="/tools/faqs/">See all RECS FAQs &rsaquo;</a></p></strong>
        </span>*/ ?>
         
        <?php /* Featured Data */ ?>
        <div class="secondary">
          <p class="no_btm_border">
          <li class="head"><h2>Featured Data Tables</h2></li>
          <p><a href="data/2009/#fueluses">Fuels Used & End Uses</a></p>
                    <p class="no_btm_border"><a href="data/2009/#appliances">Appliances</a></p>

        </span> 
        <?php /* Other Consumption Surveys */ ?>
        <div class="secondary">
<ul>
<li class="head"><h2>Other End Use Surveys</h2></li>
            <p><a href="/emeu/cbecs/contents.html">Commercial Buildings - CBECS</a></p>
            <p><a href="/emeu/mecs/contents.html">Manufacturing - MECS</a>
      <p class="no-border"><a href="/consumption/archive/rtecs/contents.html">Transportation</a></p>
      </span>
        </div>
      <?php /*/ Side Content */ ?>

