          
          
<span class="grey_side green_top">
<h4><a href="../residential/data/index.php">Residential Energy Consumption Survey (RECS)</a></h4>
              
 
2005 data  (most recent):  
<ul>
  <li><a href="../residential/data/2005/index.php">Household characteristics </a></li>
<li> <a href="../residential/data/2005/index.php">Home energy use & costs</a></li>
<li> <a href="../residential/reports/index.php">Related analysis & reports</a></li>
</ul>
</ul>

  <a href="../residential/data/2005/microdata.php">Public use microdata</a>
  <p class="no_btm_border">Comma delimited data files available for public use with various software applications.          </p>
<h5><a href="../whats_new.php">2009 data coming soon!</a></h5>
<a href="http://www.eia.gov/listserv_signup.html#residential">Get e-mail updates on Residential energy use &rsaquo;</a></p>
          </span>
          <?php /* FAQ Promo */ ?>
        <span class="blue_side">
        <h4 class="q_side"><a href="consumption_faqs.php#rfaq1">What is the basis for EIA&#8217;s statistics on household energy consumption and expenditures?</a></h4>
          <p><a href="consumption_faqs.php">See all Energy End Use FAQs &rsaquo;</a></p>
</span>