<?php include ('side_nav_residential.inc') ; ?>
<?php /*
 <span class="grey_side green_top">
  <p><a href="/consumption/residential/about.php">About the RECS</a></p>
  <p><a href="/consumption/residential/maps.php">RECS Maps</a></p>
  <p><a href="/consumption/residential/terminology.php">RECS Terminology</a></p>
  <p class="no-border"><a href="/consumption/residential/data/archive.php">Archived Reports</a></p>
  </span>
  <?php if ( $page['year'] == "2009") {?>
    <div class="secondary">
<ul>
<li class="head"><h2><?php echo "$page['year']"?> Survey Forms</h2></li>
<li>
<ul>
      <li><a href="/survey/form/eia_457/form.pdf" class="ico_pdf" title="2009 RECS 457-A Household Survey">457-A Household Survey</a></li>
      <li><a href="/survey/form/eia_457/2009 RECS 457-C Rental Agent Questionnaire.pdf" class="ico_pdf" title="2009 RECS 457-C Rental Agent Questionnaire">457-C Rental Agent Questionnaire</a></li>
      <li><a href="/survey/form/eia_457/2009 RECS 457-D LPGPropane Usage Form.pdf" class="ico_pdf" title="2009 RECS 457-D LPGPropane Usage Form">457-D LPGPropane Usage Form</a></li>
      <li><a href="/survey/form/eia_457/2009 RECS 457-E Electricity Usage Form.pdf" class="ico_pdf" title="2009 RECS 457-E Electricity Usage Form">457-E Electricity Usage Form</a></li>
      <li><a href="/survey/form/eia_457/2009 RECS 457-F Natural Gas Usage Form.pdf" class="ico_pdf" title="2009 RECS 457-F Natural Gas Usage Form">457-F Natural Gas Usage Form</a></li>
      <li><a href="/survey/form/eia_457/2009 RECS 457-G Fuel Oil-kerosene Usage Form.pdf" class="ico_pdf" title="2009 RECS 457-G Fuel Oil-kerosene Usage Form">457-G Fuel Oil-kerosene Usage Form</a></li>
      <li><a href="/survey/<?php echo "$"?>eia-457"><strong>See all Survey Forms ></strong></a></li>
    </ul>
    </span>
    <div class="secondary">
<ul>
<li class="head"><h2>2009 Features</h2></li>
    <p><a href="/consumption/residential/reports/2009-RECS-methodology-square-footage-data.php">Where does RECS square footage data come from?</a><br />
    <em>July 9, 2012</em>
    <p><a href="/consumption/residential/reports/2009-RECS-show-decreased-home-energy-consumption.php">RECS data show decreased energy consumption per household</a><br />
    <em>June 6, 2012</em>
    <p><a href="/consumption/residential/reports/2009-square-footage.php">The impact of increasing home size on energy demand</a><br />
    <em>April 1, 2012</em>
    <p><a href="/consumption/residential/reports/air_conditioning09.php">Did you know that air conditioning is in nearly 100 million U.S. homes?</a><br />
    <em>August 19, 2011</em>
    </p>
    <p><a href="/consumption/residential/reports/2009overview.php">How are we using energy in homes today?</a><br />
    <em>March 28, 2011</em></p>
    <p><a href="/consumption/residential/reports/16-states.php">EIA expands household energy use data series to include 16 states</a><br />
    <em>March 28, 2011</em></p>
    <p><a href="/consumption/residential/reports/electronics.php">Share of energy used by appliances and consumer electronics increases in U.S. homes</a><br />
    <em>March 28, 2011</em>
    </p>
    <li class="sub-head"><strong><a href="/consumption/residential/reports.php">See more RECS features and reports ></a></strong></li>
  </span>
  
  <?php  } // end if ?>
  <?php if ( $page['year'] == "2005") {?>
    <div class="secondary">
<ul>
<li class="head"><h2><?php echo "$page['year']"?> Survey Forms</h2></li>
<li>
<ul>
      <li><a href="/survey/form/eia_457/2005 RECS 457-A Household Survey.pdf" class="ico_pdf" title="2005 RECS 457-A Household Survey">457-A Household Survey</a></li>
      <li><a href="/survey/form/eia_457/2005 RECS 457-D Bottled Gas.pdf" class="ico_pdf" title="2005 RECS 457-D Bottled Gas Form">457-D Bottled Gas Form</a></li>
      <li><a href="/survey/form/eia_457/2005 RECS 457-E Electricity Usage Form.pdf" class="ico_pdf" title="2005 RECS 457-E Electricity Usage Form">457-E Electricity Usage Form</a></li>
      <li><a href="/survey/form/eia_457/2005 RECS 457-F Natural Gas Usage Form.pdf" class="ico_pdf" title="2005 RECS 457-F Natural Gas Usage Form">457-F Natural Gas Usage Form</a></li>
      <li><a href="/survey/form/eia_457/2005 RECS 457-G Fuel Oil-kerosene Usage Form.pdf" class="ico_pdf" title="2005 RECS 457-G Fuel Oil-kerosene Usage Form">457-G Fuel Oil-kerosene Usage Form</a></li>
      <li><a href="/survey/<?php echo "$"?>eia-457">View All Years</a></li>
    </ul>
    </span>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "2001") {?>
    <div class="secondary">
<ul>
<li class="head"><h2><?php echo "$page['year']"?> Survey Forms</h2></li>
<li>
<ul>
      <li><a href="/survey/form/eia_457/2001 RECS 457-A Household Survey.pdf" class="ico_pdf" title="2001 RECS 457-A Household Survey">457-A Household Survey</a></li>
      <li><a href="/survey/form/eia_457/2001 RECS 457-B Nationwide Household Mail Survey.pdf" class="ico_pdf" title="2001 RECS 457-B Nationwide Household Mail Survey">457-B Nationwide Household Mail Survey</a></li>
      <li><a href="/survey/form/eia_457/2001 RECS 457-C Rental Agent Questionnaire.pdf" class="ico_pdf" title="2001 RECS 457-C Rental Agent Questionnaire">457-C Rental Agent Questionnaire</a></li>
      <li><a href="/survey/form/eia_457/2001 RECS 457-D Bottled Gas.pdf" class="ico_pdf" title="2001 RECS 457-D Bottled Gas">457-D Bottled Gas</a></li>
      <li><a href="/survey/form/eia_457/2001 RECS 457-E Electricity Usage Form.pdf" class="ico_pdf" title="2001 RECS 457-E Electricity Usage Form">457-E Electricity Usage Form</a></li>
      <li><a href="/survey/form/eia_457/2001 RECS 457-F Natural Gas Usage Form.pdf" class="ico_pdf" title="2001 RECS 457-F Natural Gas Usage Form">457-F Natural Gas Usage Form</a></li>
      <li><a href="/survey/form/eia_457/2001 RECS 457-G Fuel Oil-kerosene Usage Form.pdf" class="ico_pdf" title="2001 RECS 457-G Fuel Oil-kerosene Usage Form">457-G</a></li>
      <li><a href="/survey/<?php echo "$"?>eia-457">View All Years</a></li>
    </ul>
    </span>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "1997") {?>
    <div class="secondary">
<ul>
<li class="head"><h2><a href="/pub/pdf/consumption/063297.pdf" class="ico_pdf">Download the full <?php echo "$page['year']"?> RECS report</a></h2></li>
    </span>
    <div class="secondary">
<ul>
<li class="head"><h2><?php echo "$page['year']"?> Survey Forms</h2></li>
<li>
<ul>
      <li><a href="/survey/form/eia_457/1997 RECS 457-A Household Survey.pdf" class="ico_pdf" title="1997 RECS 457-A Household Survey">457-A Household Survey</a></li>
      <li><a href="/survey/form/eia_457/1997 RECS 457-B Nationwide Household Mail Survey.pdf" class="ico_pdf" title="1997 RECS 457-B Nationwide Household Mail Survey">457-B Nationwide Household Mail Survey</a></li>
      <li><a href="/survey/form/eia_457/1997 RECS 457-C Rental Agent Questionnaire.pdf" class="ico_pdf" title="1997 RECS 457-C Rental Agent Questionnaire">457-C Rental Agent Questionnaire</a></li>
      <li><a href="/survey/<?php echo "$"?>eia-457">View All Years</a></li>
    </ul>

    </span>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "1993") {?>
    <div class="secondary">
<ul>
<li class="head"><h2><?php echo "$page['year']"?> Survey Forms</h2></li>
<li>
<ul>
      <li><a href="/survey/form/eia_457/1993 RECS 457-A Household Survey.pdf" class="ico_pdf" title="1993 RECS 457-A Household Survey">457-A Household Survey</a></li>
      <li><a href="/survey/<?php echo "$"?>eia-457">View All Years</a></li>
    </ul>
    </span>
  <?php  } // end if ?>
  <?php if ( $page['year'] == "previous") {?>
    <div class="secondary">
<ul>
<li class="head"><h2><?php echo "$page['year']"?> Survey Forms</h2></li>
<li>
<ul>
      <li>1990 <a href="/survey/form/eia_457/1990 RECS 457-A Household Survey.pdf" class="ico_pdf" title="1990 RECS 457-A Household Survey">457-A Household Survey</a></li>
      <li>1987 <a href="/survey/form/eia_457/1987 RECS 457-B Nationwide Household Mail Survey.pdf" class="ico_pdf" title="1987 RECS 457-B Nationwide Household Mail Survey">457-B Household Survey</a></li>
      <li>1984 <a href="/survey/form/eia_457/1984-85 RECS 457-B Nationwide Household Mail Survey.pdf" class="ico_pdf" title="1984-85 RECS 457-B Nationwide Household Mail Survey">457-B Household Survey</a></li>
      <li>1982 <a href="/survey/form/eia_457/1982-83 RECS 457-B Nationwide Household Mail Survey.pdf" class="ico_pdf" title="1982-83 RECS 457-B Nationwide Household Mail Survey">457-B Household Survey</a></li>
      <li>1981 <a href="/survey/form/eia_457/1981-82 RECS 457-B Nationwide Household Mail Survey.pdf" class="ico_pdf" title="1981-82 RECS 457-B Nationwide Household Mail Survey">457-B Household Survey</a></li>
      <li>1980 <a href="/survey/form/eia_457/1980-81 RECS 457-B Nationwide Household Mail Survey.pdf" class="ico_pdf" title="1980-81 RECS 457-B Nationwide Household Mail Survey">457-B Household Survey</a></li>
      <li><a href="/survey/<?php echo "$"?>eia-457">View All Years</a></li>
    </ul>
    </span>
  <?php  } // end if ?>
  <span class="grey_side green_top">
  <li class="head"><h2>Other End Use Survey Data</h2></li>
  <p><a href="/consumption/commercial/">Commercial Buildings - CBECS</a></p>
  <p><a href="/emeu/mecs/contents.html">Manufacturing - MECS</a></p>
  <p class="no-border"><a href="/consumption/archive/rtecs/contents.html">Transportation</a></p>
  </span> 
	
	*/ ?>