        <?php $what = 'consumption'; ?>
        <?php include ('about/new/whatsnew_sitewide.php') ; ?>
        <div class="secondary">
<ul>
<li class="head"><h2>Energy Use Data by Sector</h2></li>
<p class="no_btm_border"><strong>Residential</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="residential/">Sector Overview</a></li><li><a href="residential/data/2005/">Most Recent Data (2005)</a></li>
          <li><a href="residential/reports/">Analysis  &amp; Reports</a></li></ul>
          </p>
<p class="no_btm_border"><strong>Commercial Buildings</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="commercial/">Sector Overview</a></li>
          <li><a href="commercial/data/2003/">Most Recent Data (2003)</a></li>
          <li><a href="commercial/reports/">Analysis  &amp; Reports</a></li></ul>
          </p>
<p class="no_btm_border"><strong>Manufacturing</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="industrial/">Sector Overview</a></li>
          <li><a href="manufacturing/data/2006/">Most Recent Data (2006)</a></li>
          <li><a href="manufacturing/reports/">Analysis  &amp; Reports</a></li></ul>
          </p>
<p class="no_btm_border" ><strong>Transportation</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="transportation/">Sector Overview</a></li>
          <li><a href="transportation/data/2001/">Most Recent Data (2001)</a></li>
          <li><a href="transportation/reports/">Analysis  &amp; Reports          </a></li>
        </ul></p><span style="margin-bottom:10px">&nbsp;</span>
        <li class="head"><h2>Topics</h2></li>
        <p class="no_btm_border"><strong>Efficiency (Energy Intensity)</strong></li>
<li>
<ul>
          <li><a href="/consumption/efficiency/index.php">Overview</a></li>
          <li><a href="/consumption/efficiency/data/index.php">Data</a></li>
          <li><a href="/consumption/efficiency/reports/index.php">Analysis and Reports</a></li>
        </ul>
          
          </span>
          <?php /* FAQ Promo */ ?>
        <span class="blue_side">
          <h4 class="q_side"><a href="consumption_faqs.php#rfaq1">What is the basis for EIA&#8217;s statistics on household energy consumption and expenditures?</a></h2></li>
          <p><a href="consumption_faqs.php">See all Energy End Use FAQs &rsaquo;</a></p>
        </span>
        