<div class="side_col right"> <span class="grey_side green_top">
  <p><a href="/consumption/manufacturing/about.php">About the MECS</a></p>
  <p><a href="/survey/#eia-846">Survey forms</a></p>
  <p><a href="/consumption/manufacturing/maps.php">Maps</a></p>
  <p><a href="/consumption/manufacturing/terms.php">MECS Terminology</a></p>
  <p class="no-border"><a href="data/archive/">Archives</a></p>
  </span> 
  <?php /* FAQ Promo */ ?> 
  <?php /*span class="blue_side">
  <h4 class="q_side"> <a href="#">Were you contacted about participating in the MECS Energy Supplier Survey?</a> </h2></li>
  <strong>
  <p><a href="#">See all MECS FAQs &rsaquo;</a></p>
  </strong> </span*/ ?> 
  
  <?php /* Featured Data */ ?> 
  <span class="grey_side blue_top side_list_nocolumn">
  <li class="head"><h2>Features</h2></li>
  <p class="no-border"><a href="/pressroom/releases/press383.php">First 2010 Data Press Release</a><br />
  <p class="no-border"><a href="reports/2010/decrease_use.php">2010 Data Brief</a><br />
  </p>
  </span> 
  <?php /* Other Consumption Surveys */ ?> 
  <div class="secondary">
<ul>
<li class="head"><h2>Other End Use Surveys</h2></li>
  <p><a href="/consumption/commercial/">Commercial Buildings - CBECS</a></p>
  <p><a href="/consumption/residential/">Residential - RECS</a> </p>
  <p class="no-border"><a href="/consumption/archive/rtecs/contents.html">Transportation</a></p>
  </span> 
  
<span class="grey_side blue_top side_list_nocolumn">
  <li class="head"><h2>DOE Uses MECS Data</h2></li>
  <p class="no-border"><a href="http://www.energy.gov/eere/amo/manufacturing-energy-and-carbon-footprints-2010-mecs">Manufacturing Energy and Carbon Footprints
</a>
<p class="no-border"><img src="/consumption/manufacturing/reports/2010/images/doe_mecs.jpg" alt="manufacturing and carbon footprints">
<p class="no-border"><a href="http://www.energy.gov/eere/amo/downloads/us-manufacturing-energy-use-and-greenhouse-gas-emissions-analysis">Associated Analysis</a><br /><a href="http://www.energy.gov/eere/amo/sankey-diagram-energy-flow-us-manufacturing">Manufacturing Energy Sankey Diagrams</a><br /><a href="http://www.energy.gov/eere/amo/manufacturing-energy-flows-sankey-tool ">Manufacturing Energy Flows Tool </a>
</span>

  

  <?php /*/ Side Content */ ?>
  </div>
