<?php /* Renewable Sub Nav */ ?>
    <div class="title bg_industrial">
      <?php /* Page/Section Title */ ?>
      <a href="index.php">&lsaquo; Consumption & Efficiency</a>
      <h1>Industrial</h1>
    </div>
    <?php /*/ Page/Section Title */ ?>
    <div id="subnav">
    <?php /* Page/Sub Nav */ ?>
    <span class="right"><a href="#">Glossary &rsaquo;</a><a href="#">FAQS &rsaquo;</a></span>
      <ul>
        <li class="subnav-overview"><a href="index.php">Overview</a></li>
        <li class="subnav-residential"><a href="residential.php">Residential</a></li>
        <li class="subnav-commercial"><a href="commercial.php">Commercial</a></li>
        <li class="subnav-industrial"><a href="industrial.php">Industrial</a></li>
        <li class="subnav-tranportation"><a href="transportation.php">Tranportation</a></li>
      </ul>
    </div><?php /*/ Page/Sub Nav */ ?>