<div class="report_header"> 

<span class="left rtitle" style="width:718px"> 

<a href="/petroleum/reports.php">&lsaquo; See All Petrolem Reports</a>

  <h2>
    <?php echo "$headtitle"?>
  </h2>
  <p><strong>
    <?php echo "$data_series"?>
    </strong>&nbsp;&nbsp;|&nbsp;&nbsp;<strong>Release Date:</strong>&nbsp;
    <?php echo "$release"?>
    &nbsp;&nbsp;|&nbsp;&nbsp;<strong>Next Release Date:</strong>
    <?php echo "$next"?>
    <br />
    
  </p>
  </span> 
  
  <span class="left rtitle_form" style="width:240px; align:right;">

  <h4>Previous Issues</h4>
  <span class="rtitle_form_a">
 
 
<form name="form" id="form">
<label>Year:&nbsp;</label>
<select name="jumpMenu" size="1" id="jumpMenu" style="width:80px">

<option value="/petroleum/fueloilkerosene/archive/2016/foks_2016.php" selected="selected">2016</option>

<option value="/petroleum/fueloilkerosene/archive/2015/foks_2015.php">2015</option>
<option value="/petroleum/fueloilkerosene/archive/2014/foks_2014.php">2014</option>
<option value="/petroleum/fueloilkerosene/archive/2013/foks_2013.php">2013</option>
<option value="/petroleum/fueloilkerosene/archive/2012/foks_2012.php">2012</option>
<option value="/petroleum/fueloilkerosene/archive/2011/foks_2011.php">2011</option>
<option value="/petroleum/fueloilkerosene/archive/2010/foks_2010.php">2010</option>
<option value="/petroleum/fueloilkerosene/archive/2009/foks_2009.html">2009</option>
<option value="/petroleum/fueloilkerosene/archive/2008/foks_2008.html">2008</option>
<option value="/petroleum/fueloilkerosene/archive/2007/foks_2007.html">2007</option>
<option value="/petroleum/fueloilkerosene/archive/2006/foks_2006.html">2006</option>
<option value="/petroleum/fueloilkerosene/archive/2005/foks_2005.html">2005</option>
<option value="/petroleum/fueloilkerosene/archive/2004/foks_2004.html">2004</option>
<option value="/petroleum/fueloilkerosene/archive/2003/foks_2003.html">2003</option>
<option value="/petroleum/fueloilkerosene/archive/2002/foks_2002.html">2002</option>
<option value="/petroleum/fueloilkerosene/archive/2001/foks_2001.html">2001</option>
<option value="/petroleum/fueloilkerosene/archive/2000/foks_2000.html">2000</option>
<option value="/petroleum/fueloilkerosene/archive/1999/foks_1999.html">1999</option>
<option value="/petroleum/fueloilkerosene/archive/1998/foks_1998.html">1998</option>
<option value="/petroleum/fueloilkerosene/archive/1997/foks_1997.html">1997</option>
<option value="/petroleum/fueloilkerosene/archive/1996/foks_1996.html">1996</option>
<option value="/petroleum/fueloilkerosene/archive/1995/foks_1995.html">1995</option>
 
                 </select>
					 
<input type="button" name="go_button" class="arrow_go" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                   </form>

 
 
 
 
 
  </span> </span> 
  

   </div>
