	<?php /* Sections Promo */ ?>

 <span class="grey_side_nav blue_top">
        
<h4>Data Tables</h4>


<p>
<strong>Sales of Fuel Oil and Kerosene</strong><br>

 - <a href="/dnav/pet/pet_cons_821dst_dcu_nus_a.htm">Sales of Distillate Fuel Oil by End Use</a><br>

 - <a href="/dnav/pet/pet_cons_821rsd_dcu_nus_a.htm">Sales of Residual Fuel Oil by End Use</a><br>

 - <a href="/dnav/pet/pet_cons_821ker_dcu_nus_a.htm">Sales of Kerosene by End Use</a><br>

 - <a href="/dnav/pet/pet_cons_821use_dcu_nus_a.htm">Distillate Fuel Oil and Kerosene Sales by End Use</a>

</p>

<p>
<strong>Adjusted Sales of Fuel Oil and Kerosene</strong><br>

 - <a href="/dnav/pet/pet_cons_821dsta_dcu_nus_a.htm">Adjusted Sales of Distillate Fuel Oil by End Use</a><br>

 - <a href="/dnav/pet/pet_cons_821rsda_dcu_nus_a.htm">Adjusted Sales of Residual Fuel Oil by End Use</a><br>

 - <a href="/dnav/pet/pet_cons_821kera_dcu_nus_a.htm">Adjusted Sales of Kerosene by End Use</a><br>

 - <a href="/dnav/pet/pet_cons_821usea_dcu_nus_a.htm">Adjusted Distillate Fuel Oil and Kerosene Sales by End Use</a>

</p>
   		
    </span>

   
    <div class="clear"></div>


   