<?php /*link rel="stylesheet" href="/global/scripts/selectize/selectize.default.css" */ ?>
<link rel="stylesheet" type="text/css" href="/global/includes/bookshelf/bookshelf.css">
<link rel="stylesheet" type="text/css" href="/global/styles/L2_pages.css" />

<script type="text/javascript" src="/global/includes/bookshelf/bookshelf.js"></script>
<?php /* This is absolutely crucial for the Selectize jQuery plugin to work in MSIE8 */ ?>
<!--[if lt IE 9]>
<script src="/global/scripts/selectize/es5-shim.min.js"></script><![endif]-->
<?php /* END of absolutely critical part for IE8 */ ?>

<?php /* Load Hasher/Signals synchronously for now (instead of using RequireJS AMD loader) */ ?>
<script type="text/javascript" src="/global/scripts/selectize/hasher/signals.js"></script>
<script type="text/javascript" src="/global/scripts/selectize/hasher/hasher.js"></script>

