<div class="content-container top-border blue grey-background">
    <ul>
		<li class="head"><h2>Changes this month</h2></li>
        <li>
            <ul>
                <?php /* April 2018 */ ?>
                <li>"Approximate heat content of coal and coal coke" (<a href="/totalenergy/data/monthly/pdf/sec13_5.pdf">Table A5</a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>, <a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
                <li>"Approximate heat content of natural gas" (<a href="/totalenergy/data/monthly/pdf/sec13_4.pdf">Table A4</a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>, <a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
                <li>"Approximate heat content of petroleum consumption and fuel ethanol" (<a href="/totalenergy/data/monthly/pdf/sec13_3.pdf">Table A3</a>) has revised petroleum consumption factors for 2010-2018.</li>
                <li>Data updates</li>
                <li><a href="/totalenergy/data/monthly/whatsnew.php">See list of previous changes</a></li>
            </ul>
        </li>
    </ul>
</div>
<div class="content-container top-border green grey-background">
    <ul>
		<li class="head"><h2>Diagrams</h2></li>
        <li class="sub-head"><strong>Energy flows 2017</strong></li>
        <li><img src="/totalenergy/data/monthly/pdf/flow/overview_flow_xsmall_2017.png" alt="Total Energy diagram image"></li>
        <li>
			<ul>
                <li>
                    <a href="/totalenergy/data/monthly/pdf/flow/total_energy.pdf" class="ico_pdf">Total energy
                        <i class="ico pdf">
                            <span>PDF</span>
                        </i>
                    </a>
                </li>
                <li>
                    <a href="/totalenergy/data/monthly/pdf/flow/petroleum.pdf" class="ico_pdf">Petroleum
                <i class="ico pdf">
                            <span>PDF</span>
                        </i>
                    </a>
                </li>
                <li>
                    <a href="/totalenergy/data/monthly/pdf/flow/natural_gas.pdf" class="ico_pdf">Natural gas
                <i class="ico pdf">
                            <span>PDF</span>
                        </i>
                    </a>
                </li>
                <li>
                    <a href="/totalenergy/data/monthly/pdf/flow/coal.pdf" class="ico_pdf">Coal
                <i class="ico pdf">
                            <span>PDF</span>
                        </i>
                    </a>
                </li>
                <li>
                    <a href="/totalenergy/data/monthly/pdf/flow/electricity.pdf" class="ico_pdf">Electricity
                    <i class="ico pdf">
                            <span>PDF</span>
                        </i>
                    </a>
                </li>
            </ul>
        </li>           
        <li class="sub-head"><strong>Primary energy consumption 2017</strong></li>
        <li><img src="/totalenergy/data/monthly/pdf/flow/css_2017_xsmall.png" alt="Consumption by Source and Sector diagram image"></li>
        <li>
			<ul>
                <li>
                    <a href="/totalenergy/data/monthly/pdf/flow/css_2017_energy.pdf" class="ico_pdf">Consumption by source and sector
                        <i class="ico pdf">
                            <span>PDF</span>
                        </i>
                    </a>
                </li>
    			<li>
                    <a href="/totalenergy/data/annual/archive/energyflow.php">Archive of energy flow and consumption diagrams</a>
                </li>
			</ul>                
        </li>
    </ul>
</div>
