<div class="secondary">
    <ul>
        <li class="head">
            <h2>Changes this month</h2></li>
        <li>
			<ul>
				<li>Data updates</li>
				<li><a href="/totalenergy/data/monthly/whatsnew.php">See the list of previous changes</a></li>
			</ul>
		</ul>
		<!--
		<ul>
			<li>"Approximate heat content of coal and coal coke" (<a href="/totalenergy/data/monthly/pdf/sec13_5.pdf">Table A5<i class="ico pdf"><span>PDF</span></i></a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>,<a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
			<li>"Approximate heat content of natural gas" (<a href="/totalenergy/data/monthly/pdf/sec13_4.pdf">Table A4<i class="ico pdf"><span>PDF</span></i></a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>, <a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
			<li>"Approximate heat content of petroleum consumption and fuel ethanol" (<a href="/totalenergy/data/monthly/pdf/sec13_3.pdf">Table A3<i class="ico pdf"><span>PDF</span></i></a>) has revised petroleum consumption factors for 2010-2018.</li>
			<li>Data updates</li>
			<li><a href="/totalenergy/data/monthly/whatsnew.php">See list of previous changes</a></li>
		</ul>
		-->

    </ul>
</div>
<div class="secondary-alt">
    <ul>
        <li class="head">
            <h2>Diagrams</h2></li>
        <li class="sub-head">Energy flows 2017</li>
        <li class="image"><img src="/totalenergy/data/monthly/pdf/flow/overview_flow_xsmall_2017.png" alt="Total Energy diagram image"></li>
		
        <li class="pdf"><a href="/totalenergy/data/monthly/pdf/flow/total_energy.pdf">Total energy</a></li>
        <li class="pdf"><a href="/totalenergy/data/monthly/pdf/flow/petroleum.pdf">Petroleum</a></li>
        <li class="pdf"><a href="/totalenergy/data/monthly/pdf/flow/natural_gas.pdf">Natural gas</a></li>
        <li class="pdf"><a href="/totalenergy/data/monthly/pdf/flow/coal.pdf">Coal</a></li>
        <li class="pdf"><a href="/totalenergy/data/monthly/pdf/flow/electricity.pdf">Electricity</a></li>
		
        <li class="sub-head">Primary energy consumption 2017</li>
        <li class="image"><img src="/totalenergy/data/monthly/pdf/flow/css_2017_xsmall.png" alt="Consumption by Source and Sector diagram image"></li>
        <li class="list-spacer pdf"><a href="/totalenergy/data/monthly/pdf/flow/css_2017_energy.pdf">Consumption by source and sector</a></li>
        <li class="list-spacer">
            <ul>
                <li>
                    <a href="/totalenergy/data/annual/archive/energyflow.php">Archive of energy flow and consumption diagrams</a></li>
            </ul>
		</li>
    </ul>
</div>