<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head> 
 
<link rel="stylesheet" href="/global/styles/EIA_global.css" type="text/css" media="screen, projection">	
<script type="text/javascript" src="/global/scripts/jquery/highcharts/js/eia-theme.js"></script>
<script type="text/javascript" src="/global/scripts/jquery/highcharts/js/modules/captions.js"></script>
<script type="text/javascript" src="includes/mer_csv3.js" language="JavaScript"></script>
</head>
<body>		
	
		<?php /* 3. Add the container */ ?>
		<?php /*<table border="2"><tr><td bordercolor="#666666"><div id="container_coal" style="width: 600px; height: 400px; margin: 0 auto"></div></div></td></tr></table>*/ ?>
		
	<div id="container" style="width:227px; height:300px"><script language="JavaScript">InsertMERCode();</script></div>			
	
</body>
</html>