<?php /* <?php include ('side_data.php') ; ?> */ ?>
<?php /* Changes this month box */ ?>
<span class="grey_side blue_top side_list_nocolumn">
	<h4>Changes this month</h4>

	<ul>
	<?php /* April 2018 */ ?>
    
    <li>"Approximate heat content of coal and coal coke" (<a href="/totalenergy/data/monthly/pdf/sec13_5.pdf">Table A5</a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>, <a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
    <li>"Approximate heat content of natural gas" (<a href="/totalenergy/data/monthly/pdf/sec13_4.pdf">Table A4</a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>, <a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
	<li>"Approximate heat content of petroleum consumption and fuel ethanol" (<a href="/totalenergy/data/monthly/pdf/sec13_3.pdf">Table A3</a>) has revised petroleum consumption factors for 2010-2018.</li>
    <li>Data updates</li>
	
	<li><a href="/totalenergy/data/monthly/whatsnew.php">See list of previous changes</a></li>
	</ul>
</span>
<?php /*
 Primary Energy Bar Graph box 
<span class="grey_side green_top side_list_nocolumn" style="padding:5px">
<?php include ('mer_csv3.php') ; ?>
</span>
*/ ?>
<?php /* Start of Energy Flow Content box */ ?>
          <span class="grey_side green_top side_list_nocolumn">
          <h4 style="color:#000">Diagrams</h4>
             <p class="no-border"><strong>Energy flows 2017</strong></p>
<?php /* <a href="/totalenergy/data/monthly/pdf/flow/primary_energy.pdf"> */ ?><img src="/totalenergy/data/monthly/pdf/flow/overview_flow_xsmall_2017.png" alt="Total Energy diagram image"><?php /*</a>*/ ?>
			<dl>
			<dt>&nbsp;</dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/total_energy.pdf" class="ico_pdf">Total energy</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/petroleum.pdf" class="ico_pdf">Petroleum</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/natural_gas.pdf" class="ico_pdf">Natural gas</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/coal.pdf" class="ico_pdf">Coal</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/electricity.pdf" class="ico_pdf">Electricity</a></dt>
			</dl>           
			<p><strong>Primary energy consumption 2017</strong></p>
			<img src="/totalenergy/data/monthly/pdf/flow/css_2017_xsmall.png" alt="Consumption by Source and Sector diagram image">
			<dl>
			<dt>&nbsp;</dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/css_2017_energy.pdf" class="ico_pdf">Consumption by source and sector</a></dt>
			</dl>
<dl>
			<dt>&nbsp;</dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/annual/archive/energyflow.php">Archive of energy flow and consumption diagrams</a></dt>
			</dl>            
            
          </span>
          <?php /* End of Energy Flow Content box */ ?>
<?php /* <?php include ('mer2_chart.php') ; ?> */ ?>
<?php /*<a href="/totalenergy/data/annual/diagram1.cfm"><img src="/totalenergy/data/annual/images/overview_flow_2010_xsmall.jpg" alt="Total Energy graph image"></a>*/ ?>

	<?php /*		<ul>
			<li>&nbsp;<a href="/totalenergy/data/annual/pecss_diagram.cfm">U.S. Primary Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram1.cfm">Total Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram2.cfm">Petroleum</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram3.cfm">Natural Gas</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram4.cfm">Coal</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram5.cfm">Electricity</a></li>
			</ul>
          </span>
           Start of Energy Perspectives Content box 
          <span class="grey_side green_top side_list_nocolumn">
              <h4><a href="/totalenergy/data/annual/perspectives.cfm">Energy Perspectives</a></h4>
<a href="/totalenergy/data/annual/perspectives.cfm"><img src="/totalenergy/data/annual/images/ep_2010_xsmall.jpg" alt="Energy Perspectives image"></a>
          </span>
           End of Energy Perspectives Content box */ ?>