<div class="content-container light-top-border-container grey-background">
    <ul>
		<li class="head"><h2>Changes this month</h2></li>
		<li>"Approximate heat content of coal and coal coke" (<a href="/totalenergy/data/monthly/pdf/sec13_5.pdf">Table A5</a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>, <a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
		<li>"Approximate heat content of natural gas" (<a href="/totalenergy/data/monthly/pdf/sec13_4.pdf">Table A4</a>) includes revisions for 2017 and 2018 that affect data in <a href="/totalenergy/data/monthly/#summary">Energy overview</a>, <a href="/totalenergy/data/monthly/#consumption">Energy consumption by sector</a>, and <a href="/totalenergy/data/monthly/#environment">Environment</a>.</li>
		<li>"Approximate heat content of petroleum consumption and fuel ethanol" (<a href="/totalenergy/data/monthly/pdf/sec13_3.pdf">Table A3</a>) has revised petroleum consumption factors for 2010-2018.</li>
		<li class="sub-head">Data updates</li>
		<li><a href="/totalenergy/data/monthly/whatsnew.php">See list of previous changes</a></li>
	</ul>
</div>

<div class="content-container light-top-border-container grey-background">
	<ul>
		<li class="head"><h2>Diagrams</h2></li>
		<li class="sub-head"><strong>Energy flows 2017</strong></li>
		<li><img src="/totalenergy/data/monthly/pdf/flow/overview_flow_xsmall_2017.png" alt="Total Energy diagram image"></li>
		<li><a href="/totalenergy/data/monthly/pdf/flow/total_energy.pdf" class="ico_pdf">Total energy</a></li>
		<li><a href="/totalenergy/data/monthly/pdf/flow/petroleum.pdf" class="ico_pdf">Petroleum</a></li>
		<li><a href="/totalenergy/data/monthly/pdf/flow/natural_gas.pdf" class="ico_pdf">Natural gas</a></li>
		<li><a href="/totalenergy/data/monthly/pdf/flow/coal.pdf" class="ico_pdf">Coal</a></li>
		<li><a href="/totalenergy/data/monthly/pdf/flow/electricity.pdf" class="ico_pdf">Electricity</a></li>
		<li class="sub-head"><strong>Primary energy consumption 2017</strong></li>
		<li><img src="/totalenergy/data/monthly/pdf/flow/css_2017_xsmall.png" alt="Consumption by Source and Sector diagram image"></li>
		<li><a href="/totalenergy/data/monthly/pdf/flow/css_2017_energy.pdf" class="ico_pdf">Consumption by source and sector</a></li>
		<li><a href="/totalenergy/data/annual/archive/energyflow.php">Archive of energy flow and consumption diagrams</a></li>
	</ul>
</div>