<?php $what = 'multifuel'; ?>
        <?php include ('about/new/whatsnew_sitewide.php') ; ?>
        <?php /* Start of New in Energy Source -->
            <span class="grey_side blue_top">
                <h4>What's New in Total Energy?</h4>
                
            
            <p><a href="monthly.cfm"><strong>Monthly Energy Review &rsaquo;</strong></a>
            <p><em>released January  2011</em></p>
            <a href="annual.cfm"><strong>Annual Energy Review 2009 &rsaquo;</strong></a>
            <p><em>released August 2010</em></p>
            <a href="annual.cfm"><strong>Consumption, Price, and Expenditure Estimates &rsaquo;</strong></a>
            <p><em>complete release of final 2009 data: end of June 2011</em></p></span>
            <!-- Start of Graphics side items */ ?>
              

         <span class="grey_side green_top"> 
              
              <p><strong>Energy Flow 2009</strong></br>
              (quadrillion Btu)</p>
              
<a href="/aer/diagram1.html"><img src="/aer/overview_flow_2009_xsmall.jpg"></a>
<b>Flow Diagrams:</b>
<ul>
			<li><a href="/aer/diagram1.html" target="_self">Total Energy</a></li>
			<li><a href="/aer/diagram2.html" target="_self">Petroleum</a></li>
			<li><a href="/aer/diagram3.html" target="_self">Natural Gas</a></li>
			<li><a href="/aer/diagram4.html" target="_self">Coal</a></li>
			<li><a href="/aer/diagram5.html" target="_self">Electricity</a></li>
          </ul>
</span>
<span class="blue_side">
          <h4 class="q_side"><a href="/tools/faqs/faq.cfm?id=85&t=1">How much energy does a person use in a year? &rsaquo;</a></h4>
          <p><a href="/tools/faqs/#generalenergy" width="240"><br />
          See all general energy FAQs  &rsaquo;</a></p>
        </span>
              
             <!-- <p>State Energy Data</p>
              
<img src="" width="200"><a href=""></a>-->
        <?php /* Energy Explained Promo */ ?>
        <p><a href="/energyexplained/index.cfm?page=us_energy_home"><img src="/energyexplained/images/section-banners/usa_energy_facts.jpg"  alt="Energy Explained - U.S. Energy Facts" width="240"/></a></p>