<p>Find statistics on energy consumption and efficiency  across all fuel sources.</p>
<div class="accordion">
<div class="expand-collapse-container">
<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
</div>

<table class="contable">
	<h2><i class="ico expand-collapse"></i><a name="rec"></a>Residential Energy Consumption Survey data</h2>
	<div class="accordion-content">
		<ul>
<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/residential/data/2015/index.php?view=characteristics">Household characteristics</a></li>
			<li>
<em class="hideme">Release Date: February 27, 2017</span></li>
			<li>Characteristics data (including structural features, appliance stock, electronics stock, and square footage) for occupied primary housing units.
</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>

</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/residential/data/2015/index.php?view=consumption">Home energy use &amp; costs</a></li>
			<li>
<em class="hideme">Release Date: Anticipated Spring 2018</span></li>
			<li>Energy consumption and expenditures for occupied primary housing units by end uses and by fuel.

</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats 
<a href="#" class="ico_pdf">PDF</a>*/ ?>
</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/residential/data/2015/index.php?view=microdata">Detailed household microdata</a></li>
			<li>
<em class="hideme">Release Date: October 2017</span></li>
			<li>Data are available in two formats: CSV (a comma delimited file) and a SAS data file.
</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats 
<a href="#" class="ico_pdf">PDF</a>*/ ?>
</span></li>      


	<h2><i class="ico expand-collapse"></i><a name="cec"></a>Commercial Buildings Energy Consumption Survey data</h2>
	<div class="accordion-content">
		<ul>
<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/commercial/data/2012/">Building characteristics</a></li>
			<li>
<em class="hideme">March 2015</span></li>
			<li>Detailed tabulated data providing number of buildings and floorspace by characteristics such as geographic region, building activity, size and age, employment and occupancy, energy sources used, and energy-related equipment.<br />
</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/commercial/data/2012/index.cfm?view=consumption">Consumption and Expenditures</a></li>
			<li>
<em class="hideme">Release Date: May, 2016</span></li>
			<li>Detailed tabulated data providing total energy, electricity, natural gas, fuel oil and district heat consumption figures and data by end use (heating, cooling, lighting, etc.).  <br />
</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>     

<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/commercial/data/2012/index.cfm?view=microdata">Detailed building microdata</a></li>
			<li>
<em class="hideme">Release Date: May, 2016</span></li>
			<li>Raw data for 6,720 buildings for data users to create custom tables that are not available through the tabulated information. The data represent commercial buildings from the 50 States and the District of Columbia. Each record corresponds to a single responding, in-scope sampled building. Data are available in two formats: a comma delimited file (CSV) and a SAS data file. <br />
</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>     

	<h2><i class="ico expand-collapse"></i><a name="mfg"></a>Manufacturing Energy Consumption Survey data</h2>
	<div class="accordion-content">
		<ul>
<li>
<?php /* Data Info */ ?>
<strong>Consumption of energy for all purposes, by industry & region</li>
			<li>
<em class="hideme">Release Date: October 2017</span></li>
			<li></li>
			<li class="additional-formats">Available formats: <a href="manufacturing/data/2014/XLS/Table1_1.xlsx" class="ico_xls" title="Consumption of energy for all purposes, by industry & region "><i class="ico xls"><span>XLS</span></i></a>&nbsp;<a href="manufacturing/data/2014/pdf/Table1_1.pdf" class="ico_pdf" title="Consumption of energy for all purposes, by industry & region "><i class="ico pdf"><span>PDF</span></i></a></span></li>      

<li>
<?php /* Data Info */ ?>
<strong>Energy Used as a Nonfuel (Feedstock)</strong><strong></li>
			<li>
<em class="hideme">Release Date: October 2017</span></li>
			<li></li>
<td class="white_first"><span class="right"><a href="manufacturing/data/2014/xls/Table2_1.xlsx" class="ico_xls" title="Energy Used as a Nonfuel (Feedstock) "><i class="ico xls"><span>XLS</span></i></a>&nbsp;<a href="manufacturing/data/2014/pdf/Table2_1.pdf" class="ico_pdf" title="Energy Used as a Nonfuel (Feedstock) "><i class="ico pdf"><span>PDF</span></i></a></span></li>      

<li>
<?php /* Data Info */ ?>
<strong>Energy consumption as a fuel</strong><strong>, by industry &amp; region</li>
			<li>
<em class="hideme">Release Date: October 2017</span></li>
			<li></li>
<td class="white_first"><span class="right"><a href="manufacturing/data/2014/xls/Table3_1.xlsx" class="ico_xls" title="Energy consumption as a fuel, by industry & region "><i class="ico xls"><span>XLS</span></i></a>&nbsp;<a href="manufacturing/data/2014/pdf/Table3_1.pdf" class="ico_pdf" title="Energy consumption as a fuel, by industry & region "><i class="ico pdf"><span>PDF</span></i></a></span></li>      

<li>
<?php /* Data Info */ ?>
<strong>Offsite-produced fuel consumption, by industry </li>
			<li>
<em class="hideme">Release Date: October 2017</span></li>
			<li></li>
<td class="white_first"><span class="right"><a href="manufacturing/data/2014/xls/Table4_1.xlsx" class="ico_xls" title="Offsite-produced fuel consumption, by industry  "><i class="ico xls"><span>XLS</span></i></a>&nbsp;<a href="manufacturing/data/2014/pdf/Table4_1.pdf" class="ico_pdf" title="Offsite-produced fuel consumption, by industry  "><i class="ico pdf"><span>PDF</span></i></a></span></li>      

<li>
<?php /* Data Info */ ?>
<strong>Total consumption of electricity</strong><strong>, by industry &amp; region</li>
			<li>
<em class="hideme">Release Date: October 2017</span></li>
			<li></li>
<td class="white_first"><span class="right"><a href="manufacturing/data/2014/xls/Table11_1.xlsx" class="ico_xls" title="Total consumption of electricity, by industry & region "><i class="ico xls"><span>XLS</span></i></a>&nbsp;<a href="manufacturing/data/2014/pdf/Table11_1.pdf" class="ico_pdf" title="Total consumption of electricity, by industry & region "><i class="ico pdf"><span>PDF</span></i></a></span></li>   
<!--        
			<li class="head"><a href="../consumption/manufacturing/reports/archive/mecs_trend_9802/mecs_trend9802.html">Manufacturing industry trend data</a></li>
			<li>
Years 1998, 2002, and 2006 </li>  -->  

<!--
	<h2><i class="ico expand-collapse"></i><a name="vehicles"></a>Vehicle Energy Consumption Survey data</h2>
	<div class="accordion-content">
		<ul>
<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/archive/rtecs/nhts_survey/2001/tablefiles/page_a01.html">Vehicle characteristics</a></li>
			<li>
<em class="hideme">Release Date: November, 2005</span></li>
			<li></li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/archive/rtecs/nhts_survey/2001/tablefiles/page_a04.html">Vehicle stock</a></li>
			<li>
<em class="hideme">Release Date: November, 2005</span></li>
			<li></li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/archive/rtecs/nhts_survey/2001/tablefiles/page_a02.html">Fuel consumption</a></li>
			<li>
<em class="hideme">Release Date: November, 2005</span></li>
			<li></li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      


	<h2><i class="ico expand-collapse"></i><a name="intensity"></a>Energy intensity</h2>
	<div class="accordion-content">
		<ul>
<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/residential/data/2009/index.cfm?view=consumption#summary">Residential</a></li>
			<li>
<em class="hideme">Release Date: August, 2004</span></li>
			<li></li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="/consumption/commercial/data/2003/index.cfm?view=consumption">Commercial buildings</a></li>
			<li>
<em class="hideme">Release Date: December, 2004</span></li>
			<li></li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="manufacturing/reports/archive/iron_steel_9802/steel_9802_data.html">Manufacturing industries</a></li>
			<li>
<?php /* <em class="hideme">No Release Date Given</span></li>
			<li> */ ?>
Data for iron and steel industry<br />
1998, 2002, and 2006 Manufacturing Energy Consumption Survey (MECS)<br />
</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      

	<h2><i class="ico expand-collapse"></i><a name="consumption"></a>Consumption summaries</h2>
	<div class="accordion-content">
		<ul>
<li>
<?php /* Data Info */ ?>
<strong><a href="/totalenergy/data/monthly/#consumption">Monthly</a></li>
			<li>
<em class="hideme">Release Date: September 26, 2012</span></li>
			<li>The latest energy statistics all in one place.<br />
Monthly Energy Review (MER)<br />
</li>
			<li class="additional-formats">Available formats: 
<?php /* Alternate Formats */ ?>
</span></li>      

<li>
<?php /* Data Info */ ?>
<strong><a href="/totalenergy/data/annual/#consumption">Annual</a></li>
			<li>
<em class="hideme">Release Date: September 27, 2012</span></li>
			<li>Long-term historical statistics all in one place.			<li class="release-schedule">Annual Energy Review (AER)<br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/annual/pdf/sec2.pdf" class="ico_pdf">PDF</a>
<?php /* Alternate Formats */ ?>
</span></li>
-->     



</table>
<?php /* End of Main Column */ ?>