<table width="100%" class="basic_table">
  <caption>
  Energy consumption estimates  by sector<br />
 <span class="units"> trillion Btu</span></caption>
  
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th><div align="right">2014 (Jan-June)</div></th>
      <th><div align="right">2013</div></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Residential</td>
      <td>11,440</td>
      <td>21,287</li>
    <tr>
      <td>Commercial</td>
      <td>9,281</td>
      <td>18,047</li>
    <tr>
      <td>Industrial</td>
      <td>15,580</td>
      <td>31,154</li>
    <tr>
      <td>Transportation</td>
      <td>13,348</td>
      <td >27,147</li>
    <tr class="total">
      <td >Total primary</td>
      <td>49,659</td>
      <td >97,635</li><tfoot>
        <tr>
        <td colspan="3">Source: U.S. Energy Information Administration, <a href="/totalenergy/data/monthly/#consumption											
">Monthly Energy Review</a></li>
        </tfoot>
  </tbody>
</table>
<?php /*
<caption>Weekly Retail Gasoline and Diesel Prices<br />
</caption>(dollars per gallon, including taxes)
*/ ?>
<?php /* Table header */ ?>
