	<?php /* Sections Promo */ ?>
<?php /*<h2>Highlights</h2>
    <span>
    <p><b>Figure HL1.</b> Crude Oil and Petroleum Product Wholesale Prices<a href="images/2011-04/fig_HL1_coppwp.jpg" class="lightbox"><img src="images/2011-04/fig_HL1_coppwp_sm.jpg" /></a>
      <span class="right"><a href="#" class="ico_xls">Download Figure Data</a></span>
    </p>
    </span>*/ ?>
<?php /*    <h3>Highlights</h3>

<p><ul><li>	In 2010, the average retail price for all customer classes remained unchanged at 9.83 cents per kWh from 2009.</li> </ul>
<iframe  src="images/all_sectors_prices1.html" frameborder="0" height="373" width="355"></iframe>
<ul><li>Total U.S. retail sales of electricity were 3,754 million MWh in 2010, a 4.4-percent increase from 2009 to 2010.</li>  
<li>Total revenues in 2010 increased from $353.4 billion in 2009 to $368.9 billion in 2010.  This 4.4-percent increase was consistent with the increase in sales.</li></ul>
</p>*/ ?>
   
 
<div class="content-container light-top-border-container grey-background">
    <h2>Supplemental Data</h2>
    
<p ><?php /*class="left no-border"*/ ?>Annual Electric Utility data - EIA-861 data file, includes county service areas <a href="/electricity/data/eia861/" title="Annual Electric Utility data - EIA-861 data file, includes county service areas">dbf.xlsx</a>
<p >1990 - 2015	Average Price by State by Provider (EIA-861) <a href="/electricity/data/state/avgprice_annual.xlsx" class="ico.xlsx">XLS</a>
<p >1990 - 2015	Number of Retail Customers by State by Sector (EIA-861) <a href="/electricity/data/state/customers_annual.xlsx" class="ico.xlsx">XLS</a>
<p >1990 - 2015	Retail Sales of Electricity by State by Sector by Provider (EIA-861) <a href="/electricity/data/state/sales_annual.xlsx" class="ico.xlsx">XLS</a>
<p >1990 - 2015	Revenue from Retail Sales of Electricity by State by Sector by Provider (EIA-861) <a href="/electricity/data/state/revenue_annual.xlsx" class="ico.xlsx">XLS</a><br />
  <br/>
  <?php /*  Historical EPA Electric Sales and Revenue Spreadsheets

  <br /><br />
    <a href="/electricity/data/state/customers_annual.xls" title="Historical EPA Electric Sales and Revenue Spreadsheets: Sales State">Customers State</a>
<br />    
  <a href="/electricity/data/state/sales_annual.xls" title="Historical EPA Electric Sales and Revenue Spreadsheets: Sales State">Sales State</a>
<br />      
<a href="/electricity/data/state/revenue_annual.xls" title="Historical EPA Electric Sales and Revenue Spreadsheets: Revenue State">Revenue State</a>
    
<br />
<br />
    Class of Ownership, Number of Bundled Ultimate Consumers, Revenue, Sales, and Average Retail Price<br/>
    <a href="/electricity/sales_revenue_price/archive/2003/esr_2003_tables.xls">2003 Tables</a> 
    <br /><br />
    Class of Ownership, Number of Bundled Ultimate Consumers, Revenue, Sales, and Average Revenue per Kilowatthour<br/>
     <a href="/electricity/sales_revenue_price/archive/2002/esr_2002_tables.xls">2002 Tables</a> 
    <br />
     <a href="/electricity/sales_revenue_price/archive/2001/esr_2001_tables.xls">2001
      Tables</a> 
        
    <a href="#">Product Guide</a><br />
        <a href="#">Glossary</a><br />
        <a href="#">List of Articles</a><br />
  </p>*/ ?>
</span> 
  <div class="clear"></div>

