<p>Find statistics on energy consumption and efficiency across all fuel sources.</p>
	<div class="accordion">
		<div class="expand-collapse-container">
			<span class="expand-all">
				<i class="ico expand-collapse"></i> Expand all</span>
			<span class="collapse-all">
				<i class="ico expand-collapse"></i> Collapse all</span>
		</div>
		<h2>
			<i class="ico expand-collapse"></i>
			<a name="rec"></a>Residential Energy Consumption Survey data</h2>
		<div class="accordion-content">
			<ul>
				<li class="head">
					<strong>
						<a href="/consumption/residential/data/2015/index.php?view=characteristics">Household characteristics</a>
					</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">February 27, 2017</span>
				</li>
				<li>Characteristics data (including structural features, appliance stock, electronics stock, and square footage) for occupied
					primary housing units.</li>
			</ul>
			<ul>
				<li class="head">
					<strong>
						<a href="/consumption/residential/data/2015/index.php?view=consumption">Home energy use &amp; costs</a>
					</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">Anticipated Spring 2018</span>
				</li>
				<li>Energy consumption and expenditures for occupied primary housing units by end uses and by fuel.</li>

			</ul>
			<ul>
				<li class="head">
					<strong>
						<a href="/consumption/residential/data/2015/index.php?view=microdata">Detailed household microdata</a>
					</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li>Data are available in two formats: CSV (a comma delimited file) and a SAS data file.</li>
			</ul>
		</div>
		<!--  end  -->
		<!-- start -->
		<h2>
			<i class="ico expand-collapse"></i>
			<a name="cec"></a>Commercial Buildings Energy Consumption Survey data</h2>
		<div class="accordion-content">
			<ul>
				<li class="head">
					<strong>
						<a href="/consumption/commercial/data/2012/">Building characteristics</a>
					</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">March 2015</span>
				</li>
				<li>Detailed tabulated data providing number of buildings and floorspace by characteristics such as geographic region, building
					activity, size and age, employment and occupancy, energy sources used, and energy-related equipment.</li>

			</ul>
			<ul>
				<li class="head">
					<strong>
						<a href="/consumption/commercial/data/2012/index.cfm?view=consumption">Consumption and Expenditures</a>
					</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">May, 2016</span>
				</li>
				<li>Detailed tabulated data providing total energy, electricity, natural gas, fuel oil and district heat consumption figures
					and data by end use (heating, cooling, lighting, etc.).</li>

			</ul>
			<ul>
				<li class="head">
					<strong>
						<a href="/consumption/commercial/data/2012/index.cfm?view=microdata">Detailed building microdata</a>
					</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">May, 2016</span>
				</li>
				<li>Raw data for 6,720 buildings for data users to create custom tables that are not available through the tabulated information.
					The data represent commercial buildings from the 50 States and the District of Columbia. Each record corresponds to
					a single responding, in-scope sampled building. Data are available in two formats: a comma delimited file (CSV) and
					a SAS data file.
				</li>
			</ul>
		</div>
		<!--  end  -->
		<!-- start -->
		<h2>
			<i class="ico expand-collapse"></i>
			<a name="mfg"></a>Manufacturing Energy Consumption Survey data</h2>
		<div class="accordion-content">

			<ul>
				<li class="head">
					<strong>Consumption of energy for all purposes, by industry & region</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li class="additional-formats">Available formats:
					<a href="manufacturing/data/2014/XLS/Table1_1.xlsx" class="ico_xls" title="Consumption of energy for all purposes, by industry & region">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a>
					<a href="manufacturing/data/2014/pdf/Table1_1.pdf" class="ico_pdf" title="Consumption of energy for all purposes, by industry & region">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>

			</ul>
			<ul>
				<li class="head">
					<strong>Energy Used as a Nonfuel (Feedstock)</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li class="additional-formats">
					<a href="manufacturing/data/2014/xls/Table2_1.xlsx" class="ico_xls" title="Energy Used as a Nonfuel (Feedstock)">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a>
					<a href="manufacturing/data/2014/pdf/Table2_1.pdf" class="ico_pdf" title="Energy Used as a Nonfuel (Feedstock)">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>

			</ul>
			<ul>
				<li class="head">
					<strong>Energy consumption as a fuel, by industry &amp; region</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li class="additional-formats">
					<a href="manufacturing/data/2014/xls/Table3_1.xlsx" class="ico_xls" title="Energy consumption as a fuel, by industry & region">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a>
					<a href="manufacturing/data/2014/pdf/Table3_1.pdf" class="ico_pdf" title="Energy consumption as a fuel, by industry & region">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>

			</ul>
			<ul>
				<li class="head">
					<strong>Offsite-produced fuel consumption, by industry</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li class="additional-formats">
					<a href="manufacturing/data/2014/xls/Table4_1.xlsx" class="ico_xls" title="Offsite-produced fuel consumption, by industry">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a>
					<a href="manufacturing/data/2014/pdf/Table4_1.pdf" class="ico_pdf" title="Offsite-produced fuel consumption, by industry">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>

			</ul>
			<ul>
				<li class="head">
					<strong>Total consumption of electricity, by industry &amp; region</strong>
				</li>
				<li>
					<span class="release-date">Release Date: </span>
					<span class="date">October 2017</span>
				</li>
				<li class="additional-formats">
					<a href="manufacturing/data/2014/xls/Table11_1.xlsx" class="ico_xls" title="Total consumption of electricity, by industry & region">
						<i class="ico xls">
							<span>XLS</span>
						</i>
					</a>
					<a href="manufacturing/data/2014/pdf/Table11_1.pdf" class="ico_pdf" title="Total consumption of electricity, by industry & region">
						<i class="ico pdf">
							<span>PDF</span>
						</i>
					</a>
				</li>
			</ul>
		</div>