          <?php /* Sidenav EIA Menu side_nav*/ ?>
          
          <span class="grey_side_nav blue_top ">
              <ul class="top">
                <li><a href="/consumption/residential/index.cfm">Residential Overview</a></li>
              </ul>
              <ul>
                <li><span class="active">Data</span>
                  <ul>
                    <li><a href="/consumption/residential/data/2005/">2005</a></li>
                    <li><a href="http://www.eia.gov/emeu/recs/recs2001/detail_tables.html">2001</a></li>
                    <li><a href="http://www.eia.gov/emeu/recs/recs97/recs97.html">1997</a></li>
                    <li><a href="/consumption/residential/data/archive.cfm">Archive</a></li>
                  </ul>
                </li>
              </ul>
              <ul>
                <li><a href="/consumption/residential/reports/">Analysis &amp; Reports</a></li>
              </ul>
              <ul>
                <li class="no_btm_border"><a href="/consumption/residential/methodology/">Methodology</a></li></ul>
              
              <ul>
           <h3>   <li><a href="http://wwwdev.eia.gov/consumption/residential/about_recs.cfm">About the Residential Energy Consumption (RECS) Survey</a></li>
              
                <li><a href="http://wwwdev.eia.gov/consumption/residential/data/2005/#tabs-1">Household characteristics 2005</a> (most recent)</li>
                <li><a href="http://wwwdev.eia.gov/consumption/residential/data/2005/#tabs-2">Home energy use &amp; costs 2005</a> (most recent)</li>
                <li><a href="http://wwwdev.eia.gov/consumption/residential/data/2005/#tabs-2">2009 data coming soon</a></li>
                <li><a href="http://wwwdev.eia.gov/consumption/residential/trends.cfm">Data trends</a></li>
                <li><a href="http://wwwdev.eia.gov/consumption/residential/methodology/">Methodology</a></li>
                <li><a href="http://wwwdev.eia.gov/consumption/residential/data/archive.cfm">Archive</a></li>
                <li><a href="../../consumption_v012811/residential/data/2005/microdata.cfm">Public use microdata</a> 
              comma delimited data files </li>
                <li><a href="#tabs-2">Contact information</a></li></h3>
                 
              
        </ul>
          </span>
          <?php /* Sidenav EIA Menu */ ?>