          <?php $what = 'consumption'; ?>
        <?php include ('about/new/whatsnew_sitewide.php') ; ?>
 <span class="grey_side blue_top ">
              <ul class="top">
              <p class="no_btm_border"> 
        <h4>End use consumption<br />
        data and surveys
                  </h4>
                         
                 
        Residential Energy Consumption Survey (RECS) 	&mdash;  <a href="data/index.cfm">homes </a><hr/>
  Commercial Building Energy Consumption Survey (CBECS) 	&mdash;   
 <a href="data/2003/">commercial buildings</a> <hr/>Manufacturing Energy Consumption Survey <a href="data/2006/"> manufacturing </a><hr/>

Residential Transportation Vehicles Survey<a href="data/2006/"> 	household vehicles</a><hr/>

<h4>Sector totals:</h4>
<li><a href="/aer/txt/ptb0201e.html">annual</a> 	&mdash; 1949-2009<br />
</li>
        <li><a href="/mer/consump.html">monthly</a><br />
        </li> 
          </p></li>


<span class="grey_side green_top">
              <h4>Efficiency related:</h4>
                
                              
<ul> 
<li><a href="/emeu/recs/recs2005/hc2005_tables/detailed_tables2005.html">Lighting usage indicator tables</a>    &mdash; 2005<br />
                </li>
          <li><a href="http://www.eia.gov/forecasts/aeo/early_intensity.cfm">Key energy intensity indicators and consumption by sector</a>   &mdash; projections to 2035<br />
          </li>
                
     <li><a href"http://www.eia.gov/cneaf/electricity/epa/epa_sum.html#nine">Electric utility demand-side management</a></li>
     <li><a href="/aer/txt/ptb0208.html">Motor Vehicle Milage, Fuel Consumption, and Fuel Economy</a> 1949-2008<br />
     </li>
          
     <li><a href="http://www.eia.gov/emeu/international/total.html#IntlConsumption">International energy intensity projections to 2030</a></li></ul><p>
   <b> <a href="http://www.eia.gov/emeu/efficiency/appliance_standards.html">  Related links &rsaquo; </a> </b>   </p>  
</span>
   
         

        <?php /* Sidenav EIA Menu */ ?>