          <span class="grey_side green_top">
            <h4>2005 Data Tables<a href="../generic.cfm"></a></h4>

<p class="no_btm_border">  Most current data for Residential Energy Consumption Surveys.
  </p>
<ul>
  <li><a href="data/index.cfm">Household Characteristics </a></li>
<li> <a href="data/index.cfm">Home Energy Use & Costs</a></li>
</ul>

  <h4><a href="data/2005/microdata.cfm">Public Use Microdata</a></h4>
<p class="no_btm_border">Comma delimited data files available for public use with various software applications.          </p>
</span>
         <span class="grey_side green_top">
<p class="no_btm_border">
          <a href="http://www.eia.gov/listserv_signup.html#consumption">Get e-mail updates on Commercial Buildings Energy Use</a></p>
          </span>