        <?php $what = 'consumption'; ?>
        <?php include ('about/new/whatsnew_sitewide.php') ; ?>
        <div class="content-container light-top-border-container grey-background">
<ul>
<li class="head"><h2>Energy Use Information by Sector</h2></li>
<p class="no_btm_border"><strong>Residential</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="residential/"> overview</a></li>
          <li><a href="residential/data/2005/">most recent data (2005)</a></li>
          <li><a href="residential/reports/">analysis, projections &amp; reports</a></li></ul>
          <hr/>
<strong>Commercial Buildings</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="commercial/">overview</a></li>
          <li><a href="commercial/data/2003/">most recent data (2003)</a></li>
          <li><a href="commercial/reports/">analysis, projections &amp; reports</a></li></ul><hr/>
          <strong>Manufacturing</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="industrial/">overview</a></li>
          <li><a href="manufacturing/data/2006/">most recent data (2006)</a></li>
          <li><a href="manufacturing/reports/">analysis, projections &amp; reports</a></li></ul>
          <hr/>
<p class="no_btm_border" ><strong>Transportation</li>
			<li>
            Energy use by fuel type, housing type, and end uses
        <ul>
          <li><a href="transportation/">overview</a></li>
          <li><a href="transportation/data/2001/">most recent data (2001)</a></li>
          <li><a href="transportation/reports/">analysis, projections &amp; reports          </a></li>
        </ul></p><hr/>
        <li class="head"><h2>Topics</h2></li>
        <p class="no_btm_border"><strong>Efficiency (Energy Intensity)</strong></li>
<li>
<ul>
          <li><a href="/consumption/efficiency/index.cfm">overview</a></li>
          <li><a href="/consumption/efficiency/data/index.cfm">data</a></li>
          <li><a href="/consumption/efficiency/reports/index.cfm">aalysis, projections &amp; reports</a></li>
        </ul>
          
          </span>
          <?php /* FAQ Promo */ ?>
        <span class="blue_side">
          <h4 class="q_side"><a href="consumption_faqs.cfm#rfaq1">What is the basis for EIA&#8217;s statistics on household energy consumption and expenditures?</a></h2></li>
          <p><a href="consumption_faqs.cfm">See all Energy End Use FAQs &rsaquo;</a></p>
        </span>
        