

	      <?php /* Start of MER */ 
           /* <p class="dat"><script type="text/javascript">PubReleaseTimeStamp()</script></p> */ ?>          </h2>
          <p>Find data from forecast models on crude oil and petroleum liquids, gasoline, diesel, natural gas, electricity, coal prices, supply, and demand projections and more.<br />
          <?php /* <a href="" class="ico_pdf">PDF</a> */ ?></p>
          <div class="accordion-head"><h2><i
	<div class="expand-collapse-container">
		<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
		<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
	</div>
          <table class="contable">
<?php /* Start of Energy Overview Content  */ ?>
            	<h2><i class="ico expand-collapse"></i><a name="forecasts"></a>Monthly short-term forecasts through the next calender year</b></th>
                <th><?php /* <span class="right">additional formats</span> */ ?></th>
              </tr>
            </thead>
              <?php /*tr>
                <td>Data</td>
                
              </tr*/ ?>
              <tr>
                <td><em><a href="/outlooks/steo/">Short-Term Energy Outlook</a></em> Released: the first Tuesday following the first Thursday of each month. </td>
               			<li><span class="formats">Available formats:</span>  &nbsp;</span> </li><tr class="white_first">
                <td><p>WF01. Average consumer prices and expenditures for heating fuels during the winter</td>
                			<li><span class="formats">Available formats:</span>  <a href="/outlooks/steo/tables/pdf/wf-table.pdf" class="ico_pdf" title="Table  WF01. Average consumer prices and expenditures for heating fuels during the winter "><i class="ico pdf"><span>PDF</span></i></a> </span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=3">1. U.S. energy market summary</a><br /></td>
                			<li><span class="formats">Available formats:</span>    <a href="/outlooks/steo/tables/pdf/1tab.pdf" class="ico_pdf" title="Table  1. U.S. energy market summary "><i class="ico pdf"><span>PDF</span></i></a></span>				</li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=8">2. U.S. energy prices </a><br /></td>
                			<li><span class="formats">Available formats:</span>    <a href="/outlooks/steo/tables/pdf/2tab.pdf" class="ico_pdf" title="Table  2. U.S. energy prices  "><i class="ico pdf"><span>PDF</span></i></a> </span>				</li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=6">3a. International crude oil and liquid fuels supply, consumption, and inventories</a></td>
                			<li><span class="formats">Available formats:</span>    <a href="/outlooks/steo/tables/pdf/3atab.pdf" class="ico_pdf" title="Table  3a. International crude oil and liquid fuels supply, consumption, and inventories "><i class="ico pdf"><span>PDF</span></i></a></span>				</li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=29">3b. Non-OPEC crude oil and liquid fuels supply</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/3btab.pdf" class="ico_pdf" title="Table  3b. Non-OPEC crude oil and liquid fuels supply "><i class="ico pdf"><span>PDF</span></i></a> </span>				</li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=7">3c. OPEC crude oil and liquid fuels supply</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/3ctab.pdf" class="ico_pdf" title="Table  3c. OPEC crude oil and liquid fuels supply "><i class="ico pdf"><span>PDF</span></i></a> </span>				</li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=30">3d. World liquid fuels consumption</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/3dtab.pdf" class="ico_pdf" title="Table  3d. World liquid fuels consumption "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=9">4a. U.S. crude oil and liquid fuels supply, consumption, and inventories</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/4atab.pdf" class="ico_pdf" title="Table  4a. U.S. crude oil and liquid fuels supply, consumption, and inventories "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=27">4b. U.S. petroleum refinery balance</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/4btab.pdf" class="ico_pdf" title="Table  4b. U.S. petroleum refinery balance "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=10">4c. U.S. regional motor gasoline prices and inventories</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/4ctab.pdf" class="ico_pdf" title="Table  4c. U.S. regional motor gasoline prices and inventories "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <?php /*<tr>
                <td><a href="/forecasts/steo/tables/?tableNumber=11">4d. U.S. regional heating oil prices and inventories</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/forecasts/steo/tables/pdf/4dtab.pdf" class="ico_pdf">PDF</a></span></li>
              <tr>
                <td><a href="/forecasts/steo/tables/?tableNumber=12">4e. U.S. regional propane prices and inventories</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/forecasts/steo/tables/pdf/4etab.pdf" class="ico_pdf">PDF</a></span></li> */ ?>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=15">5a. U.S. natural gas supply, consumption, and inventories</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/5atab.pdf" class="ico_pdf" title="Table  5a. U.S. natural gas supply, consumption, and inventories "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=16">5b. U.S. regional natural gas prices</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/5btab.pdf" class="ico_pdf" title="Table 5b. U.S. regional natural gas prices "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=18">6. &nbsp; U.S. coal supply, consumption, and inventories</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/6tab.pdf" class="ico_pdf" title="Table 6. Â  U.S. coal supply, consumption, and inventories "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=19">7a. U.S. electricity overview</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/7atab.pdf" class="ico_pdf" title="Table 7a. U.S. electricity overview "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=20">7b. U.S. regional electricity retail sales</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/7btab.pdf" class="ico_pdf" title="Table 7b. U.S. regional electricity retail sales "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=21">7c. U.S. regional electricity prices</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/7ctab.pdf" class="ico_pdf" title="Table 7c. U.S. regional electricity prices "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=22">7d. U.S.  electricity generation by fuel and sector</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/7dtab.pdf" class="ico_pdf" title="Table 7d. U.S. electricity generation by fuel and sector "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=23">7e. U.S. fuel consumption for electricity generation by sector</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/7etab.pdf" class="ico_pdf" title="Table 7e. U.S. fuel consumption for electricity generation by sector "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=24">8. U.S. renewable energy supply and consumption</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/8tab.pdf" class="ico_pdf" title="Table 8. U.S. renewable energy supply and consumption "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=5">9a. U.S. macroeconomic indicators and CO<sub>2</sub> emissions</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/9atab.pdf" class="ico_pdf" title="Table 9a. U.S. macroeconomic indicators and CO2 emissions "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=4">9b. U.S. regional macroeconomic data</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/9btab.pdf" class="ico_pdf" title="Table 9b. U.S. regional macroeconomic data "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              <tr>
                <td><a href="/outlooks/steo/tables/?tableNumber=28">9c. U.S. regional weather data</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/steo/tables/pdf/9ctab.pdf" class="ico_pdf" title="Table 9c. U.S. regional weather data "><i class="ico pdf"><span>PDF</span></i></a></span></li>
              
              <tr>
                <td><a href="/cfapps/ipdbproject/IEDIndex3.cfm">International petroleum supply, disposition</a><br />
                Query tool for detailed country and regional energy data (monthly, annual)</li>
<?php /* ***** End of Energy Overview Content  ******* -->
<!-- ***** Start of Energy Consumption by Sector Content  ******* */ ?>
            	<h2><i class="ico expand-collapse"></i><a name="annualproj"></a>Annual projections to 2050</b></th>
                <th><?php /* <span class="right">additional formats</span> */ ?></th>
              </tr>
            </thead>
              <tr>
                <td><em><a href="/outlooks/aeo/">Annual Energy Outlook 2017</a></em> (released: January 5, 2017) -- Reference case main 21 tables<br />
                See complete table listing for <a href="/outlooks/aeo/tables_ref.cfm">reference case</a> and <a href="/outlooks/aeo/tables_side.cfm">side cases</a>. <a href="/outlooks/aeo/supplemental_case.cfm"> Supplemental case </a>(released June 26, 2017)</td>
               			<li><span class="formats">Available formats:</span>  &nbsp;</span> </li>
			  <?php /* <tr class="white_first">
                <td>Summary Reference Case Tables</td>
                <td><h2><span class="right"> <a href="/forecasts/aeo/pdf/appa.pdf" class="ico_pdf">PDF</a></span></h2></li>
              <tr class="white_first">
                <td>Year-by-Year Reference Case Tables</td>
                <td><h2><span class="right"> <a href="/forecasts/aeo/excel/yearbyyear.xls">XLS</a> </span></h2></li> */ ?>
               <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=1-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A1. Total energy supply and disposition demand</a> <br /></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_1.xlsx" class="ico_xls" title="Table  A1. Total energy supply and disposition demand "><i class="ico xls"><span>XLS</span></i></a>
                  <?php /* <a href="/outlooks/aeo/pdf/tbla1.pdf" class="ico_pdf">PDF</a> */ ?>
                </span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=2-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A2. Energy consumption by sector and source </a> <br /></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_2.xlsx" class="ico_xls" title="Table  A2. Energy consumption by sector and source  "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla2.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=3-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A3. Energy prices by sector and source</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_3.xlsx" class="ico_xls" title="Table  A3. Energy prices by sector and source "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla3.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=4-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A4. Residential sector key indicators and consumption</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_4.xlsx" class="ico_xls" title="Table  A4. Residential sector key indicators and consumption "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla4.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=5-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A5. Commercial sector key indicators and consumption</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_5.xlsx" class="ico_xls" title="Table  A5. Commercial sector key indicators and consumption "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla5.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=6-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A6. Industrial sector key indicators and consumption</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_6.xlsx" class="ico_xls" title="Table  A6. Industrial sector key indicators and consumption "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla6.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=7-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A7. Transportation sector key indicators and delivered energy consumption</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_7.xlsx" class="ico_xls" title="Table  A7. Transportation sector key indicators and delivered energy consumption "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/er/pdf/tbla7.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=8-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A8. Electricity supply Disposition, prices, and emissions</a></td>
                			<li><span class="formats">Available formats:</span>  <a href="/outlooks/aeo/excel/aeotab_8.xlsx" class="ico_xls" title="Table  A8. Electricity supply Disposition, prices, and emissions "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla8.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=9-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A9. Electricity generating capacity</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_9.xlsx" class="ico_xls" title="Table  A9. Electricity generating capacity "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla9.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=10-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A10. Electricity trade</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_10.xlsx" class="ico_xls" title="Table  A10. Electricity trade "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla10.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=11-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A11. Liquid fuels supply and disposition balance</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_11.xlsx" class="ico_xls" title="Table  A11. Liquid fuels supply and disposition balance "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla11.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=12-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A12. Petroleum product prices</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_12.xlsx" class="ico_xls" title="Table A12. Petroleum product prices "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla12.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=13-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A13. Natural gas supply, disposition, and prices</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_13.xlsx" class="ico_xls" title="Table A13. Natural gas supply, disposition, and prices "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla13.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=14-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A14. Oil and gas supply</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_14.xlsx" class="ico_xls" title="Table A14. Oil and gas supply "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla14.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=15-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A15. Coal supply, disposition, and price</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_15.xlsx" class="ico_xls" title="Table A15. Coal supply, disposition, and price "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla15.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=16-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A16. Renewable energy generating capacity and generation</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_16.xlsx" class="ico_xls" title="Table A16. Renewable energy generating capacity and generation "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla16.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=24-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A17. Renewable energy consumption by sector and source</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_17.xlsx" class="ico_xls" title="Table A17. Renewable energy consumption by sector and source "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla17.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=17-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A18. Carbon dioxide emissions by sector and source</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_18.xlsx" class="ico_xls" title="Table A18. Carbon dioxide emissions by sector and source "><i class="ico xls"><span>XLS</span></i></a> <?php /*<a href="/outlooks/aeo/pdf/tbla18.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=22-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A19. Energy-related carbon dioxide emissions by end-use</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_19.xlsx" class="ico_xls" title="Table A19. Energy-related carbon dioxide emissions by end-use "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla19.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=18-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A20. Macroeconomic indicators</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_20.xlsx" class="ico_xls" title="Table A20. Macroeconomic indicators "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla20.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
              <tr>
                <td><a href="/outlooks/aeo/data/browser/#/?id=19-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A21. International liquids supply disposition summary</a></td>
                			<li><span class="formats">Available formats:</span>   <a href="/outlooks/aeo/excel/aeotab_21.xlsx" class="ico_xls" title="Table A21. International liquids supply disposition summary "><i class="ico xls"><span>XLS</span></i></a> <?php /* <a href="/outlooks/aeo/pdf/tbla21.pdf" class="ico_pdf">PDF</a> */ ?></span></li>
                <?php /* <td><a href="/outlooks/aeo/tables_ref.cfm">Complete list of AEO tables for all projection scenarios</a></td>
                 */ ?>
              
              
<?php /* ***** End of Energy Consumption by Sector Content  ******* -->
<!-- ***** Start of Petroleum Content  ******* */ ?>
            	<h2><i class="ico expand-collapse"></i><a name="intlproj"></a>International projections to 2050</b></th>
                <th style="white-space: nowrap;"><strong><?php /*<span class="right">additional formats</span */ ?></strong></th>
              </tr>
            </thead>
             
<?php /* ***** End of Electricity Content  ******* -->
         </table>
          <table class="contable"> 
            <!-- ***** Start of Energy Overview Content  ******* --> */ ?>
            <?php /*tr>
                <td>Data</td>
                
              </tr
            <!-- ***** End of Energy Overview Content  ******* -->
            <!-- ***** Start of Energy Consumption by Sector Content  ******* --> */ ?>
            
              <tr>
                <td><em><a href="/outlooks/ieo/">International Energy Outlook</a></em>-- Reference Case tables released: September 14, 2017</td>
                <td><a href="/outlooks/ieo/pdf/appa.pdf" class="pdf" title="International Energy Outlook ">
PDF (all tables)</a></td>
              <?php /*			<li><span class="formats">Available formats:</span>  &nbsp;</span></td>*/ 
            
             /* <tr class="white_first">
                <td>Summary Reference Case Tables</td>
                <td><h2><span class="right"> <a href="/forecasts/aeo/pdf/appa.pdf" class="ico_pdf">PDF</a></span></h2></li>
              <tr class="white_first">
                <td>Year-by-Year Reference Case Tables</td>
                <td><h2><span class="right"> <a href="/forecasts/aeo/excel/yearbyyear.xls">XLS</a> </span></h2></li> */ ?>
            <tr class="white_first">
              <td><a href="/outlooks/aeo/data/browser/#/?id=1-IEO2017">A1. World total primary energy consumption by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_1.pdf" class="ico_pdf" title="Table  A1. World total primary energy consumption by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=2-IEO2017">A2. World total energy consumption by region and fuel</a><br /></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_2.pdf" class="ico_pdf" title="Table  A2. World total energy consumption by region and fuel "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=3-IEO2017">A3. World gross domestic product (GDP) by region expressed in purchasing power parity</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_3.pdf" class="ico_pdf" title="Table  A3. World gross domestic product (GDP) by region expressed in purchasing power parity "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=4-IEO2017">A4. World gross domestic product (GDP) by region expressed in market exchange rates</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_4.pdf" class="ico_pdf" title="Table  A4. World gross domestic product (GDP) by region expressed in market exchange rates "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=5-IEO2017">A5. World liquids consumption by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_5.pdf" class="ico_pdf" title="Table  A5. World liquids consumption by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
             <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=6-IEO2017">A6. World natural gas consumption by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_6.pdf" class="ico_pdf" title="Table  A6. World natural gas consumption by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
             <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=7-IEO2017">A7. World coal consumption by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_7.pdf" class="ico_pdf" title="Table  A7. World coal consumption by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
             <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=8-IEO2017">A8. World nuclear energy consumption by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_8.pdf" class="ico_pdf" title="Table  A8. World nuclear energy consumption by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
             <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=9-IEO2017">A9. World consumption of hydroelectricity and other renewable energy by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_9.pdf" class="ico_pdf" title="Table  A9. World consumption of hydroelectricity and other renewable energy by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=10-IEO2017">A10. World carbon dioxide emissions by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_10.pdf" class="ico_pdf" title="Table  A10. World carbon dioxide emissions by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
           <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=11-IEO2017">A11. World carbon dioxide emissions from liquids use by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_11.pdf" class="ico_pdf" title="Table  A11. World carbon dioxide emissions from liquids use by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=12-IEO2017">A12. World carbon dioxide emissions from natural gas use by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_12.pdf" class="ico_pdf" title="Table A12. World carbon dioxide emissions from natural gas use by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=13-IEO2017">A13. World carbon dioxide emissions from coal use by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_13.pdf" class="ico_pdf" title="Table A13. World carbon dioxide emissions from coal use by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <tr>
              <td><a href="/outlooks/aeo/data/browser/#/?id=14-IEO2017">A14. World population by region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/outlooks/ieo/pdf/ieotab_14.pdf" class="ico_pdf" title="Table A14. World population by region "><i class="ico pdf"><span>PDF</span></i></a></span></li>
            <?php /*tr>
              <td>A7. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=7-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Coal Consumption by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_7.xls" class="ico_xls">XLS</a></span></li>
            <!--<tr>
              <td><ul>
                <li>World Coal Consumption by Region 
                  - (million short tons)</li>
              </ul></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/table7_mst.xls" class="ico_xls">XLS</a></span></t></li> -->
            <tr>
              <td>A8. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=8-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Nuclear Energy Consumption by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_8.xls" class="ico_xls">XLS</a></span></li>
            <tr>
              <td>A9. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=9-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Consumption of Hydroelectricity and Other Renewable Energy by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_9.xls" class="ico_xls">XLS</a></span></li>
            <tr>
              <td>A10. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=10-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Carbon Dioxide Emissions by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_10.xls" class="ico_xls">XLS</a></span></li>
            <tr>
              <td>A11. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=11-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Carbon Dioxide Emissions from Liquids Use by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_11.xls" class="ico_xls">XLS</a></span></li>
            <tr>
              <td>A12. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=12-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Carbon Dioxide Emissions from Natural Gas Use by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_12.xls" class="ico_xls">XLS</a></span></li>
            <tr>
              <td>A13. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=13-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Carbon Dioxide Emissions from Coal Use by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_13.xls" class="ico_xls">XLS</a></span></li>
            <tr>
              <td>A14. <a href="/oiaf/aeo/tablebrowser/#release=IEO2013&amp;subject=0-IEO2013&amp;table=14-IEO2013&amp;region=0-0&amp;cases=Reference-d041117">World Population by Region</a></td>
              			<li><span class="formats">Available formats:</span>   <a href="/forecasts/ieo/excel/ieotab_14.xls" class="ico_xls">XLS</a></span></li>
            
            <!-- ***** End of Energy Consumption by Sector Content  ******* -->
            <!-- ***** Start of Petroleum Content  ******* -->
            <!-- ***** End of Electricity Content  ******* --> */ ?>
          </table>









<p>Find statistics on crude oil, gasoline, diesel, propane, jet fuel, ethanol, and other liquid fuels. Click on the blue bars
	below for information on petroleum prices, crude reserves and production, refining and processing, imports/exports, stocks,
	and consumption/sales.</p>
<div class="accordion-head"><h2><i
	<div class="expand-collapse-container">
		<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
		<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
	</div>
	<h2><i class="ico expand-collapse"></i>
		<!-- id="summary --><a name="summary"></a>Summary
	</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_sum_sndw_dcus_nus_w.htm">Weekly supply estimates</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Production, refinery inputs and utilization, stocks, days of supply, imports, exports, and product supplied estimates for crude oil and petroleum products by U.S., PAD District</li>
			<li class="release-schedule">Weekly and 4-week average</li>





			<li class="head"><a href="/dnav/pet/pet_sum_snd_d_nus_mbbl_m_cur.htm">Supply and disposition</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Field production, net production, imports, net receipts, stock changes, net inputs, exports, and product supplied statistics for crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_sum_crdsnd_k_m.htm">U.S. crude oil supply &amp; disposition</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Detailed statistics for crude oil supply, disposition, and ending stocks. Includes statistics for commercial and Strategic Petroleum Reserve sectors</li>





			<li class="head"><a href="/dnav/pet/pet_sum_mkt_dcu_nus_m.htm">Prices, sales volumes &amp; stocks by state</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span></li>
			<li>U.S., PAD District, and state level data includes retail prices, prime supplier sales volumes and stocks</li>





			<li class="head">Petroleum overview</li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/totalenergy/data/monthly/txt/new_merheader.inc'); ?></span> (<a href="/totalenergy/data/monthly/#petroleum">more on petroleum</a>)</li> 
			<li><span class="formats">Available formats:</span>  <a href="/totalenergy/data/monthly/pdf/sec3_3.pdf"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T03.01"><i class="ico csv"><span>CSV</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T03.01&amp;freq=m"><i class="ico xls"><span>XLS</span></i></a></li>






			<li class="head"><a href="http://tonto.eia.gov/cfapps/ipdbproject/IEDIndex3.cfm">Petroleum statistics by country</a></li>
			<li><span class="release-date">Release Date: </span><span class="date">Varies</span></li>
			<li>Query detailed country and regional energy data supply, disposition</li>
			<li class="release-schedule">Annual, selected quarterly, monthly</li>
		</ul>
	</div>
	<?php /* END Summary Content ////////////////*/ ?>




















	<h2><i class="ico expand-collapse"></i><a name="prices"></a>Prices</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/petroleum/gasdiesel/">Gasoline and diesel fuel update</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/gasdiesel/release-date_gdu.inc'); ?></span></li>
			<li>Prices of regular gasoline and on-highway diesel fuel by PAD District.</li> 
			<li class="release-schedule">Weekly</li>





			<li class="head"><a href="/petroleum/heatingoilpropane/">Heating Oil and Propane Update</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsrshopp.inc'); ?></span></li>
			<li>Weekly heating oil and propane prices; October through March..</li>
			<li class="release-schedule">Weekly</li>

			



			<li class="head"><a href="/dnav/pet/pet_pri_gnd_dcus_nus_w.htm">Weekly retail gasoline and on-highway diesel prices</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/gasdiesel/release-date_gdu.inc'); ?></span></li>
			<li>Gasoline prices by grade and formulation and diesel prices by sulfur content for U.S., PAD District, selected states and cities</li>
			<li class="release-schedule">Weekly</li>

					



			<li class="head">Motor gasoline retail prices, U.S. city average</li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/totalenergy/data/monthly/txt/new_merheader.inc'); ?></span></li>
			<li><span class="formats">Available formats:</span>  <a href="/totalenergy/data/monthly/pdf/sec9_6.pdf "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T09.04"><i class="ico csv"><span>CSV</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T09.04&amp;freq=m"><i class="ico xls"><span>XLS</span></i></a></li>

			



			<li class="head"><a href="/totalenergy/data/annual/showtext.cfm?t=ptb0524">Motor gasoline retail prices </a></li>
			<li><span class="formats">Available formats:</span>  <a href="/totalenergy/data/annual/pdf/sec5_59.pdf"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/annual/xls/stb0524.xls"><i class="ico xls"><span>XLS</span></i></a></li>
			<li><span class="release-date">Release Date: </span><span class="date">September 27, 2012</span></li>
			<li>U.S. city average, annual from 1949&#8211;current</li>
			<li class="release-schedule">Annual Energy Review</li>






			<li class="head"><a href="/dnav/pet/pet_pri_spt_s1_d.htm">Spot prices</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Crude oil and petroleum products by selected U.S. and international areas</li>
			<li class="release-schedule">Daily, weekly, monthly, annual</li>





			<li class="head"><a href="/dnav/pet/pet_pri_fut_s1_d.htm">Futures prices (NYMEX)</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Crude oil, motor gasoline, heating oil, and propane</li>
			<li class="release-schedule">Daily, weekly, monthly, annual</li>





			<li class="head"><a href="/dnav/pet/pet_pri_wfr_dcus_nus_w.htm">Weekly heating oil &amp; propane prices</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsrshopp.inc'); ?></span></li>
			<li>Residential and wholesale prices of heating oil and propane by U.S., selected PAD Districts and states</li>
			<li class="release-schedule">Weekly, monthly from October - March</li>





			<li class="head">Refiner petroleum product prices by sales type</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span></li>
			<li>Petroleum product retail and wholesale prices by U.S., PAD District and state</li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pri_refoth_dcu_nus_m.htm">Refiner petroleum product prices by sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_refmg_dcu_nus_m.htm">Refiner gasoline prices by grade, sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_refmg2_d_nus_PTG_dpgal_m.htm">Refiner gasoline prices by formulation, grade, sales type</a></li>
				</ul>
			</li>


	


			<li class="head">Refiner, reseller, and retailer monthly prices (suspended)</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date">May 2, 2011</span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">August 6, 2010</span></li>
			<li>Petroleum product retail and wholesale prices by U.S., PAD District and state</li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pri_allmg_d_nus_PTA_dpgal_m.htm">Gasoline prices by formulation, grade, sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_dist_dcu_nus_m.htm">No. 2 distillate prices by sales type and selected states</a></li>
					<li><a href="/dnav/pet/pet_pri_prop_dcu_nus_m.htm">Propane (consumer grade) prices by sales type</a></li>
					<li><a href="/dnav/pet/pet_pri_resid_dcu_nus_m.htm">Residual fuel oil prices by sales type</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/pet_pri_rac2_dcu_nus_m.htm">Refiner acquisition cost of crude oil</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span></li>
			<li>Domestic, imported, and composite costs by U.S. and PAD Districts</li>





			<li class="head">Domestic crude oil first purchase prices</li>
			<li><span class="release-date">Monthly Release Date: </span><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pri_dfp1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_pri_dfp2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_pri_dfp3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head">F.O.B. costs of imported crude oil</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pri_imc1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_pri_imc2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_pri_imc3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head">Landed costs of imported crude oil</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pri_land1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_pri_land2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_pri_land3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head"><a href="/outlooks/steo/realprices/">Real U.S. petroleum prices (past &amp; projected)</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/outlooks/steo/includes/release-date_steo.inc'); ?></span></li>
			<li>Real and nominal U.S. prices for gasoline, heating oil, diesel fuel, and imported crude oil</li>
			<li class="release-schedule">Monthly, annual; past and projected values</li>
		</ul>
	</div>





















	<h2><i class="ico expand-collapse"></i><a name="crude"></a>Crude reserves and production</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_crd_crpdn_adc_mbbl_m.htm">Crude oil production</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span> by U.S., PAD District and state</span></li>





			<li class="head"><a href="/dnav/pet/pet_crd_api_adc_mbblpd_m.htm">Crude Oil and Lease Condensate Production by API Gravity</a></li>
			<li>Monthly crude oil production by API gravity data collected on Form EIA-914 (Monthly Crude Oil, Lease Condensate, and Natural Gas Production Report)</li>
			<li class="release-schedule">Monthly</li>





			<li class="head"><a href="/energyexplained/images/charts/u.s.tight_oil_production.jpg" class="lightbox">Tight oil production estimates by play</a></li>
			<li><span class="formats">Available formats:</span>  <a href="/energyexplained/data/U.S. tight oil production.xlsx"><i class="ico xls"><span>XLS</span></i></a></li>
			<li><span class="release-date">Release Date: </span><span class="date">Monthly</span></li>
			<li>Estimated monthly production derived from state administrative data</li>
			<li class="release-schedule">Monthly</li>






			<li class="head">Proved reserves, reserves changes, and production</li>
			<li><span class="release-date">Release Date: </span><span class="date">February 13, 2018</span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_crd_pres_dcu_NUS_a.htm">Crude oil</a></li>
					<li><a href="/dnav/pet/pet_crd_cplc_dcu_NUS_a.htm">Crude oil plus lease condensate</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/PET_CRD_NPROD_DCU_NUS_A.htm">Proved nonproducing reserves</a></li>
			<li><span class="release-date">Release Date: </span><span class="date">February 13, 2018</span></li>
			<li>Reported proved reserves of crude oil, lease condensate, and wet natural gas, after lease separation by U.S., region, and state</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_gom_s1_a.htm">Gulf of Mexico Federal Offshore production</a></li>
			<li><span class="release-date">Release Date: </span><span class="date">November 19, 2015</span></li>
			<li>Production of crude oil, natural gas wet after lease separation, natural gas liquids, dry natural gas, and lease condensate</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_drill_s1_m.htm">Crude oil and natural gas drilling activity</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/dnav/pet/includes/petmer-release-date.inc') ?></span></li>
			<li>Rotary rigs in operation, footage drilled, and active well service rig counts</li>
			<li class="release-schedule">Monthly, annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_wellend_s1_m.htm">Crude oil and natural gas exploratory and development wells</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/dnav/pet/includes/petmer-release-date.inc') ?></span></li>
			<li>Exploratory and development wells drilled for crude oil, natural gas and dry holes; total footage drilled</li>
			<li class="release-schedule">Monthly, annual></li>





			<li class="head"><a href="/dnav/pet/pet_crd_wellfoot_s1_a.htm">Footage drilled for crude oil and natural gas wells</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/dnav/pet/includes/petmer-release-date.inc') ?></span></li>
			<li>Footage drilled by exploratory and development wells and by crude oil, natural gas, and dry holes</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_welldep_s1_a.htm">Average depth of crude oil and natural gas wells</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/dnav/pet/includes/petmer-release-date.inc') ?></span></li>
			<li>Average depth of wells drilled by exploratory and development wells and by crude oil, natural gas, and dry holes</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_wellcost_s1_a.htm">Costs of crude oil and natural gas wells drilled</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/dnav/pet/includes/petmer-release-date.inc') ?></span></li>
			<li>Per well and per foot costs of crude oil, natural gas, and dry hole wells</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/dnav/pet/pet_crd_seis_s1_m.htm">Maximum U.S. active seismic crew counts</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/dnav/pet/includes/petmer-release-date.inc') ?></span> by onshore/offshore/Alaska and dimension</li>
			<li class="release-schedule">Monthly</li>





			<li class="head"><a href="/petroleum/production/">Monthly Crude Oil and Natural Gas Production</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/production/includes/release-date_914.inc'); ?></span></li>
			<li>Monthly crude oil and natural gas production data collected on Form EIA-914 (Monthly Crude Oil, Lease Condensate, and Natural Gas Production Report)</li>
			<li class="release-schedule">Monthly</li>





			<li class="head"><a href="/naturalgas/archive/cost_indices_equipment_production/current/coststudy.html">Oil and gas lease equipment and operating costs 1994 Through 2009</a></li>
			<li><span class="release-date">Release Date: </span><span class="date">September 28, 2010</span></li>
			<li>Regional and national oil and gas equipping and operating cost trends.</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/naturalgas/fieldcode/">Oil and gas county code master list</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/naturalgas/fieldcode/includes/release-date_fcml.inc'); ?></span></li>
			<li>Comprehensive listing of U.S. oil and gas field names.</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/petroleum/wells/">Distribution and production of oil &amp; gas wells</a></li>
			<li><span class="release-date">Release Date: </span><span class="date">December 11, 2017</span></li>
			<li>State level tables and graphs</li>
			<li class="release-schedule">Annual</li>
		</ul>
	</div>




















	<h2><i class="ico expand-collapse"></i><a name="refining"></a>Refining and processing</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_pnp_wiup_dcu_nus_w.htm">Weekly inputs &amp; utilization</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Refiner inputs, operable capacity, percent utilization, and refinery and blender net inputs by U.S. and PAD District</li>
			<li class="release-schedule">Weekly, 4-week average</li>





			<li class="head">Weekly production</li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Production of petroleum products by U.S. and PAD District</li>
			<li class="release-schedule">Weekly, 4-week average</span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pnp_wprodrb_dcu_nus_w.htm">Refiner &amp; blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_wprodr_s1_w.htm">Refiner</a></li>
					<li><a href="/dnav/pet/pet_pnp_wprodb_s1_w.htm">Blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_wprode_s1_w.htm">Ethanol plant</a></li>
				</ul>
			</li>





			<li class="head">Net input</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Net input of crude oil and petroleum products by PAD and Refining Districts</li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pnp_inpt_dc_nus_mbbl_m.htm">Refiner & blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_inpt2_dc_nus_mbbl_m.htm">Refiner</a></li>
					<li><a href="/dnav/pet/pet_pnp_inpt3_dc_nus_mbbl_m.htm">Blender</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_unc_dcu_nus_m.htm">Refinery utilization and capacity</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Gross input to crude distillation units, operable capacity and utilization rate by PAD and Refining Districts</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_crq_dcu_nus_m.htm">Crude oil input qualities</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil sulfur content and API</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_dwns_dc_nus_mbblpd_m.htm">Downstream processing of fresh feed input</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Catalytic cracking, catalytic hydrocracking, and delayed and fluid coking by PAD and Refining Districts</li>





			<li class="head">Net production</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Net production of finished petroleum products by PAD and Refining Districts</li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pnp_refp_dc_nus_mbbl_m.htm">Refiner & blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_refp2_dc_nus_mbbl_m.htm">Refiner</a></li>
					<li><a href="/dnav/pet/pet_pnp_refp3_dc_nus_mbbl_m.htm">Blender</a></li>
					<li><a href="/dnav/pet/pet_pnp_oxy_dc_nus_mbbl_m.htm">Oxygenate (ethanol and MTBE)</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_pct_dc_nus_pct_m.htm">Refinery yield</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Percent yield of petroleum products by PAD and Refining Districts</li>





			<li class="head">Refinery Capacity</li>
			<li><span class="release-date">Release Date: </span><span class="date">June 21, 2017</span> by U.S., PAD District and state</li>
			<!-- li><span class="release-date">Annual Release Date:</span></li -->
			<li>				<ul>
					<li><a href="/dnav/pet/pet_pnp_cap1_dcu_nus_a.htm">Number and capacity</a></li>
					<li><a href="/dnav/pet/pet_pnp_capprod_dcu_nus_a.htm">Production capacity</a></li>
					<li><a href="/dnav/pet/pet_pnp_capchg_dcu_nus_a.htm">Downstream charge capacity</a></li>
					<li><a href="/dnav/pet/pet_pnp_capwork_dcu_nus_a.htm">Working storage capacity</a> (historical data 1982 - 2010)</li>
					<li><a href="/dnav/pet/pet_pnp_capshell_dcu_nus_a.htm">Shell storage capacity</a> (historical data 1982 - 2010)</li>
					<li><a href="/dnav/pet/pet_pnp_caprec_dcu_nus_a.htm">Receipts of crude oil by method of transport</a></li>
					<li><a href="/dnav/pet/pet_pnp_capfuel_dcu_nus_a.htm">Fuel consumed at refineries</a></li>
					<li><a href="/dnav/pet/pet_pnp_feedng_k_a.htm">Natural gas used as feedstock for hydrogen production</a></li>
					<li><a href="/petroleum/refinerycapacity/">Refinery capacity report</a></li>
					<li>Refinery capacity data by individual refinery as of January 1, 2017</li> 
					<li><span class="formats">Available formats:</span>  <a href="/petroleum/refinerycapacity/refcap17.xls"><i class="ico xls"><span>XLS</span></i></a></li>
					<li><a href="/totalenergy/data/annual/showtext.cfm?t=ptb0509">Refinery capacity and utilization data, annual 1949 - 2011</a></li> 
					<li><span class="formats">Available formats:</span>  <a href="/totalenergy/data/annual/pdf/sec5_23.pdf"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/annual/xls/stb0509.xls"><i class="ico xls"><span>XLS</span></i></a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/pet_pnp_gp_dc_nus_mbbl_m.htm">Natural gas plant field production</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Net production of petroleum products by PAD and Refining Districts</li>





			<li class="head"><a href="/petroleum/ethanolcapacity/">U.S. fuel ethanol plant production capacity</a></li>
			<li class="release-schedule">Release Date:  June 20, 2017</span></li>
			<li>The U.S. Energy Information Administration released its annual fuel ethanol production capacity report. The new report contains data for all operating U.S. fuel ethanol production plants as of January 1, 2017.</li>
			<li class="release-schedule">Annual</li>





			<li class="head"><a href="/biofuels/biodiesel/production/">Monthly biodiesel production</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/biofuels/biodiesel/production/includes/release-date_biodiesel.inc'); ?></span></li>
			<li>The U.S. Energy Information Administration release showing national and regional monthly biodiesel production. In addition to biodiesel production, data included producer sales, producer stocks, and feedstock inputs.</li>
		</ul>
	</div>

















	<h2><i class="ico expand-collapse"></i><a name="imports"></a>Imports/exports &amp; movements</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_move_wkly_dc_NUS-Z00_mbblpd_w.htm">Weekly imports &amp; exports</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Crude oil and petroleum products by U.S. and PAD District</li>
			<li class="release-schedule">Weekly, 4-week average</li>





			<li class="head"><a href="/dnav/pet/pet_move_wimpc_s1_w.htm">Weekly preliminary crude imports by country of origin</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>U.S. crude oil imports</li>
			<li class="release-schedule">Weekly, 4-week average</li>





			<li class="head"><a href="/dnav/pet/pet_move_imp_dc_NUS-Z00_mbbl_m.htm">Imports by area of entry</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_move_imp2_dc_R10-Z00_mbbl_m.htm">Imports by processing area</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_move_impcus_a2_nus_ep00_im0_mbbl_m.htm">U.S. imports by country of origin</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and petroleum products by country of origin</li>





			<li class="head"><a href="/dnav/pet/pet_move_impcp_a2_r10_ep00_ip0_mbbl_m.htm">PAD District imports by country of origin</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and unfinished oils by country of origin</li>





			<li class="head"><a href="/petroleum/imports/companylevel/">Company level imports</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li>Crude oil and total petroleum imports by the top 15 countries (monthly) and a summary of crude oil imports by company from the Persian Gulf (year-to-date).</li>





			<li class="head"><a href="/dnav/pet/pet_move_res_dc_nus-Z00_mbbl_m.htm">Residual fuel imports by state of entry</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span> by U.S., PAD District, state</li>





			<li class="head"><a href="/dnav/pet/pet_move_ipct_k_m.htm">Percentages of total imported crude oil by API gravity</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span> June 1, 2016</span>





			<li class="head"><a href="/dnav/pet/pet_move_exp_dc_NUS-Z00_mbbl_m.htm">Exports</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span> by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_move_expc_a_EP00_EEX_mbbl_m.htm">Exports by destination</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span> by country of export destination</li>





			<li class="head"><a href="/dnav/pet/pet_move_neti_a_EP00_IMN_mbblpd_m.htm">U.S. net imports by country</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and petroleum products by country and region</li>





			<li class="head">Movements between PAD Districts</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_move_ptb_dc_R20-R10_mbbl_m.htm">By pipeline, tanker, barge, and rail</a></li>
					<li><a href="/dnav/pet/pet_move_pipe_dc_R20-R10_mbbl_m.htm">By pipeline</a></li>
					<li><a href="/dnav/pet/pet_move_tb_dc_R20-R10_mbbl_m.htm">By tanker and barge</a></li>
					<li><a href="/dnav/pet/PET_MOVE_RAIL_A_EPC0_RAIL_MBBL_M.htm">By rail</a></li>
				</ul>
			</li>





			<li class="head"><a href="/dnav/pet/PET_MOVE_RAILNA_A_EPC0_RAIL_MBBL_M.htm">Movements of Crude Oil and Selected Products by Rail</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>





			<li class="head"><a href="/dnav/pet/pet_move_netr_d_r10-z0p_VNR_mbbl_m.htm">Net receipts of crude oil and petroleum products by pipeline, tanker, barge, and rail</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>





			<li class="head">F.O.B. costs of imported crude oil</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span> June 1, 2016</span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_move_imc1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_move_imc2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_move_imc3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>





			<li class="head">Landed costs of imported crude oil</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span></li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_move_land1_k_m.htm">By area</a></li>
					<li><a href="/dnav/pet/pet_move_land2_k_m.htm">By crude stream</a></li>
					<li><a href="/dnav/pet/pet_move_land3_k_m.htm">By API gravity</a></li>
				</ul>
			</li>
		</ul>
	</div>




















	<h2><i class="ico expand-collapse"></i><a name="stocks"></a>Stocks</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_stoc_wstk_dcu_nus_w.htm">Weekly stocks</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Crude oil and petroleum products by U.S. and PAD District</li>
			<li class="release-schedule">Weekly</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_ts_dcu_nus_m.htm">Stocks of motor gasoline, distillate fuel oil, residual fuel oil, propane, and propylene</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Stocks of selected petroleum products by U.S., PAD District, and sub-PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_typ_d_nus_SAE_mbbl_m.htm">Stocks by type</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and petroleum products by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_st_dc_NUS_mbbl_m.htm">Refinery, bulk terminal, and natural gas plant stocks by state</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and petroleum products</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_ref_dc_nus_mbbl_m.htm">Refinery stocks</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Crude oil and petroleum products by U.S., PAD and Refining District</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_cu_s1_m.htm">Crude oil stocks at tank farms & pipelines</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span> by U.S., PAD District, and Cushing, Oklahoma</li>





			<li class="head"><a href="/dnav/pet/pet_stoc_gp_dcu_nus_m.htm">Natural gas plant stocks</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span></li>
			<li>Petroleum products by U.S., PAD and Refining District</li>





			<li class="head"><a href="/petroleum/storagecapacity/">Working and net available shell storage capacity</a></li>
			<li><span class="release-date">Release Date: </span><span class="date">November 30, 2017</span></li>
			<li>Working and net available shell storage capacity as of March 31, 2017 is the U.S. Energy Information Administration's (EIA) report containing semi-annual storage capacity data. It includes three tables detailing working and net available shell storage capacity by facility type, product, and PAD District as of March 31.</li>
			<li class="release-schedule">Semi-annual</li>
		</ul>
	</div>










	<h2><i class="ico expand-collapse"></i><a name="consumption"></a>Consumption/sales</h2>
	<div class="accordion-content">
		<ul>
			<li class="head"><a href="/dnav/pet/pet_cons_wpsup_k_w.htm">U.S. weekly product supplied</a></li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/weekly/includes/release-date_wpsr.inc'); ?></span></li>
			<li>Measures the disappearance of petroleum products from primary sources; approximately represents consumption of petroleum products.</li>
			<li class="release-schedule">Weekly, 4-week average</li>





			<li class="head"><a href="/dnav/pet/pet_cons_psup_dc_nus_mbbl_m.htm">Product supplied</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/monthly/includes/release-date_psm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/supply/annual/volume1/includes/release-date_psa.inc'); ?></span> by U.S., PAD District</li>





			<li class="head"><a href="/dnav/pet/pet_cons_prim_dcu_nus_m.htm">Prime supplier sales volumes</a></li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/prime/includes/release-date_psr.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">April 1, 2013</span></li>
			<li>Sales of petroleum products by refiners, gas plant operators, importers and large inter-state distributors into the final local markets of consumption by U.S., PAD District, State</li>





			<li class="head">Refiner sales volumes</li>
			<li><span class="release-date">Monthly Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/marketing/monthly/includes/release-date_pmm.inc'); ?></span></li>
			<li><span class="release-date">Annual Release Date: </span><span class="date">June 1, 2016</span> by U.S., PAD District, state and sales type</li>
			<li>				<ul>
					<li><a href="/dnav/pet/pet_cons_refmg_d_nus_VTR_mgalpd_m.htm">Motor gasoline</a></li>
					<li><a href="/dnav/pet/pet_cons_refres_d_nus_VTR_mgalpd_m.htm">Residual fuel oil and No. 4 fuel oil</a></li>
					<li><a href="/dnav/pet/pet_cons_refoth_d_nus_VTR_mgalpd_m.htm">Other products</a></li>
				</ul>
			</li>





			<li class="head">Sales of fuel oil and kerosene</li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/fueloilkerosene/includes/release-date_foks.inc'); ?></span> by U.S., PAD District, state</li>
			<!-- li><span class="release-date">annual Release Date: </span></li -->
			<li>				<ul>
					<li><a href="/dnav/pet/pet_cons_821dst_dcu_nus_a.htm">Distillate by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821rsd_dcu_nus_a.htm">Residual fuel oil by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821ker_dcu_nus_a.htm">Kerosene by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821use_dcu_nus_a.htm">Distillate and kerosene by end use</a></li>
				</ul>
			</li>





			<li class="head">Adjusted sales of fuel oil and kerosene</li>
			<li class="include"><span class="release-date">Release Date: </span><span class="date"><?php include('css_rehab/archive/petroleum/fueloilkerosene/includes/release-date_foks.inc'); ?></span> by U.S., PAD District, state</li>
			<!-- li><span class="release-date">annual Release Date:</span></li -->
			<li>				<ul>
					<li><a href="/dnav/pet/pet_cons_821dsta_dcu_nus_a.htm">Distillate by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821rsda_dcu_nus_a.htm">Residual fuel oil by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821kera_dcu_nus_a.htm">Kerosene by end use</a></li>
					<li><a href="/dnav/pet/pet_cons_821usea_dcu_nus_a.htm">Distillate and kerosene by end use</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>