<div class="l-row header report-details">
    <div class="l-two-third-col">
        <h1>Annual Energy Review</h1>
        <div class="release-dates">Superseded -- see MER for key annual tables</div>
    </div>
    <div class="l-one-third-col gradient do-not-print">
        <span class="form-wrapper-outer">
            <h4>Annual Energy Review archives</h4>
            <span class="form-wrapper-inner">
                <form name="form" id="form">
                    <label>Year:</label>
                    <select name="jumpMenu" size="1" id="jumpMenu" style="width:80px">
                    <option value="/totalenergy/data/annual/archive/038411.pdf" selected="selected">2011</option>
                    <option value="/totalenergy/data/annual/archive/038410.pdf">2010</option>
                    <option value="/totalenergy/data/annual/archive/038409.pdf">2009</option>
                    <option value="/totalenergy/data/annual/archive/038408.pdf">2008</option>
                    <option value="/totalenergy/data/annual/archive/">all archives</option>
                    </select>				 
                    <input type="button" name="go_button" class="button" align="absmiddle" id= "go_button" value="Go" onclick="MM_jumpMenuGo('jumpMenu','parent',1)" />
                </form>
            </span>
        </span>
    </div>
</div>
