<table class="basic_table" >
<caption>Primary energy overview <br/><span class="units">quadrillion Btu</span></caption>
<?php /* Primary Energy Overview: Table 1.1 - September 2014 Release */ ?>
	<thead>
        <tr>
          <th>January to June</th>
          <th>2014</th>
          <th>2013</th>
          <th>2012</th>
        </tr>
	</thead>
    <tbody>
<?php /* Primary Energy Overview: Production - Year-to-Year data */ ?>
      <tr class="section">
          <td><b>Production</b></td>
          <td>&nbsp;</td>			 
          <td>&nbsp;</td>
          <td>&nbsp;</td>
     </tr>
      <tr class="indented">
          <td>Fossil fuel</td>
          <td>33.311</td>			 
          <td>31.405</td>
          <td>30.672</td>
     </tr>
      <tr class="indented">
          <td>Nuclear electric power</td>
          <td>4.040</td>			 
          <td>4.002</td>
          <td>3.992</td>
     </tr>
      <tr class="indented">
          <td>Renewable energy</td>
          <td>4.938</td>			 
          <td>4.756</td>
          <td>4.600</td>
     </tr>
      <tr class="indented">
          <td>Total</td>
          <td>42.290</td>			 
          <td>40.163</td>
          <td>39.265</td>
     </tr>
<?php /* Primary Energy Overview: Consumption - Year-to-Year data */ ?>
      <tr class="section">
          <td><b>Consumption</b></td>
          <td>&nbsp;</td>			 
          <td>&nbsp;</td>
          <td>&nbsp;</td>
     </tr>
      <tr class="indented">
          <td>Fossil fuel</td>
          <td>40.639</td>			 
          <td>39.579</td>
          <td>38.522</td>
     </tr>
      <tr class="indented">
          <td>Nuclear electric power</td>
          <td>4.040</td>			 
          <td>4.002</td>
          <td>3.992</td>
     </tr>
      <tr class="indented">
          <td>Renewable energy</td>
          <td>4.910</td>			 
          <td>4.760</td>
          <td>4.553</td>
     </tr>
      <tr class="indented">
          <td>Total</td>
          <td>49.659</td>			 
          <td>48.426</td>
          <td>47.140</td>
     </tr>
<?php /* Primary Energy Overview: Consumption - Year-to-Year data reference link */ ?>
    <tfoot>
    <tr>
    <td colspan="4">Source: U.S. Energy Information Administration, <a href="/totalenergy/data/monthly/pdf/sec1_3.pdf"><i>Monthly Energy Review</i>&nbsp;&mdash;&nbsp;Table 1.1</a></td>
    </tr>
    </tfoot>
	</tbody>
</table>


