
<?php /* <?php include ('side_data.php') ; ?> */ ?>
<?php /* Changes this month box */ ?>
<span class="grey_side blue_top side_list_nocolumn">
	<h4>Changes this month</h4>
	<ul>
	<li>	<a href="/totalenergy/data/monthly/pdf/sec10_8.pdf">Biodiesel Overview</a> (Table 10.4) now incorporates monthly biodiesel production data from Form EIA-22M.</li>
	<li>	<a href="/totalenergy/data/monthly/pdf/sec13_5.pdf">Approximate Heat Content of Coal and Coal Coke</a> (Table A5) has revised coal heat content values.</li>
	<li><a href="/totalenergy/data/monthly/whatsnew.cfm">See list of previous changes</a></li>
	</ul>
</span>
<?php /* Annual Energy Review energy flow box */ ?>
<span class="grey_side green_top side_list_nocolumn" style="padding:5px">
<?php /*<h4>Primary Energy</h4>*/ ?>
<?php include ('mer2_chart.php') ; ?>
<?php /*<a href="/totalenergy/data/annual/diagram1.cfm"><img src="/totalenergy/data/annual/images/overview_flow_2010_xsmall.jpg" alt="Total Energy graph image"></a>*/ ?>
</span>
	<?php /*		<ul>
			<li>&nbsp;<a href="/totalenergy/data/annual/pecss_diagram.cfm">U.S. Primary Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram1.cfm">Total Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram2.cfm">Petroleum</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram3.cfm">Natural Gas</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram4.cfm">Coal</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram5.cfm">Electricity</a></li>
			</ul>
          </span>
           Start of Energy Perspectives Content box 
          <span class="grey_side green_top side_list_nocolumn">
              <h4><a href="/totalenergy/data/annual/perspectives.cfm">Energy Perspectives</a></h4>
<a href="/totalenergy/data/annual/perspectives.cfm"><img src="/totalenergy/data/annual/images/ep_2010_xsmall.jpg" alt="Energy Perspectives image"></a>
          </span>
           End of Energy Perspectives Content box  */ ?>