<?php $what = 'multifuel'; ?>
        <?php include ('about/new/whatsnew_sitewide.php') ; ?>
        <?php /* Start of New in Energy Source -->
            <div class="secondary">
<ul>
<li class="head"><h2>What's New in Total Energy?</h2></li>
                
            
            <p><a href="monthly.php"><strong>Monthly Energy Review &rsaquo;</strong></a>
            <p><em>released January  2011</em></p>
            <a href="annual.php"><strong>Annual Energy Review 2009 &rsaquo;</strong></a>
            <p><em>released August 2010</em></p>
            <a href="annual.php"><strong>Consumption, Price, and Expenditure Estimates &rsaquo;</strong></a>
            <p><em>complete release of final 2009 data: end of June 2011</em></p></span>
            <!-- Start of Graphics side items */ ?>
              
<?php /* Start of Energy Flow Content box */ ?>
          <span class="grey_side green_top side_list_nocolumn">
             <h4 style="color:#000">Diagrams</h2></li>
             <li class="sub-head"><strong>Energy flows</strong></li>
<?php /* <a href="/totalenergy/data/monthly/pdf/flow/primary_energy.pdf"> */ ?><img src="/totalenergy/data/monthly/pdf/flow/overview_flow_xsmall.jpg" alt="Total Energy diagram image"><?php /*</a>*/ ?>
			<dl>
			<dt>&nbsp;</dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/total_energy.pdf" class="ico_pdf">Total energy</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/petroleum.pdf" class="ico_pdf">Petroleum</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/natural_gas.pdf" class="ico_pdf">Natural gas</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/coal.pdf" class="ico_pdf">Coal</a></dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/electricity.pdf" class="ico_pdf">Electricity</a></dt>
			</dl>           
			<p><strong>Primary energy consumption</strong></li>
			<img src="/totalenergy/data/monthly/pdf/flow/css_2013_xsmall.jpg" alt="Consumption by Source and Sector diagram image">
			<dl>
			<dt>&nbsp;</dt>
			<dt>&nbsp;<a style="font-weight:normal" href="/totalenergy/data/monthly/pdf/flow/css_2013_energy.pdf" class="ico_pdf">Consumption by source and sector</a></dt>
			</dl>
          </span>
          <?php /* End of Energy Flow Content box */ ?>
<span class="blue_side">
          <h4 class="q_side"><a href="/tools/faqs/faq.php?id=85&t=1">How much energy does a person use in a year? &rsaquo;</a></h2></li>
          <p><a href="/tools/faqs/#generalenergy" width="240"><br />
          See all general energy FAQs  &rsaquo;</a></p>
        </span>
              
             <!-- <p>State Energy Data</p>
              
<img src="" width="200"><a href=""></a>-->
        <?php /* Energy Explained Promo */ ?>
        <p><a href="/energyexplained/index.php?page=us_energy_home"><img src="/energyexplained/images/section-banners/usa_energy_facts.jpg"  alt="Energy Explained - U.S. Energy Facts" width="240"/></a></p>