<?php /* Start of Total Energy - Annual */ ?>
<?php /*h1>Annual Energy Review -- <i>in transition</i></h1*/ ?>
<?php /* Start of release date of AER */ ?>
<?php /*cfinclude template="includes/release_date.cfm"*/ ?>
<?php /* End of release date of AER */ ?>
<?php /*
<p class="dat">Release Date: October 19, 2011  <a href="pdf/aer.pdf" class="ico_pdf">PDF</a>  |  <a href="/totalenergy/reports.cfm">previous editions</a><br />
Next Update: August 2012<br /></p>
*/ ?>
<?php /* Start of commended out of feature by CA2 on 8/23/2012 */ ?>
<?php /*
<div class="feature"> 
<span style="padding:10px;">
As of March 15, 2012, the data in Table 1.14 for fiscal years 2003-2010 are revised. Please see Appendix A in &quot;<a href="/analysis/requests/federallands/">Sales of Fossil Fuels Produced from Federal and Indian Lands, FY 2003 through FY 2011</a>&quot; for the revised data.</span>
</div>
*/ ?>
<?php /* End of commended out of feature by CA2 on 8/23/2012 */ ?>
<div class="tie_correction">
<p>EIA has expanded the 			<li class="release-schedule">Monthly Energy Review</em> (MER) to include annual data as far back as 1949 for those data tables that are found in both the 			<li class="release-schedule">Annual Energy Review</em> (AER) and the <a href="/totalenergy/data/monthly/">MER</a><?php /*allowing monthly <b>and</b> annual data to appear in the same place*/ ?>
. In the list of tables below, grayed-out table numbers now go to MER tables that contain data series for 1949 forward. New <a href="/totalenergy/data/browser/" Title="view in Total Energy Browser">INTERACTIVE tables and graphs</a> have also been added.</p>
<?php /*&nbsp;&nbsp;<a href="about_the_data.cfm">About the data</a*/ ?></div>

<?php /*div class="notice">
<h3>Ongoing changes to the AER and MER will improve data access and findability</h3>
<p>EIA is improving the way data are provided in the 			<li class="release-schedule">Annual Energy Review</em> (AER) and the 			<li class="release-schedule">Monthly Energy Reveiw</em> (MER).                    
</p>
<ul>
<li>Review <a style="color:#189bd7" href="changes">chronology of changes to date</a></li>
<li>See <a style="color:#189bd7" href="crosswalk">crosswalk of planned changes</a></li>
<li>Sign up for <a style="color:#189bd7;" href="/tools/emailupdates/#press?value=mer">email updates  </a></li>
<li>Send <a style="color:#189bd7;" href="mailto:totalenergy@eia.gov">feedback to EIA on this project</a></li>
<li>Watch <a style="color:#189bd7;" href="video">video explaining how to use new data browser</a></li>
</ul>

<a class="show">Read more...</a>
<div class="more">
<br />     
<p>Over the next XX months EIA is changing the dissemination of AER and MER data.  All of the data that is now available will continue to be available, possibly in a different location or not continusously updated.  </p>
<p>One goal is to combine the monthly and annual data series, some back as far as 1949, in one place, rather than having  the series in two separate places.  For those series, the most current annual data (as well as monthly data) can be reached using the links below. Data that only appear in the AER will be provided below, although the series possibly will not be updated.</p>
</div>
</div*/ ?>
<p><h3>Data categories</h3></p>
<div class="accordion">
<div class="expand-collapse-container">
<span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
<span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
</div>
<table class="contable">
<col><col><col style="background-color: #cccccc;">
<?php /* ***** Start of Energy Overview Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i>
<a name="summary"></a>Energy overview</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>

<td class="no_bdr2"></li>
</tr*/ ?>

<li><span style="color:#CCC">1.0</span>&nbsp;&nbsp;Energy flow<!--,&nbsp;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/flow/total_energy.pdf" class="ico_pdf" title="Table 1.0  Energy flow ">
GRAPH</a></span></li>
<td class="no_bdr2"></li>


<li><span style="color:#CCC">1.1</span>&nbsp;&nbsp;Primary energy overview<!--, 1949&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec1_3.pdf" class="ico_pdf" title="Table 1.1  Primary energy overview "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T01.01&freq=a" class="ico_xls" title="Table 1.1  Primary energy overview "><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T01.01" class="ico_csv" title="Table 1.1  Primary energy overview "><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T01.01#/?f=A&start=200001" title="Table 1.1  Primary energy overview  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>


<li><span style="color:#CCC">1.2</span>&nbsp;&nbsp;Primary energy production by source<!--, 1949&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec1_5.pdf" class="ico_pdf" title="Table 1.2  Primary energy production by source "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T01.02&freq=a" class="ico_xls" title="Table 1.2  Primary energy production by source "><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T01.02" class="ico_csv" title="Table 1.2  Primary energy production by source "><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T01.02#/?f=A&start=200001" title="Table 1.2  Primary energy production by source  - view in Total Energy Browser">INTERACTIVE</a></span></li>


<li><span style="color:#CCC">1.3</span>&nbsp;&nbsp;Primary energy consumption estimates by source<!--, 1949&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec1_7.pdf" class="ico_pdf" title="Table 1.3  Primary energy consumption estimates by source "><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T01.03&freq=a" class="ico_xls" title="Table 1.3  Primary energy consumption estimates by source "><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T01.03" class="ico_csv" title="Table 1.3  Primary energy consumption estimates by source "><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T01.03#/?f=A&start=200001" title="Table 1.3  Primary energy consumption estimates by source  - view in Total Energy Browser">INTERACTIVE</a></span></li>


<td colspan="2" class="no_bdr"><span style="color:#CCC">1.4</span>&nbsp;&nbsp;Primary energy trade by source<!--, 1949&ndash;<script>DataEndYear(0);</script>--></li>


<td class="no_bdr">&nbsp;&nbsp;&nbsp;Imports by source</li>
<td class="no_bdr"><span class="right"> 
<a href="/totalenergy/data/monthly/pdf/sec1_10.pdf" class="ico_pdf" title="Table 1.4  Imports by source "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T01.04A" class="ico_xls" title="Table 1.4  Imports by source "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T01.04A" class="ico_csv" title="Table 1.4  Imports by source "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T01.04A#/?f=A&start=200001" title="Table 1.4  Imports by source  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">&nbsp;&nbsp;&nbsp;Exports by source</li>

<td class="no_bdr2"><span class="right">
<a href="/totalenergy/data/monthly/pdf/sec1_11.pdf" class="ico_pdf" title="Table 1.4  Exports by source "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T01.04B" class="ico_xls" title="Table 1.4  Exports by source "><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T01.04B" class="ico_csv" title="Table 1.4  Exports by source "><i class="ico csv"><span>CSV</span></i></a></span></li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T01.04B#/?f=A&start=200001" title="Table 1.4  Exports by source  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<?php /*tr>
<li>1.4b&nbsp;&nbsp;Primary Energy Exports, 1949&ndash;<script>DataEndYear(0);</script> <i>by Source and Total Net Imports</i></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/browser/xls.cfm?tbl=T01.04B&freq=a" class="ico_xls">XLS</a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T01.04B" class="ico_csv">CSV</a></span></li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T01.04B#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span></li>
</tr*/ ?>

<li><span style="color:#CCC">1.5</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0105"*/ ?>Energy consumption, expenditures, and emissions indicators estimates<!--, 1949&ndash;<script>DataEndYear(1);</script>--></a>
<?php /*br /><span class="right" style="margin-top:5px">(Find the latest annual data in 
<a 
href="/totalenergy/data/browser/index.cfm?tbl=T01.05#/?f=A">Total Energy Browser 1.5</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec1_17.pdf" class="ico_pdf" title="Table 1.5  Energy consumption, expenditures, and emissions indicators estimates "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T01.07&freq=m" class="ico_xls" title="Table 1.5  Energy consumption, expenditures, and emissions indicators estimates "><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T01.07" class="ico_csv" title="Table 1.5  Energy consumption, expenditures, and emissions indicators estimates "><i class="ico csv"><span>CSV</span></i></a>
<a href="/totalenergy/data/monthly/pdf/sec1_16.pdf" class="ico_pdf" title="Table 1.5  Energy consumption, expenditures, and emissions indicators estimates ">
GRAPH</a></span>
</li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T01.07#/?f=M&start=200001" title="Table 1.5  Energy consumption, expenditures, and emissions indicators estimates  - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li>1.6&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0106">State-level energy consumption, expenditure, and prices estimates, <script>DataEndYear(2);</script></a>
<?php /*br /><span class="right" style="margin-top:5px">(Find the latest annual data in 
<a 
href="/totalenergy/data/browser/index.cfm?tbl=T01.06#/?f=A">Total Energy Browser 1.6</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec1_15.pdf" class="ico_pdf" title="Table 1.6  State-level energy consumption, expenditure, and prices estimates, 2010"><i class="ico pdf"><span>PDF</span></i></a>
<a href="xls/stb0106.xls" class="ico_xls" title="Table 1.6  State-level energy consumption, expenditure, and prices estimates, 2010"><i class="ico xls"><span>XLS</span></i></a>
<a href="pdf/sec1_14.pdf" class="ico_pdf" title="Table 1.6  State-level energy consumption, expenditure, and prices estimates, 2010">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">1.7</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0107"*/ ?>Heating degree-days by month<!--, 1949&ndash;<script>DataEndYear(1);</script>--></a>
<?php /*br /><span class="right" style="margin-top:5px">(Find the latest annual data in 
<a 
href="/totalenergy/data/browser/index.cfm?tbl=T01.07#/?f=A">Total Energy Browser 1.7</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec1_20.pdf" class="ico_pdf" title="Table 1.7  Heating degree-days by month"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T01.09&amp;freq=m" class="ico_xls" title="Table 1.7  Heating degree-days by month"><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T01.09" class="ico_csv" title="Table 1.7  Heating degree-days by month"><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T01.09#/?f=A&start=200001" title="Table 1.7  Heating degree-days by month - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">1.8</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0108"*/ ?>Cooling degree-days by month<!--, 1949&ndash;<script>DataEndYear(1);</script>--></a>
<?php /*br /><span class="right" style="margin-top:5px">(Find the latest annual data in 
<a 
href="/totalenergy/data/browser/index.cfm?tbl=T01.08#/?f=A">Total Energy Browser 1.8</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec1_21.pdf" class="ico_pdf" title="Table 1.8  Cooling degree-days by month"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T01.10&amp;freq=m" class="ico_xls" title="Table 1.8  Cooling degree-days by month"><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T01.10" class="ico_csv" title="Table 1.8  Cooling degree-days by month"><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T01.10#/?f=A&start=200001" title="Table 1.8  Cooling degree-days by month - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">1.9</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0109"*/ ?>Heating degree-days by Census division<!--, 1949&ndash;
<script>DataEndYear(1);</script>--></a></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec1_20.pdf" class="ico_pdf" title="Table 1.9  Heating degree-days by Census division"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T01.09&amp;freq=m" class="ico_xls" title="Table 1.9  Heating degree-days by Census division"><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T01.09" class="ico_csv" title="Table 1.9  Heating degree-days by Census division"><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T01.09#/?f=A&start=200001" title="Table 1.9  Heating degree-days by Census division - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">1.10</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0110"*/ ?>Cooling degree-days by Census division<!--, 1949&ndash;
<script>DataEndYear(1);</script>--></a></li>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec1_21.pdf" class="ico_pdf" title="Table 1.10  Cooling degree-days by Census division"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T01.10&amp;freq=m" class="ico_xls" title="Table 1.10  Cooling degree-days by Census division"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T01.10" class="ico_csv" title="Table 1.10  Cooling degree-days by Census division"><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T01.10#/?f=A&start=200001" title="Table 1.10  Cooling degree-days by Census division - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">1.11</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0111"*/ ?>U.S. government energy consumption by agency, fiscal years <!--1975&ndash;
<script>DataEndYear(1);</script>--></a></li>
<?php /*td><span class="right"><a href="pdf/sec1_25.pdf" class="ico_pdf">PDF</a> 
<a href="xls/stb0111.xls" class="ico_xls">XLS</a> 
<a href="pdf/sec1_24.pdf" class="ico_pdf">GRAPH</a></span>
</td*/ ?>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec2_14.pdf" class="ico_pdf" title="Table 1.11  U.S. government energy consumption by agency, fiscal years"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T02.07&freq=m" class="ico_xls" title="Table 1.11  U.S. government energy consumption by agency, fiscal years"><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T02.07" class="ico_csv" title="Table 1.11  U.S. government energy consumption by agency, fiscal years"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T02.07#/?f=M&start=200001" title="Table 1.11  U.S. government energy consumption by agency, fiscal years - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">1.12</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0112"*/ ?>U.S. government energy consumption by source<!--,<br /> 
Fiscal years 1975&ndash;
<script>DataEndYear(1);</script></a>--></li>
<?php /*td><span class="right"><a href="pdf/sec1_27.pdf" class="ico_pdf">PDF</a> 
<a href="xls/stb0112.xls" class="ico_xls">XLS</a> 
<a href="pdf/sec1_26.pdf" class="ico_pdf">GRAPH</a></span>
</td*/ ?>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec2_15.pdf" class="ico_pdf" title="Table 1.12  U.S. government energy consumption by source"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=T02.08&freq=m" class="ico_xls" title="Table 1.12  U.S. government energy consumption by source"><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=T02.08" class="ico_csv" title="Table 1.12  U.S. government energy consumption by source"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=T02.08#/?f=M&start=200001" title="Table 1.12  U.S. government energy consumption by source - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li>1.13&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0113">U.S. government energy consumption by agency and source, fiscal years 
<script>DataEndYear(9);</script>, 
<script>DataEndYear(2);</script>, and 
<script>DataEndYear(1);</script></a>
</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec1_29.pdf" class="ico_pdf" title="Table 1.13  U.S. government energy consumption by agency and source, fiscal years 2003, 2010, and 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0113.xls" class="ico_xls" title="Table 1.13  U.S. government energy consumption by agency and source, fiscal years 2003, 2010, and 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec1_28.pdf" class="ico_pdf" title="Table 1.13  U.S. government energy consumption by agency and source, fiscal years 2003, 2010, and 2011">
GRAPH</a></span>
</li>

<li>1.14&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0114">Sales of fossil fuels produced on Federal and American Indian Lands,
<br /> 
fiscal years 2003&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec1_31.pdf" class="ico_pdf" title="Table 1.15  in physical units">PDF</a> 
<a href="xls/stb0114.xls" class="ico_xls" title="Table 1.15  in physical units">XLS</a> 
<a href="pdf/sec1_30.pdf" class="ico_pdf" title="Table 1.15  in physical units">GRAPH</a></span>
</li>


<td colspan="2" class="no_bdr"><span style="color:#CCC">1.15</span>&nbsp;&nbsp;Non-combustion use of fossil fuels<!--, 1949&ndash;<script>DataEndYear(0);</script>--></li>


<td class="no_bdr">&nbsp;&nbsp;&nbsp;in physical units</li>
<td class="no_bdr"><span class="right"> 
<a href="/totalenergy/data/monthly/pdf/sec1_22.pdf" class="ico_pdf" title="Table 1.15  in physical units"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.php?tbl=T01.11A" class="ico_xls" title="Table 1.15  in physical units"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.php?tbl=T01.11A" class="ico_csv" title="Table 1.15  in physical units"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/totalenergy/data/browser/index.php?tbl=T01.11A#/?f=A&amp;start=200001" title="Table 1.15  in physical units - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">&nbsp;&nbsp;&nbsp;in quadrillion Btu</li>

<td class="no_bdr2"><span class="right">
<a href="/totalenergy/data/monthly/pdf/sec1_23.pdf" class="ico_pdf" title="Table 1.15  in quadrillion Btu"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.php?tbl=T01.11B" class="ico_xls" title="Table 1.15  in quadrillion Btu"><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.php?tbl=T01.11B" class="ico_csv" title="Table 1.15  in quadrillion Btu"><i class="ico csv"><span>CSV</span></i></a></span></li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T01.11B#/?f=A&start=200001" title="Table 1.15  in quadrillion Btu - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<?php /*tr>
<li><span style="color:#CCC">1.15</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb0115"*/ ?><!--Non-combustion use of fossil fuels--><!--, 1980&ndash;
<script>DataEndYear(1);</script></a>--></li>
<?php /*td><span class="right"><a href="pdf/sec1_33.pdf" class="ico_pdf">PDF</a> 
<a href="xls/stb0115.xls" class="ico_xls">XLS</a> 
<a href="pdf/sec1_32.pdf" class="ico_pdf">GRAPH</a></span>
</td

			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec1_22.pdf" class="ico_pdf">PDF</a> <a href="/totalenergy/data/browser/xls.php?tbl=T01.11A&amp;freq=m" class="ico_xls">XLS</a> <a href="/totalenergy/data/browser/csv.php?tbl=T01.11A" class="ico_csv">CSV</a></span></li>
<li><span class="beta"><a href="/totalenergy/data/browser/index.php?tbl=T01.11A#/?f=A&amp;start=200001 - view in Total Energy Browser">INTERACTIVE</a></span></li>
         
</tr */ ?>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote1.pdf" class="ico_pdf">PDF</a></span>
</li>

</tr*/ ?>
<?php /* ***** End of Energy Overview Content  ******* */ ?>
<?php /* ***** Start of Energy Consumption by Sector Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="consumption"></a>Energy consumption by sector</b></th>
<th></th>
<th></th>

</thead>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li><span style="color:#CCC">2.0</span>&nbsp;&nbsp;Primary energy consumption by source and sector<!--, <script>DataEndYear(1);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/flow/css_2016_energy.pdf" class="ico_pdf" title="Table 2.0  Primary energy consumption by source and sector ">
GRAPH</a></span></li>

<li><span style="color:#CCC">2.1a</span>&nbsp;&nbsp;Energy consumption estimates by sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec2_3.pdf" class="ico_pdf" title="Table 2.1a  Energy consumption estimates by sector "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T02.01" class="ico_xls" title="Table 2.1a  Energy consumption estimates by sector "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T02.01" class="ico_csv" title="Table 2.1a  Energy consumption estimates by sector "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T02.01#/?f=A&start=200001" title="Table 2.1a  Energy consumption estimates by sector  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>


<li><span style="color:#CCC">2.1b</span>&nbsp;&nbsp;Residential sector energy consumption estimates<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec2_5.pdf" class="ico_pdf" title="Table 2.1b  Residential sector energy consumption estimates "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T02.02" class="ico_xls" title="Table 2.1b  Residential sector energy consumption estimates "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T02.02" class="ico_csv" title="Table 2.1b  Residential sector energy consumption estimates "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T02.02#/?f=A&start=200001" title="Table 2.1b  Residential sector energy consumption estimates  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">2.1c</span>&nbsp;&nbsp;Commercial sector energy consumption estimates<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec2_7.pdf" class="ico_pdf" title="Table 2.1c  Commercial sector energy consumption estimates "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T02.03" class="ico_xls" title="Table 2.1c  Commercial sector energy consumption estimates "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T02.03" class="ico_csv" title="Table 2.1c  Commercial sector energy consumption estimates "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T02.03#/?f=A&start=200001" title="Table 2.1c  Commercial sector energy consumption estimates  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">2.1d</span>&nbsp;&nbsp;Industrial sector energy consumption estimates<!--, 1949&ndash;
<script>DataEndYear(0);</script>-->
<br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec2_9.pdf" class="ico_pdf" title="Table 2.1d  Industrial sector energy consumption estimates "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T02.04" class="ico_xls" title="Table 2.1d  Industrial sector energy consumption estimates "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T02.04" class="ico_csv" title="Table 2.1d  Industrial sector energy consumption estimates "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T02.04#/?f=A&start=200001" title="Table 2.1d  Industrial sector energy consumption estimates  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">2.1e</span>&nbsp;&nbsp;Transportation sector energy consumption estimates<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec2_11.pdf" class="ico_pdf" title="Table 2.1e  Transportation sector energy consumption estimates "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T02.05" class="ico_xls" title="Table 2.1e  Transportation sector energy consumption estimates "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T02.05" class="ico_csv" title="Table 2.1e  Transportation sector energy consumption estimates "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T02.05#/?f=A&start=200001" title="Table 2.1e  Transportation sector energy consumption estimates  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">2.1f</span>&nbsp;&nbsp;Electric power sector energy consumption<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec2_13.pdf" class="ico_pdf" title="Table 2.1f  Electric power sector energy consumption "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T02.06" class="ico_xls" title="Table 2.1f  Electric power sector energy consumption "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T02.06" class="ico_csv" title="Table 2.1f  Electric power sector energy consumption "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T02.06#/?f=A&start=200001" title="Table 2.1f  Electric power sector energy consumption  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>2.2&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0202">Manufacturing energy consumption for all purposes, 
<script>DataEndYear(6)</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_13.pdf" class="ico_pdf" title="Table 2.2  Manufacturing energy consumption for all purposes, 2006"><i class="ico pdf"><span>PDF</span></i></a>
<a href="xls/stb0202.xls" class="ico_xls" title="Table 2.2  Manufacturing energy consumption for all purposes, 2006"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec2_12.pdf" class="ico_pdf" title="Table 2.2  Manufacturing energy consumption for all purposes, 2006">
GRAPH</a></span>
</li>

<li>2.3&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0203">Manufacturing energy consumption for heat, power, and electricity generation<br /> 
by end use, <script>DataEndYear(6)</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_15.pdf" class="ico_pdf" title="Table 2.3  Manufacturing energy consumption for heat, power, and electricity generation by end use, 2006"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0203.xls" class="ico_xls" title="Table 2.3  Manufacturing energy consumption for heat, power, and electricity generation by end use, 2006"><i class="ico xls"><span>XLS</span></i></a>
<a href="pdf/sec2_14.pdf" class="ico_pdf" title="Table 2.3  Manufacturing energy consumption for heat, power, and electricity generation by end use, 2006">
GRAPH</a></span>
</li>

<li>2.4&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0204">Household energy consumption by Census region, selected years,&nbsp;1978&ndash;
<script>DataEndYear(3)</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_17.pdf" class="ico_pdf" title="Table 2.4  Household energy consumption by Census region, selected years, 1978– 2009"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0204.xls" class="ico_xls" title="Table 2.4  Household energy consumption by Census region, selected years, 1978– 2009"><i class="ico xls"><span>XLS</span></i></a>
<a href="pdf/sec2_16.pdf" class="ico_pdf" title="Table 2.4  Household energy consumption by Census region, selected years, 1978– 2009">
GRAPH</a></span>
</li>

<li>2.5&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0205">Household energy consumption and expenditures by end use  and energy source, 
selected years, 1978&ndash;<script>DataEndYear(7)</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_19.pdf" class="ico_pdf" title="Table 2.5  Household energy consumption and expenditures by end use and energy source, selected years, 1978–2005"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0205.xls" class="ico_xls" title="Table 2.5  Household energy consumption and expenditures by end use and energy source, selected years, 1978–2005"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec2_18.pdf" class="ico_pdf" title="Table 2.5  Household energy consumption and expenditures by end use and energy source, selected years, 1978–2005">
GRAPH</a></span>
</li>

<li>2.6&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0206">Household end uses: fuel types and appliances and electronics, selected years, 
1978&ndash;<script>DataEndYear(3)</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_21.pdf" class="ico_pdf" title="Table 2.6  Household end uses: fuel types and appliances and electronics, selected years, 1978–2009"><i class="ico pdf"><span>PDF</span></i></a>
<a href="xls/stb0206.xls" class="ico_xls" title="Table 2.6  Household end uses: fuel types and appliances and electronics, selected years, 1978–2009"><i class="ico xls"><span>XLS</span></i></a>
<a href="pdf/sec2_20.pdf" class="ico_pdf" title="Table 2.6  Household end uses: fuel types and appliances and electronics, selected years, 1978–2009">
GRAPH</a></span>
</li>

<li>2.7&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0207">Type of heating in occupied housing units, selected years, 1950&ndash;
<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_23.pdf" class="ico_pdf" title="Table 2.7  Type of heating in occupied housing units, selected years, 1950– 2009"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0207.xls" class="ico_xls" title="Table 2.7  Type of heating in occupied housing units, selected years, 1950– 2009"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec2_22.pdf" class="ico_pdf" title="Table 2.7  Type of heating in occupied housing units, selected years, 1950– 2009">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">2.8</span>&nbsp;&nbsp;Motor vehicle mileage, fuel consumption, and fuel economy<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec1_19.pdf" class="ico_pdf" title="Table 2.8  Motor vehicle mileage, fuel consumption, and fuel economy"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T01.08" class="ico_xls" title="Table 2.8  Motor vehicle mileage, fuel consumption, and fuel economy"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T01.08" class="ico_csv" title="Table 2.8  Motor vehicle mileage, fuel consumption, and fuel economy"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T01.08#/?f=A&start=200001" title="Table 2.8  Motor vehicle mileage, fuel consumption, and fuel economy - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>2.9&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0209">Commercial buildings consumption by energy source, selected years, 1979&ndash;
<script>DataEndYear(9);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_27.pdf" class="ico_pdf" title="Table 2.9  Commercial buildings consumption by energy source, selected years, 1979– 2003"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0209.xls" class="ico_xls" title="Table 2.9  Commercial buildings consumption by energy source, selected years, 1979– 2003"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec2_26.pdf" class="ico_pdf" title="Table 2.9  Commercial buildings consumption by energy source, selected years, 1979– 2003">
GRAPH</a></span>
</li>

<li>2.10&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0210">Commercial buildings energy consumption and expenditure indicators, selected years, 
1979&ndash;<script>DataEndYear(9);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_29.pdf" class="ico_pdf" title="Table 2.10  Commercial buildings energy consumption and expenditure indicators, selected years, 1979–2003"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0210.xls" class="ico_xls" title="Table 2.10  Commercial buildings energy consumption and expenditure indicators, selected years, 1979–2003"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec2_28.pdf" class="ico_pdf" title="Table 2.10  Commercial buildings energy consumption and expenditure indicators, selected years, 1979–2003">
GRAPH</a></span>
</li>

<li>2.11&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0211">Commercial buildings electricity consumption by end use, 
<script>DataEndYear(9);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec2_31.pdf" class="ico_pdf" title="Table 2.11  Commercial buildings electricity consumption by end use, 2003"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0211.xls" class="ico_xls" title="Table 2.11  Commercial buildings electricity consumption by end use, 2003"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec2_30.pdf" class="ico_pdf" title="Table 2.11  Commercial buildings electricity consumption by end use, 2003">
GRAPH</a></span>
</li>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote2.pdf" class="ico_pdf">PDF</a></span>
</li>

</tr*/ ?>
<?php /* ***** End of Energy Consumption by Sector Content  ******* */ ?>
<?php /* ***** Start of Financial Indicators Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="financial"></a>Financial indicators</b></th>
<th></th>
<th></th>

</thead>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li>3.1&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0301">Fossil fuel production prices, 1949&ndash;
<script>DataEndYear(1)</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_3.pdf" class="ico_pdf" title="Table 3.1  Fossil fuel production prices, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0301.xls" class="ico_xls" title="Table 3.1  Fossil fuel production prices, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_2.pdf" class="ico_pdf" title="Table 3.1  Fossil fuel production prices, 1949– 2011 ">
GRAPH</a></span>
</li>

<li>3.2&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0302">Value of fossil fuel production, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_5.pdf" class="ico_pdf" title="Table 3.2  Value of fossil fuel production, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0302.xls" class="ico_xls" title="Table 3.2  Value of fossil fuel production, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_4.pdf" class="ico_pdf" title="Table 3.2  Value of fossil fuel production, 1949– 2011 ">
GRAPH</a></span>
</li>

<li>3.3&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0303">Consumer price estimates for energy by source, 1970&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_7.pdf" class="ico_pdf" title="Table 3.3  Consumer price estimates for energy by source, 1970– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0303.xls" class="ico_xls" title="Table 3.3  Consumer price estimates for energy by source, 1970– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_6.pdf" class="ico_pdf" title="Table 3.3  Consumer price estimates for energy by source, 1970– 2010 ">
GRAPH</a></span>
</li>

<li>3.4&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0304">Consumer price estimates for energy by end-use sector, 1970&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_9.pdf" class="ico_pdf" title="Table 3.4  Consumer price estimates for energy by end-use sector, 1970– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0304.xls" class="ico_xls" title="Table 3.4  Consumer price estimates for energy by end-use sector, 1970– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_8.pdf" class="ico_pdf" title="Table 3.4  Consumer price estimates for energy by end-use sector, 1970– 2010 ">
GRAPH</a></span>
</li>

<li>3.5&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0305">Consumer expenditure estimates for energy by source, 1970&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_11.pdf" class="ico_pdf" title="Table 3.5  Consumer expenditure estimates for energy by source, 1970– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0305.xls" class="ico_xls" title="Table 3.5  Consumer expenditure estimates for energy by source, 1970– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_10.pdf" class="ico_pdf" title="Table 3.5  Consumer expenditure estimates for energy by source, 1970– 2010 ">
GRAPH</a></span>
</li>

<li>3.6&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0306">Consumer expenditure estimates for energy by end-use sector, 1970&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_13.pdf" class="ico_pdf" title="Table 3.6  Consumer expenditure estimates for energy by end-use sector, 1970– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0306.xls" class="ico_xls" title="Table 3.6  Consumer expenditure estimates for energy by end-use sector, 1970– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_12.pdf" class="ico_pdf" title="Table 3.6  Consumer expenditure estimates for energy by end-use sector, 1970– 2010 ">
GRAPH</a></span>
</li>

<li>3.7&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0307">Value of fossil fuel imports, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_15.pdf" class="ico_pdf" title="Table 3.7  Value of fossil fuel imports, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0307.xls" class="ico_xls" title="Table 3.7  Value of fossil fuel imports, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_14.pdf" class="ico_pdf" title="Table 3.7  Value of fossil fuel imports, 1949– 2011 ">
GRAPH</a></span>
</li>

<li>3.8&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0308">Value of fossil fuel exports, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_17.pdf" class="ico_pdf" title="Table 3.8  Value of fossil fuel exports, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0308.xls" class="ico_xls" title="Table 3.8  Value of fossil fuel exports, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_16.pdf" class="ico_pdf" title="Table 3.8  Value of fossil fuel exports, 1949– 2011">
GRAPH</a></span>
</li>

<li>3.9&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0309">Value of fossil fuel net imports, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_19.pdf" class="ico_pdf" title="Table 3.9  Value of fossil fuel net imports, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0309.xls" class="ico_xls" title="Table 3.9  Value of fossil fuel net imports, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec3_18.pdf" class="ico_pdf" title="Table 3.9  Value of fossil fuel net imports, 1949– 2011">
GRAPH</a></span>
</li>
<?php /* Commented out by CA2 on 9/17/2012 based on AER 2011

<li>3.10&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0310">Major U.S. Energy Companies' Domestic Production<br />and Refining, 1974&ndash;<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_21.pdf" class="ico_pdf">PDF</a> <a href="xls/stb0310.xls" class="ico_xls">XLS</a> <a href="pdf/sec3_20.pdf" class="ico_pdf">GRAPH</a></span>
</li>

<li>3.11&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0311">Major U.S. Energy Companies' Net Income, 1974&ndash;<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_23.pdf" class="ico_pdf">PDF</a> <a href="xls/stb0311.xls" class="ico_xls">XLS</a> <a href="pdf/sec3_22.pdf" class="ico_pdf">GRAPH</a></span>
</li>

<li>3.12&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0312">Major U.S. Energy Companies' Profitability, 1974&ndash;<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_25.pdf" class="ico_pdf">PDF</a> <a href="xls/stb0312.xls" class="ico_xls">XLS</a> <a href="pdf/sec3_24.pdf" class="ico_pdf">GRAPH</a></span>
</li>

<li>3.13&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0313">U.S. Energy Activities by<br />Foreign-Affiliated Companies, 1978&ndash;<script>DataEndYear(6);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec3_27.pdf" class="ico_pdf">PDF</a> <a href="xls/stb0313.xls" class="ico_xls">XLS</a> <a href="pdf/sec3_26.pdf" class="ico_pdf">GRAPH</a></span>
</li>
*/ ?>
<?php /* No section 3 notes: Comment out on 10/05/2011 by CA2

<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote3.pdf" class="ico_pdf">PDF</a></span>
</li>
*/ ?>
<?php /* ***** End of Financial Indicators Content  ******* */ ?>
<?php /* ***** Start of Energy Resources Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="resources"></a>Energy resources</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li>4.1&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0401">Technically recoverable crude oil and natural gas resource estimates, 
<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_3.pdf" class="ico_pdf" title="Table 4.1  Technically recoverable crude oil and natural gas resource estimates, 2009 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0401.xls" class="ico_xls" title="Table 4.1  Technically recoverable crude oil and natural gas resource estimates, 2009 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_2.pdf" class="ico_pdf" title="Table 4.1  Technically recoverable crude oil and natural gas resource estimates, 2009 ">
GRAPH</a></span>
</li>

<li>4.2&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0402">Crude oil and natural gas cumulative production and proved reserves, 1977&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_5.pdf" class="ico_pdf" title="Table 4.2  Crude oil and natural gas cumulative production and proved reserves, 1977– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0402.xls" class="ico_xls" title="Table 4.2  Crude oil and natural gas cumulative production and proved reserves, 1977– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_4.pdf" class="ico_pdf" title="Table 4.2  Crude oil and natural gas cumulative production and proved reserves, 1977– 2010 ">
GRAPH</a></span>
</li>

<li>4.3&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0403">Crude oil, natural gas, and natural gas liquids proved reserves, 1949&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_7.pdf" class="ico_pdf" title="Table 4.3  Crude oil, natural gas, and natural gas liquids proved reserves, 1949– 2010 "><i class="ico pdf"><span>PDF</span></i></a>
<a href="xls/stb0403.xls" class="ico_xls" title="Table 4.3  Crude oil, natural gas, and natural gas liquids proved reserves, 1949– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_6.pdf" class="ico_pdf" title="Table 4.3  Crude oil, natural gas, and natural gas liquids proved reserves, 1949– 2010 ">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">4.4</span>&nbsp;&nbsp;Crude oil and natural gas rotary rigs in operation<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec5_3.pdf" class="ico_pdf" title="Table 4.4  Crude oil and natural gas rotary rigs in operation "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T05.01" class="ico_xls" title="Table 4.4  Crude oil and natural gas rotary rigs in operation "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T05.01" class="ico_csv" title="Table 4.4  Crude oil and natural gas rotary rigs in operation "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T05.01#/?f=A&start=200001" title="Table 4.4  Crude oil and natural gas rotary rigs in operation  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>4.5&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0405">Crude oil and natural gas exploratory and development wells, 1949&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_11.pdf" class="ico_pdf" title="Table 4.5  Crude oil and natural gas exploratory and development wells, 1949– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0405.xls" class="ico_xls" title="Table 4.5  Crude oil and natural gas exploratory and development wells, 1949– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_10.pdf" class="ico_pdf" title="Table 4.5  Crude oil and natural gas exploratory and development wells, 1949– 2010 ">
GRAPH</a></span>
</li>

<li>4.6&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0406">Crude oil and natural gas exploratory wells, 1949&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_13.pdf" class="ico_pdf" title="Table 4.6  Crude oil and natural gas exploratory wells, 1949– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0406.xls" class="ico_xls" title="Table 4.6  Crude oil and natural gas exploratory wells, 1949– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_12.pdf" class="ico_pdf" title="Table 4.6  Crude oil and natural gas exploratory wells, 1949– 2010 ">
GRAPH</a></span>
</li>

<li>4.7&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0407">Crude oil and natural gas development wells, 1949&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_15.pdf" class="ico_pdf" title="Table 4.7  Crude oil and natural gas development wells, 1949– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0407.xls" class="ico_xls" title="Table 4.7  Crude oil and natural gas development wells, 1949– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_14.pdf" class="ico_pdf" title="Table 4.7  Crude oil and natural gas development wells, 1949– 2010 ">
GRAPH</a></span>
</li>
<?php /* Commented out by CA2 on 8/23/2012 */ ?>
<?php /* Table 4.8 removed from AER 2011 publication: Commented out by CA2 on 8/23/2012 */ ?>
<?php /*

<li>4.8&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0408">Costs of Crude Oil and<br />Natural Gas Wells Drilled, 1960&ndash;<script>DataEndYear(4);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_17.pdf" class="ico_pdf">PDF</a> <a href="xls/stb0408.xls" class="ico_xls">XLS</a> <a href="pdf/sec4_16.pdf" class="ico_pdf">GRAPH</a></span>
</li>

<li>4.8&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0408">Crude Oil, Natural Gas,<br />and Natural Gas Liquids Gross Additions to Proved Reserves,<br />and Exploration and Development Expenditures, 1974&ndash;<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_17.pdf" class="ico_pdf">PDF</a> <a href="xls/stb0408.xls" class="ico_xls">XLS</a> <a href="pdf/sec4_16.pdf" class="ico_pdf">GRAPH</a></span>
</li>

<li>4.9&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0409">Major U.S. Energy Companies' Expenditures<br />for Crude Oil and Natural Gas Exploration and<br />Development by Region, 1974&ndash;<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_19.pdf" class="ico_pdf">PDF</a> <a href="xls/stb0409.xls" class="ico_xls">XLS</a> <a href="pdf/sec4_18.pdf" class="ico_pdf">GRAPH</a></span>
</li>
*/ ?>
<?php /* ***************************** */ ?>
<?php /* Section 4 renumber from this point  */ ?>

<li>4.8&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0408">Coal demonstrated reserve base, January 1, 
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_17.pdf" class="ico_pdf" title="Table 4.8  Coal demonstrated reserve base, January 1, 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0408.xls" class="ico_xls" title="Table 4.8  Coal demonstrated reserve base, January 1, 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_16.pdf" class="ico_pdf" title="Table 4.8  Coal demonstrated reserve base, January 1, 2011">
GRAPH</a></span>
</li>

<li>4.9&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0409">Uranium exploration and development drilling, 1949&mdash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_19.pdf" class="ico_pdf" title="Table 4.9  Uranium exploration and development drilling, 1949— 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0409.xls" class="ico_xls" title="Table 4.9  Uranium exploration and development drilling, 1949— 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_18.pdf" class="ico_pdf" title="Table 4.9  Uranium exploration and development drilling, 1949— 2011">
GRAPH</a></span>
</li>

<li>4.10&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0410">Uranium reserves, 
<script>DataEndYear(4);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_21.pdf" class="ico_pdf" title="Table 4.10  Uranium reserves, 2008"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0410.xls" class="ico_xls" title="Table 4.10  Uranium reserves, 2008"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec4_20.pdf" class="ico_pdf" title="Table 4.10  Uranium reserves, 2008">
GRAPH</a></span>
</li>

<li>4.11&nbsp;&nbsp;Concentrating solar resources</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_22.pdf" class="ico_pdf" title="Table 4.11  Concentrating solar resources">
GRAPH</a></span>
</li>

<li>4.12&nbsp;&nbsp;Photovoltaic solar resources</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_23.pdf" class="ico_pdf" title="Table 4.12  Photovoltaic solar resources">
GRAPH</a></span>
</li>

<li>4.13&nbsp;&nbsp;Onshore wind resources</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_24.pdf" class="ico_pdf" title="Table 4.13  Onshore wind resources">
GRAPH</a></span>
</li>

<li>4.14&nbsp;&nbsp;Offshore wind resources</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_25.pdf" class="ico_pdf" title="Table 4.14  Offshore wind resources">
GRAPH</a></span>
</li>

<li>4.15&nbsp;&nbsp;Geothermal resources</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_26.pdf" class="ico_pdf" title="Table 4.15  Geothermal resources">
GRAPH</a></span>
</li>

<li>4.16&nbsp;&nbsp;Biomass resources</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec4_27.pdf" class="ico_pdf" title="Table 4.16  Biomass resources">
GRAPH</a></span>
</li>
<?php /* ***** End of Energy Resources Content  ******* */ ?>
<?php /* ***** Start of Petroleum Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="petroleum"></a>Petroleum and other liquids</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li><span style="color:#CCC">5.0</span>&nbsp;&nbsp;Petroleum Flow<!--,&nbsp;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/flow/petroleum.pdf" class="ico_pdf" title="Table 5.0  Petroleum Flow">
GRAPH</a></span></li>

<li>5.1a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0501a">Petroleum and other liquids overview, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_6.pdf" class="ico_pdf" title="Table 5.1a  Petroleum and other liquids overview, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0501a.xls" class="ico_xls" title="Table 5.1a  Petroleum and other liquids overview, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_4.pdf" class="ico_pdf" title="Table 5.1a  Petroleum and other liquids overview, 1949– 2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">5.1b</span>&nbsp;&nbsp;Petroleum overview<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_3.pdf" class="ico_pdf" title="Table 5.1b  Petroleum overview "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.01" class="ico_xls" title="Table 5.1b  Petroleum overview "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.01" class="ico_csv" title="Table 5.1b  Petroleum overview "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.01#/?f=A&start=200001" title="Table 5.1b  Petroleum overview  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>5.2&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0502">Crude oil production and crude oil well productivity, 1954&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_9.pdf" class="ico_pdf" title="Table 5.2  Crude oil production and crude oil well productivity, 1954– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0502.xls" class="ico_xls" title="Table 5.2  Crude oil production and crude oil well productivity, 1954– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_8.pdf" class="ico_pdf" title="Table 5.2  Crude oil production and crude oil well productivity, 1954– 2011 ">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">5.3</span>&nbsp;&nbsp;Petroleum imports by type<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec3_9.pdf" class="ico_pdf" title="Table 5.3  Petroleum imports by type "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.03B" class="ico_xls" title="Table 5.3  Petroleum imports by type "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.03B" class="ico_csv" title="Table 5.3  Petroleum imports by type "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.03B#/?f=A&start=200001" title="Table 5.3  Petroleum imports by type  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr" colspan="2"><span style="color:#CCC">5.4</span>&nbsp;&nbsp;Petroleum imports by country of origin<!--, 1960&ndash;
<script>DataEndYear(0);</script>--></li>  

<td class="no_bdr">&nbsp;&nbsp;&nbsp;Imports from OPEC countries</li>
<td class="no_bdr"><span class="right"> 
<a href="/totalenergy/data/monthly/pdf/sec3_10.pdf" class="ico_pdf" title="Table 5.4  Imports from OPEC countries "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.03C" class="ico_xls" title="Table 5.4  Imports from OPEC countries "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.03C" class="ico_csv" title="Table 5.4  Imports from OPEC countries "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.03C#/?f=A&start=200001" title="Table 5.4  Imports from OPEC countries  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">&nbsp;&nbsp;&nbsp;Imports from non-OPEC countries</li>
<td class="no_bdr2"><span class="right">
<a href="/totalenergy/data/monthly/pdf/sec3_11.pdf" class="ico_pdf" title="Table 5.4  Imports from non-OPEC countries "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.03D" class="ico_xls" title="Table 5.4  Imports from non-OPEC countries "><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.03D" class="ico_csv" title="Table 5.4  Imports from non-OPEC countries "><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.03D#/?f=A&start=200001" title="Table 5.4  Imports from non-OPEC countries  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.5</span>&nbsp;&nbsp;Petroleum exports by type<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_9.pdf" class="ico_pdf" title="Table 5.5  Petroleum exports by type "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.03B" class="ico_xls" title="Table 5.5  Petroleum exports by type "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.03B" class="ico_csv" title="Table 5.5  Petroleum exports by type "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.03B#/?f=A&start=200001" title="Table 5.5  Petroleum exports by type  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>5.6&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0506">Petroleum exports by country of destination, 1960&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_17.pdf" class="ico_pdf" title="Table 5.6  Petroleum exports by country of destination, 1960– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0506.xls" class="ico_xls" title="Table 5.6  Petroleum exports by country of destination, 1960– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_16.pdf" class="ico_pdf" title="Table 5.6  Petroleum exports by country of destination, 1960– 2011">
GRAPH</a></span>
</li>

<li>5.7&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0507">Petroleum net imports by country of origin, 1960&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_19.pdf" class="ico_pdf" title="Table 5.7  Petroleum net imports by country of origin, 1960– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0507.xls" class="ico_xls" title="Table 5.7  Petroleum net imports by country of origin, 1960– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_18.pdf" class="ico_pdf" title="Table 5.7  Petroleum net imports by country of origin, 1960– 2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">5.8</span>&nbsp;&nbsp;Refinery and blender net inputs and net production<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec3_5.pdf" class="ico_pdf" title="Table 5.8  Refinery and blender net inputs and net production"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.02" class="ico_xls" title="Table 5.8  Refinery and blender net inputs and net production"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.02" class="ico_csv" title="Table 5.8  Refinery and blender net inputs and net production"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.02#/?f=A&start=200001" title="Table 5.8  Refinery and blender net inputs and net production - view in Total Energy Browser">INTERACTIVE</a></span>
</li>


<li>5.9&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0509">Refinery capacity and utilization, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_23.pdf" class="ico_pdf" title="Table 5.9  Refinery capacity and utilization, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0509.xls" class="ico_xls" title="Table 5.9  Refinery capacity and utilization, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_22.pdf" class="ico_pdf" title="Table 5.9  Refinery capacity and utilization, 1949– 2011">
GRAPH</a></span>
</li>

<li>5.10&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0510">Natural gas plant liquids production, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_25.pdf" class="ico_pdf" title="Table 5.10  Natural gas plant liquids production, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0510.xls" class="ico_xls" title="Table 5.10  Natural gas plant liquids production, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_24.pdf" class="ico_pdf" title="Table 5.10  Natural gas plant liquids production, 1949– 2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">5.11</span>&nbsp;&nbsp;Petroleum products supplied by type<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec3_15.pdf" class="ico_pdf" title="Table 5.11  Petroleum products supplied by type"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.05" class="ico_xls" title="Table 5.11  Petroleum products supplied by type"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.05" class="ico_csv" title="Table 5.11  Petroleum products supplied by type"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.05#/?f=A&start=200001" title="Table 5.11  Petroleum products supplied by type - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.12</span>&nbsp;&nbsp;Heat content of petroleum products supplied<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_17.pdf" class="ico_pdf" title="Table 5.12  Heat content of petroleum products supplied"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.06" class="ico_xls" title="Table 5.12  Heat content of petroleum products supplied"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.06" class="ico_csv" title="Table 5.12  Heat content of petroleum products supplied"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.05#/?f=A&start=200001" title="Table 5.12  Heat content of petroleum products supplied - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.13a</span>&nbsp;&nbsp;Petroleum consumption estimates: residential and commercial sectors<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_19.pdf" class="ico_pdf" title="Table 5.13a  Petroleum consumption estimates: residential and commercial sectors"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.07A" class="ico_xls" title="Table 5.13a  Petroleum consumption estimates: residential and commercial sectors"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.07A" class="ico_csv" title="Table 5.13a  Petroleum consumption estimates: residential and commercial sectors"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.07A#/?f=A&start=200001" title="Table 5.13a  Petroleum consumption estimates: residential and commercial sectors - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.13b</span>&nbsp;&nbsp;Petroleum consumption estimates: industrial sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_20.pdf" class="ico_pdf" title="Table 5.13b  Petroleum consumption estimates: industrial sector"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.07B" class="ico_xls" title="Table 5.13b  Petroleum consumption estimates: industrial sector"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.07B" class="ico_csv" title="Table 5.13b  Petroleum consumption estimates: industrial sector"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.07B#/?f=A&start=200001" title="Table 5.13b  Petroleum consumption estimates: industrial sector - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.13c</span>&nbsp;&nbsp;Petroleum consumption estimates: transportation sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_21.pdf" class="ico_pdf" title="Table 5.13c  Petroleum consumption estimates: transportation sector"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.07C" class="ico_xls" title="Table 5.13c  Petroleum consumption estimates: transportation sector"><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.07C" class="ico_csv" title="Table 5.13c  Petroleum consumption estimates: transportation sector"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.07C#/?f=A&start=200001" title="Table 5.13c  Petroleum consumption estimates: transportation sector - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.13d</span>&nbsp;&nbsp;Petroleum Consumption Estimates: Electric Power Sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_21.pdf" class="ico_pdf" title="Table 5.13d  Petroleum Consumption Estimates: Electric Power Sector"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.07C" class="ico_xls" title="Table 5.13d  Petroleum Consumption Estimates: Electric Power Sector"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.07C" class="ico_csv" title="Table 5.13d  Petroleum Consumption Estimates: Electric Power Sector"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.07C#/?f=A&start=200001" title="Table 5.13d  Petroleum Consumption Estimates: Electric Power Sector - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.14a</span>&nbsp;&nbsp;Heat content of petroleum consumption estimates: residential and commercial sectors<!--, 
1949&ndash;<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_24.pdf" class="ico_pdf" title="Table 5.14a  Heat content of petroleum consumption estimates: residential and commercial sectors"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.08A" class="ico_xls" title="Table 5.14a  Heat content of petroleum consumption estimates: residential and commercial sectors"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.08A" class="ico_csv" title="Table 5.14a  Heat content of petroleum consumption estimates: residential and commercial sectors"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.08A#/?f=A&start=200001" title="Table 5.14a  Heat content of petroleum consumption estimates: residential and commercial sectors - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.14b</span>&nbsp;&nbsp;Heat content of petroleum consumption estimates: industrial sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec3_25.pdf" class="ico_pdf" title="Table 5.14b  Heat content of petroleum consumption estimates: industrial sector"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.08B" class="ico_xls" title="Table 5.14b  Heat content of petroleum consumption estimates: industrial sector"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.08B" class="ico_csv" title="Table 5.14b  Heat content of petroleum consumption estimates: industrial sector"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.08B#/?f=A&start=200001" title="Table 5.14b  Heat content of petroleum consumption estimates: industrial sector - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">5.14c</span>&nbsp;&nbsp;Heat content of petroleum consumption estimates: transportation and electric power 
Sectors<!--, 1949&ndash;<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_26.pdf" class="ico_pdf" title="Table 5.14c  Heat content of petroleum consumption estimates: transportation and electric power Sectors"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.08C" class="ico_xls" title="Table 5.14c  Heat content of petroleum consumption estimates: transportation and electric power Sectors"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.08C" class="ico_csv" title="Table 5.14c  Heat content of petroleum consumption estimates: transportation and electric power Sectors"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.08C#/?f=A&start=200001" title="Table 5.14c  Heat content of petroleum consumption estimates: transportation and electric power Sectors - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>5.15&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0515">Fuel oil and kerosene sales, 1984&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_41.pdf" class="ico_pdf" title="Table 5.15  Fuel oil and kerosene sales, 1984– 2010"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0515.xls" class="ico_xls" title="Table 5.15  Fuel oil and kerosene sales, 1984– 2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_40.pdf" class="ico_pdf" title="Table 5.15  Fuel oil and kerosene sales, 1984– 2010">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">5.16</span>&nbsp;&nbsp;Petroleum primary stocks by type<!--, end of year 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec3_13.pdf" class="ico_pdf" title="Table 5.16  Petroleum primary stocks by type"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T03.04" class="ico_xls" title="Table 5.16  Petroleum primary stocks by type"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T03.04" class="ico_csv" title="Table 5.16  Petroleum primary stocks by type"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T03.04#/?f=A&start=200001" title="Table 5.16  Petroleum primary stocks by type - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>5.17&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0517">Strategic Petroleum Reserve, 1977&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_45.pdf" class="ico_pdf" title="Table 5.17  Strategic Petroleum Reserve, 1977– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0517.xls" class="ico_xls" title="Table 5.17  Strategic Petroleum Reserve, 1977– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_44.pdf" class="ico_pdf" title="Table 5.17  Strategic Petroleum Reserve, 1977– 2011">
GRAPH</a></span>
</li>

<li>5.18&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0518">Crude oil domestic first purchase prices, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_47.pdf" class="ico_pdf" title="Table 5.18  Crude oil domestic first purchase prices, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0518.xls" class="ico_xls" title="Table 5.18  Crude oil domestic first purchase prices, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_46.pdf" class="ico_pdf" title="Table 5.18  Crude oil domestic first purchase prices, 1949– 2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">5.19</span>&nbsp;&nbsp;Landed costs of crude oil imports from selected countries<!--, 1973&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec9_5.pdf" class="ico_pdf" title="Table 5.19  Landed costs of crude oil imports from selected countries"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T09.03" class="ico_xls" title="Table 5.19  Landed costs of crude oil imports from selected countries"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T09.03" class="ico_csv" title="Table 5.19  Landed costs of crude oil imports from selected countries"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T09.03#/?f=A&start=200001" title="Table 5.19  Landed costs of crude oil imports from selected countries - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>5.20&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0520">Value of crude oil imports from selected countries, 1973&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_51.pdf" class="ico_pdf" title="Table 5.20  Value of crude oil imports from selected countries, 1973– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0520.xls" class="ico_xls" title="Table 5.20  Value of crude oil imports from selected countries, 1973– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_50.pdf" class="ico_pdf" title="Table 5.20  Value of crude oil imports from selected countries, 1973– 2011">
GRAPH</a></span>
</li>

<li>5.21&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0521">Crude oil refiner acquisition costs, 1968&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_53.pdf" class="ico_pdf" title="Table 5.21  Crude oil refiner acquisition costs, 1968– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0521.xls" class="ico_xls" title="Table 5.21  Crude oil refiner acquisition costs, 1968– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_52.pdf" class="ico_pdf" title="Table 5.21  Crude oil refiner acquisition costs, 1968– 2011">
GRAPH</a></span>
</li>

<li>5.22&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0522">Refiner sales prices and refiner margins for selected petroleum products, 
<script>DataEndYear(17);</script>&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_55.pdf" class="ico_pdf" title="Table 5.22  Refiner sales prices and refiner margins for selected petroleum products, 1995–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0522.xls" class="ico_xls" title="Table 5.22  Refiner sales prices and refiner margins for selected petroleum products, 1995–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_54.pdf" class="ico_pdf" title="Table 5.22  Refiner sales prices and refiner margins for selected petroleum products, 1995–2011">
GRAPH</a></span>
</li>

<li>5.23&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0523">All sellers sales prices for selected petroleum products,1994&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec5_57.pdf" class="ico_pdf" title="Table 5.23  All sellers sales prices for selected petroleum products,1994– 2010"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0523.xls" class="ico_xls" title="Table 5.23  All sellers sales prices for selected petroleum products,1994– 2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec5_56.pdf" class="ico_pdf" title="Table 5.23  All sellers sales prices for selected petroleum products,1994– 2010">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">5.24</span>&nbsp;&nbsp;Retail motor gasoline and on-highway diesel fuel prices<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
</li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec9_6.pdf" class="ico_pdf" title="Table 5.24  Retail motor gasoline and on-highway diesel fuel prices"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T09.04" class="ico_xls" title="Table 5.24  Retail motor gasoline and on-highway diesel fuel prices"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T09.04" class="ico_csv" title="Table 5.24  Retail motor gasoline and on-highway diesel fuel prices"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T09.04#/?f=A&start=200001" title="Table 5.24  Retail motor gasoline and on-highway diesel fuel prices - view in Total Energy Browser">INTERACTIVE</a></span>
</li>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote5.pdf" class="ico_pdf">PDF</a></span>
</li>

</tr*/ ?>
<?php /* ***** End of Petroleum Content  ******* */ ?>
<?php /* ***** Start of Natural Gas Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="naturalgas"></a>Natural gas</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>
<li>span class="right"><a href="pdf/sec6.pdf" class="pdf">PDF (entire section)</a></span</li>

</tr*/ ?>

<li><span style="color:#CCC">6.0</span>&nbsp;&nbsp;Natural gas flow<!--,&nbsp;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/flow/natural_gas.pdf" class="ico_pdf" title="Table 6.0 Natural gas flow">
GRAPH</a></span></li>

<li><span style="color:#CCC">6.1</span>&nbsp;&nbsp;Natural gas overview<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec4_3.pdf" class="ico_pdf" title="Table 6.1  Natural gas overview"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T04.01" class="ico_xls" title="Table 6.1  Natural gas overview"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T04.01" class="ico_csv" title="Table 6.1  Natural gas overview"><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T04.01#/?f=A&start=200001" title="Table 6.1  Natural gas overview - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li>6.2&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0602">Natural gas production, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec6_7.pdf" class="ico_pdf" title="Table 6.2  Natural gas production, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0602.xls" class="ico_xls" title="Table 6.2  Natural gas production, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec6_6.pdf" class="ico_pdf" title="Table 6.2  Natural gas production, 1949– 2011 ">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">6.3</span>&nbsp;&nbsp;Natural gas imports, exports, and net imports<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec4_4.pdf" class="ico_pdf" title="Table 6.3  Natural gas imports, exports, and net imports "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T04.02" class="ico_xls" title="Table 6.3  Natural gas imports, exports, and net imports "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T04.02" class="ico_csv" title="Table 6.3  Natural gas imports, exports, and net imports "><i class="ico csv"><span>CSV</span></i></a></span>

</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T04.02#/?f=A&start=200001" title="Table 6.3  Natural gas imports, exports, and net imports  - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li>6.4&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0604">Natural gas gross withdrawals and natural gas well productivity, 1960&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec6_11.pdf" class="ico_pdf" title="Table 6.4  Natural gas gross withdrawals and natural gas well productivity, 1960– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0604.xls" class="ico_xls" title="Table 6.4  Natural gas gross withdrawals and natural gas well productivity, 1960– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec6_10.pdf" class="ico_pdf" title="Table 6.4  Natural gas gross withdrawals and natural gas well productivity, 1960– 2011 ">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">6.5</span>&nbsp;&nbsp;Natural gas consumption by sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec4_5.pdf" class="ico_pdf" title="Table 6.5  Natural gas consumption by sector "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T04.03" class="ico_xls" title="Table 6.5  Natural gas consumption by sector "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T04.03" class="ico_csv" title="Table 6.5  Natural gas consumption by sector "><i class="ico csv"><span>CSV</span></i></a></span>

</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T04.03#/?f=A&start=200001" title="Table 6.5  Natural gas consumption by sector  - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">6.6</span>&nbsp;&nbsp;Natural gas underground storage, end of year <!--1954&ndash;
<script>DataEndYear(0);</script>--><br />
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec4_6.pdf" class="ico_pdf" title="Table 6.6  Natural gas underground storage, end of year "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T04.04" class="ico_xls" title="Table 6.6  Natural gas underground storage, end of year "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T04.04" class="ico_csv" title="Table 6.6  Natural gas underground storage, end of year "><i class="ico csv"><span>CSV</span></i></a></span>

</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T04.04#/?f=A&start=200001" title="Table 6.6  Natural gas underground storage, end of year  - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">6.7</span>&nbsp;&nbsp;Natural gas wellhead, city gate, and imports prices<!--, 1949&ndash;
<script>DataEndYear(0);</script>--><br />
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec9_15.pdf" class="ico_pdf" title="Table 6.7  Natural gas wellhead, city gate, and imports prices "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T09.10" class="ico_xls" title="Table 6.7  Natural gas wellhead, city gate, and imports prices "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T09.10" class="ico_csv" title="Table 6.7  Natural gas wellhead, city gate, and imports prices "><i class="ico csv"><span>CSV</span></i></a></span>

</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T09.10#/?f=A&start=200001" title="Table 6.7  Natural gas wellhead, city gate, and imports prices  - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">6.8</span>&nbsp;&nbsp;Natural gas prices by sector<!--, 1967&ndash;
<script>DataEndYear(0);</script>--><br />
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec9_15.pdf" class="ico_pdf" title="Table 6.8  Natural gas prices by secto "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T09.10" class="ico_xls" title="Table 6.8  Natural gas prices by secto "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T09.10" class="ico_csv" title="Table 6.8  Natural gas prices by secto "><i class="ico csv"><span>CSV</span></i></a></span>

</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T09.10#/?f=A&start=200001" title="Table 6.8  Natural gas prices by secto  - view in Total Energy Browser">INTERACTIVE</a></span></li>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote6.pdf" class="ico_pdf">PDF</a></span>
</li>

</tr*/ ?>
<?php /* ***** End of Natural Gas Content  ******* */ ?>
<?php /* ***** Start of Coal Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="coal"></a>Coal</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li><span style="color:#CCC">7.0</span>&nbsp;&nbsp;Coal flow<!--,&nbsp;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/flow/coal.pdf" class="ico_pdf" title="Table 7.0 Coal flow">
GRAPH</a></span></li>

<li><span style="color:#CCC">7.1</span>&nbsp;&nbsp;Coal overview<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec6_3.pdf" class="ico_pdf" title="Table 7.1  Coal overview"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T06.01" class="ico_xls" title="Table 7.1  Coal overview"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T06.01" class="ico_csv" title="Table 7.1  Coal overview"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T06.01#/?f=A&start=200001" title="Table 7.1  Coal overview - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>7.2&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0702">Coal production, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec7_7.pdf" class="ico_pdf" title="Table 7.2  Coal production, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0702.xls" class="ico_xls" title="Table 7.2  Coal production, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec7_6.pdf" class="ico_pdf" title="Table 7.2  Coal production, 1949– 2011 ">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">7.3</span>&nbsp;&nbsp;Coal consumption by sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec6_4.pdf" class="ico_pdf" title="Table 7.3  Coal consumption by sector "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T06.02" class="ico_xls" title="Table 7.3  Coal consumption by sector "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T06.02" class="ico_csv" title="Table 7.3  Coal consumption by sector "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T06.02#/?f=A&start=200001" title="Table 7.3  Coal consumption by sector  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>7.4&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0704">Coal imports by country of origin, 2000&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec7_11.pdf" class="ico_pdf" title="Table 7.4  Coal imports by country of origin, 2000– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0704.xls" class="ico_xls" title="Table 7.4  Coal imports by country of origin, 2000– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec7_10.pdf" class="ico_pdf" title="Table 7.4  Coal imports by country of origin, 2000– 2011 ">
GRAPH</a></span>
</li>


<li>7.5&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0705">Coal exports by country of destination, 1960&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec7_13.pdf" class="ico_pdf" title="Table 7.5  Coal exports by country of destination, 1960– 2011 "><i class="ico pdf"><span>PDF</span></i></a>
<a href="xls/stb0705.xls" class="ico_xls" title="Table 7.5  Coal exports by country of destination, 1960– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec7_12.pdf" class="ico_pdf" title="Table 7.5  Coal exports by country of destination, 1960– 2011 ">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">7.6</span>&nbsp;&nbsp;Coal stocks by sector, end of year <!--1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec6_5.pdf" class="ico_pdf" title="Table 7.6  Coal stocks by sector, end of year "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T06.03" class="ico_xls" title="Table 7.6  Coal stocks by sector, end of year "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T06.03" class="ico_csv" title="Table 7.6  Coal stocks by sector, end of year "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T06.03#/?f=A&start=200001" title="Table 7.6  Coal stocks by sector, end of year  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>7.7&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0707">Coal mining productivity, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec7_17.pdf" class="ico_pdf" title="Table 7.7  Coal mining productivity, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0707.xls" class="ico_xls" title="Table 7.7  Coal mining productivity, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec7_16.pdf" class="ico_pdf" title="Table 7.7  Coal mining productivity, 1949– 2011 ">
GRAPH</a></span>
</li>

<li>7.8&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0708">Coke overview, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec7_19.pdf" class="ico_pdf" title="Table 7.8  Coke overview, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0708.xls" class="ico_xls" title="Table 7.8  Coke overview, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec7_18.pdf" class="ico_pdf" title="Table 7.8  Coke overview, 1949– 2011 ">
GRAPH</a></span>
</li>

<li>7.9&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0709">Coal prices, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec7_21.pdf" class="ico_pdf" title="Table 7.9  Coal prices, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0709.xls" class="ico_xls" title="Table 7.9  Coal prices, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec7_20.pdf" class="ico_pdf" title="Table 7.9  Coal prices, 1949– 2011">
GRAPH</a></span>
</li>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote7.pdf" class="ico_pdf">PDF</a></span></li>

</tr*/ ?>
<?php /* ***** End of Coal Content  ******* */ ?>
<?php /* ***** Start of Electricity Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="electricity"></a>Electricity</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li><span style="color:#CCC">8.0</span>&nbsp;&nbsp;Electricity flow<!--, <script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/flow/electricity.pdf" class="ico_pdf" title="Table 8.0   Electricity flow">
GRAPH</a></span></li>

<li><span style="color:#CCC">8.1</span>&nbsp;&nbsp;Electricity overview<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_3.pdf" class="ico_pdf" title="Table 8.1  Electricity overview"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.01" class="ico_xls" title="Table 8.1  Electricity overview"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.01" class="ico_csv" title="Table 8.1  Electricity overview"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.01#/?f=A&start=200001" title="Table 8.1  Electricity overview - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.2a</span>&nbsp;&nbsp;Electricity net generation: total (all sectors)<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_5.pdf" class="ico_pdf" title="Table 8.2a  Electricity net generation: total (all sectors) "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.02A" class="ico_xls" title="Table 8.2a  Electricity net generation: total (all sectors) "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.02A" class="ico_csv" title="Table 8.2a  Electricity net generation: total (all sectors) "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.02A#/?f=A&start=200001" title="Table 8.2a  Electricity net generation: total (all sectors)  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.2b</span>&nbsp;&nbsp;Electricity net generation: electric power sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_6.pdf" class="ico_pdf" title="Table 8.2b  Electricity net generation: electric power sector "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.02B" class="ico_xls" title="Table 8.2b  Electricity net generation: electric power sector "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.02B" class="ico_csv" title="Table 8.2b  Electricity net generation: electric power sector "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.02B#/?f=A&start=200001" title="Table 8.2b  Electricity net generation: electric power sector  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>8.2c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0802c">Electricity net generation: electric power sector by plant type, 1989&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_10.pdf" class="ico_pdf" title="Table 8.2c  Electricity net generation: electric power sector by plant type, 1989– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0802c.xls" class="ico_xls" title="Table 8.2c  Electricity net generation: electric power sector by plant type, 1989– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_7.pdf" class="ico_pdf" title="Table 8.2c  Electricity net generation: electric power sector by plant type, 1989– 2011 ">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">8.2d</span>&nbsp;&nbsp;Electricity net generation: commercial and industrial sectors<!--, 1989&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_7.pdf" class="ico_pdf" title="Table 8.2d  Electricity net generation: commercial and industrial sectors "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.02C" class="ico_xls" title="Table 8.2d  Electricity net generation: commercial and industrial sectors "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.02C" class="ico_csv" title="Table 8.2d  Electricity net generation: commercial and industrial sectors "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.02C#/?f=A&start=200001" title="Table 8.2d  Electricity net generation: commercial and industrial sectors  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>8.3a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0803a">Useful thermal output at combined-heat-and-power plants: total (all sectors), 1989
&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_13.pdf" class="ico_pdf" title="Table 8.3a  Useful thermal output at combined-heat-and-power plants: total (all sectors), 1989 –2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0803a.xls" class="ico_xls" title="Table 8.3a  Useful thermal output at combined-heat-and-power plants: total (all sectors), 1989 –2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_12.pdf" class="ico_pdf" title="Table 8.3a  Useful thermal output at combined-heat-and-power plants: total (all sectors), 1989 –2011 ">
GRAPH</a></span>
</li>

<li>8.3b&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0803b">Useful thermal output at combined-heat-and-power plants: electric power sector, 
1989&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_14.pdf" class="ico_pdf" title="Table 8.3b  Useful thermal output at combined-heat-and-power plants: electric power sector, 1989–2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0803b.xls" class="ico_xls" title="Table 8.3b  Useful thermal output at combined-heat-and-power plants: electric power sector, 1989–2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_12.pdf" class="ico_pdf" title="Table 8.3b  Useful thermal output at combined-heat-and-power plants: electric power sector, 1989–2011 ">
GRAPH</a></span>
</li>

<li>8.3c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0803c">Useful thermal output at combined-heat-and-power plants: commercial and industrial 
sectors, 1989&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_15.pdf" class="ico_pdf" title="Table 8.3c  Useful thermal output at combined-heat-and-power plants: commercial and industrial sectors, 1989–2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0803c.xls" class="ico_xls" title="Table 8.3c  Useful thermal output at combined-heat-and-power plants: commercial and industrial sectors, 1989–2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_12.pdf" class="ico_pdf" title="Table 8.3c  Useful thermal output at combined-heat-and-power plants: commercial and industrial sectors, 1989–2011 ">
GRAPH</a></span>
</li>

<li>8.4a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0804a">Consumption for electricity generation by energy source: total (all sectors), 
1949&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_17.pdf" class="ico_pdf" title="Table 8.4a  Consumption for electricity generation by energy source: total (all sectors), 1949–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0804a.xls" class="ico_xls" title="Table 8.4a  Consumption for electricity generation by energy source: total (all sectors), 1949–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_16.pdf" class="ico_pdf" title="Table 8.4a  Consumption for electricity generation by energy source: total (all sectors), 1949–2011">
GRAPH</a></span>
</li>

<li>8.4b&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0804b">Consumption for electricity generation by energy source: electric power sector, 
1949&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_18.pdf" class="ico_pdf" title="Table 8.4b  Consumption for electricity generation by energy source: electric power sector, 1949–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0804b.xls" class="ico_xls" title="Table 8.4b  Consumption for electricity generation by energy source: electric power sector, 1949–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_16.pdf" class="ico_pdf" title="Table 8.4b  Consumption for electricity generation by energy source: electric power sector, 1949–2011">
GRAPH</a></span>
</li>

<li>8.4c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0804c">Consumption for electricity generation by energy source: commercial and industrial 
Sectors, 1989&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_19.pdf" class="ico_pdf" title="Table 8.4c  Consumption for electricity generation by energy source: commercial and industrial Sectors, 1989–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0804c.xls" class="ico_xls" title="Table 8.4c  Consumption for electricity generation by energy source: commercial and industrial Sectors, 1989–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_16.pdf" class="ico_pdf" title="Table 8.4c  Consumption for electricity generation by energy source: commercial and industrial Sectors, 1989–2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">8.5a</span>&nbsp;&nbsp;Consumption of combustible fuels for electricity generation: total (all sectors)<!--, 
1949&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_9.pdf" class="ico_pdf" title="Table 8.5a  Consumption of combustible fuels for electricity generation: total (all sectors)"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.03A" class="ico_xls" title="Table 8.5a  Consumption of combustible fuels for electricity generation: total (all sectors)"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.03A" class="ico_csv" title="Table 8.5a  Consumption of combustible fuels for electricity generation: total (all sectors)"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.03A#/?f=A&start=200001" title="Table 8.5a  Consumption of combustible fuels for electricity generation: total (all sectors) - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.5b</span>&nbsp;&nbsp;Consumption of combustible fuels for electricity generation: electric power sector<!--, 
1949&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_10.pdf" class="ico_pdf" title="Table 8.5b  Consumption of combustible fuels for electricity generation: electric power sector"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.03B" class="ico_xls" title="Table 8.5b  Consumption of combustible fuels for electricity generation: electric power sector"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.03B" class="ico_csv" title="Table 8.5b  Consumption of combustible fuels for electricity generation: electric power sector"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.03B#/?f=A&start=200001" title="Table 8.5b  Consumption of combustible fuels for electricity generation: electric power sector - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>8.5c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0805c">Consumption of combustible fuels for electricity generation: electric power sector 
by Plant Type, 1989&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_24.pdf" class="ico_pdf" title="Table 8.5c  Consumption of combustible fuels for electricity generation: electric power sector by Plant Type, 1989–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0805c.xls" class="ico_xls" title="Table 8.5c  Consumption of combustible fuels for electricity generation: electric power sector by Plant Type, 1989–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_21.pdf" class="ico_pdf" title="Table 8.5c  Consumption of combustible fuels for electricity generation: electric power sector by Plant Type, 1989–2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">8.5d</span>&nbsp;&nbsp;Consumption of combustible fuels for electricity generation: commercial and industrial 
sectors<!--, 1989&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_11.pdf" class="ico_pdf" title="Table 8.5d  Consumption of combustible fuels for electricity generation: commercial and industrial sectors"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.03C" class="ico_xls" title="Table 8.5d  Consumption of combustible fuels for electricity generation: commercial and industrial sectors"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.03C" class="ico_csv" title="Table 8.5d  Consumption of combustible fuels for electricity generation: commercial and industrial sectors"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.03C#/?f=A&start=200001" title="Table 8.5d  Consumption of combustible fuels for electricity generation: commercial and industrial sectors - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>8.6a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0806a">Estimated consumption of combustible fuels for useful thermal output at 
combined-heat-and-power plants: total (all sectors), 1989&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_27.pdf" class="ico_pdf" title="Table 8.6a  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: total (all sectors), 1989–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0806a.xls" class="ico_xls" title="Table 8.6a  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: total (all sectors), 1989–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_26.pdf" class="ico_pdf" title="Table 8.6a  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: total (all sectors), 1989–2011">
GRAPH</a></span>
</li>

<li>8.6b&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0806b">Estimated consumption of combustible fuels for useful thermal output at 
combined-heat-and-power plants: electric power sector, 1989&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_28.pdf" class="ico_pdf" title="Table 8.6b  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: electric power sector, 1989–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0806b.xls" class="ico_xls" title="Table 8.6b  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: electric power sector, 1989–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_26.pdf" class="ico_pdf" title="Table 8.6b  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: electric power sector, 1989–2011">
GRAPH</a></span>
</li>

<li>8.6c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0806c">Estimated consumption of combustible fuels for useful thermal output at 
combined-heat-and-power plants: commercial and industrial sectors, 1989&ndash;<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_29.pdf" class="ico_pdf" title="Table 8.6c  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: commercial and industrial sectors, 1989–2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0806c.xls" class="ico_xls" title="Table 8.6c  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: commercial and industrial sectors, 1989–2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_26.pdf" class="ico_pdf" title="Table 8.6c  Estimated consumption of combustible fuels for useful thermal output at combined-heat-and-power plants: commercial and industrial sectors, 1989–2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">8.7a</span>&nbsp;&nbsp;Consumption of combustible fuels for electricity generation and useful thermal output: 
total (all sectors)<!--, 1989&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_13.pdf" class="ico_pdf" title="Table 8.7a  Consumption of combustible fuels for electricity generation and useful thermal output: total (all sectors)"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.04A" class="ico_xls" title="Table 8.7a  Consumption of combustible fuels for electricity generation and useful thermal output: total (all sectors)"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.04A" class="ico_csv" title="Table 8.7a  Consumption of combustible fuels for electricity generation and useful thermal output: total (all sectors)"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.04A#/?f=A&start=200001" title="Table 8.7a  Consumption of combustible fuels for electricity generation and useful thermal output: total (all sectors) - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.7b</span>&nbsp;&nbsp;Consumption of combustible fuels for electricity generation and useful thermal output: 
electric power sector<!--, 1989&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_14.pdf" class="ico_pdf" title="Table 8.7b  Consumption of combustible fuels for electricity generation and useful thermal output: electric power sector"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.04B" class="ico_xls" title="Table 8.7b  Consumption of combustible fuels for electricity generation and useful thermal output: electric power sector"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.04B" class="ico_csv" title="Table 8.7b  Consumption of combustible fuels for electricity generation and useful thermal output: electric power sector"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.04B#/?f=A&start=200001" title="Table 8.7b  Consumption of combustible fuels for electricity generation and useful thermal output: electric power sector - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.7c</span>&nbsp;&nbsp;Consumption of combustible fuels for electricity generation and useful thermal output: 
commercial and industrial sectors<!--, 1989&ndash;<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec7_15.pdf" class="ico_pdf" title="Table 8.7c  Consumption of combustible fuels for electricity generation and useful thermal output: commercial and industrial sectors"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.04C" class="ico_xls" title="Table 8.7c  Consumption of combustible fuels for electricity generation and useful thermal output: commercial and industrial sectors"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.04C" class="ico_csv" title="Table 8.7c  Consumption of combustible fuels for electricity generation and useful thermal output: commercial and industrial sectors"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.04C#/?f=A&start=200001" title="Table 8.7c  Consumption of combustible fuels for electricity generation and useful thermal output: commercial and industrial sectors - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.8</span>&nbsp;&nbsp;Stocks of coal and petroleum: electric power sector, end of year <!--1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec7_17.pdf" class="ico_pdf" title="Table 8.8  Stocks of coal and petroleum: electric power sector, end of year"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.05" class="ico_xls" title="Table 8.8  Stocks of coal and petroleum: electric power sector, end of year"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.05" class="ico_csv" title="Table 8.8  Stocks of coal and petroleum: electric power sector, end of year"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.05#/?f=A&start=200001" title="Table 8.8  Stocks of coal and petroleum: electric power sector, end of year - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.9</span>&nbsp;&nbsp;Electricity end use<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec7_19.pdf" class="ico_pdf" title="Table 8.9  Electricity end use"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T07.06" class="ico_xls" title="Table 8.9  Electricity end use"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T07.06" class="ico_csv" title="Table 8.9  Electricity end use"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T07.06#/?f=A&start=200001" title="Table 8.9  Electricity end use - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">8.10</span>&nbsp;&nbsp;Average retail prices of electricity<!--, 1960&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec9_11.pdf" class="ico_pdf" title="Table 8.10  Average retail prices of electricity"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T09.08" class="ico_xls" title="Table 8.10  Average retail prices of electricity"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T09.08" class="ico_csv" title="Table 8.10  Average retail prices of electricity"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T09.08#/?f=A&start=200001" title="Table 8.10  Average retail prices of electricity - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>8.11a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0811a">Electric net summer capacity: total (all sectors), 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_42.pdf" class="ico_pdf" title="Table 8.11a  Electric net summer capacity: total (all sectors), 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0811a.xls" class="ico_xls" title="Table 8.11a  Electric net summer capacity: total (all sectors), 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_40.pdf" class="ico_pdf" title="Table 8.11a  Electric net summer capacity: total (all sectors), 1949– 2011">
GRAPH</a></span>
</li>

<li>8.11b&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0811b">Electric net summer capacity: electric power sector, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_43.pdf" class="ico_pdf" title="Table 8.11b  Electric net summer capacity: electric power sector, 1949– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0811b.xls" class="ico_xls" title="Table 8.11b  Electric net summer capacity: electric power sector, 1949– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_41.pdf" class="ico_pdf" title="Table 8.11b  Electric net summer capacity: electric power sector, 1949– 2011">
GRAPH</a></span>
</li>

<li>8.11c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0811c">Electric net summer capacity: electric power sector by plant type, 1989&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_44.pdf" class="ico_pdf" title="Table 8.11c  Electric net summer capacity: electric power sector by plant type, 1989– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0811c.xls" class="ico_xls" title="Table 8.11c  Electric net summer capacity: electric power sector by plant type, 1989– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_41.pdf" class="ico_pdf" title="Table 8.11c  Electric net summer capacity: electric power sector by plant type, 1989– 2011">
GRAPH</a></span>
</li>

<li>8.11d&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0811d">Electric net summer capacity: commercial and industrial sectors, 1989&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_45.pdf" class="ico_pdf" title="Table 8.11d  Electric net summer capacity: commercial and industrial sectors, 1989– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0811d.xls" class="ico_xls" title="Table 8.11d  Electric net summer capacity: commercial and industrial sectors, 1989– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_41.pdf" class="ico_pdf" title="Table 8.11d  Electric net summer capacity: commercial and industrial sectors, 1989– 2011">
GRAPH</a></span>
</li>

<li>8.12a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0812a">Electric noncoincident peak load and capacity margin: summer peak period, 1986&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_48.pdf" class="ico_pdf" title="Table 8.12a  Electric noncoincident peak load and capacity margin: summer peak period, 1986– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0812a.xls" class="ico_xls" title="Table 8.12a  Electric noncoincident peak load and capacity margin: summer peak period, 1986– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_46.pdf" class="ico_pdf" title="Table 8.12a  Electric noncoincident peak load and capacity margin: summer peak period, 1986– 2011">
GRAPH</a></span>
</li>

<li>8.12b&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0812b">Electric noncoincident peak load and capacity margin: winter peak period, 1986&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_49.pdf" class="ico_pdf" title="Table 8.12b  Electric noncoincident peak load and capacity margin: winter peak period, 1986– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0812b.xls" class="ico_xls" title="Table 8.12b  Electric noncoincident peak load and capacity margin: winter peak period, 1986– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_47.pdf" class="ico_pdf" title="Table 8.12b  Electric noncoincident peak load and capacity margin: winter peak period, 1986– 2011">
GRAPH</a></span>
</li>

<li>8.13&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0813">Electric utility demand-Side management programs, 1989&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec8_51.pdf" class="ico_pdf" title="Table 8.13  Electric utility demand-Side management programs, 1989– 2010"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0813.xls" class="ico_xls" title="Table 8.13  Electric utility demand-Side management programs, 1989– 2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec8_50.pdf" class="ico_pdf" title="Table 8.13  Electric utility demand-Side management programs, 1989– 2010">
GRAPH</a></span>
</li>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote8.pdf" class="ico_pdf">PDF</a></span>
</li>

</tr*/ ?>
<?php /* ***** End of Electricity Content  ******* */ ?>
<?php /* ***** Start of Nuclear Energy Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="nuclear"></a>Nuclear energy</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li>9.1&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0901">Nuclear generating units, 1955&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec9_3.pdf" class="ico_pdf" title="Table 9.1  Nuclear generating units, 1955– 2011"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0901.xls" class="ico_xls" title="Table 9.1  Nuclear generating units, 1955– 2011"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec9_2.pdf" class="ico_pdf" title="Table 9.1  Nuclear generating units, 1955– 2011">
GRAPH</a></span>
</li>

<li><span style="color:#CCC">9.2</span>&nbsp;&nbsp;Nuclear power plant operations<!--, 1957&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec8_3.pdf" class="ico_pdf" title="Table 9.2  Nuclear power plant operations"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T08.01" class="ico_xls" title="Table 9.2  Nuclear power plant operations"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T08.01" class="ico_csv" title="Table 9.2  Nuclear power plant operations"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T08.01#/?f=A&start=200001" title="Table 9.2  Nuclear power plant operations - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>9.3&nbsp;&nbsp;<a href="showtext.cfm?t=ptb0903">Uranium overview, 1949&ndash;
<script>DataEndYear(1);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec9_7.pdf" class="ico_pdf" title="Table 9.3  Uranium overview, 1949– 2011 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb0903.xls" class="ico_xls" title="Table 9.3  Uranium overview, 1949– 2011 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec9_6.pdf" class="ico_pdf" title="Table 9.3  Uranium overview, 1949– 2011 ">
GRAPH</a></span>
</li>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote9.pdf" class="ico_pdf">PDF</a></span>
</li>

</tr*/ ?>
<?php /* ***** End of Nuclear Energy Content  ******* */ ?>
<?php /* ***** Start of Renewable Energy Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="renewable"></a>Renewable energy</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>

<li><span style="color:#CCC">10.1</span>&nbsp;&nbsp;Renewable energy production and consumption by primary energy source<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec10_3.pdf" class="ico_pdf" title="Table 10.1 Renewable energy production and consumption by primary energy source"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T10.01" class="ico_xls" title="Table 10.1 Renewable energy production and consumption by primary energy source"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T10.01" class="ico_csv" title="Table 10.1 Renewable energy production and consumption by primary energy source"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T10.01#/?f=A&start=200001" title="Table 10.1 Renewable energy production and consumption by primary energy source - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">10.2a</span>&nbsp;&nbsp;Renewable energy consumption: residential and commercial sectors<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec10_4.pdf" class="ico_pdf" title="Table 10.2a  Renewable energy consumption: residential and commercial sectors"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T10.02A" class="ico_xls" title="Table 10.2a  Renewable energy consumption: residential and commercial sectors"><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T10.02A" class="ico_csv" title="Table 10.2a  Renewable energy consumption: residential and commercial sectors"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T10.02A#/?f=A&start=200001" title="Table 10.2a  Renewable energy consumption: residential and commercial sectors - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">10.2b</span>&nbsp;&nbsp;Renewable energy consumption: industrial and transportation sectors<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec10_5.pdf" class="ico_pdf" title="Table 10.2b  Renewable energy consumption: industrial and transportation sectors "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T10.02B" class="ico_xls" title="Table 10.2b  Renewable energy consumption: industrial and transportation sectors "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T10.02B" class="ico_csv" title="Table 10.2b  Renewable energy consumption: industrial and transportation sectors "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T10.02B#/?f=A&start=200001" title="Table 10.2b  Renewable energy consumption: industrial and transportation sectors  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">10.2c</span>&nbsp;&nbsp;Renewable energy consumption: electric power sector<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec10_6.pdf" class="ico_pdf" title="Table 10.2c  Renewable energy consumption: electric power sector "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T10.02C" class="ico_xls" title="Table 10.2c  Renewable energy consumption: electric power sector "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T10.02C" class="ico_csv" title="Table 10.2c  Renewable energy consumption: electric power sector "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T10.02C#/?f=A&start=200001" title="Table 10.2c  Renewable energy consumption: electric power sector  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">10.3</span>&nbsp;&nbsp;Fuel ethanol overview<!--, 1981&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec10_7.pdf" class="ico_pdf" title="Table 10.3  Fuel ethanol overview "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T10.03" class="ico_xls" title="Table 10.3  Fuel ethanol overview "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T10.03" class="ico_csv" title="Table 10.3  Fuel ethanol overview "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T10.03#/?f=A&start=200001" title="Table 10.3  Fuel ethanol overview  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">10.4</span>&nbsp;&nbsp;Biodiesel overview<!--, 2001&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec10_8.pdf" class="ico_pdf" title="Table 10.4  Biodiesel overview "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=T10.04" class="ico_xls" title="Table 10.4  Biodiesel overview "><i class="ico xls"><span>XLS</span></i></a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T10.04" class="ico_csv" title="Table 10.4  Biodiesel overview "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T10.04#/?f=A&start=200001" title="Table 10.4  Biodiesel overview  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>10.5&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1005">Estimated number of alternative-fueled vehicles in use and fuel consumption, 1992&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec10_15.pdf" class="ico_pdf" title="Table 10.5  Estimated number of alternative-fueled vehicles in use and fuel consumption, 1992– 2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1005.xls" class="ico_xls" title="Table 10.5  Estimated number of alternative-fueled vehicles in use and fuel consumption, 1992– 2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec10_14.pdf" class="ico_pdf" title="Table 10.5  Estimated number of alternative-fueled vehicles in use and fuel consumption, 1992– 2010 ">
GRAPH</a></span>
</li>

<li>10.6&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1006">Solar thermal collector shipments by type, price, and trade, 1974&ndash;
<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec10_17.pdf" class="ico_pdf" title="Table 10.6  Solar thermal collector shipments by type, price, and trade, 1974– 2009 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1006.xls" class="ico_xls" title="Table 10.6  Solar thermal collector shipments by type, price, and trade, 1974– 2009 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec10_16.pdf" class="ico_pdf" title="Table 10.6  Solar thermal collector shipments by type, price, and trade, 1974– 2009 ">
GRAPH</a></span>
</li>

<li>10.7&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1007">Solar thermal collector shipments by market sector, end use, and type, 2000&ndash;
<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec10_19.pdf" class="ico_pdf" title="Table 10.7  Solar thermal collector shipments by market sector, end use, and type, 2000– 2009 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1007.xls" class="ico_xls" title="Table 10.7  Solar thermal collector shipments by market sector, end use, and type, 2000– 2009 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec10_18.pdf" class="ico_pdf" title="Table 10.7  Solar thermal collector shipments by market sector, end use, and type, 2000– 2009 ">
GRAPH</a></span>
</li>

<li>10.8&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1008">Photovoltaic cell and module shipments by type, trade, and prices, 1982&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec10_21.pdf" class="ico_pdf" title="Table 10.8  Photovoltaic cell and module shipments by type, trade, and prices, 1982– 2010"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1008.xls" class="ico_xls" title="Table 10.8  Photovoltaic cell and module shipments by type, trade, and prices, 1982– 2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec10_20.pdf" class="ico_pdf" title="Table 10.8  Photovoltaic cell and module shipments by type, trade, and prices, 1982– 2010">
GRAPH</a></span>
</li>

<li>10.9&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1009">Photovoltaic cell and module shipments by sector and end use, 1989&ndash;
<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec10_23.pdf" class="ico_pdf" title="Table 10.9  Photovoltaic cell and module shipments by sector and end use, 1989– 2010"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1009.xls" class="ico_xls" title="Table 10.9  Photovoltaic cell and module shipments by sector and end use, 1989– 2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec10_22.pdf" class="ico_pdf" title="Table 10.9  Photovoltaic cell and module shipments by sector and end use, 1989– 2010">
GRAPH</a></span>
</li>
<?php /*tr>
<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote10.pdf" class="ico_pdf">PDF</a></span>
</li>

</tr*/ ?>
<?php /* ***** End of Renewable Energy Content  ******* */ ?>
<?php /* ***** Start of Environment Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="environment"></a>Environment</h2>
	<div class="accordion-content">
		<ul>
<?php /*tr>
<li>Topic</li>


</tr*/ ?>
<?php /* Commented out by CA2 on 9/18/2012 based on AER 2011

<li>11.1&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1101">Emissions of Greenhouse Gases, 1990&ndash;<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_3.pdf" class="ico_pdf">PDF</a> <a href="xls/stb1101.xls" class="ico_xls">XLS</a> <a href="pdf/sec11_2.pdf" class="ico_pdf">GRAPH</a></span>
</li>
*/ ?>
<?php /* Section 11 renumber from this point  */ ?>

<?php /* Commented out browser version of 11.1 - 11.2e until released in MER  */ ?>
<?php /*tr>
<td class="no_bdr" colspan="2">11.1&nbsp;&nbsp;Carbon Dioxide Emissions From Energy Consumption by Source<br />
Selected Years, 1949&ndash;<script>DataEndYear(0);</script></li>  

<td class="no_bdr">Consumption by Source</li>

<td class="no_bdr">
<span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.01" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.01" class="ico_csv">CSV</a>
</span>
</li>

<li>
<span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.01#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a>
</span>
</li>

<td class="no_bdr2">Consumption From Biomass</li>

<td class="no_bdr2"><span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.07" class="ico_xls">XLS</a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.07" class="ico_csv">CSV</a> 
</span></li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.07#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>



<td class="no_bdr" colspan="2">11.2a&nbsp;&nbsp;Carbon Dioxide Emissions From Energy Consumption:<br />
Residential Sector, Selected Years, 1949&ndash;<script>DataEndYear(0);</script></li>  

<td class="no_bdr">Emissions From Energy Consumption</li>

<td class="no_bdr">
<span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.02" class="ico_xls">XLS</a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.02" class="ico_csv">CSV</a> 
</span>
</li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.02#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">Emissions From Biomass Consumption</li>

<td class="no_bdr2">
<span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.07" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.07" class="ico_csv">CSV</a>
</span>
</li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.07#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>


<td class="no_bdr" colspan="2">11.2b&nbsp;&nbsp;Carbon Dioxide Emissions From Energy Consumption:<br />
Commercial Sector, Selected Years, 1949&ndash;<script>DataEndYear(0);</script></li>  

<td class="no_bdr">Emissions From Energy Consumption</li>

<td class="no_bdr">
<span class="right">
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.03" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.03" class="ico_csv">CSV</a>
</span>
</li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.03#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">Emissions From Biomass Consumption</li>

<td class="no_bdr2">
<span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.07" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.07" class="ico_csv">CSV</a>
</span>
</li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.07#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>


<td class="no_bdr" colspan="2">11.2c&nbsp;&nbsp;Carbon Dioxide Emissions From Energy Consumption:<br />
Industrial Sector, Selected Years, 1949&ndash;<script>DataEndYear(0);</script></li>

<td class="no_bdr">Emissions From Energy Consumption</li>
<td class="no_bdr">
<span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.04" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.04" class="ico_csv">CSV</a>
</span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.04#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">Emissions From Biomass Consumption</li>

<td class="no_bdr2"><span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.07" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.07" class="ico_csv">CSV</a>
</span></li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.07#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>


<td class="no_bdr" colspan="2">11.2d&nbsp;&nbsp;Carbon Dioxide Emissions From Energy Consumption:<br />
Transportation Sector, Selected Years, 1949&ndash;<script>DataEndYear(0);</script></li>  

<td class="no_bdr">Emissions From Energy Consumption</li>

<td class="no_bdr">
<span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.05" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.05" class="ico_csv">CSV</a>
</span>
</li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.05#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">Emissions From Biomass Consumption</li>

<td class="no_bdr2"><span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.07" class="ico_xls">XLS</a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.07" class="ico_csv">CSV</a> 
</span></li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.07#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>


<td class="no_bdr" colspan="2">11.2e&nbsp;&nbsp;Carbon Dioxide Emissions From Energy Consumption:<br />
Electric Power Sector, Selected Years, 1949&ndash;<script>DataEndYear(0);</script></li>

<td class="no_bdr">Emissions From Energy Consumption</li>

<td class="no_bdr"><span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.06" class="ico_xls">XLS</a> 
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.06" class="ico_csv">CSV</a></span>
</li>

<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.06#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<td class="no_bdr2">Emissions From Biomass Consumption</li>

<td class="no_bdr2"><span class="right"> 
<a href="/totalenergy/data/browser/xls.cfm?tbl=T12.07" class="ico_xls">XLS</a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=T12.07" class="ico_csv">CSV</a> 
</span></li>

<li>
<span class="beta">
<a href="/beta/MER/index.cfm?tbl=T12.07#/?f=A&start=200001 - view in Total Energy Browser">INTERACTIVE</a>
</span>
</li>
</tr*/ ?>
<?php /* end of section 11.1-11.2e commented out until released */ ?>

<li>11.1&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1101">Carbon dioxide emissions from energy consumption by source<br />Selected Years, 1949&ndash;<script>DataEndYear(1)</script></a><?php /*br />
<span class="right" style="margin-top:5px">(Find the latest annual data by source in <a href="../monthly/#environment">MER Table 12.1</a>)</span>
<br />
<span class="right" style="margin-top:5px">(Find the latest annual data for biomass in <a href="../monthly/#environment">MER Table 12.7</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_3.pdf" class="ico_pdf" title="Table 11.1  Carbon dioxide emissions from energy consumption by source Selected Years, 1949–2011"><i class="ico pdf"><span>PDF</span></i></a><a href="xls/stb1101.xls" class="ico_xls" title="Table 11.1  Carbon dioxide emissions from energy consumption by source Selected Years, 1949–2011"><i class="ico xls"><span>XLS</span></i></a> <a href="pdf/sec11_2.pdf" class="ico_pdf" title="Table 11.1  Carbon dioxide emissions from energy consumption by source Selected Years, 1949–2011">
GRAPH</a></span>
</li>

<li>11.2a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1102a">Carbon dioxide emissions from energy consumption:<br />residential sector, selected years, 1949&ndash;<script>DataEndYear(1)</script></a><?php /*br />
<span class="right" style="margin-top:5px">(Find the latest annual data by residential sector in <a href="../monthly/#environment">MER Table 12.2</a>)</span>
<br />
<span class="right" style="margin-top:5px">(Find the latest annual data for biomass in <a href="../monthly/#environment">MER Table 12.7</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_5.pdf" class="ico_pdf" title="Table 11.2a  Carbon dioxide emissions from energy consumption: residential sector, selected years, 1949–2011"><i class="ico pdf"><span>PDF</span></i></a> <a href="xls/stb1102a.xls" class="ico_xls" title="Table 11.2a  Carbon dioxide emissions from energy consumption: residential sector, selected years, 1949–2011"><i class="ico xls"><span>XLS</span></i></a> <a href="pdf/sec11_4.pdf" class="ico_pdf" title="Table 11.2a  Carbon dioxide emissions from energy consumption: residential sector, selected years, 1949–2011">
GRAPH</a></span>
</li>

<li>11.2b&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1102b">Carbon dioxide emissions from energy consumption:<br />
commercial sector, selected years, 1949&ndash;<script>DataEndYear(1)</script></a><?php /*br />
<span class="right" style="margin-top:5px">(Find the latest annual data by commercial sector in <a href="../monthly/#environment">MER Table 12.3</a>)</span>
<br />
<span class="right" style="margin-top:5px">(Find the latest annual data for biomass in <a href="../monthly/#environment">MER Table 12.7</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_6.pdf" class="ico_pdf" title="Table 11.2b  Carbon dioxide emissions from energy consumption: 11.2b  Carbon dioxide emissions from energy consumption:  "><i class="ico pdf"><span>PDF</span></i></a>  <a href="xls/stb1102b.xls" class="ico_xls" title="Table 11.2b  Carbon dioxide emissions from energy consumption: 11.2b  Carbon dioxide emissions from energy consumption:  "><i class="ico xls"><span>XLS</span></i></a> <a href="pdf/sec11_4.pdf" class="ico_pdf" title="Table 11.2b  Carbon dioxide emissions from energy consumption: 11.2b  Carbon dioxide emissions from energy consumption:  ">
GRAPH</a></span>
</li>

<li>11.2c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1102c">Carbon dioxide emissions from energy consumption:<br />
industrial sector, selected years, 1949&ndash;<script>DataEndYear(1)</script></a><?php /*br />
<span class="right" style="margin-top:5px">(Find the latest annual data by industrial sector in <a href="../monthly/#environment">MER Table 12.4</a>)</span>
<br />
<span class="right" style="margin-top:5px">(Find the latest annual data for biomass in <a href="../monthly/#environment">MER Table 12.7</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_7.pdf" class="ico_pdf" title="Table 11.2c  Carbon dioxide emissions from energy consumption: industrial sector, selected years, 1949–2011 "><i class="ico pdf"><span>PDF</span></i></a> <a href="xls/stb1102c.xls" class="ico_xls" title="Table 11.2c  Carbon dioxide emissions from energy consumption: industrial sector, selected years, 1949–2011 "><i class="ico xls"><span>XLS</span></i></a> <a href="pdf/sec11_4.pdf" class="ico_pdf" title="Table 11.2c  Carbon dioxide emissions from energy consumption: industrial sector, selected years, 1949–2011 ">
GRAPH</a></span>
</li>

<li>11.2d&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1102d">Carbon dioxide emissions from energy consumption:<br />transportation sector, selected years, 1949&ndash;<script>DataEndYear(1)</script></a><?php /*br />
<span class="right" style="margin-top:5px">(Find the latest annual data by transportation sector in <a href="../monthly/#environment">MER Table 12.5</a>)</span>
<br />
<span class="right" style="margin-top:5px">(Find the latest annual data for biomass in <a href="../monthly/#environment">MER Table 12.7</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_8.pdf" class="ico_pdf" title="Table 11.2d  Carbon dioxide emissions from energy consumption: transportation sector, selected years, 1949–2011 "><i class="ico pdf"><span>PDF</span></i></a> <a href="xls/stb1102d.xls" class="ico_xls" title="Table 11.2d  Carbon dioxide emissions from energy consumption: transportation sector, selected years, 1949–2011 "><i class="ico xls"><span>XLS</span></i></a> <a href="pdf/sec11_4.pdf" class="ico_pdf" title="Table 11.2d  Carbon dioxide emissions from energy consumption: transportation sector, selected years, 1949–2011 ">
GRAPH</a></span>
</li>

<li>11.2e&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1102e">Carbon dioxide emissions from energy consumption:<br />electric power sector, selected years, 1949&ndash;<script>DataEndYear(1)</script></a><?php /*br />
<span class="right" style="margin-top:5px">(Find the latest annual data by electric power sector in <a href="../monthly/#environment">MER Table 12.6</a>)</span>
<br />
<span class="right" style="margin-top:5px">(Find the latest annual data for biomass in <a href="../monthly/#environment">MER Table 12.7</a>)</span*/ ?></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_9.pdf" class="ico_pdf" title="Table 11.2e  Carbon dioxide emissions from energy consumption: electric power sector, selected years, 1949–2011 "><i class="ico pdf"><span>PDF</span></i></a> <a href="xls/stb1102e.xls" class="ico_xls" title="Table 11.2e  Carbon dioxide emissions from energy consumption: electric power sector, selected years, 1949–2011 "><i class="ico xls"><span>XLS</span></i></a> <a href="pdf/sec11_4.pdf" class="ico_pdf" title="Table 11.2e  Carbon dioxide emissions from energy consumption: electric power sector, selected years, 1949–2011 ">
GRAPH</a></span>
</li>

<li>11.3&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1103">Methane emissions, 1980&ndash;
<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_11.pdf" class="ico_pdf" title="Table 11.3  Methane emissions, 1980– 2009  "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1103.xls" class="ico_xls" title="Table 11.3  Methane emissions, 1980– 2009  "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec11_10.pdf" class="ico_pdf" title="Table 11.3  Methane emissions, 1980– 2009  ">
GRAPH</a></span>
</li>

<li>11.4&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1104">Nitrous oxide emissions, 1980&ndash;
<script>DataEndYear(3);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_13.pdf" class="ico_pdf" title="Table 11.4  Nitrous oxide emissions, 1980– 2009 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1104.xls" class="ico_xls" title="Table 11.4  Nitrous oxide emissions, 1980– 2009 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec11_12.pdf" class="ico_pdf" title="Table 11.4  Nitrous oxide emissions, 1980– 2009 ">
GRAPH</a></span>
</li>

<li>11.5a&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1105a">Emissions from energy consumption for electricity generation and useful thermal output:
<br />
total (all sectors), 1989&ndash;<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_15.pdf" class="ico_pdf" title="Table 11.5a  Emissions from energy consumption for electricity generation and useful thermal output: total (all sectors), 1989–2010 "><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1105a.xls" class="ico_xls" title="Table 11.5a  Emissions from energy consumption for electricity generation and useful thermal output: total (all sectors), 1989–2010 "><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec11_14.pdf" class="ico_pdf" title="Table 11.5a  Emissions from energy consumption for electricity generation and useful thermal output: total (all sectors), 1989–2010 ">
GRAPH</a></span>
</li>

<li>11.5b&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1105b">Emissions from energy consumption for electricity generation and useful thermal output:
<br />electric power sector, 1989&ndash;<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_16.pdf" class="ico_pdf" title="Table 11.5b  Emissions from energy consumption for electricity generation and useful thermal output: electric power sector, 1989–2010">P
DF</a> 
<a href="xls/stb1105b.xls" class="ico_xls" title="Table 11.5b  Emissions from energy consumption for electricity generation and useful thermal output: electric power sector, 1989–2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec11_14.pdf" class="ico_pdf" title="Table 11.5b  Emissions from energy consumption for electricity generation and useful thermal output: electric power sector, 1989–2010">
GRAPH</a></span>
</li>

<li>11.5c&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1105c">Emissions From energy consumption for electricity generation and useful thermal output:
<br />
commercial and industrial sectors, 1989&ndash;<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_17.pdf" class="ico_pdf" title="Table 11.5c  Emissions From energy consumption for electricity generation and useful thermal output: commercial and industrial sectors, 1989–2010"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1105c.xls" class="ico_xls" title="Table 11.5c  Emissions From energy consumption for electricity generation and useful thermal output: commercial and industrial sectors, 1989–2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec11_14.pdf" class="ico_pdf" title="Table 11.5c  Emissions From energy consumption for electricity generation and useful thermal output: commercial and industrial sectors, 1989–2010">
GRAPH</a></span>
</li>

<li>11.6&nbsp;&nbsp;<a href="showtext.cfm?t=ptb1106">Installed nameplate capacity of fossil-fuel steam-electric generators<br />
with environmental equipment, 1985&ndash;<script>DataEndYear(2);</script></a></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec11_19.pdf" class="ico_pdf" title="Table 11.6  Installed nameplate capacity of fossil-fuel steam-electric generators with environmental equipment, 1985–2010"><i class="ico pdf"><span>PDF</span></i></a> 
<a href="xls/stb1106.xls" class="ico_xls" title="Table 11.6  Installed nameplate capacity of fossil-fuel steam-electric generators with environmental equipment, 1985–2010"><i class="ico xls"><span>XLS</span></i></a> 
<a href="pdf/sec11_18.pdf" class="ico_pdf" title="Table 11.6  Installed nameplate capacity of fossil-fuel steam-electric generators with environmental equipment, 1985–2010">
GRAPH</a></span>
</li>

<li>Section Notes</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote11.pdf" class="ico_pdf">PDF</a></span>
</li>
<?php /* ***** End of Environment Content  ******* */ ?>
<?php /* ***** Start of Appendices Content  ******* */ ?>
	<h2><i class="ico expand-collapse"></i><a name="appendices"></a>Appendices (heat content, conversion factors, and more)</h2>
	<div class="accordion-content">
		<ul>

<li>Topic</li>

<li><span style="color:#CCC">A1</span>&nbsp;&nbsp;Approximate heat content of petroleum products</li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec13_1.pdf" class="ico_pdf" title="Appendix A1 Approximate heat content of petroleum products"><i class="ico pdf"><span>PDF</span></i></a></span>
</li>

<li><span style="color:#CCC">A2</span>&nbsp;&nbsp;Approximate heat content of petroleum production, imports, and exports<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec13_2.pdf" class="ico_pdf" title="Appendix A2  Approximate heat content of petroleum production, imports, and exports"><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=TA2" class="ico_xls" title="Appendix A2  Approximate heat content of petroleum production, imports, and exports"><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=TA2" class="ico_csv" title="Appendix A2  Approximate heat content of petroleum production, imports, and exports"><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=TA2#/?f=A&start=200001" title="Appendix A2  Approximate heat content of petroleum production, imports, and exports - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">A3</span>&nbsp;&nbsp;Approximate heat content of petroleum consumption and biofuels production<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec13_3.pdf" class="ico_pdf" title="Appendix A3  Approximate heat content of petroleum consumption and biofuels production "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=TA3" class="ico_xls" title="Appendix A3  Approximate heat content of petroleum consumption and biofuels production "><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=TA3" class="ico_csv" title="Appendix A3  Approximate heat content of petroleum consumption and biofuels production "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=TA3#/?f=A&start=200001" title="Appendix A3  Approximate heat content of petroleum consumption and biofuels production  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">A4</span>&nbsp;&nbsp;Approximate heat content of natural gas<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec13_4.pdf" class="ico_pdf" title="Appendix A4  Approximate heat content of natural gas "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=TA4" class="ico_xls" title="Appendix A4  Approximate heat content of natural gas "><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=TA4" class="ico_csv" title="Appendix A4  Approximate heat content of natural gas "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=TA4#/?f=A&start=200001" title="Appendix A4  Approximate heat content of natural gas  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">A5</span>&nbsp;&nbsp;Approximate heat content of coal and coal coke<!--, 1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats:  
<a href="/totalenergy/data/monthly/pdf/sec13_5.pdf" class="ico_pdf" title="Appendix A5  Approximate heat content of coal and coal coke "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=TA5" class="ico_xls" title="Appendix A5  Approximate heat content of coal and coal coke "><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=TA5" class="ico_csv" title="Appendix A5  Approximate heat content of coal and coal coke "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=TA5#/?f=A&start=200001" title="Appendix A5  Approximate heat content of coal and coal coke  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li><span style="color:#CCC">A6</span>&nbsp;&nbsp;Approximate heat rates for electricity, and heat content of electricity <!--1949&ndash;
<script>DataEndYear(0);</script>--></li>
			<li class="additional-formats">Available formats: 
<a href="/totalenergy/data/monthly/pdf/sec13_6.pdf" class="ico_pdf" title="Appendix A6  Approximate heat rates for electricity, and heat content of electricity "><i class="ico pdf"><span>PDF</span></i></a>
<a href="/totalenergy/data/browser/xls.cfm?tbl=TA6" class="ico_xls" title="Appendix A6  Approximate heat rates for electricity, and heat content of electricity "><i class="ico xls"><span>XLS</span></i></a>
<a href="/totalenergy/data/browser/csv.cfm?tbl=TA6" class="ico_csv" title="Appendix A6  Approximate heat rates for electricity, and heat content of electricity "><i class="ico csv"><span>CSV</span></i></a></span>
</li>
<li><span class="beta">
<a href="/beta/MER/index.cfm?tbl=TA6#/?f=A&start=200001" title="Appendix A6  Approximate heat rates for electricity, and heat content of electricity  - view in Total Energy Browser">INTERACTIVE</a></span>
</li>

<li>Documentation</li>
			<li class="additional-formats">Available formats: <a href="pdf/secnote12.pdf" class="ico_pdf" title="Documentation"><i class="ico pdf"><span>PDF</span></i></a></span>
</li>

<li><span style="color:#CCC">B1</span>&nbsp;&nbsp;Metric conversion factors</li>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec13_14.pdf" class="ico_pdf" title="Appendix B1  Metric conversion factors "><i class="ico pdf"><span>PDF</span></i></a></span></li>

<li><span style="color:#CCC">B2</span>&nbsp;&nbsp;Metric prefixes</li>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec13_15.pdf" class="ico_pdf" title="Appendix B2  Metric prefixes "><i class="ico pdf"><span>PDF</span></i></a></span></li>

<li><span style="color:#CCC">B3</span>&nbsp;&nbsp;Other physical conversion factors</li>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec13_15.pdf" class="ico_pdf" title="Appendix B3  Other physical conversion factors "><i class="ico pdf"><span>PDF</span></i></a></span></li>

<li>C1&nbsp;&nbsp;U.S. Census regions and divisions</li>
			<li class="additional-formats">Available formats:  <a href="pdf/sec14_1.pdf" class="ico_pdf" title="Appendix C1  U.S. Census regions and divisions"><i class="ico pdf"><span>PDF</span></i></a></span></li>

<li><span style="color:#CCC">D1</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb1501"*/ ?>Population, U.S. gross domestic product, and implicit price deflator<!--, 1949&ndash;
<script>DataEndYear(1);</script>--></a></li>
			<li class="additional-formats">Available formats:  <a href="/totalenergy/data/monthly/pdf/sec13_19.pdf" class="ico_pdf" title="Appendix D1  Population, U.S. gross domestic product, and implicit price deflator"><i class="ico pdf"><span>PDF</span></i></a> <a href="/totalenergy/data/browser/xls.cfm?tbl=TC1&freq=a" class="ico_xls" title="Appendix D1  Population, U.S. gross domestic product, and implicit price deflator"><i class="ico xls"><span>XLS</span></i></a> <a href="/totalenergy/data/browser/csv.cfm?tbl=TC1" class="ico_csv" title="Appendix D1  Population, U.S. gross domestic product, and implicit price deflator"><i class="ico csv"><span>CSV</span></i></a></span></li>
<li><span class="beta"><a href="/beta/MER/index.cfm?tbl=TC1#/?f=A&start=1991" title="Appendix D1  Population, U.S. gross domestic product, and implicit price deflator - view in Total Energy Browser">INTERACTIVE</a></span></li>

<li><span style="color:#CCC">E1</span>&nbsp;&nbsp;<?php /*a href="showtext.cfm?t=ptb1601"*/ ?>Estimated primary energy consumption in the United States, 1635-1945</a></li>
			<li class="additional-formats">Available formats: <a href="/totalenergy/data/monthly/pdf/sec13_21.pdf" class="ico_pdf" title="Appendix E1  Estimated primary energy consumption in the United States, 1635-1945"><i class="ico pdf"><span>PDF</span></i></a></span></li>

<li>Appendix F: Alternatives for estimating energy consumption</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec17.pdf" class="ico_pdf" title="Appendix F: Alternatives for estimating energy consumption"><i class="ico pdf"><span>PDF</span></i></a></span>
</li>

<li>F1&nbsp;&nbsp;Conversion efficiencies of noncombustible renewable energy sources</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec17_3.pdf" class="ico_pdf" title="Appendix F1  Conversion efficiencies of noncombustible renewable energy sources"><i class="ico pdf"><span>PDF</span></i></a></span>
</li>

<li>F1&nbsp;&nbsp;Primary energy consumption and delivered total energy, 
<script>DataEndYear(2);</script></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec17_5.pdf" class="ico_pdf" title="Appendix F1  Primary energy consumption and delivered total energy, 2010">
GRAPH</a></span>
</li>

<li>F2&nbsp;&nbsp;Energy consumption by sector, 
<script>DataEndYear(2);</script></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec17_6.pdf" class="ico_pdf" title="Appendix F2  Energy consumption by sector, 2010"><i class="ico pdf"><span>PDF</span></i></a></span>
</li>

<li>F3&nbsp;&nbsp;Noncombustible renewable primary energy consumption by energy source, 
<script>DataEndYear(2);</script></li>
			<li class="additional-formats">Available formats: <a href="pdf/sec17_6.pdf" class="ico_pdf" title="Appendix F3  Noncombustible renewable primary energy consumption by energy source, 2010"><i class="ico pdf"><span>PDF</span></i></a></span>
</li>

<li>Glossary</li>
			<li class="additional-formats">Available formats: <a href="pdf/sec18.pdf" class="ico_pdf" title="Glossary"><i class="ico pdf"><span>PDF</span></i></a></span>
</li>
<?php /* ***** End of Appendices Content  ******* */ ?>
</table>          
<?php /* Start of Annual Total Energy Subject Matter Contact link */ ?>	
<br /><br />
<p><b><a href="/about/contact/totalenergy.cfm">Total Energy Experts</a></b></p>   
<?php /* End of Annual Total Energy Subject Matter Contact link */ ?>	

<?php /* End of Total Energy - Annual */ ?>
<?php /* End of Main Column */ ?>