<?php /* <?php include ('side_data.php') ; ?> */ ?>
          <?php /* Start of Side Content box */ ?>
          <?php /* Start of Energy Perspectives Content box */ ?>
          <?php /*span class="grey_side green_top side_list_nocolumn">
              <h4><a href="/totalenergy/data/annual/perspectives.cfm">Energy Perspectives</a></h4><p style="font-size:10px">Forty-two interactive graphs showing trends in U.S. energy production, consumption, and trade from 1949-2011</p><a href="/totalenergy/data/annual/perspectives.cfm"><img src="images/ep_2011_xsmall.png" alt="Energy Perspectives image"></a>
          </span*/ ?>
          <?php /* End of Energy Perspectives Content box */ ?>
          <span class="grey_side blue_top side_list_nocolumn">
          <?php /* Start of Changes in AER 2011 right side box content */ ?>
            <h4>Changes to the  AER</h4>
            <ul>
				<li>Tables with grayed-out numbers go to the MER (the most recent data).  The remaining tables still go to the AER 2011 (data through 2011).  In some cases the table numbering of the AER differs from that of the MER.
				</li>
				<?php /*li>Where a given year is shown in two places, the MER data are the most recent.
				</li*/ ?>
				<li>Explanatory notes for the most recent  AER can be found in archived AER 2011 (data year dropdown above).  MER notes and sources are linked at the bottom of the interactive tables.
				</li>
				<?php /*li><a href="/totalenergy/data/annual/pdf/sec1_31.pdf">Sales of Fossil Fuels Produced on Federal and American Indian Lands</a> (Table 1.14),  previously titled "Fossil Fuel Production on Federally Administered Lands,"  now provides data on sales of fossil fuels from Federal and American Indian lands for fiscal years 2003 through 2011.
				</li>
				<li>
				<a href="/totalenergy/data/annual/pdf/sec2_9.pdf">Industrial Sector Energy Consumption Estimates</a> (Table 2.1d), <a href="/totalenergy/data/annual/pdf/sec10_7.pdf">Renewable Energy Consumption: Industrial and Transportation Sectors</a> (Table 10.2b), <a href="/totalenergy/data/annual/pdf/sec8_11.pdf">Electricity Net Generation: Commercial and Industrial Sectors</a>, (Table 8.2d), and <a href="/totalenergy/data/annual/pdf/sec8_19.pdf">Consumption for Electricity Generation by Energy Source: Commercial and Industrial Sectors</a> (Table 8.4c) have been modified to include industrial wind consumption.
				</li>
				<li>
				<a href="/totalenergy/data/annual/pdf/sec5_6.pdf">Petroleum and Other Liquids Overview</a> (Table 5.1a), <a href="/totalenergy/data/annual/pdf/sec5_7.pdf">Petroleum Overview</a> (Table 5.1b), and <a href="/totalenergy/data/annual/pdf/sec5_9.pdf">Crude Oil Production and Crude Oil Well Productivity</a> (Table 5.2) now incorporate revisions to crude oil production, total field production, and adjustments in coordination with the <i>Petroleum Supply Monthly</i>.
				</li*/ ?>
				<li>
					<a href="whatsnew.cfm">See a full list of content changes to all AER reports by year.&nbsp;&gt;</a>
				</li>
			</ul>
          <?php /* End of Changes in AER 2011  right side box content */ ?>
            <p class="no_btm_border"></p>
          </span>
          <?php /* End of Side Content box */ ?>
          <?php /* Start of Energy Flow Content box */ ?>
          <?php /*span class="grey_side green_top side_list_nocolumn">
             <h4>Energy Graphs</h4>
<a href="/totalenergy/data/annual/diagram1.cfm"><img src="images/overview_flow_2011_xsmall.png" alt="Total Energy graph image"></a>
			<ul>
			<li>&nbsp;<a href="/totalenergy/data/annual/pecss_diagram.cfm">U.S. Primary Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram1.cfm">Total Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram2.cfm">Petroleum</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram3.cfm">Natural Gas</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram4.cfm">Coal</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram5.cfm">Electricity</a></li>
			</ul>
          </span*/ ?>
          <?php /* End of Energy Flow Content box */ ?>
