<div class="secondary">
    <ul>
        <li class="head">
            <h2>Changes to the AER</h2></li>
        <li>
            <ul>
                <li>Tables with grayed-out numbers go to the MER (the most recent data). The remaining tables still go to the AER 2011 (data through 2011). In some cases the table numbering of the AER differs from that of the MER.</li>
                <li>Explanatory notes for the most recent AER can be found in archived AER 2011 (data year dropdown above). MER notes and sources are linked at the bottom of the interactive tables.</li>
                <li class="foot"><a href="whatsnew.cfm">See a full list of content changes to all AER reports by year.</a></li>
            </ul>
</li>
    </ul>
</div>