<div class="call-out">
    <p>EIA has expanded the <em>Monthly Energy Review</em> (MER) to include annual data as far back as 1949 for those data tables that are found in both the <em>Annual Energy Review</em> (AER) and the <a href="/totalenergy/data/monthly/">MER</a>. In the
        list of tables below, grayed-out table numbers now go to MER tables that contain data series for 1949 forward. New <a href="/totalenergy/data/browser/" title="view in Total Energy Browser">INTERACTIVE tables and graphs</a> have also been added.</p>
</div>