<?php /* <?php include ('side_data.php') ; ?> */ ?>
          <?php /* Start of Side Content box */ ?>
          <span class="grey_side blue_top side_list_nocolumn">
            <h4>Energy Perspective charts</h4>
            <p><a href="pdf/perspectives_2011.pdf" id="ep_pdf" class="ico_pdf" alt="PDF logo">All figures in a single PDF file</a></p>
            <p><a href="EnergyPerspectives.xls" id="ep_excel" class="ico_xls" alt="Excel logo">All figures and data in a single Excel file</a></p>
             <p><a href="http://www.eia.gov/todayinenergy/index.cfm?tg=%20Energy%20Perspectives" >Related articles</a></p>
<table  class="zebra">
<tr class="darkrow">
	<th><strong>Total Energy</strong></th>
</tr>
<tr>
	<td>1. <A class="EPG_link" id="ep1" name="chart_maker.cfm?epg=1"><span style="display:none;">F0101a</span>U.S. Primary Energy Production, Consumption, Imports, and Exports, 1949-2011</A></li>
<tr>
	<td>2. <A class="EPG_link" name="chart_maker.cfm?epg=2"><span style="display:none;">F0105d</span>U.S. Primary Energy Consumption per Capita, 1949-2011</A></li></li>
<tr>
	<td>3. <A class="EPG_link" name="chart_maker.cfm?epg=3"><span style="display:none;">F0105c</span>U.S. Primary Energy Consumption per Real Dollar of Gross Domestic Product, 1949-2011</A></li>
<?php /*tr>
	<td>4. <A class="EPG_link" name="chart_maker.cfm?epg=4"><span style="display:none;">P_04</span>Primary Energy Consumption by Major Source</A></td>
</tr*/ ?>
<tr>
	<td>4. <A class="EPG_link" name="chart_maker.cfm?epg=4"><span style="display:none;">P_05</span>U.S. Primary Energy Consumption Estimates by Major Source, 1949-2011</A></li>
<tr>
	<td>5. <A class="EPG_link" name="chart_maker.cfm?epg=5"><span style="display:none;">P_06</span>U.S. Primary Energy Consumption Estimates by Source, 1775-2011</A></li>
<tr>
	<td>6. <A class="EPG_link" name="chart_maker.cfm?epg=6"><span style="display:none;">F0201aa</span>U.S. Total Energy Consumption Estimates by End-Use Sector, 1949-2011</A></li>
<tr>
	<td>7. <A class="EPG_link" name="chart_maker.cfm?epg=7"><span style="display:none;">P_08</span>U.S. Residential and Commercial Sector Total Energy Consumption Estimates by Major Source, 1949-2011</A></li>
<tr>
	<td>8. <A class="EPG_link" name="chart_maker.cfm?epg=8"><span style="display:none;">F0201bc</span>U.S. Industrial Sector Total Energy Consumption Estimates by Major Source, 1949-2011</A></li>
<tr>
	<td>9. <A class="EPG_link" name="chart_maker.cfm?epg=9"><span style="display:none;">P_10</span>U.S. Transportation Sector Total Energy Consumption Estimates by Major Source, 1949-2011</A></li>
<tr>
	<td>10. <A class="EPG_link" name="chart_maker.cfm?epg=10"><span style="display:none;">F0102b</span>U.S.  Primary Energy Production by Major Source, 1949-2011</A></li>
<?php /*<tr>
	<td>11. <A class="EPG_link" name="chart_maker.cfm?epg=11"><span style="display:none;">F0701c</span>U.S. Energy Production as Share of Consumption by Type of Fossil Fuel, 1949-2010</A></li>*/ ?>
<tr class="darkrow">
	<th><strong>Petroleum and Other Liquids</strong></th>
</tr>
<tr>
	<td>11. <A class="EPG_link" name="chart_maker.cfm?epg=11"><span style="display:none;">F0501ba</span>U.S. Petroleum and Other Liquids Production, Estimated Consumption, and Net Imports, 1949-2011</A></li>
<tr>
	<td>12. <A class="EPG_link" name="chart_maker.cfm?epg=12"><span style="display:none;">F0502c</span>48 States and Alaskan Crude Oil Production, 1954-2011</A></li>
<tr>
	<td>13. <A class="EPG_link" name="chart_maker.cfm?epg=13"><span style="display:none;">F0513aa</span>U.S. Petroleum Consumption Estimates by Sector, 1949-2011</A></li>
<tr>
	<td>14. <A class="EPG_link" name="chart_maker.cfm?epg=14"><span style="display:none;">F0511a</span>U.S. Petroleum Consumption Estimates by Selected Product, 1949-2011</A></li>
<tr>
	<td>15. <A class="EPG_link" name="chart_maker.cfm?epg=15"><span style="display:none;">F0521b</span>U.S. Refiner Acquisition Cost of Crude Oil, 1968-2011</A></li>
<tr>
	<td>16. <A class="EPG_link" name="chart_maker.cfm?epg=16"><span style="display:none;">F0524a</span>Motor Gasoline Retail Prices, U.S. City Average, 1978-2011</A></li>
<tr>
	<td>17. <A class="EPG_link" name="chart_maker.cfm?epg=17"><span style="display:none;">F0501bd</span>U.S. Petroleum Imports and Exports, 1949-2011</A></li>
<tr>
	<td>18. <A class="EPG_link" name="chart_maker.cfm?epg=18"><span style="display:none;">F0504a</span>U.S. Petroleum Imports From OPEC and Non-OPEC Countries, 1960-2011</A></li>
<tr>
	<td>19. <A class="EPG_link" name="chart_maker.cfm?epg=19"><span style="display:none;">F0504c</span>U.S. Petroleum Imports From Selected OPEC Countries, 1960-2011</A></li>
<tr>
	<td>20. <A class="EPG_link" name="chart_maker.cfm?epg=20"><span style="display:none;">F0504d</span>U.S. Petroleum Imports From Canada and Mexico, 1960-2011</A></li>
<tr>
	<td>21. <A class="EPG_link" name="chart_maker.cfm?epg=21"><span style="display:none;">F0517d</span>U.S. Strategic Petroleum Reserve Stocks as Days of Petroleum Net Imports, 1977-2011</A></li>
<tr>
	<td>22. <A class="EPG_link" name="chart_maker.cfm?epg=22"><span style="display:none;">F0208a</span>U.S. Motor Vehicle Indicators, 1949-2010</A></li>
<tr class="darkrow">
	<th><strong>Natural Gas</strong></th>
</tr>
<tr>
	<td>23. <A class="EPG_link" name="chart_maker.cfm?epg=23"><span style="display:none;">F0601a</span>U.S. Natural Gas Production, Consumption, and Net Imports, 1949-2011</A></li>
<tr>
	<td>24. <A class="EPG_link" name="chart_maker.cfm?epg=24"><span style="display:none;">F0605a</span>U.S. Natural Gas Consumption by Sector, 1949-2011</A></li>
<tr>
	<td>25. <A class="EPG_link" name="chart_maker.cfm?epg=25"><span style="display:none;">F0608a</span>U.S. Natural Gas Real Prices by Sector, 1967-2011</A></li>
<tr class="darkrow">
	<th><strong>Coal </strong></th>
</tr>
<tr>
	<td>26. <A class="EPG_link" name="chart_maker.cfm?epg=26"><span style="display:none;">F0701a</span>U.S. Coal Production, Consumption, and Net Exports, 1949-2011</A></li>
<tr>
	<td>27. <A class="EPG_link" name="chart_maker.cfm?epg=27"><span style="display:none;">F0703a</span>U.S. Coal Consumption by Sector, 1949-2011</A></li>
<tr>
	<td>28. <A class="EPG_link" name="chart_maker.cfm?epg=28"><span style="display:none;">F0706b</span>U.S. Coal Mining Productivity, 1949-2011</A></li>
<tr>
	<td>29. <A class="EPG_link" name="chart_maker.cfm?epg=29"><span style="display:none;">F0702c</span>U.S. Coal Production by Mining Method, 1949-2011</A></li>
<tr>
	<td>30. <A class="EPG_link" name="chart_maker.cfm?epg=30"><span style="display:none;">F0702d</span>U.S. Coal Production by Location, 1949-2011</A></li>
<?php /*<tr>
	<td>32. <A class="EPG_link" name="chart_maker.cfm?epg=32"><span style="display:none;">F0708a</span>U.S. Coal Prices by Type, 1949-2010</A></li>*/ ?>
<tr class="darkrow">
	<th><strong>Electricity</strong></th>
</tr>
<tr>
	<td>31. <A class="EPG_link" name="chart_maker.cfm?epg=31"><span style="display:none;">F0802aa</span>U.S. Electricity Net Generation by the Electric Power and Commercial and Industrial Sectors, 1949-2011</A></li>
<tr>
	<td>32. <A class="EPG_link" name="chart_maker.cfm?epg=32"><span style="display:none;">P_44</span>U.S. Electricity Net Generation by Source, 1949-2011</A></li>
<tr>
	<td>33. <A class="EPG_link" name="chart_maker.cfm?epg=33"><span style="display:none;">P_45</span>U.S. Electric Net Summer Capacity by Source, 1989-2011</A></li>
<tr>
	<td>34. <A class="EPG_link" name="chart_maker.cfm?epg=34"><span style="display:none;">F0810d</span>U.S. Average Retail Prices of Electricity by Sector, 1960-2011</A></li>
<tr>
	<td>35. <A class="EPG_link" name="chart_maker.cfm?epg=35"><span style="display:none;">F0809c</span>U.S. Electricity Retail Sales by Sector, 1949-2011</A></li>
<?php /*tr>
	<td>39. <A class="EPG_link" name="chart_maker.cfm?epg=39"><span style="display:none;">F0901b</span>Nuclear Net Summer   Capacity</A></td>
</tr*/ ?>
<tr>
	<td>36. <A class="EPG_link" name="chart_maker.cfm?epg=36"><span style="display:none;">F0901a</span>U.S. Operable Nuclear Units, 1957-2011</A></li>
<tr class="darkrow">
	<th><strong>Renewable Energy</strong></th>
</tr>
<tr>
	<td>37. <A class="EPG_link" name="chart_maker.cfm?epg=37"><span style="display:none;">F1001b</span>U.S. Renewable Energy Consumption by Major Source, 1949-2011</A></li>
<tr>
	<td>38. <A class="EPG_link" name="chart_maker.cfm?epg=38"><span style="display:none;">P_42</span>U.S. Renewable Energy Consumption by Sector, 1949-2011</A></li>
<tr class="darkrow">
	<th><strong>Emissions</strong></th>
</tr>
<tr>
	<td>39. <A class="EPG_link" name="chart_maker.cfm?epg=39"><span style="display:none;">F1202c</span>Estimated U.S. Total Carbon Dioxide Emissions From Energy Consumption by End-Use Sector, 1949-2011</A></li>
<tr>
	<td>40. <A class="EPG_link" name="chart_maker.cfm?epg=40"><span style="display:none;">F1207c</span>Estimated U.S. Carbon Dioxide<sup>1</sup> Emissions From Energy Consumption by Major Source, 1949-2011</A></li>
<tr>
	<td>41. <A class="EPG_link" name="chart_maker.cfm?epg=41"><span style="display:none;">F1207d</span>Estimated U.S. Sulfur Dioxide Emissions From Energy Consumption, 1989-2010</A></li>
<tr>
	<td>42. <A class="EPG_link" name="chart_maker.cfm?epg=42"><span style="display:none;">F1207e</span>Estimated U.S. Nitrogen Oxide Emissions From Energy Consumption, 1989-2010</A></li>
</table>
            <p class="no_btm_border"></p>
          </span>
          <?php /* End of Side Content box */ ?>
          <?php /* Start of Energy Flow Content box */ ?>
          <span class="grey_side green_top side_list_nocolumn">
             <h4>Energy Graphs</h4>
<a href="/totalenergy/data/annual/diagram1.cfm"><img src="images/overview_flow_2011_xsmall.png" alt="Total Energy graph image"></a>
			<ul>
			<li>&nbsp;<a href="/totalenergy/data/annual/pecss_diagram.cfm">U.S. Primary Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram1.cfm">Total Energy</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram2.cfm">Petroleum</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram3.cfm">Natural Gas</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram4.cfm">Coal</a></li>
			<li>&nbsp;<a href="/totalenergy/data/annual/diagram5.cfm">Electricity</a></li>
			</ul>
          </span>
          <?php /* End of Energy Flow Content box */ ?>
          <?php /* Start of Energy Perspectives Content box: Commented out on 08/02/2011 */ ?>
          <?php /* 
          <span class="grey_side green_top side_list_nocolumn">
              <h4><a href="/totalenergy/data/annual/pdf/perspectives_2009.pdf" class="ico_pdf">Energy Perspectives</a></h4>
              <a href="/totalenergy/data/annual/pdf/perspectives_2009.pdf"><img src="images/ep_55_xsmall.jpg" alt="Energy Perspectives image"></a>
          </span>
		   */ ?>
          <?php /* End of Energy Perspectives Content box */ ?>