<div class="l-row header report-header">
    <div class="l-two-third-col">
        <h2>Annual Energy Review</h2>
        <div class="publish-metadata">Superseded -- see MER for key annual tables</div>
    </div>
    <div class="l-one-third-col gradient do-not-print">
        <div class="report-selector-container">
            <h4>Annual Energy Review archives</h4>
            <!--div class="dropdown" -->
            <form action="#">
                <fieldset>
                    <label>Select Year</label>
                    <span class="select-style"></span>
                    <select class="select-menu" onchange="location = this.value;">
                    <option value="/totalenergy/data/annual/archive/038411.pdf" selected="selected">2011</option>
                    <option value="/totalenergy/data/annual/archive/038410.pdf">2010</option>
                    <option value="/totalenergy/data/annual/archive/038409.pdf">2009</option>
                    <option value="/totalenergy/data/annual/archive/038408.pdf">2008</option>
                    <option value="/totalenergy/data/annual/archive/">all archives</option>
                </select>
                </fieldset> <span class="formats">Available formats:</span> <i class="ico xls"><span>XLS</span></i>
            </form>
        </div>
    </div>
</div>