<div class="l-row header report-header">
    <div class="l-full-width-col">
        <h2>Annual Energy Review</h2>
        <div class="publish-metadata">Superseded -- see MER for key annual tables</div>

        <div class="report-selector-container do-not-print">
            <form>
                <fieldset>
                    <label>Archives for data year <span class="inline"><i class="ico pdfs"></i></span></a></label>
                    <select class="select-download-menu" onchange="location = this.value;">
                        <option value="/totalenergy/data/annual/archive/038411.pdf" selected="selected">2011</option>
                        <option value="/totalenergy/data/annual/archive/038410.pdf">2010</option>
                        <option value="/totalenergy/data/annual/archive/038409.pdf">2009</option>
                        <option value="/totalenergy/data/annual/archive/038408.pdf">2008</option>
                        <option value="/totalenergy/data/annual/archive/">all archives</option>
                    </select>
                </fieldset>
            </form>
        </div>
    </div>
</div>