<div class="l-row header report-header">
    <div class="l-two-third-col">
        <h2>Annual Energy Review</h2>
        <div class="publish-metadata">Superseded -- see MER for key annual tables</div>
    </div>
    <div class="l-one-third-col gradient do-not-print">
        <div class="report-selector-container">
            <h4>Annual Energy Review archives</h4>
            <div class="dropdown">
                <a>Select Year</a>
                <div class="dropdown-content">
                    <p><a href="/totalenergy/data/annual/archive/038411.pdf" selected="selected">2011</a><p>
                    <p><a href="/totalenergy/data/annual/archive/038410.pdf">2010</a><p>
                    <p><a href="/totalenergy/data/annual/archive/038409.pdf">2009</a><p>
                    <p><a href="/totalenergy/data/annual/archive/038408.pdf">2008</a><p>
                    <p><a href="/totalenergy/data/annual/archive/">all archives</a><p>
                </div>
            </div>
        </div>
    </div>
</div>
