<!--- Data Source: STEO price summary table as shown on http://wwwdev.eia.gov/forecasts/steo/index.php --->
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="basic_table" >
  <caption>Price summary (historical and forecast) 
  </caption>
  <thead>
    <tr>
      <th>
      <th>2013</th>
      <th>2014</th>
      <th><em>2015</em></th>
      <th><em>2016</em></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      			<li class="head">WTI Crude Oil<sup>a</sup></li>
			<li><span style="font-size:11px; font-style:italic">dollars per barrel</span></td>
      <td>97.91</td>
      <td>93.17</td>
      <td><em>55.35</li>
      <td><em>62.04</em></li>
    <tr>
      			<li class="head">Brent Crude Oil</li>
			<li>
<span style="font-size:11px; font-style:italic">dollars per barrel</span></td>
      <td>108.64</td>
      <td>98.89</td>
      <td><em>60.53</li>
      <td><em>67.04</em></li>
    <tr>
      			<li class="head">Gasoline<sup>b</sup></li>
			<li>
<span style="font-size:11px; font-style:italic">dollars per gallon</span></td>
      <td>3.51</td>
      <td>3.36</td>
      <td><em>2.44</li>
      <td><em>2.55</em></li>
    <tr>
      			<li class="head">Diesel<sup>c</sup></li>
			<li>
<span style="font-size:11px; font-style:italic">dollars per gallon</span></td>
      <td>3.92</td>
      <td>3.83</td>
      <td><em>2.88</li>
      <td><em>3.04</em></li>
    <tr>
      			<li class="head">Heating Oil<sup>d</sup></li>
			<li>
<span style="font-size:11px; font-style:italic">dollars per gallon</span></td>
      <td>3.78</td>
      <td>3.72</td>
      <td><em>2.84</li>
      <td><em>2.89</em></li>
    <tr>
      			<li class="head">Natural Gas<sup>d</sup></li>
			<li>
<span style="font-size:11px; font-style:italic">dollars per thousand cubic feet</span></td>
      <td>10.30</td>
      <td>10.94</td>
      <td><em>10.23</li>
      <td><em>10.38</em></li>
    <tr>
      			<li class="head">Electricity<sup>d</sup></li>
			<li>
<span style="font-size:11px; font-style:italic">cents per kilowatthour</span></td>
      <td>12.12</td>
      <td>12.50</td>
      <td><em>12.79</li>
      <td><em>13.09</em></li>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="1"><sup>a</sup>West Texas Intermediate.<br />
        <sup>b</sup>Average regular pump price.
        <br />Note: Italics indicate forecast.
        <br />Source: <a href="/forecasts/steo/">Short-Term Energy Outlook</a>
        </td>
        <td style="text-align:left" colspan="4">
        <sup>c</sup>On-highway retail.<br />
        <sup>d</sup>U.S. Residential average.</li>
  </tfoot>
</table>
