<table class="basic_table" >
<?php /* Source: STEO Table 1: Energy Markets Summary - 2014 data - March 2014 release (http://wwwdev.eia.gov/forecasts/steo/tables/pdf/1tab.pdf)*/ ?>
<caption>U.S. Economic Indicators&nbsp;&ndash;&nbsp;2014 by quarter<br/><span class="units">percent change from prior year</span></caption>
	<thead>
        <tr>
          <th></th>
          <th><b>1st</b></th>
          <th><b>2nd</b></th>
          <th><b>3rd</b></th>
          <th><b>4th</b></th>
        </tr>
	</thead>
    <tbody>
      <tr>
          <td>Real Gross Domestic Product</td>
          <td>1.9</td>			 
          <td>2.6</td>
          <td>2.7</td>
          <td>2.5</li>
      <tr>
          <td>GDP Implicit Price Deflator</td>
          <td>1.4</td>			 
          <td>1.7</td>
          <td>1.6</td>
          <td>1.2</li>
      <tr>
          <td>Real Disposable Personal Income</td>
          <td>2.4</td>			 
          <td>2.2</td>
          <td>2.3</td>
          <td>3.2</li>
      <tr>
          <td>Manufacturing Production Index</td>
          <td>2.4</td>			 
          <td>3.8</td>
          <td>4.6</td>
          <td>4.4</li>
<?php /*
 Upstream financial review reference link 
    <tfoot>
    <tr>
    			<li>Source: U.S. Energy Information Administration, <a href="/finance/review/pdf/financial.pdf">Upstream Financial Review &mdash; <em>July 2014</em></a></li>
    </tfoot>
*/ ?>
	</tbody>
</table>


