<br />
<h3>Feedback</h3>
<p>We welcome your feedback and insights concerning this report.</p>
<p><form action="efmi_feedback.php" method="post">
   <textarea name="feedback" cols="40" rows="5" style="width:400px;"></textarea><br />
   <label>Email:</label><br /><input name="email" type="text" style="width:400px;"/>
   <br /><input name="submit" type="submit" class="submit_btn"/>
   </form>
</p>

<?php /*span class="left" style="width:240px;">We welcome your feedback and insights concerning this report.</span>
   <span class="right" style="text-align:right;"><form action="efmi_feedback.php" method="post"><textarea name="feedback" cols="40" rows="5"></textarea><br /><input name="submit" type="submit" class="submit_btn"/></form></span*/ ?>
<div class="clear"></div>