<?php $locale = ''; ?>
<div class="pub_title bg_pub_default"><?php /* Page/Section Title */ ?>
      <h3>Energy & Financial Markets</h3>
      <h1 style="padding-top:0px;">WHAT DRIVES CRUDE OIL PRICES?</h1>
      <p style="font-size:14px;margin-top:-6px;">An analysis of 7 factors that influence oil markets, with chart data updated monthly and quarterly</p>
    </div><?php /*/ Page/Section Title */ ?>
	<div class="subnav"><?php /* Page/Sub Nav */ ?>
    <?php /*span class="right"><a href="<?php echo "$glossary_path"?>">Glossary &rsaquo;</a><a href="<?php echo "$faqs_path"?>">FAQS &rsaquo;</a></span*/ ?>
       <ul>
        <li <?php if ( $locale == 'overview') {?>class="active"<?php  } // end if ?>><a href="/finance/markets/">Overview</a></li>
      </ul>
    </div><?php /*/ Page/Sub Nav */ ?>
