            <?php /* Sections Promo */ ?>
            <h2>Sections</h2>
               <ul class="split_2columns">
                  <li><a href="pdf/major.pdf" class="ico_pdf">Major Findings</a></li>
                  <li><a href="pdf/financial.pdf" class="ico_pdf">Financial Developments</a></li>
                  <li><a href="pdf/production.pdf" class="ico_pdf">Oil and Gas Production</a></li>
                  <li><a href="pdf/r&m.pdf" class="ico_pdf">Refining and Marketing</a></li>
                  <li><a href="pdf/aboutCOs.pdf" class="ico_pdf">About the FRS Companies</a></li>
                  <li><a href="pdf/overview.pdf" class="ico_pdf">Overview of 2009 Petroleum and Natural Gas Markets</a></li>
                </ul>
                       

            <hr class="hr_soft"/> 
			<?php /* press */ ?>
                  <strong><p>Supplemental</p></strong>
                <ul>
                    <li><a href="pdf/acronyms.pdf" class="ico_pdf">Acronyms</a></li>
                    <li><a href="pdf/terms.pdf " class="ico_pdf">Description of Financial Terms</a></li></ul>
                <?php /* press */ ?>

<?php /* Data Table 
            <h2>Data Tables</h2>
                <table class="aeo_data">
                  <tr>
                    <td><b>A1</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=1-AEO2011&region=0-0&cases=ref2011-d120810c">Total Energy Supply and Disposition Demand</a></td>
                    <td><a href="pdf/tbla1.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_1.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A2</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=2-AEO2011&region=1-0&cases=ref2011-d120810c">Energy Consumption by Sector and Source</a></td>
                    <td><a href="pdf/tbla2.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_2.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A3</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=3-AEO2011&region=1-0&cases=ref2011-d120810c">Energy Prices by Sector and Source</a></td>
                    <td><a href="pdf/tbla3.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_3.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A4</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=4-AEO2011&region=0-0&cases=ref2011-d120810c">Residential Sector Key Indicators and Consumption</a></td>
                    <td><a href="pdf/tbla4.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_4.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A5</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=5-AEO2011&region=0-0&cases=ref2011-d120810c">Commercial Sector Key Indicators and Consumption</a></td>
                    <td><a href="pdf/tbla5.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_5.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A6</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=6-AEO2011&region=0-0&cases=ref2011-d120810c">Industrial Sector Key Indicators and Consumption</a></td>
                    <td><a href="pdf/tbla6.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_6.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A7</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=7-AEO2011&region=0-0&cases=ref2011-d120810c">Transportation Sector Key Indicators and Delivered Energy Consumption</a></td>
                    <td><a href="pdf/tbla7.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_7.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A8</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=8-AEO2011&region=0-0&cases=ref2011-d120810c">Electricity Supply, Disposition, Prices, and Emissions</a></td>
                    <td><a href="pdf/tbla8.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_8.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A9</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=9-AEO2011&region=0-0&cases=ref2011-d120810c">Electricity Generating Capacity</a></td>
                    <td><a href="pdf/tbla9.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_9.xls" class="xls_link">&nbsp;</a></li>
                  <tr>
                    <td><b>A10</b></td>
                    <td><a href="/oiaf/aeo/tablebrowser/#release=AEO2011&subject=0-AEO2011&table=10-AEO2011&region=0-0&cases=ref2011-d120810c">Electricity Trade</a></td>
                    <td><a href="pdf/tbla10.pdf" class="pdf_link">&nbsp;</a></td>
                    <td><a href="excel/aeotab_10.xls" class="xls_link">&nbsp;</a></li>
                </table>
		        <p><a href="tables_ref.php"><b>View More &rsaquo;</b></a></p>
            <hr class="hr_soft"/> */ ?>