<div class="primary-alt">
    <ul>
        <li class="head">
            <h3><i class="ico table-viewer"><span>Interactive Table Viewer Icon</i>Interactive Table Viewers</h3></li>
        <li class="description">provides custom data views of forecast data</li>
        <li><a href="/beta/steo/">STEO — 18-month forecast</a></li>
        <li><a href="/beta/aeo/?src=-f1">AEO — projections to 2050</a></li>
        <li><a href="/beta/aeo/?src=-f1#/?id=3-IEO2016">IEO  — international projections</a></li>
    </ul>
</div>