<p>Find data from forecast models on crude oil and petroleum liquids, gasoline, diesel, natural gas, electricity, coal prices, supply, and demand projections and more.</p>
<div class="accordion">
    <div class="expand-collapse-container">
        <span class="expand-all"><i class="ico expand-collapse"></i> Expand all</span>
        <span class="collapse-all"><i class="ico expand-collapse"></i> Collapse all</span>
    </div>


	<h2><i class="ico expand-collapse"></i><a name="forecasts"></a>Monthly short-term forecasts through the next calender year</h2>
	<div class="accordion-content">
		<ul>
			<li class="highlight solid-divider"><em><a href="/outlooks/steo/">Short-Term Energy Outlook</a></em> Released: the first Tuesday following the first Thursday of each month. </li>
<!-- end special styling -->
			<li>WF01. Average consumer prices and expenditures for heating fuels during the winter</li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/wf-table.pdf" title="Table  WF01. Average consumer prices and expenditures for heating fuels during the winter"><i class="ico pdf"><span>PDF</span></i></a> </li>
			<li><a href="/outlooks/steo/tables/?tableNumber=3">1. U.S. energy market summary</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/1tab.pdf" title="Table  1. U.S. energy market summary"><i class="ico pdf"><span>PDF</span></i></a>				</li>
			<li><a href="/outlooks/steo/tables/?tableNumber=8">2. U.S. energy prices </a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/2tab.pdf" title="Table  2. U.S. energy prices "><i class="ico pdf"><span>PDF</span></i></a> </span>				</li>
			<li><a href="/outlooks/steo/tables/?tableNumber=6">3a. International crude oil and liquid fuels supply, consumption, and inventories</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/3atab.pdf" title="Table  3a. International crude oil and liquid fuels supply, consumption, and inventories"><i class="ico pdf"><span>PDF</span></i></a>				</li>
			<li><a href="/outlooks/steo/tables/?tableNumber=29">3b. Non-OPEC crude oil and liquid fuels supply</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/3btab.pdf" title="Table  3b. Non-OPEC crude oil and liquid fuels supply"><i class="ico pdf"><span>PDF</span></i></a> </span>				</li>
			<li><a href="/outlooks/steo/tables/?tableNumber=7">3c. OPEC crude oil and liquid fuels supply</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/3ctab.pdf" title="Table  3c. OPEC crude oil and liquid fuels supply"><i class="ico pdf"><span>PDF</span></i></a> </span>				</li>
			<li><a href="/outlooks/steo/tables/?tableNumber=30">3d. World liquid fuels consumption</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/3dtab.pdf" title="Table  3d. World liquid fuels consumption"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=9">4a. U.S. crude oil and liquid fuels supply, consumption, and inventories</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/4atab.pdf" title="Table  4a. U.S. crude oil and liquid fuels supply, consumption, and inventories"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=27">4b. U.S. petroleum refinery balance</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/4btab.pdf" title="Table  4b. U.S. petroleum refinery balance"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=10">4c. U.S. regional motor gasoline prices and inventories</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/4ctab.pdf" title="Table  4c. U.S. regional motor gasoline prices and inventories"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=15">5a. U.S. natural gas supply, consumption, and inventories</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/5atab.pdf" title="Table  5a. U.S. natural gas supply, consumption, and inventories"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=16">5b. U.S. regional natural gas prices</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/5btab.pdf" title="Table 5b. U.S. regional natural gas prices"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=18">6. &nbsp; U.S. coal supply, consumption, and inventories</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/6tab.pdf" title="Table 6.   U.S. coal supply, consumption, and inventories"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=19">7a. U.S. electricity overview</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/7atab.pdf" title="Table 7a. U.S. electricity overview"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=20">7b. U.S. regional electricity retail sales</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/7btab.pdf" title="Table 7b. U.S. regional electricity retail sales"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=21">7c. U.S. regional electricity prices</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/7ctab.pdf" title="Table 7c. U.S. regional electricity prices"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=22">7d. U.S.  electricity generation by fuel and sector</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/7dtab.pdf" title="Table 7d. U.S. electricity generation by fuel and sector"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=23">7e. U.S. fuel consumption for electricity generation by sector</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/7etab.pdf" title="Table 7e. U.S. fuel consumption for electricity generation by sector"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=24">8. U.S. renewable energy supply and consumption</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/8tab.pdf" title="Table 8. U.S. renewable energy supply and consumption"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=5">9a. U.S. macroeconomic indicators and CO<sub>2</sub> emissions</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/9atab.pdf" title="Table 9a. U.S. macroeconomic indicators and CO2 emissions"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=4">9b. U.S. regional macroeconomic data</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/9btab.pdf" title="Table 9b. U.S. regional macroeconomic data"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/steo/tables/?tableNumber=28">9c. U.S. regional weather data</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/steo/tables/pdf/9ctab.pdf" title="Table 9c. U.S. regional weather data"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li class="additional-formats solid-divider"><a href="/cfapps/ipdbproject/IEDIndex3.cfm">International petroleum supply, disposition</a><br />Query tool for detailed country and regional energy data (monthly, annual)</li>
        </ul>
    </div>  
	<h2><i class="ico expand-collapse"></i><a name="annualproj"></a>Annual projections to 2050</h2>
	<div class="accordion-content">
		<ul>
			<li class="highlight"><em><a href="/outlooks/aeo/">Annual Energy Outlook 2017</a></em> (released: January 5, 2017) -- Reference case main 21 tables<br />See complete table listing for <a href="/outlooks/aeo/tables_ref.cfm">reference case</a> and <a href="/outlooks/aeo/tables_side.cfm">side cases</a>. <a href="/outlooks/aeo/supplemental_case.cfm"> Supplemental case </a>(released June 26, 2017)</li>
            <!-- end special styling -->
			<li><a href="/outlooks/aeo/data/browser/#/?id=1-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A1. Total energy supply and disposition demand</a> </li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_1.xlsx" class="ico_xls" title="Table  A1. Total energy supply and disposition demand"><i class="ico xls"><span>XLS</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=2-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A2. Energy consumption by sector and source </a> </li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_2.xlsx" class="ico_xls" title="Table  A2. Energy consumption by sector and source "><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla2.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=3-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A3. Energy prices by sector and source</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_3.xlsx" class="ico_xls" title="Table  A3. Energy prices by sector and source"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla3.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=4-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A4. Residential sector key indicators and consumption</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_4.xlsx" class="ico_xls" title="Table  A4. Residential sector key indicators and consumption"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla4.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=5-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A5. Commercial sector key indicators and consumption</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_5.xlsx" class="ico_xls" title="Table  A5. Commercial sector key indicators and consumption"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla5.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=6-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A6. Industrial sector key indicators and consumption</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_6.xlsx" class="ico_xls" title="Table  A6. Industrial sector key indicators and consumption"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla6.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=7-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A7. Transportation sector key indicators and delivered energy consumption</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_7.xlsx" class="ico_xls" title="Table  A7. Transportation sector key indicators and delivered energy consumption"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/er/pdf/tbla7.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=8-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A8. Electricity supply Disposition, prices, and emissions</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_8.xlsx" class="ico_xls" title="Table  A8. Electricity supply Disposition, prices, and emissions"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla8.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=9-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A9. Electricity generating capacity</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_9.xlsx" class="ico_xls" title="Table  A9. Electricity generating capacity"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla9.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=10-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A10. Electricity trade</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_10.xlsx" class="ico_xls" title="Table  A10. Electricity trade"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla10.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=11-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A11. Liquid fuels supply and disposition balance</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_11.xlsx" class="ico_xls" title="Table  A11. Liquid fuels supply and disposition balance"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla11.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=12-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A12. Petroleum product prices</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_12.xlsx" class="ico_xls" title="Table A12. Petroleum product prices"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla12.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=13-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A13. Natural gas supply, disposition, and prices</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_13.xlsx" class="ico_xls" title="Table A13. Natural gas supply, disposition, and prices"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla13.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=14-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A14. Oil and gas supply</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_14.xlsx" class="ico_xls" title="Table A14. Oil and gas supply"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla14.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=15-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A15. Coal supply, disposition, and price</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_15.xlsx" class="ico_xls" title="Table A15. Coal supply, disposition, and price"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla15.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=16-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A16. Renewable energy generating capacity and generation</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_16.xlsx" class="ico_xls" title="Table A16. Renewable energy generating capacity and generation"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla16.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=24-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A17. Renewable energy consumption by sector and source</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_17.xlsx" class="ico_xls" title="Table A17. Renewable energy consumption by sector and source"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla17.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=17-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A18. Carbon dioxide emissions by sector and source</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_18.xlsx" class="ico_xls" title="Table A18. Carbon dioxide emissions by sector and source"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla18.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=22-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A19. Energy-related carbon dioxide emissions by end-use</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_19.xlsx" class="ico_xls" title="Table A19. Energy-related carbon dioxide emissions by end-use"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla19.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=18-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A20. Macroeconomic indicators</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_20.xlsx" class="ico_xls" title="Table A20. Macroeconomic indicators"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla20.pdf">PDF</a> --></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=19-aeo2017&amp;cases=ref2017~ref_no_cpp&amp;sourcekey=0">A21. International liquids supply disposition summary</a></li>
			<li class="additional-formats solid-divider">Available formats: <a href="/outlooks/aeo/excel/aeotab_21.xlsx" class="ico_xls" title="Table A21. International liquids supply disposition summary"><i class="ico xls"><span>XLS</span></i></a> <!-- <a href="/outlooks/aeo/pdf/tbla21.pdf">PDF</a> --></li>
        </ul>
    </div>    
	<h2><i class="ico expand-collapse"></i><a name="intlproj"></a>International projections to 2050</h2>
	<div class="accordion-content">
		<ul>
			<li class="highlight"><em><a href="/outlooks/ieo/">International Energy Outlook</a></em>-- Reference Case tables released: September 14, 2017</li>
			<li class="highlight"><a href="/outlooks/ieo/pdf/appa.pdf" class="pdf" title="International Energy Outlook">PDF (all tables)</a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=1-IEO2017">A1. World total primary energy consumption by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_1.pdf" title="Table  A1. World total primary energy consumption by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=2-IEO2017">A2. World total energy consumption by region and fuel</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_2.pdf" title="Table  A2. World total energy consumption by region and fuel"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=3-IEO2017">A3. World gross domestic product (GDP) by region expressed in purchasing power parity</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_3.pdf" title="Table  A3. World gross domestic product (GDP) by region expressed in purchasing power parity"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=4-IEO2017">A4. World gross domestic product (GDP) by region expressed in market exchange rates</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_4.pdf" title="Table  A4. World gross domestic product (GDP) by region expressed in market exchange rates"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=5-IEO2017">A5. World liquids consumption by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_5.pdf" title="Table  A5. World liquids consumption by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=6-IEO2017">A6. World natural gas consumption by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_6.pdf" title="Table  A6. World natural gas consumption by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=7-IEO2017">A7. World coal consumption by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_7.pdf" title="Table  A7. World coal consumption by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=8-IEO2017">A8. World nuclear energy consumption by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_8.pdf" title="Table  A8. World nuclear energy consumption by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=9-IEO2017">A9. World consumption of hydroelectricity and other renewable energy by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_9.pdf" title="Table  A9. World consumption of hydroelectricity and other renewable energy by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=10-IEO2017">A10. World carbon dioxide emissions by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_10.pdf" title="Table  A10. World carbon dioxide emissions by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=11-IEO2017">A11. World carbon dioxide emissions from liquids use by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_11.pdf" title="Table  A11. World carbon dioxide emissions from liquids use by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=12-IEO2017">A12. World carbon dioxide emissions from natural gas use by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_12.pdf" title="Table A12. World carbon dioxide emissions from natural gas use by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=13-IEO2017">A13. World carbon dioxide emissions from coal use by region</a></li>
			<li class="additional-formats dashed-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_13.pdf" title="Table A13. World carbon dioxide emissions from coal use by region"><i class="ico pdf"><span>PDF</span></i></a></li>
			<li><a href="/outlooks/aeo/data/browser/#/?id=14-IEO2017">A14. World population by region</a></li>
			<li class="additional-formats solid-divider">Available formats: <a href="/outlooks/ieo/pdf/ieotab_14.pdf" title="Table A14. World population by region"><i class="ico pdf"><span>PDF</span></i></a></li>
        </ul>
    </div>
</div>