<?php /* Interactive Table Viewer Promo */ ?>
 <span class="blue_side">
        <h4 class="d_side">Interactive Table Viewers</h4>
        
        <p><em>provides custom data views of forecast data</em><br />
        <br />
        <b><a href="/beta/steo/">STEO &mdash; 18-month forecast &rsaquo;</a><br />
        <a href="/beta/aeo/?src=-f1">AEO &mdash; projections to 2050 &rsaquo;</a><br />
        <a href="/beta/aeo/?src=-f1#/?id=3-IEO2016">IEO  &mdash; international projections &rsaquo;</a></b>

   <?php /* Interactive Table Viewer Promo */ ?>
