<a name="weeklies">
</a>
<div class="content-container-border primary-alt">
    <ul>
        <li class="head">
            <h2>Regular Weekly Releases*</h2>
        </li>
        <li class="sub-head">
            <h3>Monday</h3>
        </li>

        <li><a href="/petroleum/gasdiesel/">Gasoline and Diesel Fuel Update &rsaquo;</a></li>
        <li class="date">Usually Monday by 5:00 p.m. Eastern Time</li>

        <li class="sub-head">
            <h3>Wednesday</h3>
        </li>

        <li><a href="/oil_gas/petroleum/data_publications/weekly_petroleum_status_report/wpsr.html">Weekly Petroleum Status Report &rsaquo;</a>
            <li>
                <li class="date"> 10:30 a.m. Eastern Time</li>

                <li><a href="/petroleum/weekly/">This Week in Petroleum &rsaquo;</a></li>
                <li class="date">After 1:00 p.m. Eastern Time</li>

                <li><a href="/petroleum/heatingoilpropane/">Heating Oil and Propane Update &rsaquo;</a>
                    <li>
                        <li class="date">After 1:00 p.m. Eastern Time (Oct - March)</li>

                        <li class="date">*No releases: Monday, Tuesday, or Friday. Releases change on weeks with Federal holidays.</li>
    </ul>
</div>