<!-- start module -->
<!-- start module -->
<!-- start module -->
<div class="content-container content-container-border blue-background">
	<ul>
		<li class="head"><h2>Data Highlights</h2></li>
		<li class="sub-head"><a href="/">WTI crude oil futures price</a></li>
		<li class="date">9/12/2017: <strong>$48.23/barrel</strong></li>
		<li><i class="down-arrow" title="Down"></i>$0.43 from week earlier</li>
		<li><i class="up-arrow" title="Up"></i>$1.94 from year earlier</li>
		<li class="sub-head"><a href="/">Natural gas futures price</a></li>
		<li class="date">9/12/2017:<strong>$3.001/MMBtu</strong></li>
		<li><i class="up-arrow" title="Up"></i>$0.029 from week earlier</li>
		<li><i class="up-arrow" title="Up"></i>$0.086 from year earlier</li>
		<li class="sub-head"><a href="/">Retail gasoline price</a></li>
		<li class="date">9/11/2017: <strong>$2.685/gal</strong></li>
		<li><i class="up-arrow" title="Up"></i>$0.006 from week earlier</li>
		<li><i class="up-arrow" title="Up"></i>$0.483 from year earlier</li>
		<li class="sub-head"><a href="/">Crude oil inventories</a></li>
		<li class="date">9/8/2017: <strong>468.2 million barrels&nbsp; </strong></li>
		<li><i class="up-arrow" title="Up"></i>5.9 million barrels from week earlier</li>
		<li><i class="down-arrow" title="Down"></i>11.9 million barrels from year earlier</li>
		<li class="sub-head"><a href="/">Weekly coal production</a></li>
		<li class="date">9/2/2017: <strong>16.421 million tons</strong></li>
		<li><i class="down-arrow" title="Down"></i>0.322 million tons from week earlier</li>
		<li><i class="up-arrow" title="Up"></i>0.819 million tons from year earlier</li>
	</ul>
</div>
<!-- start module -->
<!-- start module -->
<!-- start module -->
