<h2>Data Highlights</h2>
<h3><a href="http://www.eia.gov/petroleum/gasdiesel/">Retail gasoline price</a></h3>
<p class="p12">7/9/2018: <b>$2.857/gal</b><br>
</p><p><span class="ico_up">up</span>$0.013   from week earlier<br>
<span class="ico_up">up</span>$0.560   from year earlier</p>

<h3><a href="http://www.eia.gov/petroleum/gasdiesel/">Retail diesel price</a></h3>
<p class="p12">7/9/2018: <b>$3.243/gal</b><br>
</p><p><span class="ico_up">up</span>$0.007   from week earlier<br>
<span class="ico_up">up</span>$0.762   from year earlier</p>

<h3><a href="http://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=PET&amp;s=RCLC1&amp;f=D">WTI crude oil futures price</a></h3>
<p class="p12">7/6/2018: <b>$73.80/barrel</b><br>
</p><p><span class="ico_down">down</span>$0.35   from week earlier<br>
<span class="ico_up">up</span>$28.28   from year earlier</p>

<h3><a href="http://www.eia.gov/dnav/ng/hist/rngc1d.htm">Natural gas futures price</a></h3>
<p class="p12">7/6/2018: <b>$2.858/MMBtu</b><br>
</p><p><span class="ico_down">down</span>$0.066    from week earlier<br>
<span class="ico_down">down</span>$0.030   from year earlier</p>

<h3><a href="http://www.eia.gov/cneaf/coal/weekly/weekly_html/wcpweek.html">Weekly coal production</a></h3>
<p class="p12">6/30/2018: <b>14.574  million tons</b><br>
</p><p><span class="ico_up">up</span>0.037  million tons from week earlier<br>
<span class="ico_down">down</span>0.970  million tons from year earlier</p>
