<div class="content-container energy-kids">
	<a href="/kids/">
		<!--
			<picture>
			<source srcset="http://via.placeholder.com/300x165" media="(min-width: 2300px)">
			<source srcset="http://via.placeholder.com/230x133" media="(min-width: 956px)">
			<source srcset="http://via.placeholder.com/750x412" media="(min-width: 801px)">
			<source srcset="http://via.placeholder.com/230x133" media="(min-width: 600px)">
			<source srcset="http://via.placeholder.com/430x236" media="(min-width: 480px)">
			<img srcset="http://via.placeholder.com/270x150" alt="Small image of Energy Kids banner with host Energy Ant">
		</picture>
-->
		<div class="energy-kids-image"></div>
	</a>
</div>

