<!-- start module -->
<!-- start module -->
<!-- start module -->
<div class="content-container dark-top-border-container">
	<ul>
		<li class="head"><h2>Especially For...</h2></li>
		<div class="l-responsive">
			<li><a href="about/careers/">Job Seekers</a></li>
			<li><a href="about/especiallyfor/analysts.cfm">Policy Analysts</a></li>
			<li><a href="pressroom/">Media</a></li>
			<li><a href="tools/models/">Researchers</a></li>
			<li><a href="/kids">Students</a></li>
		</div>
		<div class="l-responsive">
			<li><a href="/kids/energy.cfm?page=6">Teachers</a></li>
			<li><a href="/survey/">Survey Respondents</a></li>
			<li><a href="about/especiallyfor/employees.cfm">EIA Employees</a></li>
			<li><a href="/developer/">Developers API</a></li>
		</div>
	</ul>
</div>
<!-- start module -->
<!-- start module -->
<!-- start module -->
