<div class="content-container dark-top-border-container features">
	<h2>Features</h2>
	<div>
		<a href="https://www.eia.gov/beta/realtime_grid/">
			<picture>
				<!-- source srcset="http://via.placeholder.com/300x165" media="(min-width: 2300px)" -->
				<source srcset="http://via.placeholder.com/185x100" media="(min-width: 956px)">
				<source srcset="http://via.placeholder.com/750x412" media="(min-width: 801px)">
				<source srcset="http://via.placeholder.com/185x100" media="(min-width: 600px)">
				<source srcset="http://via.placeholder.com/430x236" media="(min-width: 480px)">
				<img srcset="http://via.placeholder.com/270x150" alt="">
			</picture>
			<!--img src="homepage/images/features/electric_data_sys.jpg" alt="Electricity Data Browser" / -->
		</a>
		<ul>
			<li class="head"><h3><a href="https://www.eia.gov/beta/realtime_grid/">Electric System Operating Data Tool</a></h3></li>
			<li>Near real-time electricity operations data for the Lower 48 states.</li>
		</ul>
	</div>

	<div>
		<a href="http://www.noggateway.org">
			<picture>
				<!-- source srcset="http://via.placeholder.com/300x165" media="(min-width: 2300px)" -->
				<source srcset="http://via.placeholder.com/185x100" media="(min-width: 956px)">
				<source srcset="http://via.placeholder.com/750x412" media="(min-width: 801px)">
				<source srcset="http://via.placeholder.com/185x100" media="(min-width: 600px)">
				<source srcset="http://via.placeholder.com/430x236" media="(min-width: 480px)">
				<img srcset="http://via.placeholder.com/270x150" alt="">
			</picture>		
			<!--img src="homepage/images/features/gateway.jpg" alt="Gateway" / -->
		</a>
		<ul>
			<li class="head"><h3><a href="http://www.noggateway.org">National Oil &amp; Gas Gateway</a></h3></li>
			<li>Well-level data and maps now available.</li>
		</ul>
	</div>

	<div>
		<a href="/state/maps.cfm">
			<picture>
				<!-- source srcset="http://via.placeholder.com/300x165" media="(min-width: 2300px)" -->
				<source srcset="http://via.placeholder.com/185x100" media="(min-width: 956px)">
				<source srcset="http://via.placeholder.com/750x412" media="(min-width: 801px)">
				<source srcset="http://via.placeholder.com/185x100" media="(min-width: 600px)">
				<source srcset="http://via.placeholder.com/430x236" media="(min-width: 480px)">
				<img srcset="http://via.placeholder.com/270x150" alt="">
			</picture>
			<!--mg src="homepage/images/features/energy_mapping_system.jpg" alt="U.S. Energy Mapping System" / -->
		</a>
		<ul>
			<li class="head"><h3><a href="/state/maps.cfm">U.S. Energy Mapping System</a></h3></li>
			<li>Rankings, layers of energy information, and state comparisons.</li>
		</ul>
	</div>
</div>