<div class="content-container dark-top-border-container features">
	<h2>Features</h2>
	<div>
		<div>
			<a href="https://www.eia.gov/beta/realtime_grid/" style="background-image: url(homepage/images/features/electric_data_sys.jpg)" title="Electricity Data Browser"></a>
		</div>
		<ul>
			<li class="head"><h3><a href="https://www.eia.gov/beta/realtime_grid/">Electric System Operating Data Tool</a></h3></li>
			<li>Near real-time electricity operations data for the Lower 48 states.</li>
		</ul>
	</div>

	<div>
		<div>
			<a href="http://www.noggateway.org" style="background-image: url(homepage/images/features/gateway.jpg)" title="Gateway"></a>
		</div>
		<ul>
			<li class="head"><h3><a href="http://www.noggateway.org">National Oil &amp; Gas Gateway</a></h3></li>
			<li>Well-level data and maps now available.</li>
		</ul>
	</div>

	<div>
		<div>
			<a href="/state/maps.cfm" style="background-image: url(homepage/images/features/energy_mapping_system.jpg)" title="U.S. Energy Mapping System"></a>
		</div>
		<ul>
			<li class="head"><h3><a href="/state/maps.cfm">U.S. Energy Mapping System</a></h3></li>
			<li>Rankings, layers of energy information, and state comparisons.</li>
		</ul>
	</div>
</div>