<li style="background-image: url(homepage/images/slider/slide01.jpg)">
	<div class="slider-overlay">
	<h2><a href="/outlooks/aeo/">Annual Energy Outlook 2018</a></h2> 
	<h3><a href="/outlooks/aeo/">Full Annual Energy Outlook with projections to 2050</a></h3>
	</div>
</li>
<li style="background-image: url(homepage/images/slider/slide02.jpg)">
	<div class="slider-overlay">
	<h2><a href="/outlooks/ieo/section_issues.php#uon">Capital investment in upstream oil and natural gas industries</a></h2> 
	<h3><a href="/outlooks/ieo/section_issues.php#uon">Issue in Focus from IEO2017</a></h3>
	</div>
</li>
<li style="background-image: url(homepage/images/slider/slide03.jpg)">
	<div class="slider-overlay">
	<h2><a href="/naturalgas/crudeoilreserves/">U.S. Crude Oil and<br />Natural Gas Proved Reserves, Year-end 2016</a></h2> 
	<h3></h3>
	</div>
</li>
<li style="background-image: url(homepage/images/slider/slide04.jpg)">
	<div class="slider-overlay">
	<h2><a href="/petroleum/drilling/">Drilling Productivity Report</a></h2> 
	<h3><a href="/petroleum/drilling/">Assessing the productivity of oil and gas drilling operations&#8212;February 2018 report</a></h3>
	</div>
</li>
<li style="background-image: url(homepage/images/slider/slide05.jpg)">
	<div class="slider-overlay">
	<h2><a href="/forecasts/steo/">Short-Term Energy Outlook February 2018</a></h2> 
	<h3><a href="/forecasts/steo/">Energy projections for supply, demand, and prices</a></h3>
	</div>
</li>
<li style="background-image: url(homepage/images/slider/slide06.jpg)">
	<div class="slider-overlay">
	<h2><a href="/conference/2018/">2018 EIA Energy Conference, June 4&#8211;5</a></h2> 
	<h3><a href="/conference/2018/">Registration is now open</a></h3>
	</div>
</li>