<li class="feature_new1">
  <div class="home_feature_overlay">
    <div class="hfcontent">
    <h2><a href="/outlooks/aeo/">Annual Energy Outlook 2018</a></h2> 
    <h3><a href="/outlooks/aeo/">Full Annual Energy Outlook with projections to 2050 &rsaquo;</a></h3>
  </div>
  </div>
</li>

<li class="feature_new2">
  <div class="home_feature_overlay">
    <div class="hfcontent">
    <h2><a href="/outlooks/ieo/section_issues.php#uon">Capital investment in upstream oil and natural gas industries</a></h2> 
    <h3><a href="/outlooks/ieo/section_issues.php#uon">Issue in Focus from IEO2017 &rsaquo;</a></h3>
  </div>
  </div>
</li>



<li class="feature_new3">
  <div class="home_feature_overlay">
    <div class="hfcontent">
    <h2><a href="/naturalgas/crudeoilreserves/">U.S. Crude Oil and<br />Natural Gas Proved Reserves, Year-end 2016 &rsaquo;</a></h2> 
    <h3></h3>
  </div>
  </div>
</li>

<li class="feature_new4">
  <div class="home_feature_overlay">
    <div class="hfcontent">
    <h2><a href="/petroleum/drilling/">Drilling Productivity Report</a></h2> 
    <h3><a href="/petroleum/drilling/">Assessing the productivity of oil and gas drilling operations&#8212;February 2018 report &rsaquo;</a></h3>
  </div>
  </div>
</li>

<li class="feature_new5">
  <div class="home_feature_overlay">
    <div class="hfcontent">
    <h2><a href="/forecasts/steo/">Short-Term Energy Outlook February 2018
</a></h2> 
    <h3><a href="/forecasts/steo/">Energy projections for supply, demand, and prices &rsaquo;</a></h3>
  </div>
  </div>
</li>

<li class="feature_new6">
  <div class="home_feature_overlay">
    <div class="hfcontent">
    <h2><a href="/conference/2018/">2018 EIA Energy Conference, June 4&#8211;5
</a></h2> 
    <h3><a href="/conference/2018/">Registration is now open &rsaquo;</a></h3>
  </div>
  </div>
</li>

