<?php
/* edit the link URL, Label and Date below */
/* no need to add the  > or the &nbsp;› or the  &rsaquo; */

$slideOneURL = "/petroleum/drilling/";
$slideOneImage = "https://www.eia.gov/css_rehab/archive/homepage/images/slider/slide01.jpg";
$slideOneLabel = "Drilling Productivity Report";
$slideOneDescription = "Approach to assessing the productivity of oil and gas drilling operations&#8212; March report";

$slideTwoURL = "/forecasts/steo/";
$slideTwoImage = "https://www.eia.gov/css_rehab/archive/homepage/images/slider/slide02.jpg";
$slideTwoLabel = "Short-Term Energy Outlook March 2018";
$slideTwoDescription = "Energy projections for supply, demand, and prices";

$slideThreeURL = "/outlooks/aeo/";
$slideThreeImage = "https://www.eia.gov/css_rehab/archive/homepage/images/slider/slide03.jpg";
$slideThreeLabel = "Annual Energy Outlook 2018";
$slideThreeDescription = "Full Annual Energy Outlook with projections to 2050";

$slideFourURL = "/conference/2018/";
$slideFourImage = "https://www.eia.gov/css_rehab/archive/homepage/images/slider/slide04.jpg";
$slideFourLabel = "2018 EIA Energy Conference, June 4&#8211;5";
$slideFourDescription = "Session topics now available";

$slideFiveURL = "/petroleum/marketing/monthly/";
$slideFiveImage = "https://www.eia.gov/css_rehab/archive/homepage/images/slider/slide05.jpg";
$slideFiveLabel = "Petroleum Marketing Monthly";
$slideFiveDescription = "Monthly price and volume statistics on crude oil and petroleum products";

$slideSixURL = "/beta/international/analysis.cfm?iso=SDN";
$slideSixImage = "https://www.eia.gov/css_rehab/archive/homepage/images/slider/slide06.jpg";
$slideSixLabel = "Most of Sudan's and South Sudan's oil and gas reserves extend into both countries";
$slideSixDescription = "Read the Country Analysis Brief";

/* DO NOT EDIT BELOW */
?>


<li>
	<img src='<?=$slideOneImage?>' alt='<?=$slideOneLabel?>' />
	<div class="slider-overlay">
		<h2><a href='<?=$slideOneURL?>' title='<?=$slideOneLabel?>'><?=$slideOneLabel?></a></h2> 
		<h3><a href='<?=$slideOneURL?>'><?=$slideOneDescription?></a></h3>
	</div>
</li>
<li>
	<img src='<?=$slideTwoImage?>' alt='<?=$slideTwoLabel?>' />
	<div class="slider-overlay">
		<h2><a href='<?=$slideTwoURL?>' title='<?=$slideTwoLabel?>'><?=$slideTwoLabel?></a></h2> 
		<h3><a href='<?=$slideTwoURL?>'><?=$slideTwoDescription?></a></h3>
	</div>
</li>
<li>
	<img src='<?=$slideThreeImage?>' alt='<?=$slideThreeLabel?>' />
	<div class="slider-overlay">
		<h2><a href='<?=$slideThreeURL?>' title='<?=$slideThreeLabel?>'><?=$slideThreeLabel?></a></h2> 
		<h3><a href='<?=$slideThreeURL?>'><?=$slideThreeDescription?></a></h3>
	</div>
</li>
<li>
	<img src='<?=$slideFourImage?>' alt='<?=$slideFourLabel?>' />
	<div class="slider-overlay">
		<h2><a href='<?=$slideFourURL?>' title='<?=$slideFourLabel?>'><?=$slideFourLabel?></a></h2> 
		<h3><a href='<?=$slideFourURL?>'><?=$slideFourDescription?></a></h3>
	</div>
</li>
<li>
	<img src='<?=$slideFiveImage?>' alt='<?=$slideFiveLabel?>' />
	<div class="slider-overlay">
		<h2><a href='<?=$slideFiveURL?>' title='<?=$slideFiveLabel?>'><?=$slideFiveLabel?></a></h2> 
		<h3><a href='<?=$slideFiveURL?>'><?=$slideFiveDescription?></a></h3>
	</div>
</li>
<li>
	<img src='<?=$slideSixImage?>' alt='<?=$slideSixLabel?>' />
	<div class="slider-overlay">
		<h2><a href='<?=$slideSixURL?>' title='<?=$slideSixLabel?>'><?=$slideSixLabel?></a></h2> 
		<h3><a href='<?=$slideSixURL?>'><?=$slideSixDescription?></a></h3>
	</div>
</li>