		<!-- start module -->
		<!-- start module -->
		<!-- start module -->
		<div class="content-container main-content-container">
			<h1>Today in Energy<span class="date">Posted September 14, 2017</span></h1>
			<h2>
				<a href="/">EIA projects 28% increase in world energy use by 2040</a>
			</h2>
			<p>The U.S. Energy Information Administration's latest
				<em>International Energy Outlook 2017</em> (IEO2017) <a href="/">projects</a> that world energy consumption will grow by 28% between
				2015 and 2040. Most of this growth is expected to come from countries that are not in the Organization for Economic
				Cooperation and Development (OECD), and especially in countries where demand is driven by strong economic growth,
				particularly in Asia.
				<a href="/">More</a>
			</p>
			<div class="media">
				<a href="/">

					<picture>
<!-- source srcset="http://via.placeholder.com/300x155" media="(min-width: 2300px)" -->
						<!-- source srcset="http://via.placeholder.com/" media="(min-width: 1250px)" -->
						<source srcset="http://via.placeholder.com/430x215" media="(min-width: 956px)">
<source srcset="http://via.placeholder.com/800x400" media="(min-width: 801px)">
						<!-- source srcset="http://via.placeholder.com/450x250" media="(min-width: 600px)" -->
						<source srcset="http://via.placeholder.com/600x300" media="(min-width: 600px)">
						<source srcset="http://via.placeholder.com/430x215" media="(min-width: 480px)">
						<img srcset="http://via.placeholder.com/300x150" alt="">
					</picture>
<!--img src="https://www.eia.gov/todayinenergy/images/2018.02.12/feature_p1.png?<?php /* echo(rand() . ''); */ ?>" alt="U.S. net energy trade, as explained in the article text" / -->
				</a>
			</div>
			<figure>
				<strong>Source: </strong>EIA,  Federal Energy Regulatory Commission (FERC) Financial Reports, as accessed by Ventyx Velocity Suite
			</figure>
		</div>
		<!-- end module -->
		<!-- end module -->
		<!-- end module -->