<!--begin content -->
<div class="tie">
<h2><span class="tie_date right">Posted March 9, 2018</span>Today in Energy</h2>
</div>

<div class="white_box no-border>">



<!--<div class="tie_correction"> <p></p></div>-->

<h3>
<a href="/todayinenergy/detail.cfm?id=35272"><strong>Investment in tight oil, oil sands, and deepwater drives long-term oil production growth</strong>&nbsp;&rsaquo;</a>
</h3>


<p>Upstream investment in crude oil and liquids production is highly sensitive to crude oil prices, particularly production of higher-cost resources from tight rock formations, oil sands, and offshore deepwater. In EIA’s <em>International Energy Outlook 2017</em> (IEO2017) Reference case, increasing crude oil prices lead to more investment, driving production growth in these higher-cost resources.         

						 
<a href="/todayinenergy/detail.cfm?id=35272"><strong>More</strong> &rsaquo;</a> </p>

<a href="/todayinenergy/detail.cfm?id=35272" border="0">
<img src="/todayinenergy/images/2018.03.09/feature_p1.png" alt="production of crude oil from tight oil, oil sands, and offshore deepwater, as explained in the article text"></a>
<br clear="all">
<p style="font-size:11px;color:#999; line-height:1em;" id="TIEp1source">
<strong>Source: </strong>EIA, <em>International Energy Outlook 2017</em> Reference case



</p> 


</div>