<!-- start module -->
<!-- start module -->
<!-- start module -->
<div class="content-container dark-top-border-container one">
	<ul>
		<li class="head"><h2>What's New</h2></li>
		<li><a href="/">Drilling Productivity Report</a></li>
		<li class="date">Month 1</li>
		<li><a href="/">Short-Term Energy Outlook</a></li>
		<li class="date">Month 15</li>
		<li><a href="/">Petroleum Marketing Monthly</a></li>
		<li class="date">Month 31</li>
		<li class="foot"><a href="/">More</a></li>
	</ul>
</div>
<!-- end module -->
<!-- end module -->
<!-- end module -->
